### ISSUE TITLE
nuclei still not indentify gbk [issue]

### ISSUE THREAD

**Issue by kitezzzGrim** [projectdiscovery/nuclei#1018]
**Describe the bug**
nuclei still not indentify gbk

**Nuclei version**
`2.5.1`

**Screenshot of the error or bug**
<img width="412" alt="Snipaste_2021-09-14_08-51-38" src="https://user-images.githubusercontent.com/32265931/133176092-98dc00c7-4629-485a-9784-e78ac8aa94a3.png">

**Comment by Ice3man543** [comment]
This looks like an issue with string comparison where we expected `gbk` to be in lowercase. This will be fixed very soon.

**Comment by kitezzzGrim** [comment]
> This looks like an issue with string comparison where we expected `gbk` to be in lowercase. This will be fixed very soon.

good .  I'm already looking forward to it
