### ISSUE TITLE
[Feature Request] Add single target support, json output support

### ISSUE THREAD

**Issue by r0oth3x49** [projectdiscovery/nuclei#102]
I have few feature requests if you guys consider it useful.

Support:
  - Single target directly with some sort of switch `e.g:- -d, --domain`
  - Json output (Useful to integrate with other tools)
  - Example Json output:
     ```
     {
	"templates": [
		{
			"name": "template_name",
			"author": "AuthorName",
			"severity": "high/low/median",
			"protocol": "http/https",
			"port": "80/443",
			"response": [
				"LIST OF RESPONSES"
			]
		   }
	    ]
      }
     ```
  

You guys have done a great job. Thanks for sharing it with community.

**Comment by epinna** [comment]
+1 for the JSON output

**Comment by r0oth3x49** [comment]
@bauthard thanks for the `-json` feature.
are you going to consider the other feature request to scan a target?

You can close if this feature request is implemented.

**Comment by bauthard** [comment]
Hey @r0oth3x49, 

Both features will be implemented in next update of nuclei.

**Comment by Ice3man543** [comment]
This is done by PRs #114 #113. We can close this now.
