### ISSUE TITLE
Reporting example shows incorrect field for GitLab

### ISSUE THREAD

**Issue by revblock** [projectdiscovery/nuclei#1039]
**Describe the bug**
The example config file for issue reporting shows the following field for gitlab.

`# project-id is the ID of the repository.
project-id: ""`

However, in the code for this, it looks for a `ProjectName` field in the `gitlab.go` file on line 27

`ProjectName string `yaml:"project-name"``

Either the example should be changed to reflect the code, but keeping the comment to say it should be project id because that is correct, or the code should be changed to reflect what the actual field name should be called.

I'm happy to put a PR in for either for these 👍 

**Nuclei version**
Latest dev branch

**Comment by ehsandeep** [comment]
@revblock this has been updated in the following PR - https://github.com/projectdiscovery/nuclei/pull/1256
