### ISSUE TITLE
Markdown export doesn't include multiple results from same template

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1041]
**Describe the bug**
`markdown-export / me` flag is used to export results in a markdown formatted file to a given directory, it has been identified that markdown export misses valid results to write in case of multiple results are part of the same template using multiple matchers.

To reproduce this:

```
echo https://example.com | nuclei -t misconfiguration/http-missing-security-headers.yaml -me reports
```
Result count: 15
Markdown file: 1

**Nuclei version**
2.5.2

**Comment by Ice3man543** [comment]
This is fixed by https://github.com/projectdiscovery/nuclei/commit/1bf023abc223fb0cf274dad48730d4d6dbd69db0, which makes engine export report including matcher or extractor name as well in filepath.
