### ISSUE TITLE
use -validate flag for further examination

### ISSUE THREAD

**Issue by d4rkh0rse** [projectdiscovery/nuclei#1044]
I updated nuclei v2.5.2

but I got this error use -validate for further examination.
and I uninstall nuclei and nuclei templates after that update templates but same error occur

![nucl](https://user-images.githubusercontent.com/8256271/134042020-692cb2cb-d8be-4aea-af26-170eccd582cc.PNG)
![template](https://user-images.githubusercontent.com/8256271/134042027-aa623292-41be-4639-86ee-c3ea245da1cd.PNG)
.

**Comment by ehsandeep** [comment]
@d4rkh0rse this will be updated automatically as soon as a new release for the template project will be pushed, changes are already applied here - https://github.com/projectdiscovery/nuclei-templates/pull/2692.

**Comment by ehsandeep** [comment]
Should be fixed with https://github.com/projectdiscovery/nuclei-templates/releases/tag/v8.5.3
