### ISSUE TITLE
the gbk i can see but nuclei not can .... 

### ISSUE THREAD

**Issue by kitezzzGrim** [projectdiscovery/nuclei#1048]
**Describe the bug**
2.5.2 nuclei i can see the gbk website，but nuclei maybe not can..
 

**Nuclei version**
2.5.2

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/32265931/134271816-5738f8b1-d8c2-41c2-8cd5-cc11d2dbb43e.png)
![image](https://user-images.githubusercontent.com/32265931/134271840-323dbcac-62e6-4b3b-b391-472737dca616.png)

**Comment by ehsandeep** [comment]
@kitezzzGrim it's a known issue getting tracked at https://github.com/projectdiscovery/nuclei/issues/1018, closing this as duplicate, we will update it in the next version.
