### ISSUE TITLE
AXIOM + NUCLEI error >> Could not find template '/root/nuclei-templates': could not find file: stat /root/nuclei-templates: permission denied

### ISSUE THREAD

**Issue by wasp76b** [projectdiscovery/nuclei#1049]
after the last update of the nuclei engine I'm having problems using the axiom+nuclei, here are the evidences of the error:

![nuclei+axiom_01](https://user-images.githubusercontent.com/75587705/134354334-dae20307-5540-44e7-81b3-bdec74a36734.png)

![nuclei+axiom_02](https://user-images.githubusercontent.com/75587705/134354375-bde2668d-3114-4656-8edb-6dbb4692f39b.png)

the command I have been using is as follows:
axiom-scan 200http -m nuclei -t /root/nuclei-templates -impact low -impact medium -impact high -impact critical -o result

**Comment by ehsandeep** [comment]
@wasp76b you can do the following to achieve the same, as a default all the templates are loaded.

```
nuclei -impact low,medium,high,critical -o result
```
