### ISSUE TITLE
Adding debug flag to display debug information

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#105]
This will add native support and allow users to debug the request and response, which will be helpful for testing newly created templates. 

suggested flag:- `-debug`, `-http-debug`, `-dns-debug`

**Comment by Ice3man543** [comment]
Hey, in pr #107, I have improved verbose mode which will allow you to see if nuclei is sending requests or sitting idle and also added a `debug` flag to see the sent requests and responses. Closing this issue now!
