### ISSUE TITLE
Support semantic versioning in docker tags for every release

### ISSUE THREAD

**Issue by rseedorff** [projectdiscovery/nuclei#1051]
**Is your feature request related to a problem? Please describe.**
As a `nuclei` user i would like do decide more precisely which version of `nuclei` is currently running in my infrastructure.
In an automated (docker) container cluster setup it is somehow a little bit risky to always reference a latest docker tag image instead of specific versions. With only a maintained `latest` tag reference there is no control as user about specific upgrade path. 

**Describe the solution you'd like**
It would be great if your release process will be extended to create stable semantic version tags as docker image tags and push them to dockerhub on every release. There are some helpful GitHub actions that could do the job easily.

**Additional context**
- https://hub.docker.com/r/projectdiscovery/nuclei/tags?page=1&ordering=last_updated

**Comment by ehsandeep** [comment]
@rseedorff this is now supported - https://hub.docker.com/r/projectdiscovery/nuclei/tags?page=1&ordering=last_updated

**Comment by rseedorff** [comment]
That's great 😀 🙏🏻🎉
