### ISSUE TITLE
Nuclei Parse \r\n As New Line Even I Did Escape To The Backslash

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#1053]
**Describe the bug**

While Using unsafe: true , Nuclei Parse \r\n As New Line Even I Did Escape To The Backslash
And Here Is My Template 

```
id: 0x00

info:
  name: Demo
  author: 0xAwali
  severity: low

requests:
  - raw:
      - |+
        GET / HTTP/1.1
        User-Agent: any\r\nHeader: Value
        Accept-Encoding: gzip, deflate
        Accept: */*
        Host: {{Hostname}}
        
    unsafe: true
    matchers:
      - type: word
        words:
          - 'Not Found'
```
Output As You See

![Screenshot_2021-09-24_10_38_54](https://user-images.githubusercontent.com/54332136/134646022-2ca1f9e6-533c-4909-be07-3200b7a8fef5.jpg)

**Nuclei version**
2.5.2

**Comment by geeknik** [comment]
Hi, please try rewriting your template to match the [documentation](https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#unsafe-http-requests):

```
requests:
  - raw:
      - |+
 ```

You’re missing a `+` on the 10th line. Let us know if that helps. 🤙🏻

**Comment by 0xAwali** [comment]
Nope That Doesn't Help , Still The Same

![Screenshot_2021-09-24_13_29_32](https://user-images.githubusercontent.com/54332136/134667546-ea5327e9-fe1a-4f04-ac09-cea922af267c.jpg)

**Comment by 0xAwali** [comment]
Plus If I Did Escaping , Something Weird Happened e.g. MY Template 


```
id: 0x00

info:
  name: Demo
  author: 0xAwali
  severity: low

requests:
  - raw:
    - |+
      GET / HTTP/1.1
      User-Agent: any\\r\\nHeader: Value
      Accept-Encoding: gzip, deflate
      Accept: */*

    unsafe: true
    matchers:
      - type: word
        words:
          - 'Not Found'
```

As You See

![Screenshot_2021-09-24_13_33_23](https://user-images.githubusercontent.com/54332136/134668196-6ec7b7dd-8b73-4107-96e7-63928eeab326.jpg)

User-Agent: any Became \ser-Agent: any\ Plus New Line Too

**Comment by geeknik** [comment]
That's a neat bug. Let's page @ehsandeep and see if we can't fix it. 👍🏻

**Comment by ehsandeep** [comment]
@0xAwali @geeknik this is expected behavior, `\r\n` is transformed at engine level if included in the template, but we might want to exclude this transformation behavior for `unsafe` templates?

**Comment by 0xAwali** [comment]
that will be useful

**Comment by ehsandeep** [comment]
@0xAwali @geeknik this is now fixed in the dev version, thank you again for reporting this.


```console
echo https://example.com | ./nuclei -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.2

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.5.2 (latest)
[INF] Using Nuclei Templates 8.5.4 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates added in last update: 82
[INF] Templates loaded for scan: 1
[INF] [0x00] Dumped HTTP request for https://example.com

GET / HTTP/1.1
User-Agent: any\r\nHeader: Value
Accept-Encoding: gzip, deflate
Accept: */*
Host: example.com
```

**Comment by 0xAwali** [comment]
Yah It's Work Now ,  **Thank You** 
![Screenshot_2021-09-27_00_50_31](https://user-images.githubusercontent.com/54332136/134826821-91340196-d4ab-4692-91ec-78c7d8c9a85f.jpg)
