### ISSUE TITLE
Create Nuclei Server

### ISSUE THREAD

**Issue by cfsdes** [projectdiscovery/nuclei#1088]
Please add a feature to run nuclei as a server.

This way, when it receives a request, for example, in the following format:
```http
POST /api/parse HTTP/1.1
Host: 127.0.0.1:5000
User-Agent: Nuclei Scanner
Authorize: <Auth_TOKEN>
Content-Type: application/json
Connection: close

{
    "url": "http://target.com/api/foo",
    "req": "<base64_request>",
}
```

It will automatically scan the target.
(This can be useful for future integration with Burpsuite or other tools)

**Comment by cfsdes** [comment]
Okay, thank you so much!

**Comment by k4n5ha0** [comment]
> Hello @cfsdes,
> 
> This feature will only be available starting from nuclei `v3`.

hi，v3 will be include any request ?like this pic
![image](https://user-images.githubusercontent.com/22064977/144734896-f3a13b57-30a3-4819-a68f-4574ff3791e8.png)
if some sql injection in deep url。so is there all request will be scan in nuclei ？
