### ISSUE TITLE
Headless Browsing Login on Websites not Working

### ISSUE THREAD

**Issue by ctao5660** [projectdiscovery/nuclei#1095]
**Describe the bug**
Headless Browsing login flow on websites not working

**Nuclei version**
Nuclei v 2.5.2

**Screenshot of the error or bug**
Has anyone tried authenticating into a modern website via Nuclei headless browsing? I've been trying to log into Trello but the login flow which should lead me here after inputting my email(tested on regular browser):
<img width="1367" alt="Screen Shot 2021-10-07 at 2 09 53 PM" src="https://user-images.githubusercontent.com/39934918/136462667-070eafbe-25cc-4b72-9bbe-aaeebc5dcfdd.png">

in Nuclei headless seems to instead lead me back to this page: 
<img width="1762" alt="Screen Shot 2021-10-07 at 2 11 13 PM" src="https://user-images.githubusercontent.com/39934918/136462845-c65a0e9f-9921-492f-851f-aa41ff8a5021.png">

**Comment by forgedhallpass** [comment]
Hello @ctao5660 

Could you share the template you are using?

**Comment by ctao5660** [comment]
@forgedhallpass ah, one clarification is that Trello seems to recognize valid emails, and will only show you the screen I screenshotted if entering a valid email. Can you try using the email I was using? `torit94770@neragez.com` I think once you enter the email the screen saying "Log in with Atlassian" will show up

I will take those into consideration. Thanks!

**Comment by ctao5660** [comment]
@forgedhallpass So is Nuclei just not able to send these cookies? Or is there some sort of customization that will fix this issue?

**Comment by ctao5660** [comment]
@forgedhallpass I tried running your template on the latest version( 2.5.3) and it still doesn't show up correctly for me.  Still leading me back to this page.
![image](https://user-images.githubusercontent.com/39934918/140984036-59de4d5a-e984-47d4-9887-2347d323fdfb.png)
What options are you using to run this template?

**Comment by forgedhallpass** [comment]
@ctao5660 the implementation has been merged into the `dev` branch, but will be released in the next version only. If you don't want to wait until the new release, you can build it yourself.

**Comment by ctao5660** [comment]
Oh okay sorry for the confusion!

**Comment by forgedhallpass** [comment]
No problem. Let us know if you need any help.

**Comment by ctao5660** [comment]
Hey again, I build the dev branch and that login part works. I went a little further with the template, inputting a password and clicking the login button, but I seem to be getting an error when actually loading the Trello home page which makes the headless browser just exit:
<img width="885" alt="Screen Shot 2021-11-10 at 1 54 43 PM" src="https://user-images.githubusercontent.com/39934918/141199715-3f4e6a01-e140-4f4e-ac2f-2bb7daf17828.png">

I tried sleep and waitvisible for a random element on the Trello home page, both don't work. 
Here's the template for reference: 
```
id: trello-headless-login-example
info:
    name: Trello Headless Login Example
    severity: info
    author: forgedhallpass

headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}/login"
      - action: waitload
      - action: text
        args:
          by: x
          value: mened69404@d3ff.com
          xpath: //input[@id='user']
      - action: waitvisible
        args:
          by: x
          xpath: //input[@id='login']
          timeout: 3
          pollTime: 100
      - action: click
        args:
          by: x
          xpath: //input[@id='login']
      - action: waitload
      - action: waitvisible
        args:
          by: x
          xpath: //div[@title='mened69404@d3ff.com']
          timeout: 3
          pollTime: 100
      - action: text
        args:
          by: x
          value: password!
          xpath: //input[@id='password']
      - action: waitload
      - action: waitvisible
        args:
          by: x
          xpath: //*[@id="login-submit"]
          timeout: 3
          pollTime: 100
      - action: click
        args:
          by: x
          xpath: //*[@id="login-submit"]
      - action: waitload
      - action: sleep
        args:
          duration: 3
      - action: waitvisible
        args:
          by: x
          xpath: //*[@id="content"]/div/div[2]/div/div[1]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div
          timeout: 3
          pollTime: 100
      - action: click
        args:
          by: x
          xpath: //*[@id="header"]/div[4]/button[2]/div
          timeout: 3
          pollTime: 100
```

**Comment by forgedhallpass** [comment]
The `could not reset mouse` message is misleading/incorrect. The error is raised because the page does not load in 1 second (it requires couple more). We probably need to add an optional `timeout` parameter to `waitload`, or increase the default.  For testing purposes this can be worked around with a `waitvisible` or a simple `sleep` instead of `waitload`, but the page will still not load properly:

![image](https://user-images.githubusercontent.com/13679401/141788244-7899b7ec-94aa-4f47-8298-aaa2713635e0.png)

This is most likely because still some cookies are not sent along, or some javascript execution fails. If I open the `http://trello.com` in the same browser session, in a new tab, it works though.

**Comment by Mzack9999** [comment]
`trello.com` consider the default user agent of chromium headless as deprecated:
```
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36
```

Customizable User Agent is tracked at #1250
