### ISSUE TITLE
Raw request's does not send a request if `/` is not there

### ISSUE THREAD

**Issue by rojan-rijal** [projectdiscovery/nuclei#110]
## Summary

Raw request's `{{BaseUrl}}` can take the whole URL from a .txt file and split it into paths and hostname in the request however the way it is done is kind of unreliable. Here is an example. 

`File: targets.txt` has as the target. https://api.apiurl.com/api/endpoint

The YAML file has the following raw request defined 
```
- |
     GET / HTTP/1.1
     User-Agent: User-agent-value
     Host: {{BaseUrl}}
     Connection: Close
```

In this case, the request goes to `https://api.apiurl.com/api/endpoint/` notice the extra `/` added. That is due to `GET / HTTP/1.1`. This will result in some API endpoints having 404 responses since it gets recognized as directory rather than paths. Now if you put `GET ? HTTP/1.1` it could fix the problem however Nuclei does not send the request at all if there is a `?` or anything other than `/` in that section. 

This was tested with `--debug` option to see if any requests were sent.

**Comment by Ice3man543** [comment]
This has been fixed by PR #121. Thank you for the issue @rojan-rijal.
