### ISSUE TITLE
[feature] Add missing headless actions tests

### ISSUE THREAD

**Issue by pmareke** [projectdiscovery/nuclei#1102]
Doing this [PR](https://github.com/projectdiscovery/nuclei/pull/1101) I realised that almost all the actions don't have a test in the `page_actions.go`:

- ActionScreenshot
- ActionTimeInput
- ActionSelectInput
- ActionFilesInput
- ActionWaitLoad
- ActionGetResource
- ActionExtract
- ActionSetMethod
- ActionAddHeader
- ActionDeleteHeader
- ActionSetBody
- ActionWaitEvent
- ActionKeyboard
- ActionDebug
- ActionSleep

I would like to add the missing ones if you think it adds some value to Nuclei.

Best regards, Pedro!

**Comment by forgedhallpass** [comment]
@pmareke it would be great, thank you!
