### ISSUE TITLE
Could not initialize interactsh client[issue]

### ISSUE THREAD

**Issue by Deathpoolxrs** [projectdiscovery/nuclei#1103]
**Describe the bug**
Could not initialize interactsh client

**Nuclei version**
2.5.2

**Screenshot of the error or bug**
		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.5.2 (latest)
[INF] Using Nuclei Templates 8.5.8 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates added in last update: 10
[INF] Templates loaded for scan: 2169
[INF] Templates clustered: 331 (Reduced 29890 HTTP Requests)
[ERR] Could not initialize interactsh client: could not create client: could not make register request: POST https://interact.sh/register giving up after 6 attempts: Post "https://interact.sh/register": dial tcp: lookup interact.sh on 192.168.0.1:53: server misbehaving

**Comment by Deathpoolxrs** [comment]
package github.com/projectdiscovery/nuclei/v2/cmd/nuclei@dev: cannot use path@version syntax in GOPATH mode

**Comment by ehsandeep** [comment]
@Deathpoolxrs you are running an outdated version of go, go1.17 is required for this.
