### ISSUE TITLE
support of relative path for nuclei templates using installed path location

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#112]
As in the latest update nuclei supports downloading nuclei-templates using `-update-templates` flag which downloads nuclei-templates on the `/root/` path with a file named `.nuclei-config.json` or any custom location provided by the user. 
```bash

> cat .nuclei-config.json 

{"templates-directory":"/root/nuclei-templates/","current-version":"1.0.0"}
```

This addition will allow users to call/define templates using relative path instead of the full path, for example:- 

```
echo https://www.example.com | nuclei -t cves/ 
``` 

This will run all the templates from the following location `/root/nuclei-templates/cves/`, another example to use this is chained templates. 

```
id: workflow-example
info:
  name: Simple Workflow
  author: mzack9999
variables:
  jira-dectect: panel/jira-detect.yaml
  jira-cve:  cves/cve1.yaml
  jira-cve2: cves/cve2.yaml
  jira-cve3: cves/cve3.yaml
logic: 
    |
  if jira-dectect() {
     jira-cve()
     jira-cve2()
     jira-cve3()
  }
```

**Comment by Ice3man543** [comment]
Done by #115 .
