### ISSUE TITLE
[issue] Inconsistent behaviour with trailing "/" in template path

### ISSUE THREAD

**Issue by EAAZ02** [projectdiscovery/nuclei#1126]
**Describe the bug**
I have noticed that when a scan is launched with a path for the templates ending in a "/" sometimes it does not show all the "positive" templates, causing false negatives results, launching the same scan without the trailing "/" will report the correct results.

**Nuclei version**
2.5.2

**Screenshot of the error or bug**
Nuclei with trailing "/" in template path:
![imagen](https://user-images.githubusercontent.com/7225206/137481248-47bda401-6bba-49f3-9481-240a58aa2851.png)

Nuclei without the trailing "/" in template path:
![imagen](https://user-images.githubusercontent.com/7225206/137481313-dc1d5bee-dfc5-4eb1-aecd-311b0d46f0ac.png)

Another site, same weird behaviour:
![imagen](https://user-images.githubusercontent.com/7225206/137482064-cfe1a65a-5275-41c7-b289-f7aee47e7562.png)

**Comment by ehsandeep** [comment]
@EAAZ02 This appears to be more consistent behavior than inconsistent behavior; inserting a slash (`/`) in your template with less result indicates that the website you are providing as input behaves differently; you can validate this by running these templates with the `-debug` flag enabled.

In general, you should not include a slash (`/`) in the template if it's not required for the detection.
