### ISSUE TITLE
Export nuclei API so it can be used as a library

### ISSUE THREAD

**Issue by Cylkal** [projectdiscovery/nuclei#1152]
First of all, thank you very much for such a great tool. So that I want to integrate it into my go code.
But when i import "github.com/projectdiscovery/nuclei/v2/internal/runner", due to pkg runner is in the internal path, so that others can not import.
Is there any other way to lift the restriction?

I think this will make it known and used by more people, it will help more people, and apply it to more scenarios.
And doing so will not destroy the original logic, but will bring more flexibility and imagination.

**Comment by ehsandeep** [comment]
@Cylkal, thank you for creating a ticket for this, this is something we'd like to address in future versions so that other projects can import nuclei, we'll use this issue to track development.

**Comment by d4h0** [comment]
@ehsandeep: It seems, this was shipped already, however I can't find any information about how to use Nuclei from Go, or the API documentation. Could you please tell me where to find these resources?

PS: I have not learned Go yet, so if this is obvious to a Go programmer, I might have missed it.

**Comment by d4h0** [comment]
@ehsandeep: Awesome – thank you!
