### ISSUE TITLE
Add seamless, tag based validation for structs

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1156]
Introduce seamless, tag based validation for all structs within the solution. Add a wrapper over the `Marshal()`, `Unmarshal()`, `Encode()` and `Decode()` methods. The wrapper should contain the validation logic and should be re-used across the project.

Example:
```go
type User struct {
   Name   string `validate:"required,min=4,max=15"`
   Email  string `validate:"required,email"`
   Age    int    `validate:"required,numeric,min=18"`
}
```

Reference: https://github.com/go-playground/validator

**Comment by Mzack9999** [comment]
Note: this should be applied only to particular structures that implies `marshal/unmarshal` operation (eg. configuration files, cli options). Other structure should have the logic within a `Validate` method if necessary.
