### ISSUE TITLE
Modularize nuclei so unnecessary features are not loaded by default at runtime

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#1161]
### Please describe your feature request:
nuclei is a popular tool, no doubt about it, so i think now is the time to discuss modularizing nuclei so that users can disable some of the feature creep at runtime so nuclei can be used on more devices with less resources available.

### Describe the use case of this feature:
Can't really talk about this project much right now except to say it's cool and we could use some help squeezing nuclei into small spaces. 😎

**Comment by ehsandeep** [comment]
@geeknik can we talk about this? what features do you want to disable/control as such?

> users can disable some of the feature creep at runtime so nuclei can be used on more devices with less resources available.
