### ISSUE TITLE
Workflows to support concurrency 

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1163]
### Please describe your feature request:
currently, workflows don't support `concurrency` and `bs` flag  which can be added to make workflow execution similar to templates.

**Comment by Mzack9999** [comment]
Blocked by engine refactor in https://github.com/projectdiscovery/nuclei/pull/1066

**Comment by Mzack9999** [comment]
Fixed indirectly by #1066 - more sophisticated scheduler based on template cost and batches will be implemented later
