### ISSUE TITLE
With -validate do not run other operations

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/nuclei#1168]
### Please describe your feature request:
When running `-validate` don't run other operations.

### Describe the use case of this feature:
When the `-validate` flag is used:
- [x] include all templates (even the excluded ones like, `fuzz,dos,misc`)
- [x] implicitly enables the `-v` flag
- [x] don't perform other nuclei operations such as checking for and downloading new templates. Simply perform validation and then exit. This will make the running time of nuclei shorter and reduce requests to check for new templates.

**Comment by d4op** [comment]
is there some option to automatically remove invalid or error templates ?
