### ISSUE TITLE
Could not Initialise Interactsh Client

### ISSUE THREAD

**Issue by technicaljunkie** [projectdiscovery/nuclei#1175]
![Capture](https://user-images.githubusercontent.com/50881733/138551981-28f99131-e63a-49d6-b237-83b251b59aeb.PNG)

**Comment by ehsandeep** [comment]
@technicaljunkie Do you still have this issue? We haven't been able to reproduce it and haven't received any reports from others.

**Comment by technicaljunkie** [comment]
Not Resolved till yet 
![image](https://user-images.githubusercontent.com/50881733/146223565-1b9b8366-f6e5-4918-a311-85db5cd94144.png)

**Comment by ehsandeep** [comment]
`ulimit` has been increased on the server, this should be fixed by now.

**Comment by technicaljunkie** [comment]
Hall of Fame or something?
