### ISSUE TITLE
Add matching conditions to {{BASEURL}} 

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#1197]
I thought the latest version had this feature but it seems that is not exactly the feature I need. 

### Please describe your feature request:
While running subdomain takeover templates you face issues/annoyances like the following:

1. Tumblr subdomain take over template would show many (too many) false positives because of subdomains in the form subdomain.tumblr.com, the template is matching correctly but this cases are an exception for the rule. 
2. Same as 1. but while scanning shopify subdomains. 

In both cases there's no way to identify the false positive since the response html is the same as valid cases. 

### Describe the use case of this feature:

To fix the situation described above it's required to have a matching condition on the {{BASEURL}} or {{Hostname}} variables. Also the idea is to avoid running those requests, I'm thinking about something like 'pre-run-matching-condition'.
In the case one it would be something like:

```

id: tumblr-takeover

info:
  name: tumblr takeover detection
  author: pdteam
  severity: high
  tags: takeover

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    pre-run-matching-condition:
      - type: dsl
        dsl:
           - "!contains({{BASEURL}}, 'tumblr.com')
    matchers:
      - type: word
        words:
          - Whatever you were looking for doesn't currently exist at this address.
          - There's nothing here.
        condition: and
```

**Comment by ehsandeep** [comment]
@pdelteil this turned out be already supported, and I already fixed the template here - https://github.com/projectdiscovery/nuclei-templates/pull/3108, feel free to update other templates if you have any in mind.

**Comment by pdelteil** [comment]
@ehsandeep Thanks a lot! I already updated two templates
