### ISSUE TITLE
Refactor parts of the engine to make execution easier

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#1218]
### Please describe your feature request:

- [ ] Refactor `InternalEvent` related code to have a clearer structure instead of `map[string]interface{}`.  This would also mean exposing part info for each request protocol and having that as enum.
- [ ] Unused variables in the request should be removed like `dynamicValues`.
- [ ] Refactor templates request compilation to dynamically calculate and compile fields on runtime to make adding protocols / maintenance even easier.

**Comment by forgedhallpass** [comment]
Completed in #1066
