### ISSUE TITLE
Add gzip helper function

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/nuclei#1223]
### Please describe your feature request:
I would like a gzip helper function so that I can insert interactsh URLs into compressed payloads.

### Describe the use case of this feature:
A vulnerability I'm writing a template for accepts the payload in compressed form. There is already some gzip support implemented for Java gadgets but it would be more generic if the gzip function was available as a regular helper function also.

**Comment by meme-lord** [comment]
I think something like
```
    "gzip": func(args ...interface{}) (interface{}, error) {
        return deserialization.gadgetEncodingHelper(args[0], "gzip")
    },
```
would work in `v2/pkg/operators/common/dsl/dsl.go` but I can't get nuclei to build in my vm to test it.

**Comment by Ice3man543** [comment]
This has been added in #1066. Thank you for the feature request @meme-lord!
