### ISSUE TITLE
Feature request: Implement Zmap's 'zcrypto/tls' libary as opposed to 'crypto/tls' to increase scanning versatility

### ISSUE THREAD

**Issue by j-rolf** [projectdiscovery/nuclei#1231]
### Please describe your feature request:
Requesting that Nuclei implement the 'zcrypto/tls' [library](https://github.com/zmap/zcrypto) developed by the Zmap project, instead of the current 'crypto/tls' library. 'Zcrypto/tls' makes use of larger pool of cipher suites than 'crypto/tls' and would enable more versatile scanning. 

### Describe the use case of this feature:
The default cipher suites used by golang's crypto/tls are fairly limited, and various hosts are likely to reject tcp handshakes with scanners that don't offer a large enough pool of cipher suites for client/server negotiation. Zcrypto/tls circumvents this issue by adding a significant number of additional cipher suites to 'cipher_suites.go' in GOPATH/src/crypto/tls/. 

The process for adding a single cipher suite is fairly straightforward as done in this fork: https://github.com/phuslu/go/commit/353372383f5bf452d3ca4a9425919cc423eb7e97

**Comment by ehsandeep** [comment]
This applies to both HTTP and new SSL protocol support has been added [here](https://github.com/projectdiscovery/nuclei/pull/1066).

**Comment by Mzack9999** [comment]
This is the comparison between `crypto/tls` and `https://github.com/zmap/zcrypto`:
- SSLV1 (not supported)
- SSLV2 (not supported)
- SSLV3 (`crypto/tls`: deprecated in go1.18, `zmap/zcrypto`: supported up to go 1.16)
- TLS10 (`crypto/tls`: deprecated in go1.18, `zmap/zcrypto`: supported up to go 1.16)
- TLS11 (`crypto/tls`: deprecated in go1.18, `zmap/zcrypto`: supported up to go 1.16)
- TLS12 (`crypto/tls`: supported with safe ciphers, `zmap/zcrypto`: supported with safe+unsafe ciphers up to go 1.16)
- TLS13 (`crypto/tls`: supported with cipher auto-selection, `zmap/zcrypto`: seems not supported yet)

`https://github.com/zmap/zcrypto` is not a ready drop-in replacement of `crypto/tls` and requires using their fork of `net/http`. A solution that integrates and works with upstream `crypto/tls` would be preferred. Marking it as blocked and researching a way to extend the standard library or quickly diff/patch without requiring a fork (monkey/hot patching? diff files?)

**Comment by ehsandeep** [comment]
@j-rolf this is now supported into dev version and implemented here https://github.com/projectdiscovery/nuclei/pull/1529, **zcrypto/tls** is enabed with `-ztls` flag, as default **crypto/tls** is used as before.

**Comment by j-rolf** [comment]
@ehsandeep Thank you!
