### ISSUE TITLE
Fix displayed output if a full URI in request

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/nuclei#1264]
When using an absolute URI in an HTTP request, the output on the command line and in markdown are a bit garbled.

### Please describe your feature request:
A template can include an absolute URI in the request , e.g.:
```
GET http://127.0.0.1:25 HTTP/1.1
Host: 127.0.0.1
```

The markdown output will attempt to reconstruct the "Full url" from the values of the request (below, `example.com` was the host passed via -u and `http://127.0.0.1:25` is the absolute URI in the request). 

```
**Full URL**: https://example.comhttp://127.0.0.1:25
```

The command line looks like this:
```
[2021-11-16 22:01:20] [open-proxy-portscan] [http] [high] https://example.comhttp://127.0.0.1:22 [port=22]
``` 

### Describe the use case of this feature:
The method of recreating the "Full URL" should somehow make a more clear distinction between the target (example.com) and the absolute URI). This could be done by parsing the Request-URI (path or absolute URI) to determine which is present and handle absolute URIs slightly differently).

One possibility might be:
```
**Full URL**: https://example.com (Absolute URI: http://127.0.0.1:25)
```
or even a delimeter to indicate there is something more happening:
```
**Full URL**: https://example.com - http://127.0.0.1:25
```

**Comment by sullo** [comment]
Also noticed that the command line output incorrectly lists `[port=22]` which is from the absolute URI and not the target.

**Comment by sullo** [comment]
#1000 appears to be the same issue.

**Comment by Mzack9999** [comment]
HTTP requests with full URL as path should use `unsafe` - more details in the linked PR
