### ISSUE TITLE
Nuclei scan has been stucked and timeout while start using the Azure DevOps Pipeline

### ISSUE THREAD

**Issue by Syntax3r** [projectdiscovery/nuclei#1265]
### Current Behavior:

- Works fine if run through the Linux CLI. 
- Nuclei scan stuck if run through the Azure DevOps Pipeline.

**Command** : *nuclei -u $target_url -t /home/kali/nuclei-templates -o /home/kali/Desktop/results/nuclei_result.txt*

### Expected Behavior:

nuclei should be working the same as it's worked on Linux CLI.

**Comment by ehsandeep** [comment]
@Syntax3r do you have more details to add? how can we replicate this behavior or details around running nuclei  Azure DevOps Pipeline?

**Comment by ehsandeep** [comment]
This should be fixed with https://github.com/projectdiscovery/nuclei/pull/1286 and the latest version of nuclei, let us know in comment if it doesn't work for you.
