### ISSUE TITLE
Capability to set a {{Cookie}} template placeholder to dynamically inject a cookie header from a text file

### ISSUE THREAD

**Issue by toufik-airane** [projectdiscovery/nuclei#127]
**I try to achieve authenticated scans on a single target for security regression testing.**
Note that It could widely develop the use case of nuclei in the DevSecOps and SOAR world.

The workflow could be:
1. Run a pre-hook to sign in to a web application (using curl or script)
2. Store the session cookie into a file (cookie.txt)
3. Finally, run a nuclei scan with the cookie argument to replace the placeholder {{cookie}} in templates.

A bash command to illustrate the description:
```bash
authenticate.js > cookie.txt
nuclei -l urls.txt -b cookie.txt -t ./nuclei-templates/ -o ouput.log
```

And what the template could look alike:
```yaml
headers:
    Cookie: {{Cookie}}
```

If you need any help to develop the feature during a peer coding session, feel free to reach me.
Thank you.

**Comment by bauthard** [comment]
Thank you @toufik-airane, 

Ability to load variable value from file and system environment both are good ideas.
