### ISSUE TITLE
Spawned nuclei (child) process hangs

### ISSUE THREAD

**Issue by stancu-mihai** [projectdiscovery/nuclei#1274]
### Notes:
I've searched the known issues, hope I haven't missed anything related to this.
It might be something I'm missing from the documentation.
This is my first github issue report, please be gentle :)

### Nuclei version: 
2.4.3 - 2.5.3 (might be others affected as well).

### Current Behavior:
Spawned nuclei process hangs (does not exit, does not return exit code).
Running the same nuclei process with same parameters in bash runs fine (2-3 minutes then exits with exit code).

### Expected Behavior:
Nuclei should behave the same way in bash and spawned process.

### Steps To Reproduce:

Test this Node.js script having nuclei v2.5.3 (the script gets stuck due to waiting forever for the child to exit, also happens with v2.4.3)
```
const spawnChild =  spawn('nuclei', ['-u', '<SOME_URL_HERE>'], {});
spawnChild.on('close', function (code) {  
    // No exit code received
    console.log(`child process exited with code ${code} `);  
});  
spawnChild.on('exit', function (code, signal) {
    // No exit code received
    console.log('child process exited with ' + `code ${code} and signal ${signal}`);
});
```

Test this Node.js script in nuclei v2.1.0 (it works well in this version)
```
const spawnChild =  spawn('nuclei', ['-target', '<SOME_URL_HERE>', '-update-templates', '-t', 'cves/2019'], {});
spawnChild.on('close', function (code) {  
    // Exit code 0 received
    console.log(`child process exited with code ${code} `);  
});  
spawnChild.on('exit', function (code, signal) {
    // Exit code 0 received
    console.log('child process exited with ' + `code ${code} and signal ${signal}`);
});
```

Please disregard the difference in parameters between the 2 tests, I don't think they are relevant because I called nuclei from bash and it ran well and exited.

Please note that this is not only related to exit code. I am trying to create an automation workflow that involves nuclei, and I am also unable to get results from stdout (the exit code would have allowed me to output to a file and read that file when exit code was received). I've tried using verbose mode in nuclei, and various process spawning options and arguments, but still I can't get the results and I can't get it to exit. I've also tried spawning the process in C# to make sure that this is not related to some Node issue, and I encountered the same issue.

This worked fine in v2.1.0, so this is why I'm creating this issue. By building various versions I've managed to narrow the "faulty" commit to somewhere in between v2.1.0 (where it works) to v.2.4.3 (where it doesn't work).

**Comment by Ice3man543** [comment]
@stancu-mihai I think it could be related to the way nuclei handles stdin based input. If there is a file descriptor, it will continue trying to read it unless it reaches EOF so that could be the reason for it. I will test it out with the script you provided!

**Comment by Ice3man543** [comment]
I tested it out and made a PR #1286 which fixes the issue causing nuclei to run and exit normally with the provided nodejs script.

**Comment by ehsandeep** [comment]
@stancu-mihai thanks for reporting this, can you confirm if the fix pushed for this in following PR https://github.com/projectdiscovery/nuclei/pull/1286 solves the issue?

**Comment by stancu-mihai** [comment]
On my side this fixes the exit code and stdout issues for spawned process. However the issue reproduces when running nuclei with exact same parameters from bash. So... fixed for me, but probably will reproduce for anyone else. Please test running normally from bash before merging. Maybe it is a glitch on my side?

**Comment by ehsandeep** [comment]
@stancu-mihai thanks for confirming, do you have a bash snippet to share to double-check on our side?

**Comment by stancu-mihai** [comment]
The one below works well as child process but does nothing (is stuck after showing disclaimer) from bash (note that I am on origin/fix-stdin-parser branch):
`nuclei -u https://cover-photos.hackerone-user-content.com -debug`

**Comment by ehsandeep** [comment]
@stancu-mihai the fix for this has been reverted from dev as it needs to be improved further to cover a few more edge cases, will let you know once we push a fix for this.

**Comment by ehsandeep** [comment]
@stancu-mihai Can you try again from `fix-stdin-reading` branch?

**Comment by stancu-mihai** [comment]
Just tested now and for spawning from node:
```
const spawnChild =  spawn('nuclei', ['-u', 'https://cover-photos.hackerone-user-content.com', '-debug'], {});
spawnChild.stdout.on('data', function (data) {  
    console.log(data.toString());  
});  
spawnChild.stderr.on('data', function (data) {
    console.log(data.toString());  
});
spawnChild.on('close', function (code) {  
    console.log(`child process exited with code ${code} `);  
});  
spawnChild.on('exit', function (code, signal) {
    console.log('child process exited with ' + `code ${code} and signal ${signal}`);
});
```
... the weirdest thing happens. The data.toString() is visible in debugger if I place a breakpoint, but is not displayed in console. Maybe I have a local problem. I would say it works fine.

For bash
`nuclei -u https://cover-photos.hackerone-user-content.com -debug`
still doesn't display anything after the disclaimer.

If you've tested these cases on your end and they work fine, I wouldn't bother with it.
