### ISSUE TITLE
Multiple improvements with HTTP RAW format 

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#128]
I don't understand if this is a bug or I've missing something, but when I create a raw request template like this below, it looks like the request always ~adds '/' path automatically~ to `{{BaseURL}}` instead of `{{Hostname}}`.

```yaml
requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
```

Usage consume: `nuclei -target http://localhost/nowhere -t examples/dummy.yaml -proxy-url http://localhost:13378`

![Screenshot_2020-07-04_03-51-46](https://user-images.githubusercontent.com/25837540/86496967-d215fb00-bda9-11ea-9988-dd1062afff7d.png)

As you can see the URL request to `http://localhost/nowhere/`, not to **GET / HTTP/1.1** _(http://localhost/)_.

And other differences in the `User-Agent` header are not rewritten _(unlike requests in model template, it generates `"Go-http-client/*.*"`)_

Kind regards and have a nice weekend!

**Comment by bauthard** [comment]
Thank you, both issues are valid @dwisiswant0 and I found 3rd one while testing. 

- [ ] Appending `/` with the raw request. 

```
echo http://**.burpcollaborator.net/test | nuclei -t examples/http-raw.yaml
```
![image](https://user-images.githubusercontent.com/8293321/86506400-b54ee700-bdec-11ea-9edc-6d7d9c8f1fa4.png)

-----

- [ ] Updating user-agent with default one in case `user-agent` is not provided in the template. 

+ Remove the `User-agent` line from the template before running it. 

```
echo http://**.burpcollaborator.net/test | nuclei -t examples/http-raw.yaml
```
![image](https://user-images.githubusercontent.com/8293321/86506371-6f921e80-bdec-11ea-9fbc-e4cf039160e0.png)

-----

- [ ] Double requests are sent even defined single in the template.  

```
echo http://**.burpcollaborator.net/test | nuclei -t examples/http-raw.yaml
```

![image](https://user-images.githubusercontent.com/8293321/86506333-17f3b300-bdec-11ea-82f5-a2d318b10968.png)

**Comment by dwisiswant0** [comment]
Hi @bauthard, I can't reproduce double-requests. FYI, I'm working on the first & second issues.

**Comment by bauthard** [comment]
Thank you for the heads up.

**Comment by bauthard** [comment]
Hi @dwisiswant0, 

I was testing this change and found new changes were working as you suggested, but something is not working as expected which use to do before, here is how you can reproduce it. 

```bash
nuclei -t examples/http-raw.yaml -target http://kqecb72bl1d4n49x21b6q1jkhbn2br.burpcollaborator.net/gg
```

![image](https://user-images.githubusercontent.com/8293321/87273954-131fb500-c4f8-11ea-9864-1a83b974985e.png)

Notice the based request set to `/` instead of `/gg`

**Comment by dwisiswant0** [comment]
Do you use `BaseURL` instead of `Hosrname` in raw header?

**Comment by dwisiswant0** [comment]
I can confirm that the `BaseURL` value even before the PR related to this issue is also a pure value input the terminal. This also applies to normal templates, not just raw.

Should be create new issue, @bauthard?

**Comment by bauthard** [comment]
@dwisiswant0 DMing you on discord.

**Comment by bauthard** [comment]
Solved, not an issue.
