### ISSUE TITLE
Template loading Issue

### ISSUE THREAD

**Issue by yashanand** [projectdiscovery/nuclei#130]
I am not sure to abut this why this is behaving like this.
Steps to reproduce 
1. git clone https://github.com/projectdiscovery/nuclei-templates.git
This makes a nuclei-template directory in the current directory
2. mkdir template 
3.find nuclei-templates/ -name '*.*' -exec cp {} template \; 
This is copy all the file from nuclei-template.
4. nuclei -l url.txt -t template/
(I think this is why run all the template for each URL in the url.txt)
I am seeing this output from the above command.
![image](https://user-images.githubusercontent.com/21155589/86526589-9ebf9300-beb3-11ea-9a84-886d31f0eee4.png)

Why it loading template from nuclei-templates??

**Comment by bauthard** [comment]
Hi @yashanand, 

One possible reason could be, you don't have `template` directory on the location from where you are running the nuclei, in that case, nuclei look for default location. 

so make sure you have any custom directory in the current path you are running the nuclei or provide full path of your custom directory, for example:- `nuclei -l urls.txt -t /root/my-templates/`. 

let me know if that works for you.

**Comment by yashanand** [comment]
I have a template folder in the same directory, and it is only loading some cve from nuclei-template i don't know why this is happening.

**Comment by bauthard** [comment]
You can try to setup nuclei again? based on currently available information in this issue not sure what's wrong on your side.

**Comment by bauthard** [comment]
This is not an issue but expected behavior, this is output when running workflows, by default workflows load templates from the default location as defined in the template itself, shouldn't affect the scanning.

**Comment by yashanand** [comment]
ok, thanks for the update.
