### ISSUE TITLE
unable to build the main.go 

### ISSUE THREAD

**Issue by CR4ZYHUNT** [projectdiscovery/nuclei#1301]
i got this error when installing the go build

github.com/projectdiscovery/fileutil
/root/go/pkg/mod/github.com/projectdiscovery/fileutil@v0.0.0-20210928100737-cab279c5d4b5/file.go:198:18: undefined: os.CreateTemp

**Comment by ehsandeep** [comment]
@CR4ZYHUNT issue with go version in use, make sure you are running go1.17 to build / install nuclei, see the related issues - https://github.com/projectdiscovery/nuclei/issues?q=is%3Aissue+undefined+is%3Aclosed

**Comment by CR4ZYHUNT** [comment]
I installed the last version of go, but still not working

**Comment by CR4ZYHUNT** [comment]
Oh I saw one of the solution in the issues and it worked, thanks alot for
your time+ the great tool 🖤
