### ISSUE TITLE
Investigate a suitable solution for automated code metrics calculation

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1321]
- [x] research SAST cloud tools (e.g. SonarCloud, CodeClimate etc.)
- [x] aggregated code coverage for unit and integration tests 
  - find a way to execute the integration tests with code coverage
  - make sure the aggregation happens correctly (if the same lines are covered using both unit and integration tests, they should not be calculated twice)

The above mentioned tasks should be executed in an automated manner (e.g. using GitHub actions) on the `main` and `dev` branches. The results should be easily accessible and should potentially act as a quality gate, which prevents creating releases if the quality drops below a certain limit.

**Comment by Mzack9999** [comment]
Recommending `SonarCloud`, among setup easiness, the test coverage can be obtained by integrating via their GitHub action and with an additional step to run the specific language analyzer (as specified in the [docs](https://docs.sonarqube.org/latest/analysis/coverage/) ). Overall the setup takes less than 10 minutes.

**Comment by forgedhallpass** [comment]
Related ticket: https://github.com/projectdiscovery/nuclei/issues/1411
