### ISSUE TITLE
 Could not read nuclei-ignore file  and not ut

### ISSUE THREAD

**Issue by myrecollect** [projectdiscovery/nuclei#1366]
![image](https://user-images.githubusercontent.com/48248485/145786953-968edd51-7f19-4a03-bd4c-d43e617b54d6.png)

**Comment by zuiss** [comment]
me too on ubuntu

**Comment by ehsandeep** [comment]
@zuiss `rm -rf ~/.config/nuclei ~/nuclei-templates/ ; nuclei -ut` should fix the issue on ubuntu

**Comment by myrecollect** [comment]
![image](https://user-images.githubusercontent.com/48248485/145789742-64c64ca2-17dc-4bea-b2b2-b9fc1d35c81a.png)

**Comment by ehsandeep** [comment]
this should be fixed with latest release - https://github.com/projectdiscovery/nuclei/releases/tag/v2.5.5
