### ISSUE TITLE
Could not initialize interactsh client when running nuclei

### ISSUE THREAD

**Issue by patali09** [projectdiscovery/nuclei#1371]
\
After updating nuclei engine to Nuclei Engine 2.5.5 (latest), i am getting issue as "[ERR] Could not initialize interactsh client: could not create client: could not make register request: POST https://interact.sh/register giving up after 6 attempts: Post "https://interact.sh/register": dial tcp: lookup interact.sh on 8.8.8.8:53: server misbehaving
"
![Screenshot 2021-12-14 08:03:37](https://user-images.githubusercontent.com/55197156/145921040-31443421-6eeb-4f67-ac8f-8af091d2c0b9.png)

**Comment by a7t0fwa7** [comment]
Same issue

**Comment by Bywalks** [comment]
I meet this situation yesterday,it can not initialize interactsh client when running nuclei,and https://interact.sh can not visit,so i think this situation is because sometimes https://interact.sh can not be visit.

**Comment by ehsandeep** [comment]
@Bywalks @a7t0fwa7 @patali09 should be fixed by now.

**Comment by arun-netsentries** [comment]
This is not foxed ye.

**Comment by ehsandeep** [comment]
@arun-netsentries you need to update the client to latest version to reflect the changes.

**Comment by arun-netsentries** [comment]
I tried brew reinstall , fresh install , got based installation and everything , all fails. This is on a Mac M1 Intel based machine.

**Comment by 1213311** [comment]
$ go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest

[ERR] Could not initialize interactsh client: could not create client: could not make register request: POST https://interact.sh/register giving up after 6 attempts: Post "https://interact.sh/register": dial tcp: lookup interact.sh: no such host

**Comment by sirpratik** [comment]
hey guys, i got the solution (condition: if you are using kali on virtual machine)
just switch the network adapter to the bridge connection and that's all.
you are good to go
