### ISSUE TITLE
error in install  nuclei 

### ISSUE THREAD

**Issue by 00SoCRaT00** [projectdiscovery/nuclei#1377]

**Comment by forgedhallpass** [comment]
Duplicate of #1376

**Comment by 00SoCRaT00** [comment]
when i run as root 
GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei  
i got this error 
go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.5/internal/runner/update.go:27:2: //go:build comment without // +build comment
![image](https://user-images.githubusercontent.com/83826259/146257301-41799fa4-e70a-4b32-8ec2-da1f4c6cae21.png)

**Comment by 00SoCRaT00** [comment]
please any one help
