### ISSUE TITLE
Project doesn't prevent running templates again

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1379]
### Nuclei version:
Current Version: 2.5.5

### Current Behavior:
Project doesn't prevent running templates again

### Expected Behavior:
Project should prevent running templates again

### Steps To Reproduce:

1. Run
```bash
nuclei -u http://testphp.vulnweb.com -t ~/nuclei-templates -project -project-path `echo "$(pwd)/.cache"` 
```
2. Run 
```bash
nuclei -u http://testphp.vulnweb.com -t ~/nuclei-templates -project -project-path `echo "$(pwd)/.cache"` -debug -vv -p http://127.0.0.1:8080
```
3. Project don't prevent running templates again

**Comment by ehsandeep** [comment]
@brenocss this is now fixed in the dev version.
