### ISSUE TITLE
Functional tests target outdated version of macOS

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#1387]
### Nuclei version:
dev

### Current Behavior:
Functional tests are executed for `macos-11.0` and `macOS-latest` 

### Expected Behavior:
Unless also older OS versions are tested (not a bad idea), I think it's enough to target `macOS-latest`

**Comment by forgedhallpass** [comment]
`macOS-11` is the latest (`BigSur`). `macOS-latest` refers to `Catalina`. 
Reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

![image](https://user-images.githubusercontent.com/13679401/146522315-44267c86-d306-427b-8661-b9b7b6269adb.png)

**Comment by forgedhallpass** [comment]
Update: `macOS-11` will soon become `macOS-latest`, so indeed, we can rely on the latter.

https://github.com/actions/virtual-environments/issues/4060
