### ISSUE TITLE
Add support for missing http(s)

### ISSUE THREAD

**Issue by eugui** [projectdiscovery/nuclei#14]
Hi,

is it possible to support a list of urls with no http/https?

**Comment by Ice3man543** [comment]
Hey, you can easily do that by using this path - `http://{{BaseURL}}/<path here>`. This should work.

**Comment by eugui** [comment]
yes...I did this:
cat test2 | sed 's/^/https:\/\//g' | ./nuclei -t nuclei-templates/files/git-config.yaml
