### ISSUE TITLE
[ Issue ] In Updating the engine

### ISSUE THREAD

**Issue by nithissh200** [projectdiscovery/nuclei#1401]
Could not create runner: no compatible binary found for linux/amd64

![2C298C63-57BC-42E6-B9A5-96EEC3AABB04](https://user-images.githubusercontent.com/93642429/146674035-f0c2c79c-15e6-43a5-b20d-844ab9b7ba58.png)

**Comment by ehsandeep** [comment]
@nithissh200 you need to add `-itags fuzz` to run templates including fuzz tags in it, see the details - https://github.com/projectdiscovery/nuclei/discussions/1337
