### ISSUE TITLE
DSL expressions between quotes are not evaluated correctly

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1419]
The problem is with the following regular expression that matches the trailing `"` as well:

https://github.com/projectdiscovery/nuclei/blob/6cde5843b53104fbd6debd5f8ee5339708648743/v2/pkg/protocols/common/expressions/expressions.go#L13

It has to be rewritten using a lexical analyzer.

Testcase to be added:
```golang
{input: `"{{hex_encode('PING')}}"`, expected: `"50494e47"`, extra: map[string]interface{}{}},
```

See: https://github.com/projectdiscovery/nuclei/blob/6cde5843b53104fbd6debd5f8ee5339708648743/v2/pkg/protocols/common/expressions/expressions_test.go#L15

----

### Discussed in https://github.com/projectdiscovery/nuclei/discussions/1415

<div type='discussions-op-text'>

<sup>Originally posted by **niudaii** December 21, 2021</sup>
```
id: xxxx

info:
  name: xxxx
  author: zp857
  severity: critical
  description: xxxx
  reference: xxxx
  tags: xxxx

requests:
  - raw:
      - |
        POST /xxx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json
        
        {
          "xxx": "{{rand_text_alpha(11)}}",
          "yyy": 1, 
        }

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "xxxxx"
```
When I use the above file the following happens, if I remove the double quotes outside {{}}, I can use the helper function.
![image](https://user-images.githubusercontent.com/41844046/146881095-b25935a9-3497-4ae8-b122-5eff582225d8.png)
```
id: xxxx

info:
  name: xxxx
  author: zp857
  severity: critical
  description: xxxx
  reference: xxxx
  tags: xxxx

requests:
  - raw:
      - |
        POST /xxx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json
        
        {
          "xxx": {{rand_text_alpha(11)}},
          "yyy": 1, 
        }

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "xxxxx"
```
<img width="1283" alt="image-20211221142549305" src="https://user-images.githubusercontent.com/41844046/146882368-777df1f7-e4fa-493d-abc2-5d5d888e801c.png"></div>

**Comment by forgedhallpass** [comment]
Hello @niudaii,

Thanks for reporting the issue. Until the issue is fixed, you can use the following workaround in your template to wrap the generated payload with double quotes:

`"xxx": {{repeat("\"", 1)}}{{rand_text_alpha(11)}}{{repeat("\"", 1)}},`
OR
`"xxx": {{rand_char("\"")}}{{rand_text_alpha(11)}}{{rand_char("\"")}},`

**Comment by rskvp93** [comment]
Hi,
I found another issue with some expressions that contains the character '}'.
For example: {{url_encode('test}aaa')}}  
The parser didn't allow the character '}' inside {{...}}

**Comment by ehsandeep** [comment]
@niudaii @rskvp93 this is now fixed in the dev version with https://github.com/projectdiscovery/nuclei/pull/1440
