### ISSUE TITLE
Not able to update nuclei

### ISSUE THREAD

**Issue by AmbitiousSam** [projectdiscovery/nuclei#1430]
Trying to update nuclei from 2.5.4 to 2.5.7 on macos Monterey but gives me an build error.

### Anything else:

![Screenshot 2021-12-29 at 8 53 39 AM](https://user-images.githubusercontent.com/54389032/147624479-84f9ec79-fcea-4c8f-86e8-76cd421d3598.png)

**Comment by ehsandeep** [comment]
@AmbitiousSam that’s error related to outdated go version in nuclei, you can use “nuclei -update” to update to latest version or update your go environment.

**Comment by AmbitiousSam** [comment]
`nuclei -update` also doesnt work
![Screenshot 2021-12-29 at 1 05 20 PM](https://user-images.githubusercontent.com/54389032/147638118-cf02270f-15f0-4329-a225-a0527c24313a.png)
