### ISSUE TITLE
More global variables for HTTP protocol

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei#1433]
### Please describe your feature request:

Porting DNS protocol support global variables to HTTP protocol as described in #1174 and implemented in #1185

### Describe the use case of this feature:

```
  - raw:
      - |
        GET /{{domain}}.zip HTTP/1.1
        Host: {{Hostname}}
```

```
nuclei -t test.yaml -duc -debug -u http://testphp.vulnweb.com/

GET /vulnweb.zip HTTP/1.1
Host: testphp.vulnweb.com
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
Connection: close
Accept-Encoding: gzip
```

---

```
  - raw:
      - |
        GET /{{subdomain}}.zip HTTP/1.1
        Host: {{Hostname}}
```

```
nuclei -t test.yaml -duc -debug -u http://testphp.vulnweb.com/

GET /testphp.zip HTTP/1.1
Host: testphp.vulnweb.com
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
Connection: close
Accept-Encoding: gzip
```

**Comment by ehsandeep** [comment]
@No-Github thanks for this feature request, this is already supported for DNS protocol as described here - https://github.com/projectdiscovery/nuclei/issues/1174 and we can port the same variables for HTTP protocol as well.

**Comment by No-Github** [comment]
Great!

**Comment by ehsandeep** [comment]
@No-Github this is now supported in dev version for HTTP protocol.

- [x] `{{FQDN}}` - Fully qualified domain name (already supported)
- [x] `{{RDN}}` - Root domain name
- [x] `{{DN}}` - Domain name
- [x] `{{TLD}}` - Toplevel domain
- [x] `{{SD}}` - Sub domain

and here is how it can be interpreted using an example as `www.projectdiscovery.io`

| Global Variable | Example value           |
|-----------------|-------------------------|
| `{{FQDN}}`      | www.projectdiscovery.io |
| `{{RDN}}`       | projectdiscovery.io     |
| `{{DN}}`        | projectdiscovery        |
| `{{TLD}}`       | io                      |
| `{{SD}}`       | www                     |
