### ISSUE TITLE
how to scan full folder

### ISSUE THREAD

**Issue by noob0x01** [projectdiscovery/nuclei#1454]
Hey,
example , i have a folder

test > domain1.txt , domain2.txt , domain3.txt

how to scan full folder?

@ehsandeep bro

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/nuclei/discussions/1450#discussioncomment-1906392

**Comment by mohammedshine** [comment]
> Hey, example , i have a folder
> 
> test > domain1.txt , domain2.txt , domain3.txt
> 
> how to scan full folder?
> 
> @ehsandeep bro

Open the folder and use cat *.txt | nuclei -t nuclei-templates
