### ISSUE TITLE
Disable Unsolicited Response from servers

### ISSUE THREAD

**Issue by bugbountysatu** [projectdiscovery/nuclei#1463]
Why nuclei always Response like here

2022/01/06 15:52:41 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>

**Comment by ehsandeep** [comment]
@bugbountysatu this is not an issue or bug, but a information generated based on server responses that can be disabled.

**Comment by bugbountysatu** [comment]
This issue because I use Axiom, but if I am not use Axiom, nuclei is working fine
