### ISSUE TITLE
Multiple type of input support for templates

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#147]
Example:- 

```
nuclei -l urls.txt -t cves/ tokens/ 
```

```
nuclei -l urls.txt -t test.yaml token.yaml 
```

```
nuclei -l urls.txt -t test.yaml cves/
```

**Comment by manuelbua** [comment]
I'm proposing a pull request for this, but i implemented multiple `-t arg` options (the same as with `-H`) because that is inline with the general POSIX convention.

**Comment by bauthard** [comment]
Added in https://github.com/projectdiscovery/nuclei/pull/155
