### ISSUE TITLE
Could not find template 'nuclei-templates/subdomain-takeover/detect-all-takeovers.yaml

### ISSUE THREAD

**Issue by vansh1** [projectdiscovery/nuclei#1470]
i have updated version with updates templates 

### Current Behavior:
i am getting this error while running nuclei templates subdomain takeover 
### Expected Behavior:
it should run the subdomain takeover with my given url list

**Comment by ehsandeep** [comment]
@vansh1 you can use instead `nuclei -t takeovers`
