### ISSUE TITLE
Scan of the app based on technology

### ISSUE THREAD

**Issue by w9w** [projectdiscovery/nuclei#1498]
Hi, I'd like to add a feature request - scanning of the application depending on the technology that identified using github.com/projectdiscovery/wappalyzergo; if technologies aren't found - run an attack with all workflows. It'll decrease the scanning time and throw away excess load on the server. For example,

if "WordPress" in tech:
    nuclei -w ~/nuclei-templates/workflows/wordpress
else:
    nuclei -w ~/nuclei-templates/workflows

**Comment by geeknik** [comment]
Thanks for the suggestion, but this technology already exists in the community repo. 

https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/tech-detect.yaml
https://github.com/projectdiscovery/nuclei-templates/tree/master/technologies

👍🏻

**Comment by w9w** [comment]
Hi @geeknik! Indeed, the script for technology identifying already exists here https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/tech-detect.yaml but it's not running an automatic scan based on the technology.

**Comment by ehsandeep** [comment]
Existing discussion: https://github.com/projectdiscovery/nuclei/discussions/1477 for this feature.

**Comment by vulnz** [comment]
Good day, is it implemented?
how to use it?
is it any specific flag?
where can i see how it works?
thanks

**Comment by ehsandeep** [comment]
@vulnz `nuclei -as -l urls.txt`

```yaml
   -as, -automatic-scan         automatic web scan using wappalyzer technology detection to tags mapping
```

**Comment by vulnz** [comment]
Great @ehsandeep  thanks, you are awesome, can you please tell me how exactly this script works?
thanks
