### ISSUE TITLE
Add header suppression in templates

### ISSUE THREAD

**Issue by br-sn** [projectdiscovery/nuclei#15]
Hi,

Thanks for this great tool, have enjoyed using it so far. 

I wanted to suggest a feature where you could suppress some headers in a template, in the same way you could suppress for example the 'Host:' header in curl by specifying an empty header. This is handy in some research scenarios. 

In addition, it would be great if there was a way to also specify more parts of the request in general via the templates, such as the HTTP version. 

Cheers

**Comment by bauthard** [comment]
Thank you for the suggestion @br-sn, It looks like an interesting idea to me, we will make sure to get this added asap.

**Comment by bauthard** [comment]
Hey @br-sn, 

This is partially done with https://github.com/projectdiscovery/nuclei/pull/61 with support of the RAW request, now you can just copy-paste or submit a complete raw request to `nuclei`. 

We have no ETA for adding the ability to suppress headers as this will require customization in the standard lib.

**Comment by Mzack9999** [comment]
Implemented in #76 - Closing the issue
