### ISSUE TITLE
Adding extractor support to RAW and DNS request

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#150]
[Extractors](https://github.com/projectdiscovery/nuclei-templates/blob/master/GUIDE.md#extractors) can be used to extract and display in results a match from the response body or headers based on a regular expression, but as of now it can be only used with basic request format, as for further enhancements to reuse responses data, we need to add **extractors** for all request method we have, for example, **RAW request**, **DNS request**.

**Comment by bauthard** [comment]
Example template for RAW request, similarly for DNS request as well. 

```
id: http-raw-extractor

info:
  name: HTTP Raw Test
  author: pdteam
  severity: info

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        Connection: close
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Accept-Encoding: gzip, deflate
        Accept-Language: en-US,en;q=0.9
        
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "AIza[0-9A-Za-z\\-_]{35}"
    extractors:
      - type: regex
        part: body
        regex:
          - "AIza[0-9A-Za-z\\-_]{35}"
```

**Comment by Mzack9999** [comment]
- Raw HTTP requests already use existing HTTP extractors
- DNS Already implement extractors https://github.com/projectdiscovery/nuclei/blob/34224c537b276b6e7934684cfbe05c3c710fc839/v2/pkg/executor/executor_dns.go#L130-L135

**Comment by bauthard** [comment]
@Mzack9999 as discussed, this needs to be confirmed with sample templates shared above.

**Comment by Mzack9999** [comment]
Confirmed to work on #158
