### ISSUE TITLE
Error in scan | Unsolicited response received on idle HTTP channel

### ISSUE THREAD

**Issue by aniruddhmistry** [projectdiscovery/nuclei#1525]
Hi Team, 

After the update, I'm getting this error. 
this error has not come in every scan, it comes in 7 out of 10. 

### Nuclei version: 2.5.8

` Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:37 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:39 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:39 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:39 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:39 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:41 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:41 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:44 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:57 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>Forbidden</h2>\n"; err=<nil>
2022/01/21 18:13:58 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 403 Forbidden\r\nContent-Length: 19\r\nContent-Type: text/html\r\n\r\n<h2>`

**Comment by ehsandeep** [comment]
@aniruddhmistry we are tracking this at https://github.com/projectdiscovery/nuclei/issues/1463
