### ISSUE TITLE
Disable CLI color for windows

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1535]
### Please describe your feature request:
As CLI colors are not supported by default in Windows terminal, it would be useful to disable the color.

### Describe the use case of this feature:
enable `-no-color` flag is `if runtime.GOOS == "windows"`

**Comment by forgedhallpass** [comment]
Colors can be enabled on Windows also. See: https://github.com/projectdiscovery/nuclei/discussions/1509#discussioncomment-1990212

If we make this change, then it will be disabled for those people as well.

**Comment by ehsandeep** [comment]
Closing, as disabing as default will not allow windows users to enable the colors.
