### ISSUE TITLE
nuclei unable to parse absolute path for templates

### ISSUE THREAD

**Issue by ipk1** [projectdiscovery/nuclei#154]
hi,

when i run nuclei with templates ex:
nuclei -l urls.txt -t /root/tools/nuclei/nuclei-templates/cve/
 the following error is encountered  when it is run from either root path or some other directory, giving the absolute path does work however if i give the relative path from the current directory it works
[ERR] Could not find template file '': no such path found: /root/tools/nuclei/nuclei-templates/cve/

thanks

**Comment by bauthard** [comment]
Hi @ipk1, 

Please do include the nuclei version to make sure you are on the latest version. 

```
nuclei -version
```

**Comment by ipk1** [comment]
Current Version: 1.1.7

**Comment by bauthard** [comment]
Hi @ipk1, 

The latest version of nuclei is `2.0.4`, please make sure you are on the latest version.

**Comment by bauthard** [comment]
an issue with using the older version.
