### ISSUE TITLE
Support for DNS CAA record in DNS template

### ISSUE THREAD

**Issue by righettod** [projectdiscovery/nuclei#1542]
### Please describe your feature request:

Hi, 

It is planned to add support for the [CAA DNS record](https://docs.gandi.net/en/domain_names/faq/record_types/caa_record.html) in [DNS template](https://nuclei.projectdiscovery.io/templating-guide/protocols/dns/#type). Currently its supporting the following record types: `A, NS, CNAME, SOA, PTR, MX, TXT, AAAA` 

```console
dig caa google.com

; <<>> DiG 9.10.6 <<>> caa google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5193
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	CAA

;; ANSWER SECTION:
google.com.		21600	IN	CAA	0 issue "pki.goog"

;; Query time: 116 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jan 27 18:22:14 IST 2022
;; MSG SIZE  rcvd: 66
```

### Describe the use case of this feature:

The goal is to create templates verifying the presence of **CAA** record for a domain in a context of monitoring or post deployment security validations. Using nuclei for this can help to have a cross-platform way to do it in addition to all other existing templates that can be leveraged for such monitoring/validations.

It is a defensive usage of nuclei 😃 

Thank you very much in advance and thanks again x10000... for this amazing tool 🥇

**Comment by ehsandeep** [comment]
@righettod Thanks to your feature request, this is now supported in the dev version.

**Comment by righettod** [comment]
Guys you are all amazing !!!!

Thank you so much ❤️ ❤️ ❤️

**Comment by righettod** [comment]
Thank you very much 🥇
