### ISSUE TITLE
DSL extractors to extract response effective size

### ISSUE THREAD

**Issue by j4cqui** [projectdiscovery/nuclei#1565]
### Please describe your feature request:
Can you add the possibility to see the size of the response. 

Web server doesn't always send the `Content-Length` header, and that can be a great improvement to have the size of the response.

### Describe the use case of this feature:

When you are using some templates to dump information, which can be useful to see which one is dumping the largest or not only one information. Or when you are working on large scope to prioritize certain assets.

**Comment by Mzack9999** [comment]
The response size (calculated on the effective body length) is already available among the matchers. Hence it's already possible to filter out the assets according to any specific logic. For a quick flyover of the targets, probably httpx would be a better option.

**Comment by ehsandeep** [comment]
@j4cqui now you can do with using newly added DSL extractors:

```yaml
    extractors:
      - type: dsl
        dsl:
          - "len(body)"
```
