### ISSUE TITLE
Could not register to oast.me 

### ISSUE THREAD

**Issue by Mah3Sec** [projectdiscovery/nuclei#1566]
Hi Team, I'm facing a issue while using nuclei : 
Could not register to oast.me: could not make register request: POST https://oast.me/register giving up after 6 attempts: Post "https://oast.me/register": dial tcp: lookup oast.me: Temporary failure in name resolution, retrying with remaining
![image](https://user-images.githubusercontent.com/53621283/152189111-03476427-9c4c-490a-9c80-8c4a371e87e4.png)

I'm facing this issue in both my kali and ubuntu vm's.

**Comment by byteofjoshua** [comment]
It' still errors today, I have same problems

**Comment by ehsandeep** [comment]
this should be fixed with the latest release.

**Comment by nischalbijukchhe** [comment]
it's still error today, please provide fix

**Comment by anasbousselham** [comment]
The same problem for every requests
`[ERR] Could not register to oast.fun: could not make register request: POST https://oast.fun/register giving up after 6 attempts: Post "https://oast.fun/register": dial tcp 206.189.156.69:443: i/o timeout, retrying with remaining`

**Comment by adrianhomeuca** [comment]
Still same error:
[ERR] Could not register to oast.me: could not make register request: POST https://oast.me/register giving up after 6 attempts: Post "https://oast.me/register": dial tcp 178.128.209.14:443: i/o timeout, retrying with remaining
[ERR] Could not register to oast.me: could not make register request: POST https://oast.site/register giving up after 6 attempts: Post "https://oast.site/register": net/http: TLS handshake timeout, retrying with remaining
[INF] Using Interactsh Server: oast.online

**Comment by orangmuda** [comment]
**Hi!** @adrianhomeuca 

Please hidden our ip, attacker can steal it for more find sentivie on our Mac.

**Comment by pomsan** [comment]
Hi! I'm facing the same issue.

**Comment by the5orcerer** [comment]
I still facing this issue on my VPS on still 2024!
![Image](https://github.com/user-attachments/assets/11403c87-2d63-4e91-a5fd-604020d97bd3)
In first glance i mean in first three requests it's not generating links but after tries it makes but as i know nuclei templates takes first response of result. I'm facing this issue also in my WSL machine. 

Please provide some info, how can i make it work?

Thanks 
Abu Hurayra
