### ISSUE TITLE
Add gzip_decode() helper function

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1575]
### Please describe your feature request:

`gzip_decode(<gzipcontent>)`
### Describe the use case of this feature:

`contains(hex_encode(base64_decode(gzip_decode(gzipcontent))), 'ACED0005')`

**Comment by forgedhallpass** [comment]
The documentation has to be updated:
* https://github.com/projectdiscovery/nuclei-docs/blob/master/docs/template-examples/helper-functions.md
* https://github.com/projectdiscovery/nuclei-docs/blob/master/docs/templating-guide/helper-functions.md

These tests should also be extended (with every DSL function change):
* https://github.com/projectdiscovery/nuclei/blob/master/integration_tests/http/dsl-functions.yaml
* https://github.com/projectdiscovery/nuclei/blob/7f6c72853f2345a1f25094a9aeac60edca874e15/v2/pkg/operators/common/dsl/dsl_test.go#L152
