### ISSUE TITLE
base64 bug in Authorization

### ISSUE THREAD

**Issue by signfind** [projectdiscovery/nuclei#1604]
### Nuclei version:

```
[INF] Using Nuclei Engine 2.6.0 (latest)
[INF] Using Nuclei Templates 8.8.4 (latest)
```
### Current Behavior:

When i studying testing The Tomcat HTTP Basic Authentication bruteforce from your blog post : https://blog.projectdiscovery.io/community-powered-scanning-with-nuclei/ 
use the same template ,but burp record show the base64 not work well : 
#### burp record:
```
GET /manager/html HTTP/1.1
Host: 172.18.60.75:8089
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Authorization: Basic YWRtaW4=
Connection: close


```
`YWRtaW4=` base64decode is admin ,looks like the base64 in Authorization with bug ?

#### template:
```
id: http-raw-bruteforce
info:
  name: HTTP Basic authentication Bruteforce
  author: pdteam

requests:
  - payloads:
      username: username.txt
      password: password.txt
    attack: clusterbomb 

    raw:
      - |
        GET /manager/html HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic {{base64(username:password)}}  
        Accept-Encoding: gzip, deflate        
        Accept-Language: en-US,en;q=0.9
        Connection: close        
    # threads: 30
    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 200
```
the username.txt and password.txt like this:
admin
admin
123456

### Expected Behavior:

`admin:admin` ==> `YWRtaW46YWRtaW4=`
Authorization: Basic YWRtaW46YWRtaW4=

**Comment by ehsandeep** [comment]
@signfind there is an syntax issue with shared template, you can just take a took at [existing valid tempalte](https://github.com/projectdiscovery/nuclei-templates/blob/master/default-logins/apache/tomcat-default-login.yaml) for detecting the same issue.

**Comment by signfind** [comment]
@ehsandeep  thank u ,it's work well now !
