### ISSUE TITLE
Align extractors with matchers

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#161]
- Support conditions 
- Support multiple extractors (possible for now as well, not in a matcher format)
- Output formatting in the case of multiple extractors. 

**This issue is created for tracking purposes only, this will be worked on in the future when any use case requires this change.**  

### Reference:- 
https://github.com/projectdiscovery/nuclei/pull/158

**Comment by bauthard** [comment]
Check https://github.com/projectdiscovery/nuclei/issues/241 for more details

**Comment by ehsandeep** [comment]
Closing this issue as no action is needed now for the following reasons:

- Conditions are not required for extractors
- Extractors type and Matchers type, so not necessarily it's possible to port supported matchers type as extractor
