### ISSUE TITLE
update doenst support go1.14.1

### ISSUE THREAD

**Issue by ipk1** [projectdiscovery/nuclei#164]
hi,

when i try to update using GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei i get the following error

# math/bits
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# internal/race
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# runtime/internal/sys
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# unicode/utf8
compile: version "go1.14.1" does not match go tool version "go1.13.4"
unicode/utf16
encoding
crypto/subtle
# unicode
compile: version "go1.14.1" does not match go tool version "go1.13.4"
crypto/internal/subtle
image/color
# unicode/utf16
compile: version "go1.14.1" does not match go tool version "go1.13.4"
container/list
# encoding
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# crypto/internal/subtle
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# crypto/subtle
compile: version "go1.14.1" does not match go tool version "go1.13.4"
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
# image/color
compile: version "go1.14.1" does not match go tool version "go1.13.4"
vendor/golang.org/x/crypto/internal/subtle
# container/list
compile: version "go1.14.1" does not match go tool version "go1.13.4"
golang.org/x/net/internal/iana
internal/cpu
runtime/internal/atomic
sync/atomic
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.14.1" does not match go tool version "go1.13.4"
golang.org/x/sys/internal/unsafeheader
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# internal/nettrace
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# golang.org/x/net/internal/iana
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# sync/atomic
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# runtime/internal/atomic
compile: version "go1.14.1" does not match go tool version "go1.13.4"
# internal/cpu
compile: version "go1.14.1" does not match go tool version "go1.13.4"
runtime/cgo
# runtime/cgo
compile: version "go1.14.1" does not match go tool version "go1.13.4"

thanks

**Comment by bauthard** [comment]
Hey, as the error indicates you are using an outdated version of go, make sure to update it in order to install this from source, otherwise, you can still use the [binary](https://github.com/projectdiscovery/nuclei/releases) file. 

> compile: version "go1.14.1" does not match go tool version "go1.13.4"
