### ISSUE TITLE
Integrate docs in the nuclei repo and generate compiled docs on release

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#1657]
### Please describe your feature request:
Currently, nuclei docs are stored in [another repo](https://github.com/projectdiscovery/nuclei-docs) which increases maintenance and updating problems of the docs with each new release of nuclei.

We can store the docs In a directory called `docs/` in nuclei repo which will make maintenance easier and also it should be made necessary to update docs with engine updates as a PR step.

We also need to identify things that are missing in current docs and update them. Versioned docs can be created based on tagged nuclei releases.

**Comment by ehsandeep** [comment]
Documentation update:

- [ ] SSL Protocol (new)
- [ ] WSS Protocol (new)
- [ ] File Protocol (update)
- [ ] Raw HTTP (update)
- [ ] Network protocol (update)
- [ ] New Global variables (update)
- [ ] Helpers / Variables use in matchers / extractros (update)
- [ ] Template attributes (new)

**Comment by ehsandeep** [comment]
This is being worked on at https://github.com/projectdiscovery/nuclei/tree/docs-work
