### ISSUE TITLE
Could not update templates

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei#1679]
hi
after upgrade nuclei template not update  automatically
![image](https://user-images.githubusercontent.com/30596083/156873402-380532bc-4a79-4139-9ca7-4e50e9ffc7c2.png)

**Comment by dnmrbughunter** [comment]
Same here

**Comment by ehsandeep** [comment]
unable to reproduce this on any environment (ubuntu,mac,windows)

```console
root@testing-box:~# nuclei

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v8.8.8) to /root/nuclei-templates. GoodLuck!
[INF] Using Nuclei Engine 2.6.3 (latest)
[INF] Using Nuclei Templates 8.8.8 (latest)
[INF] Templates added in last update: 1
[INF] Templates loaded for scan: 2987
[INF] No results found. Better luck next time!
```

**Comment by D82R** [comment]
I am getting the same error as well. I uninstalled both nuclei and my template folder, reinstalled both and still get the same error
![2022-03-08-15:44:36-screenshot](https://user-images.githubusercontent.com/65426697/157330982-79dd71e1-e48d-4fe8-aebf-5b0c489c5fd8.png)
.

**Comment by d1pakda5** [comment]
same error i am getting also

**Comment by shelu16** [comment]
root@new:~# nuclei -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.3

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[ERR] Could not update templates: GET https://api.github.com/repos/projectdiscovery/nuclei-templates/releases/tags/v8.8.8: 401 Bad credentials []
root@new:~# uname -a
Linux new.localhost.com 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 GNU/Linux
root@new:~#

**Comment by lambardarr** [comment]
not fixed
can anyone assist?

**Comment by eremit4** [comment]
Up
The same error here
