### ISSUE TITLE
Date function on nuclei

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei#1680]
### Please describe your feature request:
- I want nuclei to have a function to enter the date and hour, for example like this:

```
id: date-function

info:
  name: Date function example
  author: daffainfo
  severity: info

requests:
  - raw:
      - |
        GET /log/{{date(%Y-%m-%d)}}.log HTTP/1.1
        Host: {{Hostname}}
...
```
And the request will be like this

https://example.com/log/2022-03-06.log

**Comment by bhutch** [comment]
As discussed with `@pd-team` on Discord `#nuclei-templates`, it would also be good to have a `unixtime` to human-readable `data` format for templates such as `ssl/expired-ssl.yaml`.

I'll mention that here for tracking.
