### ISSUE TITLE
Ability to Pin Specific Release Version of nuclei-templates

### ISSUE THREAD

**Issue by ErikOwen** [projectdiscovery/nuclei#1726]
### Please describe your feature request:
Currently I can use the `-update-templates` flag to update nuclei-templates to the latest version. Ideally there would be another flag to pin the nuclei-templates to a specific release version of nuclei-templates.

### Describe the use case of this feature:

As a Security Engineer, I want to have the ability to control which nuclei-templates templates are ran against a target, and **what version** of those templates are run against a target, so that I have strict control over what HTTP requests are being made against the target. Currently I can only run the latest version of nuclei templates. This worries me because if updates are made to a template that create new HTTP requests or change existing HTTP requests, I have lost the ability to audit these changes.

**Comment by forgedhallpass** [comment]
@ErikOwen have you seen this thread https://github.com/projectdiscovery/nuclei/discussions/1125?

**Comment by ErikOwen** [comment]
I have not. Thanks for the link, @forgedhallpass. Has the `-no-update-templates` flag been changed to `-disable-update-check`?

**Comment by ErikOwen** [comment]
The solution in #1125 is what I am looking for. Thanks @forgedhallpass.

**Comment by forgedhallpass** [comment]
> Has the `-no-update-templates` flag been changed to `-disable-update-check`?

Yes.

> The solution in https://github.com/projectdiscovery/nuclei/discussions/1125 is what I am looking for. Thanks

Glad to hear that, you are welcome :)
