### ISSUE TITLE
Failed to create template base folder.

### ISSUE THREAD

**Issue by sar00n** [projectdiscovery/nuclei#1751]
After updating go lang to its latest version go version go1.18 linux/amd64 and updating nuclei to 2.6.5. whenever i tried to update the templates it show the following error :

```console
nuclei -update-templates

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[ERR] Could not update templates: failed to create template base folder: mkdir : no such file or directory
```

**Comment by Mzack9999** [comment]
@sar00n I'm unable to reproduce the issue, looks like that for some reason the configured template base folder is not created. Is it different from the default one (`~/nuclei-templates`)? Can you check if your user (or the one running nuclei) has enough privileges to create the directory defined in `~/.config/nuclei/.templates-config.json` with key `nuclei-templates-directory` with the following command:
```console
$ mkdir ~/nuclei-templates # replace the path if different from default
$ ls -la ~/nuclei-templates
total 744
drwxr-xr-x 22 m m   4096 mar 29 18:33 .
drwxr-xr-x 24 m m   4096 mar 29 18:33 ..
-rw-rw-r--  1 m m 315379 mar 29 18:33 .checksum
drwxr-xr-x  6 m m   4096 mar 29 18:33 cnvd
...
```

**Comment by admin402** [comment]
I am also facing the same problem.
I have verified the privileges using `ls -la ~/nuclei-templates` command it gives output like:
`total 1544`
`drwxr-xr-x   32 user_name  staff    1024 Mar 31 12:24 .`
`drwxr-xr-x+  72 user_name  staff    2304 Mar 31 12:24 ..`
`-rw-r--r--    1 user_name  staff  346077 Mar 31 12:24 .checksum`
`-rwxr-xr-x    1 user_name  staff  122900 Mar 31 12:24 .new-additions`
`-rwxr-xr-x    1 user_name  staff    3359 Mar 31 12:24 CODE_OF_CONDUCT.md`
`-rwxr-xr-x    1 user_name  staff    4453 Mar 31 12:24 CONTRIBUTING.md`
`-rwxr-xr-x    1 user_name  staff    1079 Mar 31 12:24 LICENSE.md`
`-rwxr-xr-x    1 user_name  staff    1196 Mar 31 12:24 PULL_REQUEST_TEMPLATE.md`
`-rwxr-xr-x    1 user_name  staff   55843 Mar 31 12:24 TEMPLATES-STATS.json`
`-rwxr-xr-x    1 user_name  staff  198860 Mar 31 12:24 TEMPLATES-STATS.md`
`-rwxr-xr-x    1 user_name  staff    1320 Mar 31 12:24 TOP-10.md`
`drwxr-xr-x    6 user_name  staff     192 Mar 31 12:24 cnvd`
`-rwxr-xr-x    1 user_name  staff   32275 Mar 31 12:24 contributors.json`
`drwxr-xr-x   24 user_name  staff     768 Mar 31 12:24 cves`
`drwxr-xr-x   78 user_name  staff    2496 Mar 31 12:24 default-logins`
`drwxr-xr-x   19 user_name  staff     608 Mar 31 12:24 dns`
`drwxr-xr-x  440 user_name  staff   14080 Mar 31 12:24 exposed-panels`
`drwxr-xr-x    8 user_name  staff     256 Mar 31 12:24 exposures`
`drwxr-xr-x   10 user_name  staff     320 Mar 31 12:24 file`
`drwxr-xr-x   13 user_name  staff     416 Mar 31 12:24 fuzzing`
`drwxr-xr-x    8 user_name  staff     256 Mar 31 12:24 headless`
`drwxr-xr-x    4 user_name  staff     128 Mar 31 12:24 helpers`
`drwxr-xr-x   40 user_name  staff    1280 Mar 31 12:24 iot`
`drwxr-xr-x   24 user_name  staff     768 Mar 31 12:24 miscellaneous`
`drwxr-xr-x  127 user_name  staff    4064 Mar 31 12:24 misconfiguration`
`drwxr-xr-x   37 user_name  staff    1184 Mar 31 12:24 network`
`drwxr-xr-x    6 user_name  staff     192 Mar 31 12:24 ssl`
`drwxr-xr-x   69 user_name  staff    2208 Mar 31 12:24 takeovers`
`drwxr-xr-x  189 user_name  staff    6048 Mar 31 12:24 technologies`
`drwxr-xr-x  152 user_name  staff    4864 Mar 31 12:24 token-spray`
`drwxr-xr-x   39 user_name  staff    1248 Mar 31 12:24 vulnerabilities`
`drwxr-xr-x  187 user_name  staff    5984 Mar 31 12:24 workflows`


still I am facing the following error:
`[ERR] Could not update templates: failed to create template base folder: mkdir : no such file or directory`

**Comment by xnl-h4ck3r** [comment]
Hi. I had the same issue. The directory `~/nuclei-templates` did exist and I had correct permissions.
I solve the problem by editing `~/.config/nuclei/.templates-config.json` and manually adding `"nuclei-templates-directory":"/home/xnl/nuclei-templates"` to the settings because it was missing.

**Comment by soupnatzi** [comment]
am still facing this issue:

nuclei -update-templates

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.5

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[ERR] Could not update templates: failed to create template base folder: mkdir : no such file or directory

**Comment by ehsandeep** [comment]
This is now fixed in the dev version of the project.
