### ISSUE TITLE
downloading issues.

### ISSUE THREAD

**Issue by sushantdhopat19** [projectdiscovery/nuclei#176]
i am downloading this tool using the git clone i run this following cmd
$ > git clone https://github.com/projectdiscovery/nuclei.git
 i give the foolowing error 

fatal: could not create work tree dir 'nuclei': Read-only file system

how can i solve this error.

**Comment by manuelbua** [comment]
It looks like you don't have any writing permissions where you are checking out the project, did you try doing this in your home dir as well?

**Comment by sushantdhopat19** [comment]
ya i try also how can i can i solve this error.

**Comment by sushantdhopat19** [comment]
sorry about this i solve this error .this error occurred in my machine your tool is all clear 
thanks for reply

**Comment by bauthard** [comment]
Closing as this is resolved already.

**Comment by sushantdhopat19** [comment]
i run this cmd for find vulnerabilities 

$> cat domains.txt | nuclei -t /root/nuclei-templates/vulnerabilities/microstrategy-ssrf.yaml -o ssrf.txt

this give me 

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] [IBM InfoPrint Directory Traversal] Loaded template IBM InfoPrint 4247-Z03 Impact Matrix Printer - Directory Traversal (@Harsh Bothra) [Medium]
[INF] No results found. Happy hacking!

i also use deff vulnerabilities give me same this any error 

plz reply thanks

**Comment by bauthard** [comment]
Hey @sushantdhopat19, 

Everything is good here, you see **No results found. Happy hacking!** because none of the targets is vulnerable, you will only see results when any of your targets is vulnerable or match with the defined template.

**Comment by sushantdhopat19** [comment]
Thanks for replying 
Sorry about that  I was try to confirm only 
Thanks
