### ISSUE TITLE
[feature] Support offline processing of the response data from other tools like meg/httpx

### ISSUE THREAD

**Issue by matglas** [projectdiscovery/nuclei#177]
It would be great if the template matching could be run against data from meg or other tools with similar data output. This might also minimize the amount of request to be send to hosts again by nuclei. 

https://twitter.com/lamininx/status/1286981391411011585?s=19

**Comment by bauthard** [comment]
For more context:- 

> A feature/flag support where nuclei take output (response data) from any other tool (meg, httpx) as input and run nuclei template checks on it

**Comment by JeffreyShran** [comment]
Usage for me on this feature would be similar to https://github.com/tomnomnom/gf.

So we'd pull the body using httpx for example, then at a later date run nuclei in a grep mode using existing templates.

**Comment by matglas** [comment]
A good start could be that we use the -json-response output from nuclei itself. That way you can do a fuzz for content discovery and then run another set of templates to do more checks on the content that was discovered without redoing the requests.

Example add `-response-data` as a flag to read from nuclei json output with response data.

**Comment by Ice3man543** [comment]
This is implemented in dev branch. You can use a file based matcher, or run HTTP templates on Raw HTTP responses saved in `.txt` files. Closing this now! More details will be provided with the release regarding the feature.
