### ISSUE TITLE
Option to disable redirects in HTTP templates

### ISSUE THREAD

**Issue by yassineaboukir** [projectdiscovery/nuclei#1773]
Hi,

It appears that the HTTP request that nuclei passed to `http2curl.GetCurlCommand` library in order to convert it to a `curl` command does follow HTTP redirection automatically and by default even without explicitly using `-fr` argument. Similarly, when using `-irr` flag it returns the HTTP request and response of the host that was redirected to.

```yaml
   -dr, -disable-redirects      disable following redirects for http templates
```

### Nuclei version:
2.6.5

### Current Behavior:
```sh
nuclei -u http://yassineaboukir.com:80 -json -o test.json -t nuclei-templates/misconfiguration/http-missing-security-headers.yaml
```

```json
"curl-command":"curl -X 'GET' -d '' -H 'Accept: */*' -H 'Accept-Language: en' -H 'Referer: http://yassineaboukir.com:80' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36' 'https://www.yassineaboukir.com/'"
```

I scanned `http://yassineaboukir.com:80` but observe the `curl`command is pointing to `https://www.yassineaboukir.com/`.

Similarly, with using `-irr` to return HTTP request/response, Nuclei was found to be following the redirection:

```sh
nuclei -u http://yassineaboukir.com:80 -t nuclei-templates/misconfiguration/http-missing-security-headers.yaml -irr -json -o test.json 
```

```json
{"template-id":"http-missing-security-headers","info":{"name":"HTTP Missing Security Headers","author":["socketz","geeknik","g4l1t0","convisoappsec","kurohost","dawid-czarnecki"],"tags":["misconfig","generic"],"description":"It searches for missing security headers, but obviously, could be so less generic and could be useless for Bug Bounty.","reference":null,"severity":"info"},"matcher-name":"x-content-type-options","type":"http","host":"http://yassineaboukir.com:80","matched-at":"http://yassineaboukir.com:80","request":"GET / HTTP/1.1\r\nHost: yassineaboukir.com\r\nUser-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36\r\nConnection: close\r\nAccept: */*\r\nAccept-Language: en\r\nAccept-Encoding: gzip\r\n\r\n","response":"HTTP/1.1 200 OK\r\nConnection: close\r\nAccept-Ranges: bytes\r\nAccess-Control-Allow-Origin: *\r\nAge: 88\r\nCache-Control: max-age=600\r\nContent-Type: text/html; charset=utf-8\r\nDate: Mon, 28 Mar 2022 00:09:59 GMT\r\nEtag: W/\"6240d1a3-1472\"\r\nExpires: Sun, 27 Mar 2022 23:05:58 GMT\r\nLast-Modified: Sun, 27 Mar 2022 21:05:39 GMT\r\nServer: GitHub.
```

Observe `HTTP/1.1 200 OK` response status which was returned by `http://www.yassineaboukir.com` instead of `http://yassineaboukir.com:80` which I'm explicitly scanning and which returns `HTTP/1.1 301 Moved Permanently`

### Expected Behavior:
Nuclei must not follow redirection unless explicitly specified by the use of `-fr` argument.

**Comment by ehsandeep** [comment]
@yassineaboukir thanks for creating this issue, do you have any more examples? as in this case [misconfiguration/http-missing-security-headers.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/master/misconfiguration/http-missing-security-headers.yaml#L15) does have `redirects: true` in the template itself.

**Comment by yassineaboukir** [comment]
Hi @ehsandeep,

Thank you for promptly following-up. I had not seen `redirects: true` and definitely missed but that doesn't comply with `-fr`, so I was wondering if there is a way to set `redirects` to False in all templates while scanning, something such as the ability to set `-fr` to True or False from the command line?

**Comment by ehsandeep** [comment]
@yassineaboukir `redirects` are disabled as default and only enabled if `-fr` flag is used or defined in the template where it's required, since it is disabled as default, do you still think we required that option?

**Comment by yassineaboukir** [comment]
That makes sense but what if I want to run the same templates on a different asset that I want to disable redirection for, I can't go over all the templates I created one by one and manually change redirects to `False`. For that reason, I think a better approach would be to have control over the redirect parameter via the command line, preferably setting `-fr` to either True or `False`.

Another reason would be that an asset I'm scanning might be redirected to another external domain that doesn't belong to our company, therefore I don't want to end up running scans on an out of scope assets.

**Comment by greckko** [comment]
I used the following method to remove all `redirect` templates creating a new template folder called:

`nuclei-no-redirect-templates`

`cp -r nuclei-templates nuclei-no-redirect-templates`
`cd nuclei-no-redirect-templates`
`grep -r "redirects\:" | awk -F: '{print $1}' | xargs rm 2> /dev/null`

Confirm there are no redirect templates recursively in the `nuclei-no-redirect-templates` folder
`grep -r "redirects\:"`

Then run nuclei using all templates in the `nuclei-no-redirect-templates` folder 
`nuclei -target <url> -t /root/nuclei-no-redirect-templates`

**Comment by ehsandeep** [comment]
Similar to `fr` flag, a new flag has been added to disable redirects globally, and changes have been merged in the dev branch and will be part of the next release.

```
   -dr, -disable-redirects     disable redirects for http templates
```

@yassineaboukir @greckko ^
