### ISSUE TITLE
Automatic Scan misses custom template directories if they don't match a default template directory

### ISSUE THREAD

**Issue by jbertman** [projectdiscovery/nuclei#1791]
### Nuclei version:

2.6.5

### Current Behavior:

Automatic scan currently gathers templates from statically defined template directories as noted here:

https://github.com/projectdiscovery/nuclei/blob/master/v2/pkg/protocols/common/automaticscan/workflow.go#L97-L99

### Expected Behavior:

When additional template directories are specified, users should expect to see them included in all facets of execution, such as workflows and automaticscan.

### Steps To Reproduce:

Provide a custom template directory that does not match the glob list defined in https://github.com/projectdiscovery/nuclei/blob/master/v2/pkg/protocols/common/automaticscan/workflow.go#L97-L99

```
nuclei -u "<target>" -automatic-scan -t nuclei-templates/,custom-dir/ -v
```
where custom-dir contains:
```
├── custom
│   ├── anything
         └── test.yaml
```
~~If you change `custom` to a supported glob (such as `cves`), everything works as expected.~~ 
EDIT: I'm not certain the above is true, sometimes it appears to work, other times it doesn't.

**Comment by jbertman** [comment]
Took a quick shot at this, I'm unsure if this adheres to the exclusions, but it does work for me in testing
https://github.com/projectdiscovery/nuclei/pull/1862

**Comment by ehsandeep** [comment]
@jbertman this is now fixed in dev version with https://github.com/projectdiscovery/nuclei/pull/1870

**Comment by jbertman** [comment]
Confirmed working for me on the dev branch. Thanks @ehsandeep / @LuitelSamikshya 🚀
