### ISSUE TITLE
Support to follow meta based HTTP redirects

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei#1824]
Since we have a way to parse CSP in meta tags why don't we do the same thing to allow meta-redirects for Nuclei and httpx?
https://github.com/projectdiscovery/httpx/issues/477#event-6396686300

```html
<meta http-equiv="refresh" content="0;url=http://example.com">
```

Currently, only status code-based redirect is supported, since `net/http` can not be used to replicate headless behavior, we can try to partially support a few well-known cases/features to use with the standard http engine.

**Comment by ehsandeep** [comment]
Closing this issue, as this change may introduce other edge cases to make nuclei behave unexpectedly.
