### ISSUE TITLE
Unquoted payload variables causes govaluate to lookup for the wrong parameters

### ISSUE THREAD

**Issue by manuelbua** [projectdiscovery/nuclei#183]
**Describe the bug**
Specifying payload values such as in `brute-force/tomcat-manager-bruteforce.yaml` and referencing them for example in the `Authorization` header such as `Authorization: Basic {{base64(username:password)}}` causes govaluate to fail parameter lookup.

**Nuclei version**
Latest `@master`

**Reproduction**
```
echo 'http://localhost:9999' | nuclei -t brute-force/tomcat-manager-bruteforce.yaml -v
```

The template being used is the one from the `nuclei-templates` repo: for the payloads, `username` points to `/tmp/u` (only contains `abc`) and `password` points to `/tmp/p` (only contains `123`).

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/819314/88732049-8e5baa80-d137-11ea-895d-265051ae2724.png)

**Workaround**
If the `base64` function arguments are quoted, the evaluation will be performed correctly, so patch the template and for the `Authorization` raw request header switch it to:
```
Authorization: Basic {{base64("username:password")}}
```

Within the same command line the result is now:
![image](https://user-images.githubusercontent.com/819314/88733649-0f1aa680-d138-11ea-88bb-eb752dc93c45.png)

**Note** Comparing these to the tagged `2.0.4` version (prev):
1. two results are now returned while, in prev it was one
2. the `base64` argument needs quoting, in prev they didn't

Note that also in prev, the `base64` argument was silently truncated at the colon, so only the "username" was encoded: so if the final evaluated expression was `base64(admin:mypassw0rd)`, the executed evaluation was `base64(admin)`.

**Comment by bauthard** [comment]
Thank you for filing this issue @manuelbua, this is known behavior with master version, the way payload works has been changed slightly, so with master to make this template works `{{base64('username:password')}}` or `{{base64("username:password")}}` will work, we are adding these details in the coming guide document with the stable release of the master, and required templates will be updated at the time of release.

**Comment by manuelbua** [comment]
Cool, should i file another issue for the double-output issue i'm seeing?

**Comment by bauthard** [comment]
I've reproduced this on my side as well, going to create a new one for this.

**Comment by bauthard** [comment]
@manuelbua looks this has something to do with attack type `Cluster bomb`, I will confirm this before creating an issue. 

Ref:- https://portswigger.net/burp/documentation/desktop/tools/intruder/positions
