### ISSUE TITLE
v2.6.7 Using Nuclei From Go Code error

### ISSUE THREAD

**Issue by shadow1ng** [projectdiscovery/nuclei#1846]
https://github.com/projectdiscovery/nuclei/blob/master/DESIGN.md#using-nuclei-from-go-code

Bugs:
- [x] Update using as go code example
- [x] Integration test 

![image](https://user-images.githubusercontent.com/39651966/163302210-fbb091f0-016a-4b4c-ab56-25e6b4d6fc88.png)

```
# main
.\main.go:47:24: cannot use goflags.StringSlice{...} (type goflags.StringSlice) as type goflags.FileOriginalNormalizedStringSlice in assignment
.\main.go:79:43: not enough arguments in call to loader.NewConfig
	have (*"github.com/projectdiscovery/nuclei/v2/pkg/types".Options, *catalog.Catalog, protocols.ExecuterOptions)
	want (*"github.com/projectdiscovery/nuclei/v2/pkg/types".Options, *config.Config, *catalog.Catalog, protocols.ExecuterOptions)
```

**Comment by jimen0** [comment]
Publicly facing API changed. v2.6.7 should be retracted and v2.6.8 should be pushed eliminating that publicly facing API change. Another option, in case the change is required, would be to tag v3.0.0.
