### ISSUE TITLE
how report to my Elasticsearch

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#1848]
Please add parameters
-reportUrl
E.g:
http://127.0.0.1:9200/nuclei_index/_doc/
Then post json directly to Elasticsearch

**Comment by ehsandeep** [comment]
@hktalent see https://github.com/projectdiscovery/nuclei/blob/docs-work/docs/integrations/elasticsearch.md

**Comment by hktalent** [comment]
@ehsandeep thanks
