### ISSUE TITLE
[issue] Progress bar suppressing run time results 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#186]
**Describe the bug**

When using nuclei with a progress bar, results are suppressed and displayed once the scan is completed, expected behavior to keep the run time result as it like before, run time results are helpful in case you are running big scans. 
 
**Nuclei version**

`@master`

**Comment by manuelbua** [comment]
Yes this is something i'm still working on: as anticipated in the original PR there isn't support for real "logging" in mpb, besides setting up multiple completed progressbars with the desired output; the problem with this approach is, we need to supply a progressbar for each line of output and the colored output need to be carefully split, as it can't happen inside an escape sequence. This may require mpb to use resources only for keeping log bars alive, and i don't really like this.

I'm actually working on a different approach and trying out ideas, would be cool to have live output back.

**Comment by bauthard** [comment]
Thank you for sharing this information @manuelbua, let's keep this open as you are working on and as the run time result is something crucial when running large scans, so we are keeping that behavior as default and progress bar can be enabled with `pbar` flag.
