### ISSUE TITLE
[issue] Unexpected error on run-time 

### ISSUE THREAD

**Issue by subhash0x** [projectdiscovery/nuclei#187]
fatal error: unexpected signal during runtime execution
0x20xc001d6d0000x465123]

runtime stack:
runtime.throw(0xb49eff, 0x2a)
        /usr/lib/go-1.14/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/lib/go-1.14/src/runtime/signal_unix.go:679 +0x46a
runtime.memclrNoHeapPointers(0xc001d5c000, 0x16000)
        /usr/lib/go-1.14/src/runtime/memclr_amd64.s:76 +0x113
runtime.(*mheap).alloc(0x10b1ca0, 0xb, 0x450100, 0x10b1ca0)
        /usr/lib/go-1.14/src/runtime/mheap.go:8760xd10x140980x7fef657900010x45eb6e11520x9210470x460x7fef440000203700x66/usr/lib/go-1.14/src/runtime/proc.go10412253300xc001b239300xc001b239280x461fe00x140980xb054200xc001b23a010x7f59b910460x8950xc001b239d00xc001b239300x40e3e50xb054200x1011650x380xc001b23a000xc001b239d00x40e6d8460xc00195f8100xc145200xc0000240580x00x02190xd50xc001b23af80xc001b23a000x7f67c50xc001b23cd80xc145200xc0000240580xafdd200xc00195f7700x01630x7e0xc001b23b380xc001b23af80x7f5eee0xc0003183800xc000596e800xc001a9a6000x2f0x00x05270xe660xc001b23d980xc001b23b380x9baaa60xc0003183800xc000596e804020x1c30xc001b23ef80xc001b23d980x9b9a03github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration.func30xc00008e2e00xc0003183800xc0000ab5800xc00009f6d00x4f2540x2e60xc001b23fb80xc001b23ef80x9be82613730x10xc001b23fc00xc001b23fb80x4640f12400x4b31550xc00008e2e8560x420xc00008e2e01300x640xc0003183802610x4e0main.main170x9f190xc0003183800xc0005960800xb016c00xc0004dcc300xc089600xc0003ea2400x03530x3d80xc0003183800xc0005960800xb016c00xc0004dcc300xc0005960002900x10dgithub.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration.func30xc00008e2e00xc0003183800xc0000ab5800xc00009e0a00x472500x19c2400x4b3200xc0003183800xc0006800000xb016c00xc0008f80f00xc089600xc0006225100x03530x3d80xc0003183800xc0006800000xb016c00xc0008f80f00xc0006800002900x10dgithub.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration.func30xc00008e2e00xc000318380, 0xc0000ab580, 0xc00009e0f00x45250 +0x19c

**Comment by bauthard** [comment]
Hi @subhash0x, 

Can you please share a few more details:

a) **what method you used to install**? 
b) **what command you used before getting this error?**

**Comment by subhash0x** [comment]
I am using windows 10 64bit subsystem Kali Linux  with 8GB RAM  i5 processor  while using this command it throws an error 

 subfinder -d site.com -silent | httpx -silent | nuclei -t nuclei-templates/cves/ -o site.txt

and also it consuming so much space of HDD 

[debuginfoerror.txt](https://github.com/projectdiscovery/nuclei/files/4998507/debuginfoerror.txt)
