### ISSUE TITLE
failed interactsh integration-test

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1893]
### Nuclei version:
latest,dev

### Current Behavior:
```yaml
2022/04/25 05:38:01 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc000136028 127.0.0.1:49575 in state active
  *net.TCPConn 0xc0001360d0 127.0.0.1:49578 in state active
[✘] Test "http/interactsh.yaml" failed: incorrect number of results: 0 (actual) vs 1 (expected) 
Results:
```

### Expected Behavior:
Running test without fail

### Steps To Reproduce:
https://github.com/projectdiscovery/nuclei/runs/6152210082?check_suite_focus=true

**Comment by Mzack9999** [comment]
It seems not reproducible (https://github.com/projectdiscovery/nuclei/runs/6405457496?check_suite_focus=true). It's also not happening in other recent pull requests. I'd suggest closing the issue and reopen if it appears again.
