### ISSUE TITLE
how share one request for more yaml?

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#1895]
how share one request for more yaml?
For requests with the same target and the same request data, share it with all yamls that need it

thanks

my suggestion is,
1. Start a proxy internally to cache related requests
2. Identify requests for the same data and return them from the cache without repeating requests, thereby improving efficiency

@ehsandeep

**Comment by ehsandeep** [comment]
@hktalent that's already supported and works automatically, you can confirm it by running `echo https://example.com | nuclei -t takeovers`, which loads and runs 67 templates and makes only one request.

```diff
echo https://example.com | nuclei -t takeovers

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.9

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.9 (latest)
[INF] Using Nuclei Templates 8.9.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 67
+[INF] Templates clustered: 67 (Reduced 66 HTTP Requests)
[INF] No results found. Better luck next time!
```

let me know if you have anything to add otherwise we can close this issue.

**Comment by hktalent** [comment]
thanks
