### ISSUE TITLE
Test Fail - race-multiple

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#1907]
### Nuclei version:
dev

### Current Behavior:

For some unknown reasons, two results are getting printed in the same line, causing the test to fail due to a results count mismatch.

Note: the feature/template is working correctly.

```console
[✘] Test "http/race-multiple.yaml" failed: incorrect number of results: 4 (actual) vs 5 (expected) 
Results:
	[2022-04-28 00:19:39] [race-condition-testing] [http] [info] http://127.0.0.1:32835/[2022-04-28 00:19:39] [race-condition-testing] [http] [info] http://127.0.0.1:32835/
	[2022-04-28 00:19:39] [race-condition-testing] [http] [info] http://127.0.0.1:32835/
	[2022-04-28 00:19:39] [race-condition-testing] [http] [info] http://127.0.0.1:32835/
	[2022-04-28 00:19:39] [race-condition-testing] [http] [info] http://127.0.0.1:32835/
```
### Expected Behavior:
Fixing the result printing behavior or improving the result counter.

### Steps To Reproduce:
https://github.com/projectdiscovery/nuclei/runs/6203129878?check_suite_focus=true

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/8293321/165695148-7bcb53c2-0826-493b-9498-5fed4cba58c0.png">

**Comment by jimen0** [comment]
Hi @ehsandeep - Are these test cases being executed concurrently? If so the issue might lie on the fact that `fmt.*` calls aren't concurrency-safe. They all just write to the underlying `io.Writer` but the caller is responsible of making their code safe.

Default `log.Logger` is concurrency-safe, btw.

**Comment by dankegel** [comment]
This is happening on my laptop, corrupting results from normal use of nuclei.  
Setting concurrency to 1 works around it.

**Comment by ehsandeep** [comment]
@dankegel @jimen0 should be fixed with https://github.com/projectdiscovery/nuclei/pull/1969
