### ISSUE TITLE
[feature] severity filtering options

### ISSUE THREAD

**Issue by gy741** [projectdiscovery/nuclei#191]
Hello,

"Nuclee" is a very good tool. Thanks for sharing.

I have an opinion.

the current "-t" option should be used to use a restricted directory. This is uncomfortable.

"Nuculei templates" provide the severity option. 

It would be nice to have a severity filtering option.

For example:

(current) : ```nuclei -t nuclei-templates/```

(sample severity option) ```nuclei -t nuclei-templates/ --severity medium```

 : Of the templates, only detect medium imapct.

Thanks.

**Comment by bauthard** [comment]
Hi @gy741, 

Thanks for this suggestion and feedback, we knew it was coming, surely a good option to have, and we will add it in future updates.

**Comment by gy741** [comment]
Hello @bauthard 

Thank you for your quick and kind answer.

Have a nice day. :)
