### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei#1914]
### Nuclei version:
latest

### Current Behavior:

```
fatal error: concurrent map iteration and map write

goroutine 925221 [running]:
runtime.throw({0x5066afc, 0x0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc009ad69c0 sp=0xc009ad6990 pc=0x403ab91
runtime.mapiternext(0x4ddc9a0)
	/usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc009ad6a30 sp=0xc009ad69c0 pc=0x40152eb
net/http.Header.sortedKeyValues(0xc003219b00, 0x574b0a0)
	/usr/local/go/src/net/http/header.go:170 +0x15a fp=0xc009ad6b80 sp=0xc009ad6a30 pc=0x42be3da
net/http.Header.writeSubset(0xc0078cb7c0, {0x574b0a0, 0xc001eb29c0}, 0x0, 0x0)
	/usr/local/go/src/net/http/header.go:192 +0xc7 fp=0xc009ad6ce8 sp=0xc009ad6b80 pc=0x42be767
net/http.(*Request).write(0xc005efc100, {0x574b0a0, 0xc001eb29c0}, 0x0, 0xc00204a2a0, 0x0)
	/usr/local/go/src/net/http/request.go:651 +0x8db fp=0xc009ad6ed0 sp=0xc009ad6ce8 pc=0x42c09bb
net/http.(*persistConn).writeLoop(0xc003c746c0)
	/usr/local/go/src/net/http/transport.go:2389 +0x189 fp=0xc009ad6fc8 sp=0xc009ad6ed0 pc=0x42e7949
net/http.(*Transport).dialConn·dwrap·119()
	/usr/local/go/src/net/http/transport.go:1748 +0x26 fp=0xc009ad6fe0 sp=0xc009ad6fc8 pc=0x42e4386
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc009ad6fe8 sp=0xc009ad6fe0 pc=0x406e5e1
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1748 +0x1e65
..............
```

### Steps To Reproduce:
nuclei -l target.txt

**Comment by ehsandeep** [comment]
@akincibor, any more details to add? nuclei version in use? do you able to reproduce it with all scans or any specific action or scenario, for example, while pressing `CLT + C`?

**Comment by akincibor** [comment]
Hi, I found that it was related to a specific domain. Everything works after removing this domain & subdomains from my assets.

**Comment by ehsandeep** [comment]
> Hi, I found that it was related to a specific domain. Everything works after removing this domain & subdomains from my assets.

Hey, Could you dm the domain name on discord server to "pd-team"?

**Comment by Ramansh123454** [comment]
> @akincibor, any more details to add? nuclei version in use? do you able to reproduce it with all scans or any specific action or scenario, for example, while pressing `CLT + C`?

Hi i am facing the same issue in the newest nuclei version 2.7.3

**Comment by Ramansh123454** [comment]
> > Hi, I found that it was related to a specific domain. Everything works after removing this domain & subdomains from my assets.
> 
> Hey, Could you dm the domain name on discord server to "pd-team"?

can you please help me in resolving it
