### ISSUE TITLE
Error while running windows executable file

### ISSUE THREAD

**Issue by Droidzzzio** [projectdiscovery/nuclei#20]
OS: windows 10 64-bit
Error: This version of C:\Users\malav\nuclei\nuclei-windows-amd64.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
![nuclei_error](https://user-images.githubusercontent.com/34626959/79003754-d945b800-7b70-11ea-9e62-f4210b2c622a.PNG)

**Comment by bauthard** [comment]
This does work for me on windows 10 @Droidzzzio 

![image](https://user-images.githubusercontent.com/8293321/79055428-a67fea80-7c6a-11ea-8086-b9d25b8ef019.png)

![image](https://user-images.githubusercontent.com/8293321/79055439-b7c8f700-7c6a-11ea-9751-bb413fa211ea.png)

**Comment by Zeokat** [comment]
I have the same problem, the windows binary does't work in Windows 7 x64. The program returns the same error. Tested into another computer with Windows 10 and have the same error, maybe @bauthard you have some dependency installed that we don't have.

![winsysinfo](https://user-images.githubusercontent.com/1313154/80382866-1fa25300-88a3-11ea-8d45-13d1c0e8bd76.png)

**Comment by Zeokat** [comment]
I could run into Windows 7 x64, but i had to compile bymyself.

I had to install GIT and Go, also setup `GO111MODULE=on` to avoid using it from windows `cmd.exe`, what needs to execute `go env -w GO111MODULE=on` first.

Compiled executable: 
[nuclei.zip](https://github.com/projectdiscovery/nuclei/files/4541062/nuclei.zip)

**Comment by Zeokat** [comment]
Tested the new released Windows executable and seems that this time it works.

Anyway... exists something weird, because the executable compiled in my machine is 9,23MB while the executable released at Github is 6,81MB.

**Comment by bauthard** [comment]
This should be fixed as now we create a [binary](https://github.com/projectdiscovery/nuclei/releases) for both architectures.
