### ISSUE TITLE
after run scanner output file is deleted 

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei#202]
after run scanner output file is deleted  ,

**Comment by bauthard** [comment]
Hey @shelu16, 

it's not an issue, in v2.0, we added a feature where files with no results get auto-delete after the run, so here, if you noticing that it means those files having no results in it. 

You can the see changelog details here https://nuclei.projectdiscovery.io/releases/changelog/#nuclei-v200

**Comment by shelu16** [comment]
ok
