### ISSUE TITLE
Nuclei run long time to load templates

### ISSUE THREAD

**Issue by joyahamad074** [projectdiscovery/nuclei#2043]
Hi, when i start nuclei with some domain list it hang on so many time like on below scenario and take so long time to execute templates.

```
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.1

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.1 (latest)
[INF] Using Nuclei Templates 9.0.2 (latest)
[INF] Templates added in last update: 24
[INF] Templates loaded for scan: 3363
[INF] Templates clustered: 593 (Reduced 792780 HTTP Requests)
[INF] Using Interactsh Server: oast.pro
```
like this it wait here so long time and slowly execute the template which is so bored.How can i get rid out of it??

**Comment by ehsandeep** [comment]
@joyahamad074 when you feed the list of URLs to run with nuclei with the default list of templates (3363), it's going to take some time to complete the scan and is expected, so you can not avoid the wait time if you wanted to perform those scans; instead, you can use `-stats` flag to see the scan progression if that helps.
