### ISSUE TITLE
Output json field includes reference and matched-line as null

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#2049]
### Please describe your feature request:

Nuclei JSON output contains reference and matched-line with `null` as value, instead empty cases of these values should be omitted.

Probably custom json marshallers need to be changed along with adding `omitempty` to the required fields.

**Comment by Ice3man543** [comment]
@ehsandeep @Mzack9999 the issue here is StringSlice is a custom type and unless it is a pointer go's encoding/json always marshalls and writes `null` as value ignoring omitempty tags on custom types. To do so would require some extra work so unsure how we want to proceed here.

**Comment by ehsandeep** [comment]
Closing as per the above comment.
