### ISSUE TITLE
[feature] flag to display installed template version

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#205]
**Is your feature request related to a problem? Please describe.**

To investigate the root cause of an issue with any template, it's required to know which version of the templates the user is running. 

**Describe the solution you'd like**

- Added flag to list installed template version will solve the issue. 

**Suggested flag** : `tv` stands for template version. 

```bash
nuclei -tv 

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Installed nuclei-templates version: v3.0.8
```

The version of the installed template can be obtained from `~/.nuclei-config.json` 
```json

cat ~/.nuclei-config.json

{
  "templates-directory": "/Users/bauthard/nuclei-templates",
  "current-version": "3.0.8",
  "last-checked": "2020-08-04T16:06:41.123492+05:30"
}
```

In case, nuclei templates are not installed, followed error is expected. 

```bash 
nuclei -tv 

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[FTL] Program exiting: nuclei-templates are not installed, use update-templates flag to download.
```

**Comment by mzfr** [comment]
@bauthard The way I thought this was that we could just use the `readConfiguration` function from `update.go` in `options.go`.

So in `options.go` we could have added something like:

```
	if options.TemplateVersion {
		config, err := readConfiguration()
		if err != nil {
			return err
		}
	}
```

But I am getting `undefined` on the readConfiguration even though the package for both update.go and options.go is the same.

Could it be because readConfiguration is not exported?

**Comment by Ice3man543** [comment]
Yeah @mzfr, since readConfiguration is implemented on runner struct you cannot read it this way. This issue requires us to change the function definition allowing reading of template config file without creating a runner.

**Comment by mzfr** [comment]
yeah so should this reading be done within the options? or do you plan to do it in some other files/function?

**Comment by bauthard** [comment]
This is added here https://github.com/projectdiscovery/nuclei/commit/88d187baf1a19773d91b4501635905744066eb99.
