### ISSUE TITLE
Getting error in while using interact server

### ISSUE THREAD

**Issue by thecyberneh** [projectdiscovery/nuclei#2056]
Getting this type of errors while using interact server
Could not decode interactions: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<!doctype h|..., bigger context ...|<!doctype html><html lang="en" data-adblockkey="MFw|...

**Comment by ehsandeep** [comment]
@thecyberneh, I would suggest the following [issue template](https://github.com/projectdiscovery/nuclei/issues/new?assignees=&labels=Type%3A+Bug&template=issue-report.md) or include the required information to investigate the issue further.

Please include the following information:
- Screenshot of the error
- Nuclei version
- nuclei cmd you used
- Interactsh server in use ( if using any custom one)

**Comment by ehsandeep** [comment]
Closing this one, as further information is listed in https://github.com/projectdiscovery/nuclei/issues/2075
