### ISSUE TITLE
scanning with 370k subdomains stops before completion

### ISSUE THREAD

**Issue by marz-hunter** [projectdiscovery/nuclei#206]
I did an endpoint scan on 370k subdomains, but the nuclei stopped themselves before the scan was finished. then i tried to scan 20k and it was solved properly. I'm not sure this problem occurs in my nuclei or cloud. I use Azure with 8GB RAM spec and no other scanning is run besides nuclei. I use only one template when scanning.

**Comment by bauthard** [comment]
Hey, thanks for creating this issue,  I've already started a scan with on 500k list as input with a single template, will update this issue once the scan is completed.

**Comment by marz-hunter** [comment]
if the scanning that you run is successful then this relates to the cloud that I use

**Comment by bauthard** [comment]
Hey @marz-hunter, I can confirm this is not an issue in nuclei, just completed the scan with 500k list in around 3.5 hours without any issue with 8 GB box, here are the stats. 

```bash
wc -l all-urls.txt
567776 all-urls.txt
```

```
time nuclei -l all-urls.txt -t ~/nuclei-templates/files/***.yaml | tee nuclei-test.txt

real    216m34.901s
user    47m31.392s
sys     26m18.812s
```

```
wc -l nuclei-test.txt
95 nuclei-test.txt
```

Closing this, as it's not an issue.

**Comment by marz-hunter** [comment]
thank you for clarifying, it means that this problem comes from my cloud.
