### ISSUE TITLE
Option to exclude results based on matcher names

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2082]
### Describe the use case of this feature:

For the cases where excluding the template is not an option as the template may contain multiple results, it's not possible to exclude any desired matches in the results, to support this scenario, a new CLI flag needs to be introduced to filter results based on a given matcher or list of matcher names.

### Please describe your feature request:

**CLI flag:**

```console
   -em, -exclude-matchers string[]  template matchers to exclude in result (comma-separated, file)
```

**Exclude matchers using CLI Flag:**

```console
-em http-missing-security-headers:cross-origin-resource-policy,tech-detect:google-font-api
```

**Exclude matchers using file input:**

```sh
$ cat exclude.matchers.txt

http-missing-security-headers:cross-origin-resource-policy
tech-detect:google-font-api
```

```console
-em exclude.matchers.txt
```

**Exclude matchers using the config file:**

```yaml
exclude-matchers:
  - "http-missing-security-headers:cross-origin-resource-policy"
  - "tech-detect:google-font-api"
```

### Discussed in https://github.com/projectdiscovery/nuclei-templates/discussions/3808

<div type='discussions-op-text'>

<sup>Originally posted by **carlin-q-scott** March  2, 2022</sup>
I'd like to be able to use part of a template by excluding certain matchers. 

For instance, I'm using misconfiguration/http-missing-security-headers.yaml, but I don't want to get results for the less important headers. The template has them all set at "info" severity, but they're not equally important. If we could set severity at the matcher level, then I could update the template to raise the severity for the more important security headers.

Alternatively, if I could exclude matchers by name, that would solve my issue and would save people from having to argue about matcher severity. I'd imagine my config.yml would look something like this:
```yaml
exclude-matchers:
  - "http-missing-security-headers:cross-origin-resource-policy"
  - "tech-detect:google-font-api"
```

**Comment by Bisstocuz** [comment]
Hi, maybe its member needs a yaml field name? Check this: https://github.com/projectdiscovery/nuclei/pull/2218#issuecomment-1293167261
