### ISSUE TITLE
Append to the output file

### ISSUE THREAD

**Issue by mzfr** [projectdiscovery/nuclei#211]
**Is your feature request related to a problem? Please describe.**

currently, if we have a `results.txt` in a current working directory and we run nuclei `-o results.txt` then the existing data from that file is deleted.

**Describe the solution you'd like**

It would be nice if nuclei just open the file in append mode and write the content to it.

I think the changes required in this would have to be done in `v2/internal/runner/runner.go#L143` on [line 143](https://github.com/projectdiscovery/nuclei/blob/master/v2/internal/runner/runner.go#L143)

**Comment by bauthard** [comment]
Hey @mzfr, I'm sure there will users who don't want to append, `results.txt` might have the output of some other tool or of nuclei but don't want to mix up with old results, so we are keeping this as default considering this as a general practice.

**Comment by mzfr** [comment]
umm...yes you are right but see if there is already a results.txt in the current working directory then no matter what the content of that file is, it shouldn't be overwritten I guess.

I think appending would be much better rather than just completely making a new file which makes it lose all the data.

If you want maybe show a warning saying `results.txt already exists on the path, it will be overwritten or new output would be appended`.

Just some suggestions from my side.

**Comment by bauthard** [comment]
We appreciate your input @mzfr, just to maintain similar behavior throughout all the tools and to avoid any overlapping of results with other tools or existing output, we are keeping this behavior as default, closing this issue now.

**Comment by s3d113** [comment]
I had this issue as well, what I did is run nuclei in silent mode and append the output to a file. 
example:
nuclei -l targets.txt -t /root/nuclei-templates/ **-silent**  >> /path/to/file.txt &

I do agree with @ehsandeep  comment though, having the default behavior to overwrite the output file is the best practice.
you can always find a way to achieve your own desired result that won't affect the general behavior.

**Comment by disnhau** [comment]
It should have an option to append output
