### ISSUE TITLE
[feature] flag to disable meta Information 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#212]
**Is your feature request related to a problem? Please describe.**
When we get output from nuclei it includes, template name, template type which is required most of the time, but this also limits the ability to pass the output to any other tool or for further processing. 

**Describe the solution you'd like**

This can be improved with an additional flag that disables printing meta-information allows reuse of the output in the terminal. 

**Suggested flag:-** `no-meta` stands for disabling meta information.

Current output:- 

```bash
> chaos -silent -d hackerone.com | nuclei -t dns/ -silent

[cname-service-detector:github] [dns] docs.hackerone.com
[cname-service-detector:github] [dns] mta-sts.hackerone.com
[cname-service-detector:github] [dns] mta-sts.managed.hackerone.com
[cname-service-detector:github] [dns] mta-sts.forwarding.hackerone.com
[cname-service-detector:zendesk] [dns] support.hackerone.com
```

Output with suggested change:- 

```bash
> chaos -silent -d hackerone.com | nuclei -t dns/ -silent -no-meta

docs.hackerone.comsupport.hackerone.com
mta-sts.hackerone.com
mta-sts.managed.hackerone.com
mta-sts.forwarding.hackerone.com
```

**Comment by Ice3man543** [comment]
Done!
