### ISSUE TITLE
Saving Stats with -stats-json not working

### ISSUE THREAD

**Issue by SecTheBit** [projectdiscovery/nuclei#2160]
Hi Team,
I have used the stats-json flag for saving the stats, but in actual no file we created. Below is the command that I have used.
```
nuclei -u url -sj stats.json
```
Nuclei Details:
```
[INF] Using Nuclei Engine 2.7.2 (latest)
[INF] Using Nuclei Templates 9.0.6 (latest)
```
![Screenshot from 2022-06-14 11-22-40](https://user-images.githubusercontent.com/46895441/173531099-31664bd9-7073-4f4d-87fe-4095f8d70759.png)

**Comment by SecTheBit** [comment]
Any update team?

**Comment by ehsandeep** [comment]
@SecTheBit `stats` or `stats-json` are not meant to be saved to file and more to give an indication of the running scan, closing this issue as this is expected behavior.
