### ISSUE TITLE
Nuclei failing to run properly over large amount of hosts

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#2164]
### Nuclei version:
Using Nuclei Engine 2.7.2 (latest)

### Current Behavior:

I am running a custom nuclei template over a small amount of hosts that I know nuclei is going to give a valid match (to test the template), so I run it over 30 hosts, and it properly alerts all the 30 hosts as "vulnerable". The problem is, then I run over all my targets (aproximately 800k hosts) and it only detects 2 hosts (the 800k hosts includes all the hosts given in the short scan + a lot more, it is a tech detect).

### Expected Behavior:

So I don't know what is happening, it's the third time I run nuclei over the large list of hosts and it is not detecting all of them, it is detecting only a few.

 

### Steps To Reproduce:

Not sure how to explain it or help reproduce it. the template I am running is:

```
id: github-detection

info:
  name: github-detect
  author: me
  severity: info
  reference:
    - https://none.com
  tags: tech

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers:
      - type: word
        words:
          - 'Server: GitHub.com'
        part: header
```

Something must be off since there can't be only 2 subdomains hosted in github (I know there are more from previous scans).

**Comment by ehsandeep** [comment]
@marcelo321 you can use the below options while running your scan and debug the logs / raw response once scan gets completed.

```
   -sresp, -store-resp           store all request/response passed through nuclei to output directory
   -tlog, -trace-log string  file to write sent requests trace log
   -elog, -error-log string  file to write sent requests error log
```

**Comment by marcelo321** [comment]
The thing is I am kinda afraid if this happens to other templates, that when mass scanning something fails. I can use `-store-resp` in this scan and then grepping for `Server: GitHub.com` manually to see if it is nuclei's fault or it what is happening, but I am not sure if that's the solution

**Comment by ehsandeep** [comment]
@marcelo321 that's definitely not a solution, but more about knowing the problem that needs to be solved, I'm moving this to a discussion as there is no sufficient information to look further, please add more details to a discussion once you get to know about the issue using the flag shared above.
