### ISSUE TITLE
Not able to use nuclei

### ISSUE THREAD

**Issue by technicaljunkie** [projectdiscovery/nuclei#2165]
![11111Untitled](https://user-images.githubusercontent.com/50881733/173688635-22473f4e-3b71-4b67-bb85-ee28c1e50bed.png)

**Comment by ehsandeep** [comment]
@technicaljunkie you can use `-ni` flag to disable using interactsh server.

**Comment by technicaljunkie** [comment]
But it need to be fixed

**Comment by ehsandeep** [comment]
@technicaljunkie there are multiple interactsh used as default, if for some reason one failed to register, the next one gets selected to use for scan and can be seen after the warning msg, consider the error as a warning and it does affect the scan.
