### ISSUE TITLE
[feature] Support host without http|https

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#218]
**Is your feature request related to a problem? Please describe.**

Nuclei fails when giving a host like `hackerone.com` without telling the type of connection we are making like https://host or http://host.

**Describe the solution you'd like**

Would it be possible that nuclei automatically gets the type of connection based on the port given? So if i give nuclei:

hackerone.com:80

it would work and not fail.

**Comment by bauthard** [comment]
Hey @marcelo321, 

This is expected, as mentioned in the readme, HTTP template accepts URLs and DNS template accepts subdomains, if you are running HTTP template, pass the subdomains via `httpx`, here is tweet sharing tips for the same https://twitter.com/pdnuclei/status/1288400945752289282

```
cat subdomains | httpx | nuclei 
```

**Comment by marcelo321** [comment]
Thanks!
