### ISSUE TITLE
Multiple requests condition ignore failed requests

### ISSUE THREAD

**Issue by DShelef** [projectdiscovery/nuclei#2194]
I couldn't find any open bug report or issue about that, hope I haven't missed anything.

### Nuclei version:
I know it is relevant to latest version to date (`2.7.2` at the time of writing).
I have also tested versions `2.6.2`, `2.6.3` & `2.6.5`

### Current Behavior:
In case a template executes multiple requests and it has different conditions for every request (`req-condition: true`), any condition (or part of it) which refer to a request that failed is ignored (equivalent to returning `True`).
In case a tested website has poor network, a CVE might be detected on an unrelated website.
The template would fail only if all of the requests have failed, but not if one of the requests has failed.

### Expected Behavior:
I expect that if a parameter in the conditions is referring to a specific request and that request has failed then its test would fail as well (would return False)

### Steps To Reproduce:
The bug is statistical (depends on well timed poor network), so I created a setup which reproduces it with certainty. I attached all the necessary components for it:
* [not_http_server.py.txt](https://github.com/projectdiscovery/nuclei/files/8948367/not_http_server.py.txt)
* [template.yaml.txt](https://github.com/projectdiscovery/nuclei/files/8948381/template.yaml.txt)
Sorry for the `.txt` extensions, github doesn't support `.yaml` or `.py`. Just remove it. 

1. Execute the python script with python3.6 or above (no other dependency is required) to mimic an http server with selectively poor network. It would listen on port 1234 and would run for 60 seconds (both can be easily changed). `python3 not_http_server.py`. You can also run it in the background, for unix it would be like so: `python3 not_http_server.py &>/dev/null &`.
2. Run nuclei with the template in the git targeting the python script (before the script is closed). `nuclei -debug -vv -json -u http://127.0.0.1:1234/ -t template.yaml`

The CVE would be detected, even though the string the template is looking for (`<th scope="row" class="check-column">`) was not found, and that happens because the second request never returned.

### Anything else:
Here is me reproducing the result (the log is too long, so it is 2 screenshots):
* ![executing1](https://user-images.githubusercontent.com/88281521/174790278-aeed2404-d3b7-4641-95ee-6dcd45d978f5.png)
* ![executing2](https://user-images.githubusercontent.com/88281521/174790301-09d9b5cb-aecd-4dea-b6a2-ec0759b6e4d5.png)

I would try to be available for any other questions you might have.
I know it might seem a bit fishy - someone random on the internet requesting from you to execute a python script, but it is the simplest solution I had. Hope you would find it acceptable.

**Comment by ehsandeep** [comment]
@DShelef We've been hearing about this behavior from multiple users, but we and users had no idea what was going on because this scenario was not reproducible during the dedicated scan with specific host, and poor network requirements explain it very well, so we really appreciate the information shared here, and **now we know what to fix**, thanks again.

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/nuclei/releases/tag/v2.7.3

**Comment by DShelef** [comment]
@ehsandeep 
Your welcome, was happy to help 😄.
And thank you for the quick response.
