### ISSUE TITLE
Add debug logging option

### ISSUE THREAD

**Issue by br-sn** [projectdiscovery/nuclei#22]
Hi,

I've had a few instances recently where it seems that nuclei is not running as expected or it seems frozen. In those cases it's hard to pin point what's going on, even with the verbose option. This makes it tricky to create a new bug report and provide you with relevant information.

I would suggest to add an option to output debug logs to a file, which could improve the quality of bug reports you receive on github.

**Comment by Ice3man543** [comment]
Hey, in pr #107, I have improved verbose mode which will allow you to see if nuclei is sending requests or sitting idle and also added a `debug` flag to see the sent requests and responses. Closing this issue now!
