### ISSUE TITLE
windows 下命令行输出格式错误

### ISSUE THREAD

**Issue by Baikeryoyo** [projectdiscovery/nuclei#2205]
[[36m2022-06-22 07:51:18[0m] [[92mrobots-txt[0m] [[94mhttp[0m] [[34minfo[0m]
以上为Windows下cmd输出
显示格式错误，颜色设置没有正常显示

**Comment by ehsandeep** [comment]
@Baikeryoyo use `-no-color` flag on the windows system to avoid this.

**Comment by forgedhallpass** [comment]
There are workarounds to show colors on Windows. Please see my answer on the relevant discussion:

https://github.com/projectdiscovery/nuclei/discussions/1509#discussioncomment-1990212
