### ISSUE TITLE
Connection reuse for RFC compliant HTTP requests

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2236]
### Please describe your feature request:
For **HTTP** protocol excluding `unsafe` requests, connection reuse could be used for performance improvements.

**Comment by Mzack9999** [comment]
Enabling connection reuse (Enabling keep-alive, disabling request.Close, removing `Connection: close` header, reading all the body) for RFC compliant HTTP requests doesn't speed up elaboration towards a single target
Normal Execution:
```console
$ time echo https://192.168.1.1 | go run . -silent -t /Users/user/go/src/github.com/projectdiscovery/nuclei-templates/technologies/
real    1m28.692s
user    0m4.909s
sys     0m2.004s
```
Connection Reuse:
```console
$ time echo https://192.168.1.1 | go run . -silent -t /Users/user/go/src/github.com/projectdiscovery/nuclei-templates/technologies/
real    1m25.623s
user    0m5.803s
sys     0m1.980s
```

**Comment by brenocss** [comment]
Were speed tests done only on local networks? I think this kind of improvement shouldn't have as much impact on local networks as on external ones.
Another suggestion would be to investigate the possibility of implementing using http pipelining.
![image](https://user-images.githubusercontent.com/57222005/182729767-80236ca8-a80e-4822-9ae3-be6feea5301a.png)

https://youtu.be/vCpIAsxESFY?t=264

**Comment by Mzack9999** [comment]
This will be reworked as part of https://github.com/projectdiscovery/nuclei/issues/3077
