### ISSUE TITLE
Support for AND based tags execution (tags / etags / itags)

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2251]
### Discussed in https://github.com/projectdiscovery/nuclei-templates/discussions/4546

<div type='discussions-op-text'>

<sup>Originally posted by **AaronChen0** June  6, 2022</sup>
I want to scan only xss on wordpress sites. I try something like, `nuclei -tags wordpress -s medium -etags tag1,tag2,tag3 -l urls.txt`. 
Any better ways?
</div>

----

### Please describe your feature request:
Allow filtering template tags with and conditions.

### Describe the use case of this feature:
More control over template execution which will allow cases like, 
- Running `wordpress` template for `xss` vulnerability.
- Running `ssrf` templates in `jira`

### Proposed solutions:

New CLI flag:

```
   -tc, -tags-condition          condition to apply on tags input, and/or (default or)
```

Existing flag improvement (more flexible):

```
nuclei -tags "xss && wordpress"
nuclei -tags "xss,ssrf && wordpress,jira"
```

**Comment by Mzack9999** [comment]
Superseded by https://github.com/projectdiscovery/nuclei/issues/2358
