### ISSUE TITLE
nuclei X httpx integration

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2253]
For running **http** protocol-based nuclei templates, nuclei expect URLs as input and do not work if non-probbed subdomains or IPs are provided.

Generally, we advise users to run [httpx](https://github.com/projectdiscovery/httpx) on the subdomain or IP list before passing to nuclei which is okay but has some drawbacks as well.

1. httpx will filter out all **non-http** services that could have been used with other protocols to run **non-http** templates.
2. not all the users realize or are able to debug the problems they are experiencing with input.

To improve user experience and adaptation, httpx could be integrated into nuclei to perform necessary probing to run **http based** templates.

Since this integration is supposed to be **automatic** and done internally, this allows nuclei engine to control when and what input needs to be probed depending on template input, i.e

1. Probing will be done only for the input that does not contain URL scheme
2. Probing will be done only when running HTTP based template.
3. Probbed data will be used only with HTTP-based templates.
4. Enables **uniform input for the nuclei engine** to run all the templates.

This integration is also a requirement for another nuclei integration with [uncover](https://github.com/projectdiscovery/uncover) in https://github.com/projectdiscovery/nuclei/issues/2254

An example showcasing difference between both ways to run nuclei:

### Running nuclei with httpx in between:

```
echo ger-ned380kv.nl | httpx -silent | nuclei -pt dns,http

[INF] No results found. Better luck next time!
```

### Running nuclei httpx integration:

```
echo ger-ned380kv.nl | nuclei  -pt dns,http

[servfail-refused-hosts] [dns] [info] ger-ned380kv.nl

**Comment by Mzack9999** [comment]
Unless I misunderstand the issue, I don't think httpx can be used as is to replace the nuclei internal engine for http protocol since the tool does many more things.
I believe the integration should be considered during the pre-processing phase only if there are fqdn names without proper http/https protocol and at least one http template listed for execution. This would potentially cover this https://github.com/projectdiscovery/nuclei/issues/2025 since we would know which IP address will be used later for TCP connection.

**Comment by ehsandeep** [comment]
> I believe the integration should be considered during the pre-processing phase only if there are fqdn names without proper http/https protocol and at least one http template listed for execution.

@Mzack9999 exactly this, sorry if I was not clear initially but the idea is to probe the urls beforehand if target input contains non-probed IPs/FQDN and also running http templates.
