### ISSUE TITLE
Too many open files error running all templates on 1k targets

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#2294]
### Please describe your feature request:

Running nuclei on 1000 URLs with All public-templates (3.9k+) gives too many open files error on default configuration. ulimit -n fixes the issue but we should investigate and figure out root cause. 

Command - 

```
nuclei -t nuclei-templates -l 1000.txt -bs 50 -c 50 -rl 700 -stats
```

**Comment by Mzack9999** [comment]
I don't know if this is still relevant. I recently tested large lists with 100k, 1M, and 10M targets on windows, osx, and Linux. The only error I got was on windows with a rate limit of -1 and high concurrency values, which is expected as PowerShell enforces a 10k threads max limit.
The user was probably low privileged with a non-modifiable amount of open file descriptors.
