### ISSUE TITLE
Add `substr` DSL function

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2304]
@ehsandeep 
python3 code
```
>>> import datetime
>>> datetime.datetime.now().strftime("%Y_%m_%d")[2:]
'22_07_18'
```
If you encounter such a situation when processing some specific payloads, please also support
substr(2,-1) == python3 xxx[2:]

thanks

**Comment by forgedhallpass** [comment]
Method signature: `substr(content string, startIndex int, optionalEndIndex int)`
When the `optionalEndIndex` is not provided, it means until the end of the string.

Examples:
`substr("xxtest", 2) == "test"`
`substr("testxx", 0, -2) == "test"`
`substr("xxtestxx", 2, -2) == substr("xxtestxx", 2, 6) == "test"`
`substr("testxx", -2) == substr("testxx", 4) == "xx"`

**Comment by hktalent** [comment]
@forgedhallpass thanks

**Comment by forgedhallpass** [comment]
Re-opening it, because it's not yet implemented. I was just detailing the requirements.

**Comment by hktalent** [comment]
@forgedhallpass Need me to contribute? I'm just worried that my code can't meet your quality requirements
