### ISSUE TITLE
CPE based template execution

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2326]
A new `-cpe` flag could be added, based on which value, we could look query CVE IDs from NIST.
```sh
nuclei -vv -cpe 2.3:a:glpi-project:glpi:9.5.5 -l targets.txt
```

Example:
```sh
curl "https://services.nvd.nist.gov/rest/json/cpes/1.0/?cpeMatchString=cpe:2.3:a:glpi-project:glpi:9.5.5&addOns=cves" | jq '.result.cpes[].vulnerabilities[]' | tr -d '"' | paste -s -d, - > /tmp/cves.csv

nuclei -vv -id $(cat /tmp/cves.csv)
```

![image](https://user-images.githubusercontent.com/13679401/180200117-37a29dd0-31f7-4f12-844d-db865f3024d9.png)
 
Todos - 
- [x] Update cve-annotate to tag CPE with template
- [x] Add support for CPE Execution / filtering

**Comment by forgedhallpass** [comment]
Related: 
* #2322
* https://github.com/projectdiscovery/nuclei-templates/discussions/4673

**Comment by ehsandeep** [comment]
This is now supported into nuclei.

```
nuclei -tc 'cpe == "cpe:2.3:a:minio:minio:*:*:*:*:*:*:*:*"' -vv
```
