### ISSUE TITLE
[feature] Create .nucleignore file to exclude path/template from running if not called specifically 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#233]
**Is your feature request related to a problem? Please describe.**
To avoid possible abuse, or running all the templates without context-awareness. 

**Describe the solution you'd like**
Creating file named `.nucleignore` which includes path or template name which will be ignored to run if running with all templates.

**Comment by bauthard** [comment]
This is done at https://github.com/projectdiscovery/nuclei/commit/320f312be081607e4303e5141830e68b027e53b0

**Comment by dwisiswant0** [comment]
Whoops 💃🏻💃🏻

**Comment by nirvana-msu** [comment]
It would be great if I could create a `.nuclei-ignore`  file in the current directory which I execute nuclei from (which would take precedence over the entries from `.nuclei-ignore` that's under templates directory). I want to make use of this feature, but at the same time I don't want to edit the file under templates directory (for one thing, I'll have issues when pulling from git to update templates).
