### ISSUE TITLE
[feature] Add helper function for rand stuffs

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#234]
**Is your feature request related to a problem? Please describe.**

Hi, I think it would be very useful to add a new help function to generate random stuffs.

For example, as in the Metasploit module.
```bash
> grep "def self.rand" /usr/share/metasploit-framework/lib/rex/text.rb
def self.rand_char(bad, chars = AllChars)
def self.rand_base(len, bad, *foo)
def self.rand_text(len, bad='', chars = AllChars)
def self.rand_text_alpha(len, bad='')
def self.rand_text_alpha_lower(len, bad='')
def self.rand_text_alpha_upper(len, bad='')
def self.rand_text_alphanumeric(len, bad='')
def self.rand_text_numeric(len, bad='')
def self.rand_text_english(len, bad='')
def self.rand_text_highascii(len, bad='')
def self.randomize_space(str)
def self.rand_hostname
def self.rand_state()
```

**Comment by averagesecurityguy** [comment]
The idea would be to add random values within payloads like:

```
id: put-method-enabled

info:
  name: PUT method enabled
  author: xElkomy
  severity: high

# https://portswigger.net/kb/issues/00100900_http-put-method-is-enabled

requests:
  - raw:
      - |
        PUT /{{RandFile}} HTTP/1.1
        Content-Type: text/plain
        {{RandText}}
      - |
        GET /{{RandFile}} HTTP/1.1
        Content-Type: text/plain
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - {{RandText}}
```

If so, I believe this is the place where the values would be added to the templates, right? https://github.com/projectdiscovery/nuclei/blob/bdb3321f5fe78f255af6c52f05bc49211380e0b3/v2/pkg/requests/bulk-http-request.go#L84-L94

Would just need to define the rand methods, maybe in a new file, requests/randtext.go?

If this is all correct, I can try to put together a PR next week.

**Comment by marcelo321** [comment]
Sorry guys but can anyone like me the dcoumentation for the random string/int generation? since I can't find it and i don't know how to use it properly

**Comment by dwisiswant0** [comment]
@marcelo321 - see https://nuclei.projectdiscovery.io/templating-guide/helper-functions/
