### ISSUE TITLE
Advanced template filtering

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#2358]
### Please describe your feature request:
Allow advanced template filtering for execution with values from **id / info** section

### Describe the use case of this feature:
More control over template execution

### Proposed solutions:

New CLI flag:

```
   -tc, -template-condition          templates to run based on dsl filer
```

## Examples

```console
nuclei -tc "author=='pdteam' && ('wordpress','xss') in tags"
nuclei -tc "severity=='high' && metadata.verified"
```

```bash
id=='tect-detect' || contains(tags,'wordpress')
contains(author,'pdteam')
tag=='wordpress' || contains(tags,'xss') && !contains(tags,'excluded')
severity=='high'
```

**Comment by forgedhallpass** [comment]
@Mzack9999 why `id='tech-detect'` with a single `=`, and the rest is with `==`?

**Comment by Mzack9999** [comment]
> @Mzack9999 why `id='tech-detect'` with a single `=`, and the rest is with `==`?

Fixed
