### ISSUE TITLE
[issue] Does Discourse XSS shows false positive or i don't know how to use it?

### ISSUE THREAD

**Issue by FaizanNehal** [projectdiscovery/nuclei#236]
**Describe the bug**
I was pentesting a website. I put hundreds of different URLs in a file and run a `nuclei Discourse XSS` scan on those urls. Nuclei found out several URLs that it think is vulnerable to XSS. As you may know that it usually generates it own new link for the vulnerable link. When I copied those links and pasted in my browser nothing happened.

So basically I am asking this question because I have tested dozens of website but this was the first one in which Discourse XSS was detected. I want to ask how can I reproduce the vulnerability it detected. Is there something that I am doing wrong or am I missing out on something or whether you think it is a false positive. Sorry for my bad explanation I hope you understands it.

**Nuclei version**
Version 1

**Screenshot of the error or bug**
I cannot post screenshots because that would be a against the privacy of the website

**Comment by bauthard** [comment]
Hey, as you said you are on version 1, you need to use the latest version which is 2.1.0, please update it and run it again.

**Comment by FaizanNehal** [comment]
Hi @bauthard 
Sorry there was a typing mistake, I already have version 2

 [2[](url)](url
![Capture](https://user-images.githubusercontent.com/45764507/90338491-7921bf80-e003-11ea-8d26-ce96909c80e6.PNG)
)

**Comment by bauthard** [comment]
Thank you for confirming, for valid XSS, you can reproduce it with 

```
site.com/email/unsubscribed?email=test@gmail.com%27\"><svg/onload=alert(1337)>
```

In case it's false positive, we appreciate it if you can push fix as PR at https://github.com/projectdiscovery/nuclei-templates, or DM us in the [Discord](https://discord.gg/KECAGdH) so we can fix it.
