### ISSUE TITLE
Not Probing all templates at once

### ISSUE THREAD

**Issue by attacker007** [projectdiscovery/nuclei#237]
Hi,

Someone in one issue mentioned that by using -t flag you can input payloads directories at once as below

```
 /nuclei-templates/{vulnerabilities,cves,default-credentials,dns,files,generic-detections,panels,payloads,security-misconfiguration,subdomain-takeover,technologies,tokens,workflows}


```

Works... But its not working, It is only checking first folder  of "vulnerabilities" payloads and not the other ones.

**Comment by bauthard** [comment]
Hey! 

You can use multiple templates using multiple `-t` flag, for example:- 

```
-t cves/ -t dns/ -t files/ -t panels
```
