### ISSUE TITLE
[issue]i have problem when i run tool 

### ISSUE THREAD

**Issue by shadihh9** [projectdiscovery/nuclei#238]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
when I run tool takes much time 
and no see the 
![nuc](https://user-images.githubusercontent.com/22076930/90436512-7f826b00-e0d9-11ea-9102-b4fd43f81d0f.png)
result

**Comment by bauthard** [comment]
Hey, make sure you are using the latest version of the project, the latest version is 2.1.0 https://github.com/projectdiscovery/nuclei/releases

**Comment by bauthard** [comment]
This is an issue due to use of older version.
