### ISSUE TITLE
Problem in url list process in  nuclei

### ISSUE THREAD

**Issue by Huntlikepro** [projectdiscovery/nuclei#2385]
### Current Behavior:
I think your amazing "nuclei" tool got some problem when pipe url list, because:
when you give url list (for example a list which contains 500 URLs) after process url's, it dose not return any information! 

but when you pip URLs one by one ( `echo "https://google.com" | nuclei` ) to nuclei, it work !?

### Steps To Reproduce:

N.B: Urls.txt file contain 500 line or more...

1. cat urls.txt | nuclei
2. it doesn't return any result in almost
3. but! if you run :  `echo "https://google.com" | nuclei` 
4. nuclei work correctly

**Comment by forgedhallpass** [comment]
@Huntlikepro 

What do you mean by doesn't return any result? Is there any error message you've received? Have you tried running the scan with `-verbose` output and/or `-json`? Could you share a screenshot maybe with the command you've used, together with the output?

**Comment by hitem** [comment]
I have a similar issue, but im running the ```nuclei -l mylist.txt``` .
I get no specific errors etc, it just dosent find anything. But when i try the URL's one by one i find multiple things. Cant really show anything as there are no errors i can find, it just say "Better luck next time!". The 3 domains im scanning have vulns in them (all set up by me) and i get multiple hits when i run -u <target> instead.

**Comment by Mzack9999** [comment]
Usually, this is related to network stability. I'm unable to reproduce the issue against `google.com`. Would it be possible to share one of the domains generating different results each time (e.g., via discord to @pdteam) so that we can investigate?
