### ISSUE TITLE
[issue] Output line truncated

### ISSUE THREAD

**Issue by Kiblyn11** [projectdiscovery/nuclei#239]
**Describe the bug**
Sometimes, some output lines are truncated.
It happens also on httpx, but much less often, on nuclei it happens at least 1 of 2 times on a 100+ hosts check.

Such as:
```
[tech-detect:apache] [http] https://example.com
[tech-detect:apache] [http] https:
[tech-detect:apache] [http] https://example2.com
https:example3.com
[tech-detect:apache] [http] https:example4.com
```

I use command like this:

```
cat hosts | nuclei -silent -t /path/to/templates/cves -t /path/to/templates/vulnerabilities -o output
```

Host file is httpx output cut of the first field, like:

```
https://example.com
http://example.com:443
http://example.com:80
http://example.com:8080
```

**Nuclei version**
2.1.0

**Comment by bauthard** [comment]
Hey @Kiblyn11,

If possible do include the URL list you are using or DM us in the discord, this is not reproducible on our side, so as @Mad-robot indicated looks like some issue with your input list.

**Comment by Kiblyn11** [comment]
Hi @Mad-robot @bauthard.

Host file seems clean and is created like this, based on httpx results:
```
httpx -title -content-length -content-type -status-code -o output-httpx
cat output-httpx | cut -d" " -f1 > clean-http-servers

# Then file is sent to nuclei
```

Unfortunately, I can't give you hosts as it's private program.
It is quite irregular as restarting a new nuclei scan on the almost same host file does not reproduce the issue each time.

Here are example of results I get.

Clean
```
[web-config] [http] http://www.example.com:80/web.config
[web-config] [http] https://www.example.com:443/web.config
[citrix-vpn-detect] [http] https://citrix.example.com:443/vpn/index.html
```

Error 1
```
[web-config] [http] http://www.example.com:80/web.config
[citrix-vpn-detect] [http] https://citrix.example.com:443/vpn/index.html
truncated.example.com:80/
```

Error 2
```
truncated.com:80/
[web-config] [http] http://www.example.com:80/web.config
```

**Comment by bauthard** [comment]
This is not reproducible as confirmed on the discord.
