### ISSUE TITLE
Automatic detection/deprecation of the `req-condition` attribute

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#2393]
### Please describe your feature request:
The template attribute `req-condition` (which enables contextual request history via numeric suffix `variable_name_n`) should be enabled automatically if DSL expressions contain any reference to variables with a numeric suffix.
We need to ensure that the engine enables the functionality automatically for the existing templates that have it set to true.

### Describe the use case of this feature:
The name of the attribute is confusing and it is easy to forget, making it automatic would simplify template creation.

### Notes
The presence of the deprecated flag `req-condition` should trigger a warning during the validation process with an informative message about removing it as it's handled automatically.

**Comment by forgedhallpass** [comment]
Related: #2394
