### ISSUE TITLE
Add proxy support for network templates

### ISSUE THREAD

**Issue by CaledoniaProject** [projectdiscovery/nuclei#2400]
I'm running nuclei 2.7.5, and I'm scanning 172.16.177.101 from 172.16.177.200. 

To verify the proxy settings, I first started a proxy on 172.16.177.101:3333, then I started scanning with the proxy:

```bash
nuclei -silent -json -pi -p socks5://172.16.177.101:3333 -u http://172.16.177.101
```

However, not all requests are sent through the socks5 proxy. From wireshark statistics lots of requests are still sent directly to the target:

![screenshot 2022-08-06 at 08 25 31](https://user-images.githubusercontent.com/1357701/183226131-3b4c678d-7ed6-4be0-a33d-45822adfe7a4.jpg)

![screenshot 2022-08-06 at 08 25 25](https://user-images.githubusercontent.com/1357701/183226129-e9ec36d6-256d-4fcc-a069-ca0f03307e51.jpg)

**Comment by forgedhallpass** [comment]
@CaledoniaProject 

Have you also tried using the `-proxy-internal` flag in addition to `-proxy`?

**Comment by CaledoniaProject** [comment]
@forgedhallpass `-pi` is same as `-proxy-internal` and it does not do what I want. Does nuclei support socks5 proxy for templates with `network` tag?
