### ISSUE TITLE
Supplied input was automatically deduplicated (781 removed) [issue]

### ISSUE THREAD

**Issue by rasiras** [projectdiscovery/nuclei#243]
i do get this every time i run nuclei 
Supplied input was automatically deduplicated (42 removed)
for a list containing 50 urls

**Nuclei version**
latest

why do this happen? do this remove the urls being checked by nuclei?

**Comment by bauthard** [comment]
Hey @rasiras, the list you are supplying has duplicate URLs, and nuclei remove duplicate inputs at runtime and it's expected behavior. 

any reason you looking to run nuclei with duplicate input? 

you can confirm duplicate entry with followings:- 

```
wc -l list.txt
```

```
cat list.txt | sort -u | wc -l
```

**Comment by rasiras** [comment]
Hello @bauthard 

But my list is already done with sort -u 
But still it gives this 
Does this consider subdomain as dup?

**Comment by bauthard** [comment]
Hey, please DM us in the discord server with the list you are testing this.
