### ISSUE TITLE
[feature] Negative Lookahead support in regex template

### ISSUE THREAD

**Issue by bjhulst** [projectdiscovery/nuclei#244]
**Is your feature request related to a problem? Please describe.**
There is no "matchers rule" to invoke boolean "not". Only _and_ and _or_ are present.
So I tried a negative lookahead regex.It does not seem to support that either in v2.1.
[ERR] Could not parse file './nuclei-templates-custom/my_regex.yaml': could not compile regex: ^((?!keyword).)*$

**Describe the solution you'd like**
A negative lookahead regex in the template possible like:
matchers:
      - type: regex
        name: regexample
        regex:
          - '^((?!keyword).)*$'

to alert/find web content where this word "keyword" is **not** found.

Some reference: https://www.regular-expressions.info/lookaround.html

**Comment by Ice3man543** [comment]
@bjhulst negative lookahead support can't be added to regex since it's not allowed by go regex library, however negative support for matchers has been added by #248. This should fix the issue.

**Comment by kpoow** [comment]
@Ice3man543 what about positive lookahead assertion? I was just trying to use the following extractor to get value, after a given string "teststring".

    extractors:
      - type: regex
        name: apikey
        part: body
        internal: true
        regex:
          - "(?<=teststring)[a-zA-Z]*"


However when executed that template with nuclei, it returned error


    [WRN] Could not parse file '/tmp/login.yml': could not compile request: could not compile operators: could not compile extractor: could not compile regex: (?<=teststring)[a-zA-Z]*

Am I doing something wrong or is issue with go regex library, like for negative lookahead maches?

**Comment by Ice3man543** [comment]
@kpoow go doesn't supports lookaheads in regex, so this is not possible.
