### ISSUE TITLE
Add ResultCallback in types.Options and move package runner outside package internal

### ISSUE THREAD

**Issue by 0xdu** [projectdiscovery/nuclei#2453]
### Describe the use case of this feature:
This is very useful when integrating nuclei with other tools to get results

For example:

```go
type Options struct {
	//other options
    .........
    ResultCallback func(result *output.ResultEvent)
}
```

When a vulnerability is discovered, this option will be called like:
```go
if (runner.Options.ResultCallback != nil) {
       runner.Options.ResultCallback(issue)
}
```

**Comment by Ice3man543** [comment]
@lucy9x this is already possible using a custom output writer that satisfies output.Writer interface. 

```go
outputWriter := testutils.NewMockOutputWriter()
outputWriter.WriteCallback = func(event *output.ResultEvent) {
	fmt.Printf("Got Result: %v\n", event)
}
```

Regarding making runner public, that's not being done due to obvious reasons since we don't want to make the interface static and part of nuclei public API
