### ISSUE TITLE
Simplify TestGetPrintableDslFunctionSignatures

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#2473]
### Please describe your feature request:
Refactor the test `TestGetPrintableDslFunctionSignatures` to make hardcoded signature maintenance easier to maintain. Hardcoded color characters make it difficult to add and move around function signatures easily.

**Comment by forgedhallpass** [comment]
I am not saying that it's very convenient, but you can put a breakpoint in https://github.com/projectdiscovery/nuclei/blob/c4ba2b4edbc23e86a7a720642be2634c28130704/v2/pkg/operators/common/dsl/dsl_test.go#L194, evaluate the return value of the `GetPrintableDslFunctionSignatures(false)` method, copy and paste it as the expected value. Your IDE should show you the exact changes from the previous version, hence you can make sure that it's indeed ok.

![image](https://user-images.githubusercontent.com/13679401/185910301-ec0ee1ed-94dd-4545-b5c3-5acdb7c5a75f.png)

It takes less than a minute.
