### ISSUE TITLE
interactsh-client 

### ISSUE THREAD

**Issue by nirsarkar** [projectdiscovery/nuclei#2513]
Version: 2.7.7
Templates loaded then problem 
Could not initialize interactsh client: could not create client: could not register to servers: could not make register request: POST https://-debug/register giving up after 1 attempts: Post

**Comment by ehsandeep** [comment]
@nirsarkar see https://status.projectdiscovery.io, public interactsh servers are subject to down based on load; either you can disable template involving oast testing with `-no-interactsh` or use [self-hosted interactsh server](https://github.com/projectdiscovery/interactsh#using-protected-self-hosted-server) with your nuclei scan using `-iserver` flag.

we are aware of the issue and working internally, but we don't have any fixed ETA or timeline for this.

**Comment by ehsandeep** [comment]
Closing as this is not an issue in nuclei and more of an availability issue of public interactsh server (being tracked internally)
