### ISSUE TITLE
Leave the browser window open upon debugging headless templates

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#2571]
Also when debug is requested, start the browser with the developer tools open. This would make debugging headless templates faster and more convenient.

**Comment by Mzack9999** [comment]
Notes:
- Child processes are usually killed when the main one terminates. A possible solution could be to pause nuclei execution before exiting and await user input (e.g. pressing a button or `CTRL + C`)

**Comment by Mzack9999** [comment]
Not planned - This can be already accomplished by using `-headless -show-browser` and sleep action in the template where it's necessary to stop:

```yaml
 - action: sleep
      args:
        duration: 9999
```
