### ISSUE TITLE
[issue] JSON output doesn't print the Name attribut 

### ISSUE THREAD

**Issue by toufik-airane** [projectdiscovery/nuclei#258]
**Describe the bug**
Following the best practice, a Nuclei template should contain the next structure:

```
info:
  name:
  author:
  severity:
  description:
```

https://github.com/projectdiscovery/nuclei-templates/blob/0997f039d823763299cc2285ef2a4785404df9a3/files/git-config.yaml#L3-L7

However, using the JSON output, the Nuclei engine doesn't parse the **name** attribute:

https://github.com/projectdiscovery/nuclei/blob/f63f5774d8c7b735cebd21d0f4468a0670791b9b/v2/pkg/executer/output_http.go#L20-L25

Would you mind to correctly parse the name attribute for proper JSON output?

Also note that on nuclei-templates, many of them lack of **description**.
So I think to add a **description** for each of them.

Thanks.

**Nuclei version**
2.1.0

**Comment by bauthard** [comment]
Hey @toufik-airane, 

Nice catch, we should definitely add `name` of template in the json output, about description, it's added lately in nuclei with following PR https://github.com/projectdiscovery/nuclei/pull/140 and was not part of it initially, it's optional field, so it's going to take some time (manual work) to add those information in all existing templates.
