### ISSUE TITLE
Download of chromium does not honor proxy settings

### ISSUE THREAD

**Issue by Skyr** [projectdiscovery/nuclei#2582]
### Nuclei version:
2.7.7

### Current Behavior:
Starting nuclei (with -v -validate; http_proxy and https_proxy environment variables are set) after fresh installation will try to download the chromium binary:
```[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[VER] Using http://proxy.intranet:3128 as proxy server
[launcher.Browser]2022/09/09 13:57:33 try to find the fastest host to download the browser binary
[launcher.Browser]2022/09/09 13:57:33 check https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1033860/chrome-linux.zip
[launcher.Browser]2022/09/09 13:57:33 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1033860/chrome-linux.zip
[launcher.Browser]2022/09/09 13:57:33 check https://playwright.azureedge.net/builds/chromium/1033860/chromium-linux-arm64.zip
```
This eventually runs into a timeout, it seems nuclei tries to connect directly to the sites (which is forbidden inside the company's network). On another machine without network restrictions, the download succeeds.

### Expected Behavior:
Download should use the proxy given by the http_proxy/https_proxy environment variables.

### Steps To Reproduce:
Use an empty home directory (no browser download cached) in a network that requires usage of an http proxy.

### Anything else:
I assume it's related to the rod library; either rod has somehow to be told to use a proxy... or I'm at the wrong location with my bug report ;-)

**Comment by Mzack9999** [comment]
I looked at the go-rod library. Unfortunately, it creates its http client. We have two options:
- Set the proxy globally so that also the go-rod one will honor that (hopefully)
- Send a patch upstream to accept a custom http client (preferred)
