### ISSUE TITLE
The program created too many directories in the /tmp directory

### ISSUE THREAD

**Issue by kw0ngr** [projectdiscovery/nuclei#2586]
Error:
Could not initialize protocols: could not create dialer: mkdir /tmp/hm4232307751: no space left on device

At the end of the program scan, the temporary files should be cleaned up.

**Comment by ehsandeep** [comment]
@kw0ngr what version of nuclei you running?

**Comment by kw0ngr** [comment]
@ehsandeep v2.7.7

**Comment by forgedhallpass** [comment]
Duplicate of #2583
