### ISSUE TITLE
[feature] dynamic key-value field support for template information 

### ISSUE THREAD

**Issue by toufik-airane** [projectdiscovery/nuclei#259]
**Is your feature request related to a problem? Please describe.**

In nuclei templates, we see people including **source** or **reference**  in comment to include external resources.

https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/cached-aem-pages.yaml#L7
https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/git-config-nginxoffbyslash.yaml#L6
https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/ibm-infoprint-directory-traversal.yaml#L8

**Describe the solution you'd like**

Would you mind to accept a field named **reference** to include external links to further materials?

Thanks.

**Comment by toufik-airane** [comment]
I would like to introduce you to the SARIF format (https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html).
It could be awesome to have the same in the DAST world.

**Comment by bauthard** [comment]
@toufik-airane we can allow dynamic `key: value` as it allows more customization for adding more info to the templates and currently will be supported for JSON output only. 

```
info:
  author: tracertea
  description: 'test capture group extraction'
  name: extraction_test_google
  severity: high
  category: fingerprint
  software: search
  random: random-x
```

**Comment by bauthard** [comment]
Thanks to @tracertea for the idea.

**Comment by bauthard** [comment]
Here we go @toufik-airane @tracertea, this is added into master. 

```
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  cve-rating: 5.9 
  product: test-application
  vul-type: xss

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
    matchers:
      - type: word
        words:
          - "burp"
        part: all
```

![image](https://user-images.githubusercontent.com/8293321/96442165-4fb22980-1228-11eb-87f5-fc6e448d5ae4.png)

**Comment by forgedhallpass** [comment]
Note: we are making the template parsing stricter to improve template validation and to avoid typos etc., hence starting with the next release (probably `2.4.4`), the desired custom meta-data will be moved under `additional-fields` attribute.
