### ISSUE TITLE
Heuristic checks

### ISSUE THREAD

**Issue by Kiblyn11** [projectdiscovery/nuclei#26]
Is there a way to do heuristics checks ?
Like the one in qsfuzz https://github.com/ameenmaali/qsfuzz#heuristics-based-testing ?

**Comment by bauthard** [comment]
Hi @Kiblyn11, 

Thank you for creating an issue for this, this is something we see it as improvement and will be added in coming updates.

**Comment by Mzack9999** [comment]
I think #111 Can address this partially
