### ISSUE TITLE
Case-insensitive matches in a smarter way

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#261]
**Is your feature request related to a problem? Please describe.**

Currently the engine does supports case-insensitive matches using regex, however it's costly since for each regex run we need to match for both Uppercase-Lowercase variants. What we could do however is add a flag called `case-insensitive: true` flag in the request block which would convert the response to lowercase at once, allowing us to match both Uppercase and lowercase by conversion at runtime.

**Comment by savushkin-yauheni** [comment]
Hi guys. It would be a great feature, because right now if there are a lot of extractors it's really expensive make them  case-insensitive.

**Comment by theguly** [comment]
sorry to reopen this, but looks like that case-insensitive only works for the word matcher, regex is still not supported even if it was the main request for this issue.

do you have a plan for supporting the /i flag in the regex, or maybe really convert the response to lowercase to workaround?
