### ISSUE TITLE
Custom Template download / update support from GitHub

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2613]
### Please describe your feature request:
As a user, I create multiple custom templates on a personal public / private GitHub repository that I wish to run / update while using nuclei from any environment without manually downloading the GitHub repository everywhere.

### Describe the use case of this feature:
- Easily sync and use personal public/private nuclei templates from GitHub in any environment.

New CLI Option under update section:

```console
   -gtr, -github-template-repo string  github template repository to download / update from
   -gt, -github-token string           github token to download templates from private project
```

Update options after change:

```console
UPDATE:
   -nu, -nuclei-update                 update nuclei engine to the latest released version
   -tu, -template-update string        update nuclei-templates to latest released version (community,github)
   -gt, -github-token string           github token to download templates from private project
   -gtr, -github-template-repo string  github template repository to download / update from
   -tud, -template-update-dir string   custom directory / location to install nuclei-templates
   -duc, -disable-update-check         disable automatic nuclei/templates update check
```

Directory structure of templates:

```bash
tree $HOME/nuclei-templates/

nuclei-templates/
├── cloud # TODO
├── community # Default nuclei templates
└── github # Custom templates downloaded from public / private GitHub project
```

Note:

1. `github-template-repo` flag accepts single, multiple (comma separated), file input.
2. `github-token` flag accept a string or ENV variable (`GITHUB_TOKEN`) input

Example uses:

Single / Multiple input:

```
nuclei -gtr ehsnadeep/template,ehsandeep/private_template -tu github
```

File input:

```console
$ cat github_projects.txt

ehsandeep/template
ehsandeep/custom_template

nuclei -gtr github_projects.txt -tu github -github-token GITHUB_TOKEN
```

```bash
$ tree $HOME/nuclei-templates/github/

github/
├── custom_template/
└── template/
```

Example run with custom nuclei templates downloaded from github:

```console
nuclei -t github/custom_template -u https://example.com
```

**Comment by vzamanillo** [comment]
I think this could be easier / abstract managing source repository files (something similar to software repositories on many Linux distributions), this way we would need a set of new options to:

- `add` a repository (from Github / anywhere, public / private)
- `remove` a repository
- `update` (all / single repository)
- `list` the repository templates, maybe using a combo `-tl -rn` (rn = repository name)

I have not clear at all which would be the best choice to specify the repository template set to use.
