### ISSUE TITLE
The silent flag seems to be being ignored with custom workflow

### ISSUE THREAD

**Issue by vzamanillo** [projectdiscovery/nuclei#262]
Nuclei 2.1.0

Related to this comment by @JeffreyShran

https://github.com/projectdiscovery/nuclei/issues/242#issuecomment-680744960

Needs to be investigated.

**Comment by Ice3man543** [comment]
@vzamanillo I think what @JeffreyShran expected from the `-silent` flag was that it will not print anything however by default it only suppresses extra output printing valid results in the end. Can @JeffreyShran weigh in here with what he expected?

**Comment by JeffreyShran** [comment]
@Ice3man543 That's correct. I would expect `-silent` to not display anything at all.

**Comment by Ice3man543** [comment]
@JeffreyShran Unfortunately, that's not how we designed it. Hence i'm closing this issue. If you feel this is needed, please feel free to reopen. For getting desired results, you can simply pipe everything to `/dev/null`!
