### ISSUE TITLE
Error upon 0 (unknown) status code

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#2626]
Response example:

Curl / burp

```http
HTTP/1.1 0 Unknown
Connection: close
Content-Type: text/html
Date: Sun, 25 Sep 2022 09:44:07 GMT
```

Nuclei error:

```console
net/http: HTTP/1.x transport connection broken: malformed HTTP status code "0"
```

Error example:

```console
[WRN] [brightsign-dsdws-ssrf] Could not execute request for http://redacted: GET http://redacted/speedtest?url=cco2507kobjllaog0n00p1jbww8oz668o.oast.online giving up after 2 attempts: Get "http://redacted/speedtest?url=cco2507kobjllaog0n00p1jbww8oz668o.oast.online": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "0"
```

Template blocked 
- [ ] https://github.com/projectdiscovery/nuclei-templates/pull/5254

Depends on:
- https://github.com/projectdiscovery/rawhttp/issues/58

**Comment by Mzack9999** [comment]
Not sure how to proceed here as `0` is not a valid HTTP status code (ref. https://www.rfc-editor.org/rfc/rfc7231#section-6.1):

> [6](https://www.rfc-editor.org/rfc/rfc7231#section-6).  Response Status Codes
>
>   The status-code element is a three-digit integer code

We could consider adding support for it if unsafe mode is used, but it's indeed a best parsing effort.

**Comment by Mzack9999** [comment]
Depends on https://github.com/projectdiscovery/rawhttp/pull/59
