### ISSUE TITLE
workflows add variable passing

### ISSUE THREAD

**Issue by capiton0** [projectdiscovery/nuclei#2627]
### Please describe your feature request:

I want to use nuclei to automate the blasting of weak passwords on the login page
So I have designed 3 templates

First, use the `tech-loginpage` template to detect the presence of a login box
```
id: tech-loginpage
info:
  name: tech-loginpage
  author: capiton

requests:
  - raw:
      - |-
        GET / HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: word
        name: loginpage
        part: body
        words:
          - "<input type=\"password\""
```
Second, use the `fuzzing-loginpage-param` template to fuzz the login interface
Matching by keywords, e.g. login fail to detect if the interface is valid
There are three parts to be fuzzy tested here:
username_param,password_param,path
```
id: fuzzing-loginpage-param

info:
  name: fuzzing-loginpage-param
  author: capiton

requests:
  - raw:
      - |-
        POST /{{path}} HTTP/1.1
        Host: {{Hostname}}

        {{user_param}}={{randstr}}&{{pass_param}}={{randstr}}

    
    payloads:
      path:
        - login
        - Login
        - login.php

      user_param:
        - username
        - user
        - account 

      pass_param:
        - password
        - pass


    attack: clusterbomb
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        condition: or
        words:
          - "login fail"
          - "user or pass wrong"
          - "pass error"

```
If the template `fuzzing-loginpage-param` matches successfully
Just start executing the template `fuzzing-loginpage-weak-password`
And I need to bring the three variables (path, user_param, pass_param) that match successfully in the template `fuzzing-loginpage-param` into the template `fuzzing-loginpage-weak-password`
If, for example, the login success flag appears
it means the weak password burst is successful
```
id: fuzzing-loginpage-weak-password

info:
  name: fuzzing-loginpage-weak-password
  author: capiton

requests:
  - raw:
      - |-
        POST /{{path}} HTTP/1.1
        Host: {{Hostname}}

        {{user_param}}={{username}}&{{pass_param}}={{password}}

    
    payloads:
      username:
        - admin
        - root

      password:
        - 123456
        - admin123


    attack: clusterbomb
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        condition: or
        words:
          - "login fail"
          - "user or pass wrong"
          - "pass error"
        negative: true

      - type: word
        condition: or
        words:
          - "login success"

```

### Describe the use case of this feature:

So, in response to the above idea
I want to achieve this through workflows templates
This is the workflows template I designed:
```
id: workflows-fuzzing-loginpage-weak-password

info:
  name: workflows-fuzzing-loginpage-weak-password
  author: capiton

workflows:
  - template: tech/tech-loginpage.yaml
    subtemplates:
      - template: fuzzing/fuzzing-loginpage-param.yaml
        extractors:    #(Here the name I did not think well, I do not know much English)
          - path
          - user_param
          - pass_param
        subtemplates:
          - template: fuzzing/fuzzing-loginpage-weak-password.yaml

```
Based on this workflows template, I want to add the ability to pass a variable to the next template after a successful match
If this function can be implemented
it would be possible to automate the blasting of many simple login pages with weak passwords
If there is additional content, I also hope to get feedback, thank you very much!

**Comment by ehsandeep** [comment]
@capiton0 it's something you will be able to do with https://github.com/projectdiscovery/nuclei/pull/2576; this PR will allow you to share: 

**1)** extracted value 
**2)** session cookie

from one template to another within the **same** workflow.

**Comment by ehsandeep** [comment]
Closing as this is being tracked as part of https://github.com/projectdiscovery/nuclei/issues/1162, an example will be shared once PR gets merged.
