### ISSUE TITLE
failed test (http/raw-unsafe-request.yaml) on windows

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2677]
### Nuclei version:
dev

### Current Behavior:

Test is failing at the initial run and passing on 2nd run with debug mode.

```
[✘] Test "http/raw-unsafe-request.yaml" failed: incorrect number of results: 0 (actual) vs 1 (expected)  Results:
```

```console
HTTP/1.1 200 OK
  Content-Length: 36
  Content-Type: text/plain; charset=utf-8
  
  This is test raw-unsafe-matcher test
  [2022-10-04 11:33:22] [basic-raw-unsafe-request-example:word-1] [http] [info] http://127.0.0.1:5431/
  
  [✓] Test "http/raw-unsafe-request.yaml" passed!
```

### Expected Behavior:
passing windows test

### Steps To Reproduce:
https://github.com/projectdiscovery/nuclei/actions/runs/3181716187/jobs/5186784229

**Comment by ehsandeep** [comment]
looks like we still have issues with this test.

**Comment by Mzack9999** [comment]
Probably related: https://github.com/projectdiscovery/nuclei/actions/runs/3311636245/jobs/5467321098

Note: somehow output on the GH action Windows shell is not parsed correctly for those tests that are run in the middle of others

**Comment by tarunKoyalwar** [comment]
Issue not reproducible  tried manually triggering on dev and by a commit on fork .
Based on execution history Failed templates are always random
