### ISSUE TITLE
[feature] Default Parameters / Headers

### ISSUE THREAD

**Issue by ossie-git** [projectdiscovery/nuclei#268]
**Is your feature request related to a problem? Please describe.**
It's not really a problem it's just related to stream-lining my work

**Describe the solution you'd like**
I sometimes find myself repeating headers (such as User-Agent) using -H over and over again. It would be great if I would save them once in a default config file and they would be used without me having to repeat it

**Comment by bauthard** [comment]
This will be handled in https://github.com/projectdiscovery/nuclei/issues/472
