### ISSUE TITLE
Issue on variable value substitution

### ISSUE THREAD

**Issue by zy9ard3** [projectdiscovery/nuclei#2684]
### Nuclei version:

2.7.8-dev

### Current Behavior :

There is an issue on Nuclei developing version `2.7.8-dev` variable value substitution as when providing value for a variable, the request is merging `=` also along with values

![dev](https://user-images.githubusercontent.com/67743789/194430971-86a7a462-d12b-4dc1-a9b1-ad0f58f44a90.png)

### Expected Behavior :

only the value should be substituted on variable

![master](https://user-images.githubusercontent.com/67743789/194431027-4e34d575-9a42-4c01-9e0b-c8bc13f86199.png)

### Steps To Reproduce :

Run `nuclei -t token-spray/any-token-spray-template.yaml -V token=xyz -debug`

**Comment by ehsandeep** [comment]
@zy9ard3 this is now fixed in the dev version.

**Comment by zy9ard3** [comment]
@pdteam

Thanks for the time !!

The issue has been fixed 

Thanks & Regards,
@zy9ard3
