### ISSUE TITLE
flagSet.CommaSeparatedStringSliceVarP undefined in cmd/nuclei/main.go

### ISSUE THREAD

**Issue by cokeBeer** [projectdiscovery/nuclei#2686]
### Nuclei version:

v2.7.7
### Current Behavior:

flagSet.CommaSeparatedStringSliceVarP undefined in cmd/nuclei/main.go
### Expected Behavior:

no errror or missing in source code
### Steps To Reproduce:

copy the cmd/nuclei/main.go to you IDE and the bug will be reported 
<img width="715" alt="image" src="https://user-images.githubusercontent.com/70683161/194524345-bfce9ea0-9f75-4245-befe-1694bdbe5458.png">

### Anything else:

seems the goflag package delete the apis in these issue/merge:
https://github.com/projectdiscovery/goflags/issues/46
https://github.com/projectdiscovery/goflags/pull/52/files
but nuclei does not update

**Comment by ehsandeep** [comment]
@cokeBeer this is fixed in dev that is using the latest goflags version; either you can pull code from dev branch or wait for next release - https://github.com/projectdiscovery/nuclei/pull/2676
