### ISSUE TITLE
[feature] Try Both http and https

### ISSUE THREAD

**Issue by ossie-git** [projectdiscovery/nuclei#269]
**Is your feature request related to a problem? Please describe.**
Is there any way to tell nuclei to try to connect using both http and https either in the CLI or in the template itself? While writing a template, I noticed that if I just use the domain, it may or may not find the target depending on if I passed in an http or https URL. In most cases this isn't an issue as you can configure your template to follow redirects but in some cases like mine (pfSense), there is no automatic redirect and the panel can be on either port. 

**Describe the solution you'd like**
It would be nice if this was either a CLI option (try both http and https) or a template option

**Comment by bauthard** [comment]
Hey @ossie-git, 

Thanks for creating this issue, but this is not in the scope of the nuclei, nuclei probe for the URLs you feed in the input list and doesn't probe on its own, so in case you don't want to miss anything just prepare your input list accordingly, as nuclei just process your input list, and does not probe on its own, with that said closing this issue as no action needed on this.
