### ISSUE TITLE
Running nuclei with multiple templates!

### ISSUE THREAD

**Issue by cyanpiny** [projectdiscovery/nuclei#27]
I guess it doesn't work on Win10?
![test](https://user-images.githubusercontent.com/41749543/79584687-68098600-80d7-11ea-9f0e-ca602cab0193.jpg)

**Comment by cyanpiny** [comment]
Using a single template works.

![](https://user-images.githubusercontent.com/41749543/79585282-41981a80-80d8-11ea-97d8-8f1fb9b7b27b.jpg)

**Comment by bauthard** [comment]
Hi @cyanpiny, 

As of now `nuclei` only supports single directory and you are passing multiple directories at once, to make it work, here is how it can be used to make it work. 

```
nuclei -l urls.txt -t "nuclei-templates/cves/*.yaml"
```
