### ISSUE TITLE
[issue] Nuclei Inconsistent Output

### ISSUE THREAD

**Issue by prodigysml** [projectdiscovery/nuclei#270]
**Describe the bug**
The output provided by nuclei, when using the -o option is inconsistent. It provides partial output at times, as displayed below:
```
      1 ]
      1 <redacted>/WEB-INF/web.xml
      1 ce<redacted>/
      1 [cgi-test-page]
      1 [citrix-vpn-detect]
      1 [//compliance-dra<redacted>/wp-content/debug.log
      1 [crlf-injection]
      1 ent/debug.log
      1 -get]
      1 [google-api-key]
      1 om/xmlrpc.php
      1 ono<redacted>.com/xmlrpc.php
      1 p-actuator]
      1 [phpinfo-files]
      1 rpc.php
      1 rs
      1 s://business<redacted>/WEB-INF/web.xml
      1 [spring-boot-dumbug.log
      1 [sp<redacted>/WEB-INF/web.xml
      1 [tech-<redacted>/.well-known/security.txt
```
**Nuclei version**
2.1.0

**Screenshot of the error or bug**
An example of where the output gets muddled is below:
```
[spring-boot-dump-actuator] [http] https://compl[wp-debug-logs] [http]
```

**Comment by toufik-airane** [comment]
I have the same issue with the `-json -o` options.
The output is still inconsistent and unprocessable.

Example:
```[...]"severity":{"template"[...]
"info",[...]}```

**Comment by bauthard** [comment]
@prodigysml @toufik-airane Can you try this branch https://github.com/projectdiscovery/nuclei/tree/fix-inconsistent-output to verify the fix?

**Comment by bauthard** [comment]
@prodigysml I've verified this on my side, should be fixed now.

**Comment by prodigysml** [comment]
Awesome work! Seems fixed to me!
