### ISSUE TITLE
nuclei 2.7.8, [ERR] Could not find template

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2702]
nuclei-templates
The same configuration, but some can be loaded and some can't. I speculate that the template directory cannot be set to the upper level directory of nuclei-templates

Of course this is important, I have some private yaml that needs to be placed in a directory at the same level as nuclei-templates

thanks

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/18223385/194906091-06689ec4-2ffd-458c-ae60-a6bfb3beca00.png">

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/nuclei-templates/discussions/5630
