### ISSUE TITLE
Building with armv7l throws error

### ISSUE THREAD

**Issue by DeC1pher** [projectdiscovery/nuclei#2736]
Hi Guys,

I just wanna let you know that when building the go package with `armv7l` I get following error:

```
github.com/projectdiscovery/nuclei/v2/pkg/utils/ratelimit
# github.com/projectdiscovery/nuclei/v2/pkg/utils/ratelimit
../go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.8/pkg/utils/ratelimit/ratelimit.go:59:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
../go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.8/pkg/utils/ratelimit/ratelimit.go:60:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
```

Best

**Comment by tarunKoyalwar** [comment]
Hii @DeC1pher , this issue seems to be similar to https://github.com/projectdiscovery/nuclei/issues/2747  .
This was caused to a delayed dependency update . It is fixed now . If you still facing issues feel free to create new issue .
I am closing it since this is resolved
