### ISSUE TITLE
I can not install nuclei on a raspberry pi 3

### ISSUE THREAD

**Issue by codefaztaz** [projectdiscovery/nuclei#2747]
### Nuclei version:

latest version 

### Current Behavior:

when I am installing nuclei with the last version of GO I get this error 

```
github.com/projectdiscovery/nuclei/v2/pkg/utils/ratelimit
# github.com/projectdiscovery/nuclei/v2/pkg/utils/ratelimit
bugpi/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.8/pkg/utils/ratelimit/ratelimit.go:59:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
```

**Comment by jimen0** [comment]
@codefaztaz Is your OS on the raspberry pi 32 or 64 bit?
if your raspberry OS is 32 bits just deploy a 64 bits one and the project should compile just fine.

```console
➜ .../nuclei/v2/cmd/nuclei (dev) $ GOOS=linux GOARCH=arm64 go build
➜ .../nuclei/v2/cmd/nuclei (dev) $ echo $?
0
```


cc @forgedhallpass this can be reproduced by building nuclei targeting for a 32 bits arm version:

```console
➜ .../nuclei/v2/cmd/nuclei (dev) $ GOOS=linux GOARCH=arm GOARM=7 go build
# github.com/projectdiscovery/ratelimit
/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.0-20221004232058-7b82379157fa/ratelimit.go:59:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.0-20221004232058-7b82379157fa/ratelimit.go:60:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
```

It comes from: https://github.com/projectdiscovery/ratelimit/blob/main/ratelimit.go#L59-L60 which use `math.MaxInt64`.

**Comment by forgedhallpass** [comment]
Thanks @jimen0 for looking into it.

At first sight it seems that we might have a relevant ticket for it: https://github.com/projectdiscovery/ratelimit/issues/4

@Mzack9999 could you please confirm?

**Comment by Mzack9999** [comment]
@tarunKoyalwar in order to prevent this from happening again, I think we can add a further step to GH actions that install the tool from latest version/commit:
```
go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@xxx (xxx => commit/version/latest)
```

**Comment by tarunKoyalwar** [comment]
`go install xx@latest` by default uses module mirror  ex:  `https://proxy.golang.org`.  

~~~
[proxy.golang.org](https://proxy.golang.org/) - a module mirror which implements the [module proxy protocol]
(https://golang.org/ref/mod#goproxy-protocol). For users downloading large numbers of modules (e.g. for bulk static 
analysis), the mirror supports a non-standard header, Disable-Module-Fetch: true that instructs it to return only cached
 content. This will avoid slow downloads, at the cost of possibly missing some rarely-used modules.
~~~

module mirror cache is refreshed every 30 minutes  .

To download latest release one can use
~~~
GOPROXY=direct go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
~~~

**Comment by tarunKoyalwar** [comment]
Future issues similar to this will be fixed by `autorelease` schedule of ratelimit library

will be closed by https://github.com/projectdiscovery/ratelimit/pull/16
