### ISSUE TITLE
Validation for template ID

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#276]
**Is your feature request related to a problem? Please describe.**
as of now, it's allowed to use spaces, caps in template ID. 

**Describe the solution you'd like**
We need to follow this format https://github.com/projectdiscovery/nuclei-templates/pull/380

**Comment by dwisiswant0** [comment]
I don't think this validation should exist in the nuclei side itself.

**Comment by dwisiswant0** [comment]
https://github.com/actions-ecosystem/action-regex-match

**Comment by dwisiswant0** [comment]
I mean; if we talk about template validation, why not validate the whole template structure all at once?

**Comment by vzamanillo** [comment]
> I mean; if we talk about template validation, why not validate the whole template structure all at once?

That is a great idea.

What about creating a template schema definition with `JSON schema` to validate the `YAML`? Is this overcomplicate the validation?

golang packages who  provides json-schema compilation and validation:

- https://github.com/santhosh-tekuri/jsonschema
- https://github.com/neilpa/yajsv

**Comment by forgedhallpass** [comment]
The regex validator for the template id should probably be something like `(?:[a-zA-Z0-9][a-zA-Z0-9]*-?[a-zA-Z0-9]+?)+` then.

@vzamanillo JSON schema generation and validation has been introduced:
* https://github.com/projectdiscovery/nuclei/pull/968
* https://github.com/projectdiscovery/nuclei/pull/1021

**Comment by vzamanillo** [comment]
I know, thanks!
