### ISSUE TITLE
hey i get any error while using nuclei new version. While using nuclei it automatically add "%" in url when it encounter %23 or %23 in url it ad extra as %%23 or %%22.

### ISSUE THREAD

**Issue by testmebuddy1976** [projectdiscovery/nuclei#277]
hey i get any error while using nuclei new version. While using nuclei it automatically add "%" in url when it encounter %23 or %23 in url it ad extra as %%23 or %%22.

**Comment by bauthard** [comment]
Hey @testmebuddy1976, 

This is a duplicate issue of https://github.com/projectdiscovery/nuclei/issues/220, it's printing issue in the terminal, the request gets sent as defined, please check the other issue for more context, also please follow issue template while creating issues.
