### ISSUE TITLE
Certain flags output to stderr despite not being errors

### ISSUE THREAD

**Issue by mattkeeler** [projectdiscovery/nuclei#2771]
### Nuclei version:

2.7.8

### Current Behavior:

The following flags output to `stderr`: `-stats`, `-stats-json`, `-h`

This makes pipes and redirects behave in unexpected ways when running commands with those flags enabled. For example, I should be able to run `nuclei -h | grep redirects` to find only those settings related to redirects, but instead nuclei outputs the full help output. The only way to make it behave the way it should is to use `nuclei -h 2>&1 | grep redirects`.

### Expected Behavior:

These flags should output their results to `stdout`, as they are not errors.

### Steps To Reproduce:

`nuclei -u https://example.com -stats-json 2> stats.json`

`nuclei -h 2> help.txt`

**Comment by geeknik** [comment]
Not a bug in my opinion as the -stats output doesn't need to pollute the nuclei output saved to file. 🤷🏻‍♂️

**Comment by mattkeeler** [comment]
Reserving `stderr` for errors is pretty standard.

Nevertheless, I think there should _also_ be an option to specify an output file for stats, which is what is confusingly suggested by this flag's description although it isn't the case:

```
~ $ nuclei -h 2>&1 | grep stats-json
   -sj, -stats-json          write statistics data to an output file in JSONL(ines) format
~ $
```

**Comment by ehsandeep** [comment]
@mattkeeler `-h` option has already been updated in `dev` branch with https://github.com/projectdiscovery/goflags/issues/85 to split the info as stdout for easy grepping, but I'm not sure about `-stats` option as it will cause more issues while results and stats will be written the same file.

**Comment by Mzack9999** [comment]
This needs further discussion - I think `stdout` would contain lots of mixed info. Other tools like nmap and masscan print information to stdout

**Comment by mattkeeler** [comment]
Adding a bit more information about my use case with `-stats`.

I've got an automated process that scans (let's say) 50k targets using multiple templates. This can take a while, and can be _very_ noisy because of the options I'm using. In my case, `stdout` is logged, and I really just want to see the occasional stats output just to see some basic information about how the scan is progressing. I'll be automatically parsing the findings as well as the stats in later steps, so I'll need to make sure they're saved to a file. I was hoping that there was a combination of flags that would let me silence everything on `stdout` except stats output, but there really isn't. 

Here's how I ended up making it work:

`nuclei -silent -disable-update-check -stats -json -no-color -include-rr -matcher-status -t /tmp/templates -list /tmp/targets >/tmp/results.jsonl 2> >(tee -a /tmp/stats.jsonl)`

**Comment by ehsandeep** [comment]
@mattkeeler not sure if this could be helpful for you; alternate to `-stats` option, there is `-metrics` option that let you get the same information on demand during the scan time; more details at https://nuclei.projectdiscovery.io/nuclei/get-started/#scan-metrics

**Comment by mattkeeler** [comment]
@ehsandeep The `-metrics` flag is handy for local usage. In my case, however, I'm running nuclei in a container and deployed on a cluster. I may have many of these scans going at once against different sets of targets. Displaying only `-stats` information is useful for checking in on containerized nuclei runs to see how far along they are, current rps, etc.
