### ISSUE TITLE
[feature] Allow progress bar whilst also using the -silent flag

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#279]
**Is your feature request related to a problem? Please describe.**
The progress bar is hidden when the `-silent` flag is used.

**Describe the solution you'd like**
Allow `-pbar` and `-silent` to be used together.

**Comment by bauthard** [comment]
Hey @geeknik, 

we wanted to make sure `-silent` is complete silent, any specific reason or problems you are facing using `pbar` without silent flag?

**Comment by geeknik** [comment]
Well the information about the various templates loading isn't very useful to me, so if i could shut that down whilst retaining use of the progress bar that would be swell. 👍🏻

**Comment by bauthard** [comment]
@geeknik this feature is added in the master code, thanks to @vzamanillo for quicking adding this support.

**Comment by geeknik** [comment]
Many thanks friend! \m/
