### ISSUE TITLE
Concurrency issue - Nuclei Scan is taking too long to complete compare than previous versions

### ISSUE THREAD

**Issue by zy9ard3** [projectdiscovery/nuclei#2793]
Hi Team,

Hope All are going well !!

### Nuclei version :

> Latest - 2.7.8

### Issue :

* There seems to be issue on concurrency, where nuclei scan is getting dropped to too slow and taking too long ( days++... ) to complete compared to previous versions 

* Even though tried with all adjustments like increased concurrency, parallel analyze hosts, etc... has set to maximum whatever!!, but still the same and no improvements in duration

> ![Too Long](https://user-images.githubusercontent.com/67743789/199450651-c8746e03-b0ff-4b68-80ae-b1c0ca7d203b.png)

* I started a scan for lists of 11000+ hosts 2 days ago with excluded severity of info,unknown ( `-es info,unknown` ) even along with increased max concurrency of `-c 80` and `-bs 80`, but the scan is still running and not seems even completed 40% of scanning

* From my observation, the issue started occurring after the fix for [Memory leak issue](https://github.com/projectdiscovery/nuclei/issues/2567) on last release

*Kindly let me know if anything I missed out, I'm glad to assist with pleasure on any questions/infos if required further*

Thanks & Regards,
@zy9ard3

**Comment by zy9ard3** [comment]
**And the scan is still running ( 07 Days 07 Hours 55 Minutes ) and seems still not even completed 50% of scan**

> ![7 Days](https://user-images.githubusercontent.com/67743789/200396576-71828720-f259-4af1-bacc-864950b1c3b4.png)

Thanks & Regards,
@zy9ard3

**Comment by tarunKoyalwar** [comment]
@hakrishi  @zy9ard3  , Since testing with scaling is not easy .pls provide following data

1. Exact command used .
2. total no of hosts that were being Scanned.
3. VPS/System setting ( cores, RAM , possibly network bandwidth (ex: 50mbps) )
4. Data indicating performance . Ex it took 50 hrs consumed 20GB RAM etc (anything you remember or can share).

the more accurate that is better . 
Thanks and Regards,

**Comment by zy9ard3** [comment]
Hi @tarunKoyalwar 

Thanks for looking into this !!

> Exact command used

nuclei -u targets.txt -es info,unknown -o out.txt

> total no of hosts that were being Scanned

11727

> VPS/System setting ( cores, RAM , possibly network bandwidth (ex: 50mbps) )

Digitalocean VPS with

Cores - 4
RAM - 8GB
Network Bandwidth - 30mb/s

> Data indicating performance

It took **11 Days 09 Hours 50 Minutes** to complete the scan

*Kindly let me know if anything I missed out, I'm glad to assist with pleasure on any questions/infos if required further*

Thanks & Regards,
@zy9ard3

**Comment by tarunKoyalwar** [comment]
@zy9ard3  , I'm working on this . resolving this requires major changes and code refractoring . so I am letting you know It may take a while

**Comment by zy9ard3** [comment]
@tarunKoyalwar 

Thanks for the update and confirmation !!

Thanks & Regards,
@zy9ard3

**Comment by tarunKoyalwar** [comment]
Hii @hakrishi  @zy9ard3 .  For the time being use `-bs 100` and `-c 10` as a temporary measure . this will prevent RPS dropouts and keep it constant . If you want to change it just try to keep `bs x c < 1500` or 2000 . It might be lower depending on available bandwidth and RAM

**Comment by tarunKoyalwar** [comment]
also do not rate limit unless required or scanning single host .
