### ISSUE TITLE
New Input type (Raw Requests) support for authenticated query parameters fuzzing 

### ISSUE THREAD

**Issue by parthmalhotra** [projectdiscovery/nuclei#2795]
### New input type support : Raw Requests

Use cases for url query fuzzing / post body fuzzing

Take raw requests as Input in nuclei, Parse the request and run fuzzing engine with the input raw request, this the request can be supplied via multiple options :

1) individual reqs saved in txt files in a directory which can be generated via nuclei burp extension / Dump - burp extension
2) Automatically parse from burp's project file
3) proxify
optional global session/csrf handling helper templates (replacers)

In the future helpers of the fuzzing engine can be added to generate/extract valid csrf/session tokens, user can easily define how a valid csrf/session token can be extracted and where it should be replaced in the input raw request in the case of strict csrf/session validation

This will also help in automating horizontal / vertical permission checks/ idors etc with additions of replacers in raw reqs

**Comment by ehsandeep** [comment]
Suppressed by https://github.com/projectdiscovery/nuclei/issues/2795
