### ISSUE TITLE
[issue] Header with colon gets cut

### ISSUE THREAD

**Issue by DeC1pher** [projectdiscovery/nuclei#280]
Hey Team,

I just figured out, that when running nuclei with additional headers provided via `-H` colons get cut

**Example**

`echo "https://randomhost.de" | nuclei -t vulnerabilities/cached-aem-pages.yaml -proxy-url http://localhost:8080 -H "Referer: http://localhost:1337"`

I can see following in burp:

```
GET /dispatcher/invalidate.cache HTTP/1.1
Host: randomhost.de
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)
Accept: */*
Accept-Language: en
CQ-Handle: /content
CQ-Path: /content
Connection: close
Referer: http//localhost1337
Accept-Encoding: gzip, deflate
```

So the additional header is set but the colons removed.

Kind regards,
DeC1pher

**Comment by bauthard** [comment]
Thank you for creating the issue @DeC1pher

**Comment by bauthard** [comment]
@DeC1pher this is fixed in the master code.
