### ISSUE TITLE
Using Nuclei From Go Code need to update

### ISSUE THREAD

**Issue by shadow1ng** [projectdiscovery/nuclei#2803]
- [ ] Update the [existing](https://github.com/projectdiscovery/nuclei/blob/master/DESIGN.md#using-nuclei-from-go-code
) code example.
- [ ] Add Integration test for using nuclei as code

https://github.com/projectdiscovery/nuclei/blob/master/DESIGN.md#using-nuclei-from-go-code

```console
cannot use ratelimit.New(150) (value of type "go.uber.org/ratelimit".Limiter) as type *"github.com/projectdiscovery/nuclei/v2/pkg/utils/ratelimit".Limiter in struct literal
```

**Comment by forgedhallpass** [comment]
The integration test will be handled in another ticket: https://github.com/projectdiscovery/team-backlogs/issues/224

**Comment by shadow1ng** [comment]
ok
