### ISSUE TITLE
Scan report shows different results in Direct command and in Bash script 

### ISSUE THREAD

**Issue by vijaykumar-h1** [projectdiscovery/nuclei#2808]
### Nuclei version:
Latest 

### Current Behavior:
Scan report shows different results in Direct command and in Bash script 

### Expected Behavior:
It should show same results as direct command. 

### Steps To Reproduce:
1.Run the below direction command. 
nuclei -l [input_file] -es info -o [output_file].
2.Now run the same command in bash script as function.
Ex : 
nuclei_list()
{
nuclei -l [input_file] -es info -o [output_file]
}
3.Now run both separately and the results would be different. 

 

### Anything else:
Attaching the screenshots. Remove it if you find it sensitive. 
![image](https://user-images.githubusercontent.com/64110106/200120826-380f4934-29e8-4e45-a51b-092647ebc8de.png)
![image](https://user-images.githubusercontent.com/64110106/200120790-256556d6-4017-44af-8869-1e0892b852c7.png)
![image](https://user-images.githubusercontent.com/64110106/200123961-15f6809b-c551-4c2f-af28-752b4ef5041d.png)

**Comment by vijaykumar-h1** [comment]
![image](https://user-images.githubusercontent.com/64110106/200124021-fd6610cc-90d0-42a4-899c-9ad5e8d7b993.png)
I think the first image of Function code in bash script didn't come clear hence uploading it again. Please have a look and let me know if it's a problem with my server or it's a problem with the tool.

**Comment by ZishanAdThandar** [comment]
because it is resuming the progress. nuclei saves progress. try it in different device.

**Comment by tarunKoyalwar** [comment]
@vijaykumar-h1  ,

This is more likely a network issue .  try to use `-stats` flag whenever possible this will shows stats (total req,errors etc)
and it also depends on the server . 

If you see more than expected errors in nuclei output . try to adjust the scan settings depending on network connectivity and  web server

```sh
RATE-LIMIT:
   -rl, -rate-limit int               maximum number of requests to send per second (default 150)
   -rlm, -rate-limit-minute int       maximum number of requests to send per minute
   -bs, -bulk-size int                maximum number of hosts to be analyzed in parallel per template (default 25)
   -c, -concurrency int               maximum number of templates to be executed in parallel (default 25)
   -hbs, -headless-bulk-size int      maximum number of headless hosts to be analyzed in parallel per template (default 10)
   -headc, -headless-concurrency int  maximum number of headless templates to be executed in parallel (default 10)
```

**Comment by tarunKoyalwar** [comment]
If you want to add bash function to nuclei . Use arguments instead of fixed paths 

~~~sh
nuclei_scan()
{
   nuclei -l $1 -headless -stats -o $2  -es info 
}
~~~

The input files in screenshots are relative and depends on the directory where they are run which is most likely the case  in the screenshots the targets in both the screenshots are different 

I am closing this issue since this is not a problem . Feel free to open it if you face any issue

https://github.com/projectdiscovery/nuclei/issues/2808#issue-1437044473
