### ISSUE TITLE
Timestamp format broken in Windows executable

### ISSUE THREAD

**Issue by H2Cyber** [projectdiscovery/nuclei#2812]
### Nuclei version:
2.7.8

### Current Behavior:
Timestamp information seems to be broken in recent Nuclei versions for Windows : 

![Screenshot from 2022-11-06 20-41-43](https://user-images.githubusercontent.com/764189/200191554-14e02069-bc6f-41da-94ac-e394ee3bbebd.png)

### Steps To Reproduce:
1. Download Nuclei 2.7.8 for Windows Amd64 
2. Launch a scan via CMD or Powershell
3. Notice how the timestamp field is misformatted

**Comment by ehsandeep** [comment]
@H2Cyber use `-nc` option to disable color, which is not supported on windows.
