### ISSUE TITLE
Open Redirect template issue

### ISSUE THREAD

**Issue by RutgerHrm** [projectdiscovery/nuclei#2816]
### Nuclei version:
2.7.8

### Current Behavior:
Executing `open-redirect.yaml` uses target path `/{{redirect}}` on the target `http://example.com/redir.php?r=` resulting in payloads like `/redir.php/%0a/interact.sh/?r=`. 

### Expected Behavior:
The payloads should be inserted after `?r=` in order for the application to redirect, e.g. `/redir.php?r=https://malicious.com`

### Steps To Reproduce:
1. Run `nuclei -t open-redirect.yaml -u "http://testphp.vulnweb.com/redir.php?r=" -debug`
2. See sent payloads, e.g. `/redir.php/https://www.malicious.com?r=`

**Comment by forgedhallpass** [comment]
Note, the following doesn't work either:
1. ` GET {{concat(BaseURL, redirect)}} HTTP/1.1`

The requests are being made against the `BaseURL` only.

2. `GET {{redirect)}} HTTP/1.1` without the forward slash (one might expect implicit concatenation to the input URL) results in undefined variable for `redirect`.

**Comment by ehsandeep** [comment]
@RutgerHrm you can use https://github.com/projectdiscovery/fuzzing-templates/blob/main/redirect/open-redirect.yaml for the usecase you shared above.

**Comment by RutgerHrm** [comment]
@ehsandeep Perfect, thanks!
