### ISSUE TITLE
not finding subdomain takeovers and not fully scanning all domains

### ISSUE THREAD

**Issue by soupnatzi** [projectdiscovery/nuclei#283]
hi ,

nuclei is not fully finding vulnerable subdomain takeovers and not fully scanning all domains in a file list i on purpose place a domain vulnerable to heroku subdomain takeover in the file list.

running:
first i get this warning which out of 600 domains it only gives output of only 6 or 7 domains it does not fully scan all domains.

nuclei -l /root/Desktop/subdomains-takeovers/domains.txt -t /root/nuclei-templates/subdomain-takeover/detect-all-takeovers.yaml

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] Supplied input was automatically deduplicated (321 removed).
[INF] Loading templates...
[INF] [detect-all-takeovers] Subdomain Takeover Detection (@melbadry9 & pxmme1337) [high]
[INF] Using 1 rules (1 templates, 0 workflows)

[detect-all-takeovers:thinkific] [http] https://domain.com/
[detect-all-takeovers:heroku] [http] https://domain.com/
[detect-all-takeovers:thinkific] [http] https://domain.com/
[detect-all-takeovers:thinkific] [http] https://domain.com/
[detect-all-takeovers:heroku] [http] https://domain.com/
[detect-all-takeovers:heroku] [http] https://domain.com/
[detect-all-takeovers:heroku] [http] https://domain.com/
[detect-all-takeovers:heroku] [http] https://domain.com/

is there something am doing wrong here?i doubted tho but would love to know the issue here.

**Comment by bauthard** [comment]
@soupnatzi, 

About warning, `nuclei` remove duplicate entry before starting scans, you can confirm this locally with 

```
wc -l your_list.txt
```

```
sort -u your_list.txt | wc -l
```

about missing valid takeover of `heroku`, here is [defined template logic](https://github.com/projectdiscovery/nuclei-templates/blob/master/subdomain-takeover/detect-all-takeovers.yaml#L163), you can confirm if it's a valid match or not. 

If something is defined in the template and you see the same response with your target and still not getting a match, you can reach out to us on [discord](https://discord.gg/KECAGdH) server with details so we can look more into it, if you see the problem and know the solution, feel free to update the template with PR.

**Comment by bauthard** [comment]
Closing due to lack of information.

**Comment by Akokonunes** [comment]
[Video-youtube] http://test/test#[url]onload=alert();//[/url]&amp;1=1[/video]
