### ISSUE TITLE
Can't install nuclei

### ISSUE THREAD

**Issue by gevakun** [projectdiscovery/nuclei#284]
Hi team, why if i try to install nuclei, this will happen:

cannot find package "github.com/projectdiscovery/nuclei/v2/cmd/nuclei" in any of:
	/usr/local/go/src/github.com/projectdiscovery/nuclei/v2/cmd/nuclei (from $GOROOT)
	/root/go/src/github.com/projectdiscovery/nuclei/v2/cmd/nuclei (from $GOPATH)

Any solution? thanks.

**Comment by bauthard** [comment]
Hey @gevakun, you can simply download the binary for your system from https://github.com/projectdiscovery/nuclei/releases, looks like an issue with your GO setup.

**Comment by Iamstanlee** [comment]
I had the same issue, the install from [github](https://github.com/projectdiscovery/nuclei#from-github) worked

**Comment by gevakun** [comment]
> Hey @gevakun, you can simply download the binary for your system from https://github.com/projectdiscovery/nuclei/releases, looks like an issue with your GO setup.

Hi @bauthard ,  i just tried download the binary and move it to gopath, now it's working! Thanks :)

**Comment by gevakun** [comment]
Hey @Iamstanlee, maybe you can try the steps like @bauthard mentioned above.

**Comment by vlakhani28** [comment]
Hello 

I had also encountered this issue 

![image](https://user-images.githubusercontent.com/42069316/92325754-a85ba780-f06a-11ea-8774-c6c7521491d5.png)

I resolved this using a simple thing

The below command has the folder "v2" but if u run this and manually check the go path u will encounter that there is no such folder "v2"
go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei

So all you have to do is create a folder "v2" and simply shift the whole "cmd" folder into the newly created folder "v2" and then rerun the command go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei

It worked for me i hope it works for u too

![image](https://user-images.githubusercontent.com/42069316/92325875-86165980-f06b-11ea-856b-c05b46b47c14.png)

**Comment by tanujjane** [comment]
Try this 

GO111MODULE=auto go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei

**Comment by DeC1pher** [comment]
Really strange, I have also a issue.

With go1.14.4 `go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei` works.
With go version go1.15 I get also `cannot find package` error but `go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei` without v2 works on 1.15.. if I run that on 1.14.4 I get nuclei v1...
