### ISSUE TITLE
Resuming rewriting the output file contents, so previous data removed

### ISSUE THREAD

**Issue by ZishanAdThandar** [projectdiscovery/nuclei#2851]
### Current Behavior:
Resuming nuclei command with same output file rewriting the output file contents, so previous data removed. 

### Expected Behavior:
When using same command to resume nuclei with same output file, new scan results should append on the output file instead of creating new file and overwriting on it.

### Steps To Reproduce:
1. Run 'nuclei -t templates -l hosts.txt -o a.txt'
2. CTRL+C
3.  Run again 'Run 'nuclei -t templates -l hosts.txt -o a.txt''
4. Now check output file, that first scan data removed from the file after rerunning the script.

**Comment by ehsandeep** [comment]
@ZishanAdThandar JFYI, resuming scan needs to be used with `-resume` option, for the default run, it's expected to be overwritten to file as it counts as a new scan, we are fixing this issue with append the result when `-resume` option is used.
