### ISSUE TITLE
Could not read nuclei-ignore file: open /home/kali/.config/nuclei/.nuclei-ignore: no such file or directory

### ISSUE THREAD

**Issue by bondhondas** [projectdiscovery/nuclei#2853]
Could not read nuclei-ignore file: open /home/kali/.config/nuclei/.nuclei-ignore: no such file or directory
<img width="501" alt="Screenshot_20221116_053442" src="https://user-images.githubusercontent.com/19687230/202030192-e7ccc8fc-b24a-4119-af10-6c44444dc324.png">

**Comment by ehsandeep** [comment]
@bondhondas cloud you also share the output of `nuclei -hc`?

**Comment by Mzack9999** [comment]
Closing as not reproducible
