### ISSUE TITLE
[feature] flag to update nuclei to latest version. 

### ISSUE THREAD

**Issue by team-projectdiscovery** [projectdiscovery/nuclei#289]
**Is your feature request related to a problem? Please describe.**

To make the UX better and avoid issues related to the use of older versions causing issues. 

**Describe the solution you'd like**

Adding a new flag named `update` will simply pull the latest released binary file for a specific OS and move the binary to the executable location on the system.

**Comment by bauthard** [comment]
This will also include the version check feature similar in a way we do nuclei-templates and warn the users if using an outdated version of nuclei.

**Comment by pankajninjasec** [comment]
i didnt able to install new version of nuclei

**Comment by team-projectdiscovery** [comment]
This will be handled with a separate tool allowing to self-check / update all the tools released under https://github.com/projectdiscovery
