### ISSUE TITLE
[feature] Rate-limit control per host 

### ISSUE THREAD

**Issue by putsi** [projectdiscovery/nuclei#292]
**Is your feature request related to a problem? Please describe.**
Nuclei currently provides `-c` for limiting number of concurrent requests. However it would be useful to limit maximum speed of requests per host.

For example, some bug bounty policies state that any testing should not exceed 10 requests / host / second. The current implementation can easily lead to hundreds of requests per second even when using `-c 1`.

**Describe the solution you'd like**
Add flag for manually limiting requests per host per second/minute.

**Comment by bauthard** [comment]
@putsi this makes sense, thank you for creating an issue for this, we will add this feature in future updates.

**Comment by nirvana-msu** [comment]
@Mzack9999 did this feature disappear in the recent v2.2.0? You've previously added `-rl` flag to limit number of requests **per host**, it was then renamed to `rate-limit`, and eventually description changed to `Maximum requests/second` [here](https://github.com/projectdiscovery/nuclei/commit/8eea7345bd0e62291dac345aad60292e8b64ffad). It appears to not be per-host anymore? This is a very obscure change not mentioned anywhere in the changelog, and the old behaviour was immensely useful..

**Comment by bauthard** [comment]
Hi @nirvana-msu, 

Unfortunately, we moved to the global rate limit strategy and updated other flags to control other variables that allow controlling per host executions, you can read about it in details here https://github.com/projectdiscovery/nuclei#rate-limits

**Comment by nil0x42** [comment]
> Hi @nirvana-msu,
> 
> Unfortunately, we moved to the global rate limit strategy and updated other flags to control other variables that allow controlling per host executions, you can read about it in details here https://github.com/projectdiscovery/nuclei#rate-limits

Hi ! As an example, if you run nuclei on 100 hosts, how to make sure that it sends at most 1req/sec per host ?

**Comment by geeknik** [comment]
-rl 1 -rlm 60

**Comment by ehsandeep** [comment]
As geeknik suggested, either you can use `rl` to define max number of requests allowed to make per second or `rlm` for per minute.

**Comment by nil0x42** [comment]
I tried this:

----
`simplehttpserver -https -listen 0.0.0.0:443`

----

`cat /tmp/hosts`
```
https://127.0.0.1
https://127.0.0.2
...
https://127.0.0.99
https://127.0.0.100
```

----
`nuclei -l /tmp/hosts -rl 1 -bs 100 -v`

----

And unfortunately, nuclei makes 1req/sec GLOBALLY, so every individual host theorically receives 1req every 100seconds in average. It makes scanning danm slow.

I'm missing so much the per-host rate limit

**Comment by ehsandeep** [comment]
ooh looks like we misunderstood @nil0x42, yes that's true, nuclei doesn't support the per-host rate limit, initially, we did but the way nuclei scan works, like taking thousands of host and hundreds of templates to process, per host limits became hurdles at the code level, so we introduced global rate limit, so as you noticed already, `rl` or `rlm` will set global rate limit and not per host.

**Comment by sbani** [comment]
Hi @ehsandeep, just wanted to add myself to the list of users who really anticipate this feature.

I have a list of 6000 domains but I have no control over the max. number of requests per host. However, my "customers" will always ask me to limit the requests on their host. That said, they obviously mean the limit per host because they don't care about the other hosts on the list - even if they belong to themself.

With this comment here I hope to push the topic again. Feel free to ask whatever comes to your mind :) 

Thank you for doing such a great work here.

**Comment by tarunKoyalwar** [comment]
@sbani , it is now being tracked in a new issue here https://github.com/projectdiscovery/nuclei/issues/3547
