### ISSUE TITLE
When debugging make variables output optional

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#2928]
### Nuclei version:
`main` and `dev`

### Current Behavior:
The `-debug` flag prints out request/response + variables, making the output unreadable

### Expected Behavior:
Variables should be printed in a more concise way (eg. batched inline) or only if requested

### Steps To Reproduce:
```console
$ go run . -t test.yaml -debug -u http://scanme.sh
...
[DBG] Protocol response variables:
        1. Scheme => https
        2. service => sts
        3. BaseURL => http://scanme.sh
....
        100. File => /
...
```

**Comment by ehsandeep** [comment]
@Mzack9999 this is already done in `dev`, as part of https://github.com/projectdiscovery/nuclei/issues/2670

**Comment by Mzack9999** [comment]
Duplicate of https://github.com/projectdiscovery/nuclei/issues/2670
