### ISSUE TITLE
[feature] Headless Browser Support

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#295]
**Is your feature request related to a problem? Please describe.**
It would be nice to have headless browser support of certain type of requests

**Comment by bolli95** [comment]
I would say this is a very important feature as access via libraries like net/http is very often denied by WAFs/CDNs. A headless browser can be configured to act like a real user for WAFs/CDNs.  It would even make sense to use it for all HTTP requests.

**Comment by Ice3man543** [comment]
This should be done by PR #562. Closing!
