### ISSUE TITLE
Issue with custom config input

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2956]
### Nuclei version:
`master` | `dev`

### Current Behavior:
default + custom config file is being utilised combined when custom config is passed.

### Expected Behavior:
when custom config file is passed using `-config` option, default config should be ignored completely.

### Steps To Reproduce:

```
nuclei -config test_config.yaml -u https://example.com -id tech-detect
```

This will load both `test_config.yaml ` and `~/.config/nuclei/config.yaml`

**Comment by tarunKoyalwar** [comment]
@ehsandeep  , nuclei has two options two specify configs

1. `-config-directory`  which loads config directory (i.e .nuclei-ignore and config.yaml file )
2. `-config` which loads config.yaml but also tries to load `.nuclei-ignore` file it is present in that directory 

`config.yaml` and `.nuclei-ignore` are both used to load configs . 
`-config` flag currently loads defaults (from default config dir) and overrides it with extra config from (xxx/config.yaml)

If we were to force `-config` to skip defaults completely it would be equivalent to `-config-dir` and there would be no difference between these flags

**Comment by ehsandeep** [comment]
Thank you for sharing these additional points @tarunKoyalwar, it seems that keeping the current behavior would be the best option as changing it could cause more problems than it would solve.
