### ISSUE TITLE
Nuclei unable to reach host under workflow

### ISSUE THREAD

**Issue by funderpanda** [projectdiscovery/nuclei#2967]
### Nuclei version:
Current Version: 2.7.9 (in docker)

### Current Behavior:
I'm working with a website behind a VPN scanning with a nuclei workflow is unable to reach the host however when I scan without a workflow it can reach the host (same network conditions)

### Expected Behavior:
I shouldn't get a WRN saying it's unable to reach the host

### Steps To Reproduce:
Here are my two workflows
```
id: session-sharing-workflow

info:
  name: Value Sharing Test
  author: pdteam

workflows:
  - template: ./auth.yaml
```

```
id: auth
info: Test RAW template
author: funderpanda
severity: info

requests:
  - raw:
      - |
        GET /login?username=user&password=pass HTTP/1.1
        Referer: /Curam/logon.jsp

    cookie-reuse: true
    redirects: true
    max-redirects: 10

```

### Anything else:
I've tried using system resolvers flag but no change

**Comment by Mzack9999** [comment]
@funderpanda Thanks for opening this issue. Two questions while using the VPN:
- Are you able to reach the host executing the single template (eg, `nuclei -u https//your.host -t auth.yaml`)?
- Are you reaching the host with curl (eg `curl -k https//your.host)?

**Comment by funderpanda** [comment]
Hi I managed to fix this. When using the workflow it wasn't using my system DNS despite using system resolvers. When I specified my resolver in a txt file the issue fixed itself
