### ISSUE TITLE
Support for actual valid JSON and proper naming of `-json` and `-jsonl`

### ISSUE THREAD

**Issue by JaneX8** [projectdiscovery/nuclei#2976]
`JSON !== JSONL` which is why this is just painful to look at: `-json             -            write output in JSONL(ines) format`

I suggest for the sake of accuracy to rename the `-json` flag to a more accurate description `-jsonl`. Also it literally takes a few more characters to make it a full valid JSON object:
- `[` at the beginning
- `]` at the end 
- `,` between every line

I don't know why JSONL was chosen over actual fully valid JSON. I can only imagine that's possibly easier to process in case of one massive JSON object, but this choice isn't motivated or documented as far as I can tell. However I would never stuff multiple JSON objects into one file without making it a full JSON object. Also I would call it JSON or using the `.json` file extension for that matter because it's syntax would not be valid JSON.

I know that doing this would break backwards compatibility (bc), but I still think it's worth it considering it's currently misleading, inaccurate, producing not valid JSON but the semi-standard JSONL. Alternatively for this major version `-json` could be bc and `-jsonl` and `-all-json` or `-full-json` or something like that could maybe fix the issue too.

**Comment by forgedhallpass** [comment]
JSONLines is more efficient for both producing and processing because you don't need to load the whole content into the memory. You can append and read line-by-line.

If you are using `jq` for post-processing, you can use the `--slurp` flag to transform it into one JSON object.

**Comment by JaneX8** [comment]
JSONLines shouldn't even be a format to begin with in my opinion and before Nuclei I've never heard of it. However, I understand it's potential use cases and benefits but my problem with this is more fundamental. It's calling it something that it isn't. 

Correct: `JSON == JSON` and `JSON Lines = JSON Lines`. 
Incorrect: `JSONL == JSON`, that's the current use and it's wrong.

Using `-json` for JSONL format at least suggests it's something that it isn't.

As for the documentation I suggest something like this:

> `-json` will output one JSON object with all results. Note that using one JSON object for all results can result in a massive JSON object when large result sets are involved. Such a large JSON object would potentially require more system memory for processing. When large result sets are expected consider the use of `-jsonl` instead.

> `-jsonl` will output a valid JSON object per new line according to the JSONL (or JSON Lines) format. This can be helpful for processing with less system memory when large result sets are expected. If one JSON object for all results is prefered consider using `-json` instead. Note that JSONL can also be converted back to one JSON object with tools such as `jq --slurp`.

**Side-note:** I didn't test this but output that is converted to JSONL format needs to have all new lines in it escaped with no single exception or the whole JSONL file is broken. We've seen this with ancient CSV-like formats too.

**Comment by kchason** [comment]
@JaneX8 I created a pull request (https://github.com/projectdiscovery/nuclei/pull/3466) for this that does the following:

- Switch the existing `-json` option to `-jsonl` to more accurately reflect the format
- Update test objects and documentation related to switching the `-json` option to `-jsonl`
- Add  `-je, -json-export string` option that exports the results to a JSON file. This is related to your request to support a JSON array output but is intended to be more inline with the `-me, -markdown-export string` and `-se, -sarif-export string` export options
