### ISSUE TITLE
Missing Docker HEALTHCHECK

### ISSUE THREAD

**Issue by JaneX8** [projectdiscovery/nuclei#2982]
The [Center for Internet Security (CIS)](https://www.cisecurity.org/cis-benchmarks/) benchmark recommends that every dockerfile has a HEALTHCHECK defined and currently the [Dockerfile](https://github.com/projectdiscovery/nuclei/blob/main/Dockerfile) does not have one defined.

> The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working. This can detect cases such as a web server that is stuck in an infinite loop and unable to handle new connections, even though the server process is still running. - https://docs.docker.com/engine/reference/builder/

**Comment by Mzack9999** [comment]
@ JaneX8 This instruction would benefit containers running a web service.
In the case of nuclei, unless I'm mistaken, the "container running" would mean the nuclei process is active. So something like:

```docker
HEALTHCHECK --interval=5m --timeout=3s \
  CMD ps -aux | grep nuclei || exit 1
```

Does this make sense?

**Comment by Mzack9999** [comment]
Closing as completed - Stats are available via the embedded web server bound to localhost
