### ISSUE TITLE
CLI variables are not accessible in SSL Protocol

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#2986]
### Nuclei version:
2.8.1

### Current Behavior:
I'm using a template that receives a variable value from cli, but there's no way (I could find) to retrieve the value to the template and to the assign variable. In none of my tests I was able to retrieve the value of variable test. 

This works:

```
nuclei -t http.yaml -u hackerone.com -var test=gg
```

```console
nuclei -t http.yaml -var test=gg -u hackerone.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.1

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.1 (latest)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[basic-example] [http] [info] https://hackerone.com [gg]
```

Not this:

```
nuclei -t ssl.yaml -u hackerone.com -var test=gg
```

Template:

```console
nuclei -t test.yaml -var test=gg -u hackerone.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.1

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.1 (latest)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
```

**Comment by xm1k3** [comment]
Hi @pdelteil,
Can I ask you to provide me with more information about these templates?
just to know what is in `http.yaml` and `ssl.yaml` to debug

Thanks

**Comment by Mzack9999** [comment]
@xm1k3 I guess the template should be similar to this one:

```yaml
$ cat test.yaml
id: mismatched-ssl

info:
  name: Mismatched SSL Certificate
  author: pdteam
  severity: low
  tags: ssl

ssl:
  - address: "{{Host}}{{test}}:{{Port}}"

    matchers:
      - type: dsl
        dsl:
          - "mismatched == true"
$ go run . -t test.yaml -var test=.com -u hackerone -v
```

@pdelteil CLI/ENV variables support for SSL templates wasn't implemented since there is no data transmission. I think we also might have some limitation with payloads and expressions in general. This is also something that might be useful?

**Comment by pdelteil** [comment]
Hi there @xm1k3 ,

This is the template I was testing (doesn't work): 

```
id: check-ssl

info:
  name: Mismatched SSL Certificate
  author: pdteam
  severity: low
  tags: ssl

ssl:
  - address: "{{Host}}:{{Port}}"
    matchers:
      - type: dsl
        dsl:
          - "print_debug(issuer_org)"
          - "print_debug(test)"
        condition: and

```
In this case, there's no way of retrieving the variable value. 

Running ` nuclei -t ssl.yaml -u https://google.com -V test=OK`

```
[INF] Using Nuclei Engine 2.8.3 (latest)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] print_debug value: [[Google Trust Services LLC]]
[INF] No results found. Better luck next time!

```

The expected output is to include the value of the variable **test**. 

This one works:

```
id: test

info:
  name: test
  author: pdteam

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: dsl
        dsl:
          - 'print_debug(test)'
        condition: and
```
Running ` nuclei -t test.yaml -u https://google.com -V test=OK`

Output
```
[INF] Using Nuclei Engine 2.8.3 (latest)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] print_debug value: [OK]
[test] [http] [] https://google.com
```

**Comment by pdelteil** [comment]
> 

My u

> @xm1k3 I guess the template should be similar to this one:
> 
> ```yaml
> $ cat test.yaml
> id: mismatched-ssl
> 
> info:
>   name: Mismatched SSL Certificate
>   author: pdteam
>   severity: low
>   tags: ssl
> 
> ssl:
>   - address: "{{Host}}{{test}}:{{Port}}"
> 
>     matchers:
>       - type: dsl
>         dsl:
>           - "mismatched == true"
> $ go run . -t test.yaml -var test=.com -u hackerone -v
> ```
> 
> @pdelteil CLI/ENV variables support for SSL templates wasn't implemented since there is no data transmission. I think we also might have some limitation with payloads and expressions in general. This is also something that might be useful?

My use case is to use strings as input variable to check against values returned by the ssl request. Mismatch value returned is not enough.
