### ISSUE TITLE
Nuclei unable to handle 1 lakh requests at a time.

### ISSUE THREAD

**Issue by 0xdekster** [projectdiscovery/nuclei#2999]
Hi Team

I was using fuzzing templates to scan 1 lakh endpoints of a domain , but the process is getting killed automatically.
Attached the screenshot.
Please check

Using hetzner server - 4 cpu , 8gb ram, 20tb traffic

<img width="1047" alt="Screenshot 2022-12-08 at 10 15 07 AM" src="https://user-images.githubusercontent.com/1160576/206369864-a2841305-960b-4cac-a7f8-ee2357943225.png">

**Comment by tarunKoyalwar** [comment]
might be related to https://github.com/projectdiscovery/nuclei/issues/2999

**Comment by tarunKoyalwar** [comment]
@0xdekster can  you can run nuclei with `-profile-mem <profile.pprof> `flag and share the profile.pprof file . There might be a memory leak issue .

also can you try using nuclei with`-stream` and check if you facing same issue

**Comment by tarunKoyalwar** [comment]
lastly paste output of following command 

```sh
 /usr/bin/time -l nuclei -t /root/fuzzing-templates/ -list giphy-urls.txt -c 100 
```

**Comment by tarunKoyalwar** [comment]
@0xdekster  while scanning on scale increase/modify `-bs` and not `-c` . depending on your config `-bs 200 -c 10 `  should work .
