### ISSUE TITLE
[feature] Allow multiple dynamic values extraction

### ISSUE THREAD

**Issue by CasperGN** [projectdiscovery/nuclei#304]
**Is your feature request related to a problem? Please describe.**
As of now, the `dynamicvalue` as returned by the extractor is only allowed to be 1 extracted item. This works well on CSRF tokens, cookies and other but when dynamic endpoints is wanted based on the output of the page, this functionality is restrictive.

**Describe the solution you'd like**
Ideally the `dynamicvalue` could allow for more than one match of the regex. When inspecting `executer_http.go` lines 256-260:
```
	for _, extractor := range e.bulkHTTPRequest.Extractors {
		for match := range extractor.Extract(resp, body, headers) {
                        // here match can return several items from the extractor
			if _, ok := dynamicvalues[extractor.Name]; !ok {
				dynamicvalues[extractor.Name] = match // but this will always be a single, from which i think is because dynamicvalues is a non-iterable interface (e.g. map[string]interface{} vs. map[string]interface{})
			}
```
it may be because the map of `dynamicvalue` does not allow for more than one entry. 

Test:
```
compiled as:
	for _, extractor := range e.bulkHTTPRequest.Extractors {
		for match := range extractor.Extract(resp, body, headers) {
			fmt.Println(match, "<- outer")
			if _, ok := dynamicvalues[extractor.Name]; !ok {
				dynamicvalues[extractor.Name] = match
				fmt.Println(match, "-> inner")
			}
```
result from running:
```
[robots-txt-endpoints] [http] https://---.com/robots.txt
 /link <- outer
 /link -> inner
 /common/error <- outer
 /rc/ <- outer
 /cgi- <- outer
 /www <- outer
```
**Edit:**
This would also allow for using the same RAW request to conduct the dynamic requests i'd assume.

Thoughts?

Cheers!
/ Casper

**Comment by CasperGN** [comment]
#bb55f4a is awaiting the potential merge of PR #294. If it's rejected I'll have to attempt the fix from a new fork since my local master was polluted with the other PR (bad practice on my part, apologies).

/ Casper

**Comment by bauthard** [comment]
Support for multiple dynamic values extraction is added in the dev branch. Closing now!
