### ISSUE TITLE
Nuclei memory leak in stream mode

### ISSUE THREAD

**Issue by yaabdala** [projectdiscovery/nuclei#3043]
### Current Behavior:
Nuclei hangs or quits unexpectedly. Using the -hm flag I have a generated dump file which I have attached
[nuclei-stacktrace.dump.txt](https://github.com/projectdiscovery/nuclei/files/10230961/nuclei-stacktrace.dump.txt)

This seems to happen with specific hosts. I have a handful of dns names that I ran through dnsx and httpx before feeding into nuclei. 

### Expected Behavior:
I expect Nuclei to log errors when scanning a group of hosts. If one host fails or hangs, it should continue scanning the rest. Failing that, it should print which host failed with which template

### Steps To Reproduce:
go/bin/nuclei -l targets_ab.txt  -v -hm -stats -ni -stream

Unfortunately I cannot share the hosts scanned but I can answer that I am scanning 5 hosts, some of which are WAF protected in AWS. Only 1 returns 200 from httpx, the others have redirects for authentication

**Comment by Mzack9999** [comment]
@yaabdala could you confirm if you are able to complete the scan without the `-stream` flag?

**Comment by yaabdala** [comment]
Scan does not complete when the `-stream` flag is left off. It just fails slower

**Comment by vzamanillo** [comment]
I was able to reproduce this even using the dev branch, I think there is a memory leak somewhere (15GB avg before quit)

**Comment by tarunKoyalwar** [comment]
@vzamanillo @yaabdala can you run nuclei with below format and print the output . This will give us more details regarding the crash. 

```sh
/usr/bin/time -l -h nuclei -l targets_ab.txt -v -hm -stats -ni -stream
```

**Comment by vzamanillo** [comment]
I think the leak is located here

https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/core/inputs/hybrid/hmap.go#L250

**Comment by yaabdala** [comment]
I can't pass time the `-l -h` flags but I ran 

`/usr/bin/time go/bin/nuclei -l targets_ab.txt -v -hm -stats -ni -stream`

result

`538.29user 40.67system 2:50.15elapsed 340%CPU (0avgtext+0avgdata 46394588maxresident)k
0inputs+200outputs (0major+574574minor)pagefaults 0swaps`

I also concur with @vzamanillo that there seems to be a memory leak when using the `-stream` flag.

**Comment by tarunKoyalwar** [comment]
@yaabdala If it is memory leak pls share pprof file using option `-profile-mem pprof.out`

**Comment by vzamanillo** [comment]
@tarunKoyalwar it's a confirmed memory leak check my previous comment.

**Comment by yaabdala** [comment]
[pprof.out.txt](https://github.com/projectdiscovery/nuclei/files/10239939/pprof.out.txt)

Here is a copy of the memory dump for the run. Had to change the extension to .txt due to github upload restrictions

**Comment by yaabdala** [comment]
without the stream flag, I don't see a memory leak. Infant, memory utilization is very low. Any ideas why we are seeing the failures?

`[0:00:55] | Templates: 4473 | Hosts: 5 | RPS: 85 | Matched: 5 | Errors: 656 | Requests: 4696/30340 (15%)
[WRN] Could not make network request for <HOST>:465: could not connect to server request: no address found for host
[WRN] Could not make network request for <HOST>:21: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:25: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:23: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:8080: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:8009: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:23: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:3310: could not connect to server request: could not connect to any address found for host
[WRN] Could not make network request for <HOST>:139: could not connect to server request: could not connect to any address found for host
[0:01:00] | Templates: 4473 | Hosts: 5 | RPS: 78 | Matched: 5 | Errors: 665 | Requests: 4705/30340 (15%)
[0:01:05] | Templates: 4473 | Hosts: 5 | RPS: 72 | Matched: 5 | Errors: 665 | Requests: 4705/30340 (15%)
[0:01:10] | Templates: 4473 | Hosts: 5 | RPS: 67 | Matched: 5 | Errors: 665 | Requests: 4705/30340 (15%)
[0:01:15] | Templates: 4473 | Hosts: 5 | RPS: 62 | Matched: 5 | Errors: 665 | Requests: 4705/30340 (15%)
[0:01:20] | Templates: 4473 | Hosts: 5 | RPS: 58 | Matched: 5 | Errors: 665 | Requests: 4705/30340 (15%)
[0:01:25] | Templates: 4473 | Hosts: 5 | RPS: 55 | Matched: 5 | Errors: 665 | Requests: 4705/30340 (15%)
[WRN] Could not make network request for <HOST>:465: could not connect to server request: no address found for host
[0:01:28] | Templates: 4473 | Hosts: 5 | RPS: 53 | Matched: 5 | Errors: 666 | Requests: 4706/30340 (15%)
profile: memory profiling disabled, pprof.out
477.90user 40.82system 2:11.37elapsed 394%CPU (0avgtext+0avgdata 38185276maxresident)k
0inputs+496outputs (0major+724639minor)pagefaults 0swaps`

**Comment by vzamanillo** [comment]
Also, using the `filekv` default options allocates an excessive memory amount (2147483647) due to the boom filter initialization for dedupe.

https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/core/inputs/hybrid/hmap.go#L56
