### ISSUE TITLE
[issue] Unable to update all Nuclei templates

### ISSUE THREAD

**Issue by 0xgb** [projectdiscovery/nuclei#305]
**Describe the bug**
I'm unable to update all nuclei templates. When updating the Nuclei template, the workflow and vulnerabilities folder are returning empty.
Also, I'm getting the following error:
`[WRN] Could not update templates: Could not create uncompressed file: open /Users/<username>/nuclei-templates/vulnerabilities/bullwark-momentum-series-directory-traversal.yaml: too many open files`

**Operating system**

MacOS Catalina Version 10.15.6

**Nuclei version**
```
 nuclei --version

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 2.1.0
```

**Screenshot of the error or bug**

<img width="1096" alt="Screenshot 2020-09-15 at 11 21 00 AM" src="https://user-images.githubusercontent.com/13043764/93171291-715e5380-f746-11ea-9f78-e3bb28dc7968.png">

**Comment by bauthard** [comment]
@0xgb, looks like specific to the system? works fine here, do you get the same every time you run this flag or just once or twice? 

```
# nuclei -update-templates -v 

                       __     _ 
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ / 
   / / / / /_/ / /__/ /  __/ /  
  /_/ /_/\__,_/\___/_/\___/_/   v2.1									  

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[update-templates] Downloading nuclei-templates (v7.0.3) to /root/nuclei-templates
[INF] Successfully updated nuclei-templates (v7.0.3). Enjoy!
```

**Comment by CasperGN** [comment]
Hi @0xgb,
I noticed `too many open files` - could you try the following:
```
$ ulimit
$ cat /proc/sys/fs/file-nr
$ lsof | wc -l
```
And see if the reported from ulimit are close to or at any of the reported from cat/lsof.

/ Casper

**Comment by 0xgb** [comment]
Thanks @CasperGN 

This fixed my issue.

Also for Mac OS, the following blog was really helpful:
https://medium.com/mindful-technology/too-many-open-files-limit-ulimit-on-mac-os-x-add0f1bfddde
