### ISSUE TITLE
HTTP preflight improvements

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3064]
### Nuclei version:
'main|dev' 

### Current Behavior:
HTTP pre-flights aren't using httpx but a standard http client

### Expected Behavior:
If possible, implement the following improvements:
- [x] Perform pre-flight with the `HEAD` method
- [x] Use httpx in stream mode (support fallbacks and more edge cases for server-edge cases and recoverable errors)
- [x] Reuse pre-flight responses during clustering for matching templates requests

**Comment by ShubhamRasal** [comment]
https://github.com/projectdiscovery/nuclei/pull/3261
