### ISSUE TITLE
Do not support picker of regular expressions.

### ISSUE THREAD

**Issue by spac3wh1te** [projectdiscovery/nuclei#3074]
The system does not seem to support this kind of regular expressions.

?=、?<=、?!、?<! 

![image](https://user-images.githubusercontent.com/93125368/209088377-72de79e2-1e30-4893-8902-f5be66302fc2.png)

**Comment by forgedhallpass** [comment]
It is because the standard Golang library doesn't support positive/negative lookahead/lookbehinds, mostly because they want to guarantee the evaluation in O(n) time.

**Comment by spac3wh1te** [comment]
Thanks for answer!
