### ISSUE TITLE
Nuclei unable to detect/loading templates for panels Automatically . User needs to enter full path of that templet for panels

### ISSUE THREAD

**Issue by JanmejayaSwainOfficial** [projectdiscovery/nuclei#310]
**Describe the bug**
echo https://eng.uber.com | nuclei -t panels/ -v

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[DBG] Found template in nuclei-templates directory: /home/ec2-user/nuclei-templates/panels
[WRN] Error, no templates were found in '/home/ec2-user/nuclei-templates/panels'.
[INF] Loading templates...
[FTL] Error, no templates were found.
![Screenshot from 2020-09-17 01-44-07](https://user-images.githubusercontent.com/31533983/93387739-55160000-f887-11ea-8fd8-ef50667b52ef.png)

Nuclei unable to detect templates for panels . User needs to enter full path of that templet for panels
like 
echo https://eng.uber.com | nuclei -t panels/phpmyadmin-panel.yaml -v

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[DBG] Found template in nuclei-templates directory: /home/ec2-user/nuclei-templates/panels/phpmyadmin-panel.yaml
[INF] Loading templates...
**Nuclei version**
v2.1.1

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
![Screenshot from 2020-09-17 01-44-07](https://user-images.githubusercontent.com/31533983/93387804-67903980-f887-11ea-9dce-72aeae380d39.png)

**Comment by bauthard** [comment]
Update your templates, this should be fixed, this was not an issue but the feature we have added into the master code that follows `.nuclei-ignore` file to exclude templates on default run, more details will be added on next release.

**Comment by dohnjoeph** [comment]
I'm also experiencing this issue. I already updated the template using the `-update-templates` flag but same error. 
Any help @bauthard? Thanks!

**Comment by dohnjoeph** [comment]
Oh, I see it now! You updated the structure and the -t files/ is no longer available. You should update the README :)

**Comment by bauthard** [comment]
@dohnjoeph we have added the Information with template release https://github.com/projectdiscovery/nuclei-templates/releases/tag/v8.0.0
