### ISSUE TITLE
Template Clustering support for DNS protocol

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei#3128]
### Please describe your feature request:

I'm scanning for these 2 templates. They make the same request so they should be regrouped but actually nuclei makes 2 requests.

* azure-takeover-detection.yaml
* elasticbeantalk-takeover.yaml

Similar to HTTP request clustering, same can be done for DNS requests as well, and this can behavior can be disabled using the existing option `-dc, -disable-clustering` 

### Describe the use case of this feature:
Reduce request

**Comment by ehsandeep** [comment]
@akincibor updated the existing issue for the same - https://github.com/projectdiscovery/nuclei/issues/2439
