### ISSUE TITLE
Option to disable skipping host from scan list based on error count

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3138]
### Please describe your feature request:

New option to disable the default `-mhe` feature.

```console
   -nmhe, -no-mhe  disable skipping host from scan based on errors
```
### Describe the use case of this feature:
 https://github.com/projectdiscovery/nuclei/discussions/3132#discussioncomment-4580089

**Comment by catchmeifyoucaan** [comment]
this option is not available yet, do we have to wait till next update ? because even thousands of domain that went through httpx, that work in previous nuclei are all not responding now.

nuclei -l priv -s critical -no-mhe
flag provided but not defined: -no-mhe
