### ISSUE TITLE
Add Status Code, length  & Title flags

### ISSUE THREAD

**Issue by attacker007** [projectdiscovery/nuclei#314]
**Is your feature request related to a problem? Please describe.**

Sometimes there are lot of incorrect results and as we are not able to see status-code ,length & Title we have to manually check (its good for few results but not good for thousands of results).
 

**Describe the solution you'd like**

Please add status code, length and title flag as you've added for httpx.

**Comment by bauthard** [comment]
Hey, thank you for the suggestion, but this is not the use case or purpose of nuclei. 

> Sometimes there are lot of incorrect results. 

In that case, you need to check/fix/update the template producing invalid results, adding more checks to results is not going to solve this issue.

**Comment by attacker007** [comment]
Hi @bauthard if not the "Status Length" or "Title" ..I think "Status Code" should at least be returned in results.

**Comment by bauthard** [comment]
Hey @attacker007, 

With this https://github.com/projectdiscovery/nuclei/issues/212, you can pipe the results into httpx and see the desired data in future.
