### ISSUE TITLE
Add support for interactsh-url placeholders to SNI request annotations

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3152]
### Please describe your feature request:
Request annotations for SNI should support interactsh placeholders:

```yaml
- |
        @tls-sni:interactsh-url
        GET / HTTP/1.1
        Host: test
```

### Anything else?
- https://www.invicti.com/blog/web-security/ssrf-vulnerabilities-caused-by-sni-proxy-misconfigurations/

**Comment by brenocss** [comment]
would be better if annotations handle all dsl
`{{extractors}}`, `{{interactsh-url}}`...
