### ISSUE TITLE
[feature] Flag to stop/exit on first match

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#318]
Sometimes I create templates that make a lot of requests to a host/s. I would want, if possible, that nuclei stops making requests to a host if at least one of them matches.

Let say we make a template that does 50 requests with different paths and checks for "root" in response. If nuclei gets a valid hit in request 3, it stops and continues with another host or ends there.

The flag could be something like -fm like "firstMatch" or something like that? This would be really cool.

**Comment by bauthard** [comment]
@marcelo321 this has been added into master code, `-stop-at-first-match`. 

⚠️ - Make sure to use this with a specific template, using with all template will break workflow or chained templates.
