### ISSUE TITLE
Analyze/reorder structs fields to improve memory alignment

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3181]
### Please describe your feature request:
Structs fields should be analyzed and reordered if necessary to minimize memory occupation and improve performances

```
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
fieldalignment <package_path>
```

Additionally, this should also be added among GH tests to ensure structs order is optimized

**Comment by vzamanillo** [comment]
The golangci `govet` linter has an analyzer to check this: `fieldalignment`

https://golangci-lint.run/usage/linters/#govet

**Comment by Mzack9999** [comment]
Not planned - This will be reworked as part of common GH standard actions.
