### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by noob0x01** [projectdiscovery/nuclei#319]
![nuclei](https://user-images.githubusercontent.com/51519007/93972903-19060200-fd95-11ea-8993-b0fe05d056bf.PNG)

Installation Issue : OS: WINDOWS 10; GO version : go1.15.2 windows/amd64

**Comment by bauthard** [comment]
@noob0x01 You can download the windows binary from here https://github.com/projectdiscovery/nuclei/releases

**Comment by Cloufish** [comment]
I do have the same Installation issues, how-to-install section refers to /nuklei/v2/cmd directory which does not exist in the repo. To what directory should I change the path?

**Comment by bauthard** [comment]
This is fixed, the same command should work now.
