### ISSUE TITLE
signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb8059a]

### ISSUE THREAD

**Issue by wesamlibya** [projectdiscovery/nuclei#3194]
welcome
I have this problem and I need a solution please

![image](https://user-images.githubusercontent.com/8293321/212673935-90b23886-d6f6-4985-8fbd-c520b2ca5fff.png)

**Comment by ehsandeep** [comment]
@wesamlibya 1) can you update you nuclei to latest version? i.e v2.8.7 

```
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
```

and what's inside `js.txt`? is it file input?

**Comment by ehsandeep** [comment]
@wesamlibya `go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@dev` should fix this.
