### ISSUE TITLE
Nuclei stucks on windows for some reason

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei#3212]
### Current Behavior:
When i run nuclei in windows  with --silent i'm getting few checks then its just stucks, if i remove --silent im not getting any results

`cat domain.txt | ./nuclei.exe -rl 10000 -c 700 -t temps/ -o domain.txt
`
outputs 
```
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.7

                projectdiscovery.io

[INF] Using Nuclei Engine 2.8.7 (latest)
[INF] Using Nuclei Templates 9.3.4 (latest)
[INF] Templates added in last update: 15
[INF] Templates loaded for scan: 4778
[INF] No results found. Better luck next time!

```

and if i do add --silent its works a bit and then stuck with no progress, if there is a way to debug this please let me know.
### Expected Behavior:
To finish scanning of every template

### Steps To Reproduce:
1. Add example.com to domain.txt
2. Open Git Bash
3. Run `cat domain.txt | ./nuclei.exe -rl 10000 -c 700 -t temps/ -o domain.txt`

**Comment by tarunKoyalwar** [comment]
@mastercho  ,  stuck is a vague term to use . you should use `-stats` option if you want to view progress of scan 
```console
$ nuclei -u https://scanme.sh -c 200 -stats

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.7

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.7 (latest)
[INF] Using Nuclei Templates 9.3.4 (latest)
[INF] Templates added in last update: 15
[INF] Templates loaded for scan: 4781
[INF] Targets loaded for scan: 1
[INF] Templates clustered: 905 (Reduced 835 HTTP Requests)
[INF] Using Interactsh Server: oast.live
[http-missing-security-headers:permissions-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:x-frame-options] [http] [info] https://scanme.sh
[http-missing-security-headers:x-permitted-cross-domain-policies] [http] [info] https://scanme.sh
[http-missing-security-headers:referrer-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:strict-transport-security] [http] [info] https://scanme.sh
[http-missing-security-headers:clear-site-data] [http] [info] https://scanme.sh
[http-missing-security-headers:cross-origin-opener-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:cross-origin-resource-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:access-control-expose-headers] [http] [info] https://scanme.sh
[http-missing-security-headers:access-control-max-age] [http] [info] https://scanme.sh
[http-missing-security-headers:access-control-allow-methods] [http] [info] https://scanme.sh
[http-missing-security-headers:access-control-allow-headers] [http] [info] https://scanme.sh
[http-missing-security-headers:content-security-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:x-content-type-options] [http] [info] https://scanme.sh
[http-missing-security-headers:cross-origin-embedder-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:access-control-allow-origin] [http] [info] https://scanme.sh
[http-missing-security-headers:access-control-allow-credentials] [http] [info] https://scanme.sh
[self-signed-ssl] [ssl] [low] scanme.sh
[nameserver-fingerprint] [dns] [info] scanme.sh [ns69.domaincontrol.com.,ns70.domaincontrol.com.]
[0:00:05] | Templates: 4781 | Hosts: 1 | RPS: 171 | Matched: 19 | Errors: 16 | Requests: 860/6621 (12%)
[robots-txt-endpoint] [http] [info] https://scanme.sh/robots.txt
[0:00:10] | Templates: 4781 | Hosts: 1 | RPS: 155 | Matched: 20 | Errors: 23 | Requests: 1559/6621 (23%)
[ssl-issuer] [ssl] [info] scanme.sh [pd]
^C[INF] CTRL+C pressed: Exiting

```

**Comment by mastercho** [comment]
> @mastercho , stuck is a vague term to use . you should use `-stats` option if you want to view progress of scan
> 
> ```
> $ nuclei -u https://scanme.sh -c 200 -stats
> 
>                      __     _
>    ____  __  _______/ /__  (_)
>   / __ \/ / / / ___/ / _ \/ /
>  / / / / /_/ / /__/ /  __/ /
> /_/ /_/\__,_/\___/_/\___/_/   v2.8.7
> 
> 		projectdiscovery.io
> 
> [INF] Using Nuclei Engine 2.8.7 (latest)
> [INF] Using Nuclei Templates 9.3.4 (latest)
> [INF] Templates added in last update: 15
> [INF] Templates loaded for scan: 4781
> [INF] Targets loaded for scan: 1
> [INF] Templates clustered: 905 (Reduced 835 HTTP Requests)
> [INF] Using Interactsh Server: oast.live
> [http-missing-security-headers:permissions-policy] [http] [info] https://scanme.sh
> [http-missing-security-headers:x-frame-options] [http] [info] https://scanme.sh
> [http-missing-security-headers:x-permitted-cross-domain-policies] [http] [info] https://scanme.sh
> [http-missing-security-headers:referrer-policy] [http] [info] https://scanme.sh
> [http-missing-security-headers:strict-transport-security] [http] [info] https://scanme.sh
> [http-missing-security-headers:clear-site-data] [http] [info] https://scanme.sh
> [http-missing-security-headers:cross-origin-opener-policy] [http] [info] https://scanme.sh
> [http-missing-security-headers:cross-origin-resource-policy] [http] [info] https://scanme.sh
> [http-missing-security-headers:access-control-expose-headers] [http] [info] https://scanme.sh
> [http-missing-security-headers:access-control-max-age] [http] [info] https://scanme.sh
> [http-missing-security-headers:access-control-allow-methods] [http] [info] https://scanme.sh
> [http-missing-security-headers:access-control-allow-headers] [http] [info] https://scanme.sh
> [http-missing-security-headers:content-security-policy] [http] [info] https://scanme.sh
> [http-missing-security-headers:x-content-type-options] [http] [info] https://scanme.sh
> [http-missing-security-headers:cross-origin-embedder-policy] [http] [info] https://scanme.sh
> [http-missing-security-headers:access-control-allow-origin] [http] [info] https://scanme.sh
> [http-missing-security-headers:access-control-allow-credentials] [http] [info] https://scanme.sh
> [self-signed-ssl] [ssl] [low] scanme.sh
> [nameserver-fingerprint] [dns] [info] scanme.sh [ns69.domaincontrol.com.,ns70.domaincontrol.com.]
> [0:00:05] | Templates: 4781 | Hosts: 1 | RPS: 171 | Matched: 19 | Errors: 16 | Requests: 860/6621 (12%)
> [robots-txt-endpoint] [http] [info] https://scanme.sh/robots.txt
> [0:00:10] | Templates: 4781 | Hosts: 1 | RPS: 155 | Matched: 20 | Errors: 23 | Requests: 1559/6621 (23%)
> [ssl-issuer] [ssl] [info] scanme.sh [pd]
> ^C[INF] CTRL+C pressed: Exiting
> ```

Already tried `-stats` before post issue here, but when i use stats doesn't find a single thing even its completes 100% with -stats doesn't find even info tags such as `http-missing-security-headers`. Without stats would find results but it's just stucks for days ( i waited 3 days and never finished) meanwhile on -stats its finishes in 5 hours

**Comment by tarunKoyalwar** [comment]
@mastercho ,`-stats` only shows stats of nuclei and does not have any impact/relation with scanning or even templates. If you are not getting results it might be related to your own network or the target you are scanning you can use
```console
   -elog, -error-log string  file to write sent requests error log
```
to save all errors to file and look for actual issue

**Comment by mastercho** [comment]
> ```
> elog
> ```

thanks this gives me point of view where might be the issue, on every template im getting

`"error":"context deadline exceeded","type":"http"`

Which i assume is timeout, and this is bit weird as i tried to check site uptime while nuclei works and its never timeouts but for some reason nuclei can't reach the website

**Comment by tarunKoyalwar** [comment]
@mastercho , as you were saying `context deadline exceeded` is caused when that specific operation (ex: making a http request) exceeds allotted time . In nuclei we implement a timeout to increase speed and performance . 

For this situation . I think the target is slow (high latency) . nuclei provides below options to configure timeouts
```console
   -timeout int                        time to wait in seconds before timeout (default 10)
   -irt, -input-read-timeout duration  timeout on input read (default 3m0s)
   -page-timeout int            seconds to wait for each page in headless mode (default 20)
``` 

the current default timeout is `10` you should try increasing it to `-timeout 30` or other if you still face timeout exceeded issues .
