### ISSUE TITLE
SARIF output's ruleIndex should not be -1

### ISSUE THREAD

**Issue by tperich** [projectdiscovery/nuclei#3221]
Hello,

I've come across an issue with Jenkins parsing nuclei's SARIF output. The parser throws an `IndexOutOfBoundsException` when it tries to parse the `ruleIndex` property which, at the time, has a value of `-1`.

The [SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127835) states that if `ruleIndex` isn't an array index, it shouldn't be there at all.

> ...a result object MAY contain a property named ruleIndex whose value is the array index (§3.7.4) of theDescriptor within theComponent.ruleDescriptors (§3.19.23). Otherwise, ruleIndex SHALL be absent.

The issue likely occurs around this line: https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/reporting/exporters/sarif/sarif.go#L128

```plaintext
128	ruleIndex := len(exporter.rules) - 1
```

### Nuclei version:
2.8.7 (specifically, docker image `projectdiscovery/nuclei:latest`)

### Current Behavior:
`ruleIndex` in SARIF output can be `-1`.

### Expected Behavior:
`ruleIndex` in SARIF output should not be `-1`.

### Steps To Reproduce:
1. Run `docker run --rm -v $(pwd):/app projectdiscovery/nuclei -target example.com -se /app/nuclei.sarif`
2. Verify that you see `"ruleIndex": -1,` within the SARIF output
3. Optionally, try parsing in Jenkins

Problematic SARIF example: https://gist.github.com/tperich/dbcb72ce33884aa0e1599913a495cc76

**Comment by ehsandeep** [comment]
@tperich this is now fixed in latest release of nuclei - https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.5
