### ISSUE TITLE
vote.yaml and html_editor.yaml is missing

### ISSUE THREAD

**Issue by ilqar200** [projectdiscovery/nuclei#3227]
### Nuclei version:
2.8.7

### Current Behavior:
 I want to test some sites that is created with bitrix. I found that nuclei is missing vote.yaml and html_editor.yaml  . Also i am getting error : Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory

### Expected Behavior:
 Testing some sites for bitrix bug with nuclei.

### Steps To Reproduce:

nuclei -u https://testsite.com -templates ./nuclei/vote.yaml
[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v9.3.5) to /root/.local/nuclei-templates. GoodLuck!
[ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory
[ERR] Could not find template './nuclei/vote.yaml': could not find template file: no such path found: ./nuclei/vote.yaml
[INF] Using Nuclei Engine 2.8.7 (latest)
[INF] Using Nuclei Templates 9.3.5 (latest)
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no valid templates were found

nuclei -u https://testsite.com -templates ./nuclei/html_editor.yaml
[ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory
[ERR] Could not find template './nuclei/html_editor.yaml': could not find template file: no such path found: ./nuclei/html_editor.yaml
[INF] Using Nuclei Engine 2.8.7 (latest)
[INF] Using Nuclei Templates 9.3.5 (latest)
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no valid templates were found

**Comment by ehsandeep** [comment]
None of these templates are part of [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates) project, you are probably using a template created by someone from the community from GitHub.
