### ISSUE TITLE
Incorrect {{BaseURL}} parsing on AWS serverless environment

### ISSUE THREAD

**Issue by Jay3shh** [projectdiscovery/nuclei#3228]
### Nuclei version:
Current Version: 2.8.7

### Current Behavior:
This seems to be working fine on my local Linux and VPS based Ubuntu environment. However, It looks like there's some compatibility Issues with certain environments as I've been facing an Issue with my nuclei deployment on an AWS serverless environment. 

The Issue specifically seems to be that the {{BaseURL}} is not being parsed correctly as It is ignoring any parameters passed with the URI and and It is appending additional text after the host Instead of appending it after the parameter passed in the URI. As a result, the request results in the following error:

`
[WRN] [ScanMySQLiErrorBased] Could not execute request for http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net?hello=: GET http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net')?hello= giving up after 2 attempts: Get "http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net')?hello=": no address found for host
    [INF] No results found. Better luck next time!
`

Below is the YAML template for reference:
https://raw.githubusercontent.com/Jay3shh/custom-templates/main/ScanMySQLiErrorBased.yaml

Below are the logs produced with debug:

`
    [INF] [ScanMySQLiErrorBased] Dumped HTTP request for http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net')?hello=

    GET /?hello= HTTP/1.1
    Host: 77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net')
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
    Connection: close
    Accept: */*
    Accept-Language: en
    Accept-Encoding: gzip

    [WRN] [ScanMySQLiErrorBased] Could not execute request for http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net?hello=: GET http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net')?hello= giving up after 2 attempts: Get "http://77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net')?hello=": no address found for host
`

### Expected Behavior:
As per the debug logs - You should be able to see that the payload `')` was appended after `77czc126ubt50fr3awpxcdzv6mcc01.burpcollaborator.net` Whereas, It should have been appended after `?hello=` 

### Steps To Reproduce:
nuclei -u http://i9sam3i2qo74yy5gmg99fzu0krqje8.burpcollaborator.net?hello= -t custom-templates/ScanMySQLiErrorBased.yaml --debug

**Comment by Jay3shh** [comment]
Hi, I've had another look at this and It seems that this error specifically occurs on the latest release 2.8.7 even on my local Linux / Ubuntu VPS. It works perfectly on 2.8.3 as per my test. Perhaps It could be a wide-scale Issue affecting all users on the latest release?

**Comment by ehsandeep** [comment]
> Hi, I've had another look at this and It seems that this error specifically occurs on the latest release 2.8.7 even on my local Linux / Ubuntu VPS. It works perfectly on 2.8.3 as per my test. Perhaps It could be a wide-scale Issue affecting all users on the latest release?

Yes, it is a known issue affecting the last release of nuclei, there is fix for it - https://github.com/projectdiscovery/nuclei/pull/3211

Closing as this is being tracked at https://github.com/projectdiscovery/nuclei/issues/3167
