### ISSUE TITLE
very slow for vulnerable scan

### ISSUE THREAD

**Issue by ranktopgg** [projectdiscovery/nuclei#3260]
i try scan a list with only 100 url,, but it take like 2 hour to finish? i am doing something wrong or ?

nuclei -l list.txt -output result.txt

**Comment by tarunKoyalwar** [comment]
@ranktopgg  , you should checkout https://nuclei.projectdiscovery.io/nuclei/get-started/#mass-scanning-using-nuclei about parameter tuning . default concurrency parameters are not optimized for mass scanning >= 100 .

also I recommend using `-stats` flag that shows scan progress and most important (RPS: Requests per second)

**Comment by vzamanillo** [comment]
Scan Strategy, Concurrency & Bulk-Size or Stream use should be detected based on the targets length and report it, I could say, no one reads the docs before running nuclei.

The tool should be smart enough to run optimally with zero configuration (or parameters), it's great that it's flexible and allows it to be adjusted to the needs of each user, but non-advanced users can't be penalized for not knowing how nuclei works internally.

**Comment by tarunKoyalwar** [comment]
@vzamanillo  ,yeah  that's true and we do have open issues for that 

- https://github.com/projectdiscovery/nuclei/issues/3076
- https://github.com/projectdiscovery/nuclei/issues/3072

but it can fine tune only to a certain extent . Ex: it is not possible to guess ratelimit of target or even adapt it without being blacklisted .
