### ISSUE TITLE
Use nuclei as a library like other projectdiscovery project

### ISSUE THREAD

**Issue by nbxiglk0** [projectdiscovery/nuclei#3264]
Hi,
I found that the nuclei runner module is in an internal package, which makes it impossible to reference nuclei as a library in third party code like other projectdiscovery projects. Just need to configure a runner to do the scanning? After all, if the internal package is copied manually into the third-party code, it is not conducive to modification and subsequent updates, and makes development more difficult.  

![image](https://user-images.githubusercontent.com/24366795/216295027-7a12af11-759b-47d1-948a-c392f2683095.png)

**Comment by ehsandeep** [comment]
@nbxiglk0 here is the code - https://github.com/projectdiscovery/nuclei#using-nuclei-from-go-code, let me know if you find any difficulties in the shared example.

**Comment by nbxiglk0** [comment]
This was helpful, thanks
