### ISSUE TITLE
Raw Request in nuclei doesn't support Big Request

### ISSUE THREAD

**Issue by adik69** [projectdiscovery/nuclei#328]
**Describe the bug**
I made nuclei template using nuclei documentation for sending raw request . So I added a large list of headers in the request
So I made a request to my collaborator to just see all headers are passing in it. I didn't get any callback.

echo "https://my.burpcollaborator.net" |nuclei -t rawrequest.yaml
[rawrequest.txt](https://github.com/projectdiscovery/nuclei/files/5287230/rawrequest.txt)

**Comment by bauthard** [comment]
Hey @adik69, 

Please make sure to review your template before running them, you have added `Host: https://www.example.com` as a header payload, that gets used as `host` header instead of your input host (burp), remove the above header from your payload list and it will work as expected.
