### ISSUE TITLE
pdtm integration for self-update / version check option

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3285]
### Please describe your feature request:
Update `v2/pkg/protocols/common/updatecheck/client.go` with [pdtm](https://github.com/projectdiscovery/pdtm) API

### Describe the use case of this feature:
Uniform API for update / version check feature

**Comment by ShubhamRasal** [comment]
#3428

**Comment by ehsandeep** [comment]
Closing as duplicate of https://github.com/projectdiscovery/team-backlogs/issues/249
