### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by sircat88** [projectdiscovery/nuclei#3297]
i think i have came across this issue before but not sure if it has to do with the go version am running when running nuclei i got this error twice "fatal error: concurrent map writes".
environment:  Linux kali 5.18.0-kali7-amd64

I am running the latest nuclei engine:
[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)

go version:
go version go1.19.2 linux/amd64

should i update my go version or is there something else here please let me.

**Comment by tarunKoyalwar** [comment]
@sircat88 , closing this since issue is already resolved and available in `dev` branch .  more details at https://github.com/projectdiscovery/nuclei/issues/3253
