### ISSUE TITLE
Condition bug on file protocol

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei#3327]
![image](https://user-images.githubusercontent.com/36522826/218766480-69d20623-782b-43eb-8c9a-3dd62daa00a5.png)

When i use file protocol and using word matcher with condition and, the nuclei said no result

**Comment by daffainfo** [comment]
![image](https://user-images.githubusercontent.com/36522826/218767028-12a49a03-3f66-4c20-a3a3-19956079c1f8.png)
If the condition was removed, nuclei will print the output

**Comment by ShubhamRasal** [comment]
Hey @daffainfo , Thanks for raising a issue, 
By default we read file in chunks (line by line). But in case of `and` condition we have to read file in buffer. 
To do so, you need to also pass `matchers-condition: and` before matchers. 
```
id: matcher-with-and

info:
  name: File Matcher With AND
  author: pdteam
  severity: info
  tags: file

file:
  - extensions:
      - all
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "CCC"
          - "DDD"
        condition: and
```

**Comment by daffainfo** [comment]
@ShubhamRasal I apologize for the confusion. I don't understand why `matchers-condition: and` is used when there is only one matcher. In an HTTP request template, you dont need to use `matchers-condition` if there is only one matcher, but you need to use it in a file template.
