### ISSUE TITLE
Problems related to TestDownloadCustomTemplatesFromGitHub test

### ISSUE THREAD

**Issue by xm1k3** [projectdiscovery/nuclei#3345]
### Nuclei version:

2.8.9

### Current Behavior:

branch: `dev`

```
--- FAIL: TestDownloadCustomTemplatesFromGitHub (10.01s)
    github_test.go:31: 
        	Error Trace:	/home/runner/work/nuclei/nuclei/v2/pkg/external/customtemplates/github_test.go:31
        	Error:      	unable to find file "/tmp/template-custom-935556463/github/nuclei-templates-ehsandeep"
        	Test:       	TestDownloadCustomTemplatesFromGitHub
        	Messages:   	cloned directory does not exists
```

### Expected Behavior:

Success test

### Steps To Reproduce:

```
go test ./...
```

### Anything else:

more info also here: https://github.com/projectdiscovery/nuclei/actions/runs/4223199715/jobs/7332787046

**Comment by tarunKoyalwar** [comment]
@xm1k3 , closing this since this was fixed . above unit tests downloads template from `ehsandeep/nuclei-templates` which was accidently deleted and it is now restored

**Comment by xm1k3** [comment]
@tarunKoyalwar I figured that was the problem as it returned 404, I had spoken to @Mzack9999 if for future purposes we could make it more dynamic, maybe a repo under pd org, but if it is restored it's ok

**Comment by ehsandeep** [comment]
This test started to fail again on windows even https://github.com/ehsandeep/nuclei-templates does exist.

```console
--- FAIL: TestDownloadCustomTemplatesFromGitHub (42.52s)
    github_test.go:34: 
        	Error Trace:	D:/a/nuclei/nuclei/v2/pkg/external/customtemplates/github_test.go:34
        	Error:      	unable to find file "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\template-custom-13578[49](https://github.com/projectdiscovery/nuclei/actions/runs/5504540247/jobs/10030852874?pr=3916#step:6:50)[51](https://github.com/projectdiscovery/nuclei/actions/runs/5504540247/jobs/10030852874?pr=3916#step:6:52)2\\github\\nuclei-templates-ehsandeep"
        	Test:       	TestDownloadCustomTemplatesFromGitHub
        	Messages:   	cloned directory does not exists
```

**Comment by Mzack9999** [comment]
@ehsandeep, please delete and recreate your `nuclei-templates` fork. There is an extra space in one of the templates paths which are not compatible with Windows, causing the test to fail:
![image](https://github.com/projectdiscovery/nuclei/assets/13421144/87ea5390-64ad-4c41-a6d9-10b3497d941f)
