### ISSUE TITLE
The "-max-host-error" Flag Not Functioning As Expected

### ISSUE THREAD

**Issue by ErikOwen** [projectdiscovery/nuclei#3353]
### Current Behavior:

My project's automation tweaks DNS resolution before invoking Nuclei, so the automation can target a single IP address with a corresponding DNS record. I've noticed that the `-max-host-error` flag isn't respected when there are errors (possibly?) related to DNS resolution. I am setting the `-max-host-error` flag to 1, and I will see more than 1 errors using the `-stats` flag. This is causing issues in my project's automation, because it causes the scan duration to be much longer compared to using the previous nuclei version v2.7.4, because scans aren't being skipped when they should be.

### Expected Behavior:
When the `-max-host-error` flag is set, it is respected, and the scan is skipped when more errors occur than specified by the`-max-host-error` flag.

### Steps To Reproduce:
1. Tweak your DNS resolution so a DNS record resolves to a different IP address:
 ```
 sudo sh -c "echo '34.35.36.36 projectdiscovery.io' >> /etc/hosts"
 ```
2. Run the following nuclei command:
 ```
 nuclei --target https://projectdiscovery.io -rl 15 -tags tech -mhe 1 -stats -v
 ```
3. Notice that the `-mhe` flag was set to 1, but the error count greatly surpasses 1 in the stats output?
 ```
 [0:00:15] | Templates: 585 | Hosts: 1 | RPS: 1 | Matched: 0 | Errors: 25 | Requests: 25/616 (4%)
 ```
### Anything else:
The `-v` flag in the command above shows a lot of errors that say `context deadline exceeded`:
```
[WRN] [wordpress-redux-framework] Could not execute request for https://projectdiscovery.io: context deadline exceeded
```
Perhaps this is related?

**Comment by tarunKoyalwar** [comment]
@ErikOwen , `-mhe` only tracks certain errors https://github.com/projectdiscovery/nuclei/blob/1467815ca333d47fc3a6b50c62b6f57524bd7e47/v2/pkg/protocols/common/hosterrorscache/hosterrorscache.go#L125-L127

In your case `context deadline exceeded` is caused because of timeout in nuclei (slow response from server) . we skipped this intentionally cause this error depends on concurrency and other factors and highly unstable and would generate more false positivies

**Comment by ErikOwen** [comment]
@tarunKoyalwar - thank you for the reply! Is it possible to add a flag (that is disabled by default) to count timeout errors as part of `-mhe`? Or do you know of another solution to prevent timeout errors like this from drastically increasing the scan duration of Nuclei scans? This bug is causing certain hosts to be scanned 5-10X slower compared to previous versions of Nuclei, which is slowing down my project's automation. Ideally there could be a way to skip a scan if there are a lot of failures like this. Thanks!

**Comment by austintraver** [comment]
@tarunKoyalwar what changes would I need to make to implement @ErikOwen's suggestion? As a starting point, I have created draft PR https://github.com/projectdiscovery/nuclei/pull/3399

**Comment by tarunKoyalwar** [comment]
thanks for the PR @austintraver , This looks fine but I think we can just add a flag that takes error[s] as value and tracks them along with predefined list . This way we can make it more generic without affecting the normal functionality

- [ ] Add New Flag of type `StringSliceVarP` below mhe flag. (refer `proxy` flag for implementation)
```
  -mhe, -max-host-error int           max errors for a host before skipping from scan (default 30)
  -te, -track-error string            track given error as part of max host error feature
  -nmhe, -no-mhe                      disable skipping host from scan based on errors
```
- [ ]  if value of `-te` flag is not empty we can add given strings to above regex (tip use `\Q%v\E` so we don't have to escape anything)

**Comment by austintraver** [comment]
PR https://github.com/projectdiscovery/nuclei/pull/3399 is now ready for review 👍🏻

**Comment by ehsandeep** [comment]
@ErikOwen arbitrary error input is now supported in dev branch with https://github.com/projectdiscovery/nuclei/pull/3399#issuecomment-1466905064, new release of nuclei will be pushed soon.

**Comment by aviadavi** [comment]
it looks like "context deadline exceeded" error is either way not counted as an error. (even with using `-track-error` option)
