### ISSUE TITLE
Add example section to bottom of help output

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/nuclei#3359]
### Please describe your feature request:
The `-h` output is very verbose, which makes it both useful and a lot to take in. An example of another CLI with a lot of configuration is the vercel CLI, and they provide some examples at the bottom of their help output. This is clearly broken into: beginner, power user, and expert levels to cater to various users. I believe we could achieve the same thing.

<img width="965" alt="CleanShot 2023-02-24 at 13 26 34@2x" src="https://user-images.githubusercontent.com/6044920/221260158-01293a3b-f7d8-4861-8f78-0d20c6177d9a.png">

For example, what if at the bottom of `-h` we saw

```
Examples:

   Run the default community templates against one host

   $ nuclei -u example.com

   Run custom templates against a list of hosts 

   $ nuclei -l targets.txt -t ./custom-templates

   Run templates tagged with CVE against an uncover query, a custom resolver, and report findings to an external system

   $ nuclei -t cves -uc -uq 'html:"Foo Bar"' -rdb prod -rc ./jira-out.yaml -r 172.0.0.53

   Get help with a specific set of flags - say Nuclei Cloud

   $ nuclei -h cloud
```

### Describe the use case of this feature:
This will help both new users and current users unaware of some features of the CLI to better access how to use Nuclei.

**Comment by kchason** [comment]
I can take this one

**Comment by kchason** [comment]
This will require: https://github.com/projectdiscovery/goflags/pull/124 to be merged and released before this can be efficiently done

**Comment by kchason** [comment]
This has been completed in https://github.com/projectdiscovery/nuclei/pull/3978
