### ISSUE TITLE
add an option that can send all request with headless browser

### ISSUE THREAD

**Issue by breaking153** [projectdiscovery/nuclei#3383]
sometimes WAF add a js script and add a cookie or header,to recognize whether the request is sent by browser or scanner,so i think why couldn't we giving an option that whether to use headless browser to send all templates request.

**Comment by tarunKoyalwar** [comment]
@breaking153 . you can also add your custom tamper logic in proxify to evade WAF and just proxy all nuclei traffic through [proxify](https://github.com/projectdiscovery/proxify)

**Comment by breaking153** [comment]
> @breaking153 . you can also add your custom tamper logic in proxify to evade WAF and just proxy all nuclei traffic through [proxify](https://github.com/projectdiscovery/proxify)

thanks for reply but if i use single proxify to modify request by single rules, i should update the logic every time. so i think it's nessesary to make all request sent through go-rod headless explorer. i will try by myself.
