### ISSUE TITLE
Update Nuclei 

### ISSUE THREAD

**Issue by kolor33** [projectdiscovery/nuclei#3388]
Hi team I would like ask .You are stop update Nuclei.Thru 2 weeks I do not see any update.You stop support this project.??? What is going on.??

**Comment by ehsandeep** [comment]
@kolor33 releases are pushed only when their are significant changes pushed and gone through some testing, if you are looking to use updated code on daily basis, feel free to build nuclei from `dev` branch or install it using

```
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@dev
```
