### ISSUE TITLE
JARM and ja3 output don't exist in Nuclei Engine 

### ISSUE THREAD

**Issue by pussycat0x** [projectdiscovery/nuclei#3403]
### Please describe your feature request:

TLSX has  jarm and ja3 output support, but Nuclei engine doesn't have.
```
"jarm_hash": ""
"ja3_hash": ""
```

```echo "google.com" | tlsx -ja3 -jarm```
  

```
  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.5

		projectdiscovery.io

google.com:443 [27d40d40d29d40d1dc42d43d00041d4689ee210389f4f6b4b5b1b93f92252d] [a4f7219fbfd4687a8a1bc1e648517be2]
```

Proposed implementation in ssl templates:
```
- address: "{{Host}}:{{Port}}"
    probes:
      - ja3
      - jarm
```

**Comment by Mzack9999** [comment]
Notes:
- `ja3` doesn't seem to be very helpful as it's related to the client
- `ja3s` requires lots of probes. Hence it might be implemented as a helper function like `ja3s()` to minimize the execution time, and the result stored in some internal kv cache to avoid recalculating it multiple times

**Comment by Mzack9999** [comment]
Indirectly completed via https://github.com/projectdiscovery/nuclei/pull/3906
