### ISSUE TITLE
no-stdin flag doesnot work if used together with stat flag

### ISSUE THREAD

**Issue by AyushXtha** [projectdiscovery/nuclei#3404]
no-stdin flag doesnot work if used together with stat flag

### Nuclei version:
latest version 2.8.9
### Current Behavior:
When no-stdin flag is used together with stat, nuclei doesnot behave as intended. For example: 
```
cat test | while read line;do nuclei -u $line -t ~/Desktop/param-fuzzer.yaml -no-stdin -stats; echo 'runn other stuff';done
```
when the above code is run, only the first line of test is executed and the program terminates. ``` echo 'runn other stuff';``` gets triggered only once.
### Expected Behavior:
In the above example nuclei should run as many times as the lines in the test.

### Steps To Reproduce:

1. make a test file with more than one line of urls
2. run below code in cli using any template:
```
cat test | while read line;do nuclei -u $line -t  <template> -no-stdin -stats; echo 'runn other stuff';done
```
3. nuclei and ``` echo 'runn other stuff'``` only runs once

![image](https://user-images.githubusercontent.com/84903531/224389935-1c3dfa65-8b4f-4032-87c4-e604a79bcda8.png)

**Comment by ehsandeep** [comment]
@AyushXtha it's the `-no-stdin` option that instructs nuclei to not read input from stdin and at the same time if you feeding input via stdin (`cat tet`), so it's expected not to work, either remove the `-no-stdin` option or feed the input using `-list` option.
