### ISSUE TITLE
Extend the `update-existing` option to all the issue tracker types

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#3429]
There is an `update-existing` reporting configuration option for Jira. This option controls whether to create a new ticket, or rather append the finding to an existing ticket. It would be nice to extend this functionality to the other issue trackers as well (e.g. GitHub, GitLab etc.)

Reference:
* https://github.com/projectdiscovery/nuclei/issues/754

**Comment by ehsandeep** [comment]
This is now supported for GitLab, GitHub as well.
