### ISSUE TITLE
Add multi-core/multi-arch support for GH actions

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3441]
### Nuclei version:
`dev/main`

### Description
GH actions should be executed on different multi-core configurations and archs (32bit, 64bit, ARM)

**Comment by dogancanbakir** [comment]
Quick update: Based on the information provided in the [documents](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), it appears that GitHub-hosted runners have limitations in terms of flexibility. While they do support [high-end machine specs](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#machine-specs-for-larger-runners), utilizing Self-hosted runners is necessary to achieve support for varying hardware architectures.

**Comment by dogancanbakir** [comment]
Upon discussion, closing this as not planned.
