### ISSUE TITLE
[issue] Path ignored from input

### ISSUE THREAD

**Issue by Marmelatze** [projectdiscovery/nuclei#345]
**Describe the bug**
Before #287 the path was taken from the input URL and template paths appended. Now the path is replaced.
So running nuclei with target http://example.com/foo will produce the same as running with http://example.com

I would expect nuclei to use the given path as BaseURL in the templates.

**Nuclei version**
2.1.1, master

**Screenshot of the error or bug**
![Screenshot 2020-10-07 um 09 23 39](https://user-images.githubusercontent.com/199681/95300417-6bf4b480-087f-11eb-9abd-e42514489763.png)

**Comment by bauthard** [comment]
to reproduce:- 

```
echo http://67bx7clgkz761pmyk4lckwh41v7rvg.burpcollaborator.net/testing/ | ./nuclei -t panels/phpmyadmin-panel.yaml -debug
```

```http
GET /phpmyadmin/ HTTP/1.1
Host: 67bx7clgkz761pmyk4lckwh41v7rvg.burpcollaborator.net
Connection: close
Accept: */*
Accept-Language: en
Connection: close
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)

[INF] Dumped HTTP response for http://67bx7clgkz761pmyk4lckwh41v7rvg.burpcollaborator.net/testing/ (phpmyadmin-panel)

HTTP/1.1 200 OK
Content-Length: 53
Content-Type: text/html
Server: Burp Collaborator https://burpcollaborator.net/
X-Collaborator-Version: 4

<html><body>js76wrbfzmbd1qyt0rcp0czjogz</body></html>
[INF] Dumped HTTP request for http://67bx7clgkz761pmyk4lckwh41v7rvg.burpcollaborator.net/testing/ (phpmyadmin-panel)

GET /admin//phpmyadmin/ HTTP/1.1
Host: 67bx7clgkz761pmyk4lckwh41v7rvg.burpcollaborator.net
Connection: close
Accept: */*
Accept-Language: en
Connection: close
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)
```

**Comment by bauthard** [comment]
Thank you for reporting this @Marmelatze, this is now fixed with this PR https://github.com/projectdiscovery/nuclei/pull/346, thank you @vzamanillo for quickly jumping on this with fix.
