### ISSUE TITLE
Workflow not detected + Templates deleted

### ISSUE THREAD

**Issue by funderpanda** [projectdiscovery/nuclei#3460]
### Nuclei version:
2.9.0
### Current Behavior:
When running Nuclei I am able to change the template dir with the "-t" flag. However it cannot find my workflow despite it being there and if I press Ctrl+C to cancel it deletes my template files

### Expected Behavior:
It should be able to find my workflow and not delete the templates file

### Steps To Reproduce:
Run in Docker
Use the "-t" flag and specify a path that is not your current working directory
Have a custom workflow in that directory and use that
(image attached below)

### Anything else:
https://imgur.com/a/lu1sBBz

**Comment by tarunKoyalwar** [comment]
@funderpanda  ,`-t` flag doesn't change directory but it tries to load all `.yaml` files from that directory , if you have templates in multiple directories you can use below command

```console
nuclei -t ~/nuclei-templates -t ~/mytemplates
```
^ this will load all templates from both directories , you can also pass a specific file instead of template with `-t` flag

**Comment by funderpanda** [comment]
Hi @tarunKoyalwar it seems like adding the HOME variable to the directory nuclei-templates is in fixes this. 
We're not using .nuclei-ignore
Also re-installing the templates also fixes this. However since I'm running it on AWS our security policy means we arent allowed to pull from github directly, for now I'll change the HOME env variable but if there's any other ideas feel free to share :)

**Comment by funderpanda** [comment]
Thank you. By default on Alpine the home env is /root/ so I changed it to /home and moved my files there. I believe since nuclei always looks for templates in the HOME env variable changing it to /home fixes this issue. I see and thank you, this issue should be closed :)
