### ISSUE TITLE
Docker Image doesn't support -pbar [issue]

### ISSUE THREAD

**Issue by Sicks3c** [projectdiscovery/nuclei#349]
**Describe the bug**
Hello Team

I would like to report a bug that occurs when using docker via WSL2 the `pbar` seems to print an infinite loop of `…`

**Nuclei version**
Latest `projectdiscovery/nuclei` docker image

**Screenshot of the error or bug**
> Command
![image](https://user-images.githubusercontent.com/32225186/95659809-8b0f7280-0b1b-11eb-8e04-346028cb2128.png)
> Output
![image](https://user-images.githubusercontent.com/32225186/95659808-834fce00-0b1b-11eb-8dbf-421384115b92.png)

Regards

**Comment by team-projectdiscovery** [comment]
@Sicks3c in the latest release 2.2.0, `pbar` is replaced with `stats`.

**Comment by Sicks3c** [comment]
Hello @team-projectdiscovery 

Yes you're right I have submitted this bug before the 2.2.0 release
Keep it up the good work

Regards
