### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by ayoubackup** [projectdiscovery/nuclei#3496]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/3495

<div type='discussions-op-text'>

<sup>Originally posted by **ayoubackup** April  2, 2023</sup>
Hi projectdiscovery

i have run nuclei for big list and sometimes i got output :

2023/04/02 04:25:02 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 200 BANNED\r\n"; err=<nil>

i try to filter it using grep but i got same error

cat list.txt | httpx.exe -t 200 -silent | nuclei -t mytemplate.yaml -silent -timeout 1 | grep -v "Unsolicited response"

is there any solustion to stop this noise output

NOTE: i doubt because i ' m not using --no-color flag !</div>

**Comment by ehsandeep** [comment]
This is being tracked at https://github.com/projectdiscovery/nuclei/issues/3462
