### ISSUE TITLE
Parsing .nuclei-ignore from current directory

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#350]
It would be great if I could create a `.nuclei-ignore`  file in the current directory which I execute nuclei from (which would take precedence over the entries from `.nuclei-ignore` that's under templates directory). I want to make use of this feature, but at the same time I don't want to edit the file under templates directory (for one thing, I'd have issues when pulling from git to update templates).

_Originally posted by @nirvana-msu in https://github.com/projectdiscovery/nuclei/issues/233#issuecomment-706573812_

**Comment by nirvana-msu** [comment]
Thanks. Additionally/alternatively, there could be an option to specify the path to that custom `.nuclei-ignore` file.

**Comment by bauthard** [comment]
Added here https://github.com/projectdiscovery/nuclei/pull/351 @dwisiswant0 @nirvana-msu
