### ISSUE TITLE
issue with httpx integration (fallback check is not working) 

### ISSUE THREAD

**Issue by tess-ss** [projectdiscovery/nuclei#3511]
Hello team,

I would like to bring an issue to your attention regarding the latest update of the Nuclei Engine. I have noticed that the engine now accepts results of subdomains that are not scanned for "http://" and "https://" protocols, which is a great improvement. However, I have observed that the engine only checks for "https://" and not "http://".

In some cases, the host only resolves on "http://" instead of "https://". It would be great if Nuclei could roll out an update that checks for both protocols and runs scans on both, which would minimize the chances of missing any vulnerabilities.

Thank you,
@tess-ss

**Comment by sw33tLie** [comment]
IMHO probing subdomains isn't really nuclei's role, especially if we consider unix's philosophy, and other PD tools should take care of that.

**Comment by ehsandeep** [comment]
@sw33tLie that's true, but since many times users are not aware of supported input types, we have added probing support to nuclei in the past for better UX.

@tess-ss do you have an example that can be used to repro this?

**Comment by jimen0** [comment]
@ehsandeep here is a reproducer for you.

```console
$ nuclei -t "miscellaneous/dir-listing.yaml" -u http://localhost -silent
[dir-listing] [http] [info] http://localhost
$ nuclei -t "miscellaneous/dir-listing.yaml" -u localhost -silent
$ curl -i https://localhost
HTTP/2 200 
content-length: 0
date: Thu, 06 Apr 2023 14:20:40 GMT

$ curl http://localhost
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Directory listing for /</title>
</head>
<body>
<h1>Directory listing for /</h1>
<hr>
<ul>
<li><a href="b.js">b.js</a></li>
<li><a href="c.js">c.js</a></li>
</ul>
<hr>
</body>
</html>
```

The setup is just a HTTPS server on localhost:443 returning a 200 OK and an HTTP server on localhost:80 that replies with a directory listing in it.

> However, I have observed that the engine only checks for "https://" and not "http://".

The above behavior proves this.

**Comment by tess-ss** [comment]
Thanks @jimen0 

For highlighting the issue for me, this is exactly what I wanted to highlight here as well.

Appreciate the quick response and re-opening the issue @ehsandeep I was confused whether or not to consider this as a enhancement that's the reason I closed it.

I appreciate your help on this issue. Good work ProjectDiscovery team :)

Best,
@tess-ss

**Comment by ehsandeep** [comment]
@jimen0 thank you for sharing additional detail.

@tess-ss I think the current behavior is expected and similar to httpx, i.e, when no url scheme is provided, check for `https` and if it failed, check for `http` but in the above example, looks like `https` is working, so it doesn't check for http, this in this particular case `https` and `http` both running different services which is not common and kind of edge case.

Checking for both services as default will **duplicate** nuclei scan against all the targets that we avoid with current behavior, i.e only check `http` when `https` is failed.

**Comment by ehsandeep** [comment]
I'm closing this as this is working as expected.
