### ISSUE TITLE
v2/pkg/core/execute_options.go# A bug of ScanStrategy

### ISSUE THREAD

**Issue by zhouyongchao** [projectdiscovery/nuclei#3515]
Hello team, I found a bug in the source code file: "execute_options.go" ,Version 2.9.0 ，On  line 68 of the file, it should read "scanstrategy. HostSpray”

**Comment by ehsandeep** [comment]
@zhouyongchao it's already fixed in the latest release of nuclei, i.e **v2.9.1** in https://github.com/projectdiscovery/nuclei/pull/3464, make sure to update / use the latest version of code / tool.
