### ISSUE TITLE
[issue]

### ISSUE THREAD

**Issue by pranav-byte** [projectdiscovery/nuclei#352]
**Describe the bug**
While running nuclei on multiple domains it scans one url for one bug again and again. Command used - cat domains.txt | nuclei -t /root/nuclei-templates/ -pbar . Please go through screen shot you can see that it is scanning single target for multiple times for same issue.

**Nuclei version**
2.1.1 and 2.1.0

**Screenshot of the error or bug**
![Screenshot from 2020-10-11 17-03-47](https://user-images.githubusercontent.com/51847389/95677503-8d3d0400-0be3-11eb-93c9-d5ec5eb82915.png)

**Comment by bauthard** [comment]
Hi @pranav-byte, 

No, it only scans for once and prints all unique techs used on that particular website, you can check the template to explore more https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/tech-detect.yaml

**Comment by pranav-byte** [comment]
![Screenshot from 2020-10-11 17-17-10](https://user-images.githubusercontent.com/51847389/95677753-50720c80-0be5-11eb-9a0e-1315f946d318.png)

**Comment by pranav-byte** [comment]
please go through screen shot

**Comment by bauthard** [comment]
@pranav-byte Can you upload the `domains.txt` as attachments or what command you are using for this? I'm not able to replicate this. 

```
echo http://eualert.nl | nuclei -t ~/nuclei-templates/technologies/tech-detect.yaml 

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [tech-detect] Wappalyzer Technology Detection (@hakluke) [info]
[INF] Using 1 rules (1 templates, 0 workflows)
[tech-detect:apache] [http] [info] http://eualert.nl/
[tech-detect:apache] [http] [info] http://eualert.nl/
```

**Comment by pranav-byte** [comment]
[output.txt](https://github.com/projectdiscovery/nuclei/files/5361021/output.txt)

**Comment by pranav-byte** [comment]
this is the file which im scanning.
Command used - cat output.txt | nuclei -t /root/nuclei-templates/ -pbar

**Comment by bauthard** [comment]
@pranav-byte that's not the expected way to run templates, we do not suggest to run whole template at once, you need to be specific what you looking to scan as shared in the readme file instead of running all at once, about results, in this way, you are also running all workflows which runs tech detect template multiple times, hence multiple results.

**Comment by pranav-byte** [comment]
can you suggest me command to run

**Comment by bauthard** [comment]
here is the result, when you run the specific template on your list. 
```
cat test.txt | nuclei -t ~/nuclei-templates/technologies/tech-detect.yaml

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [tech-detect] Wappalyzer Technology Detection (@hakluke) [info]
[INF] Using 1 rules (1 templates, 0 workflows)
[tech-detect:apache] [http] [info] http://aehnet.nl/
[tech-detect:apache] [http] [info] http://aehnet.nl/
[tech-detect:apache] [http] [info] http://bzkncc.nl/
[tech-detect:apache] [http] [info] http://bzkncc.nl/
[tech-detect:apache] [http] [info] http://omgaanmetidealen.nl/
[tech-detect:apache] [http] [info] http://omgaanmetidealen.nl/
[tech-detect:sdl-tridion] [http] [info] https://locov.nl/
[tech-detect:apache] [http] [info] http://atde.nl/
[tech-detect:apache] [http] [info] http://atde.nl/
```

**Comment by pranav-byte** [comment]
cat test.txt | nuclei -t ~/nuclei-templates/technologies/tech-detect.yaml as you have runned this command it is also scanning for multiple times.This is the result of the above run command by you 

[tech-detect:apache] [http] [info] http://aehnet.nl/
[tech-detect:apache] [http] [info] http://aehnet.nl/
[tech-detect:apache] [http] [info] http://bzkncc.nl/
[tech-detect:apache] [http] [info] http://bzkncc.nl/
[tech-detect:apache] [http] [info] http://omgaanmetidealen.nl/
[tech-detect:apache] [http] [info] http://omgaanmetidealen.nl/
[tech-detect:sdl-tridion] [http] [info] https://locov.nl/
[tech-detect:apache] [http] [info] http://atde.nl/
[tech-detect:apache] [http] [info] http://atde.nl/

**Comment by bauthard** [comment]
@pranav-byte if you can check the template, there is 2 matcher for the `apache` detection, hence 2 results for each host.
