### ISSUE TITLE
Enable `-nc` option when `runtime.GOOS` is windows

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/nuclei#3529]
When running nuclei in powershell, the output control characters are shown instead of colored output.

### Current Behavior:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1474884/231241123-fb2d05cb-e925-4c50-be0d-4f2b49b0ffda.png">

### Expected Behavior:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/1474884/231241215-ee04eea6-17bc-4355-b135-ee9504df364e.png">

### Version:
* v2.9.0 (dev)
* Windows 11

**Comment by ehsandeep** [comment]
@sullo this is expected https://github.com/logrusorgru/aurora#limitations, for windows, we suggest using `-nc` option.
