### ISSUE TITLE
flag provided but not defined: -c        

### ISSUE THREAD

**Issue by exp1o1t5r** [projectdiscovery/nuclei#353]
I updated nuclei latest version today and I am getting error as flag provided but not defined: -c although I provided the value for -c

**Comment by theconcierge2020** [comment]
Hi there,

currently I'm facing the same issue. 
Can you please tell me your solution? I guess you have one - as you closed the ticket.
Highly appreciated. Thank you

**Comment by theconcierge2020** [comment]
Ah - the flag "-c" does no longer exist anymore. 

It is called "-rate-limit".

**Comment by exp1o1t5r** [comment]
thank you so  much

**Comment by bauthard** [comment]
Hey, we are actively working on the master code, and looks like you have installed the master code (Github install method) with additional/updated flags.

We suggest using the last stable release for the time being before we share/update all information related to new features in the coming release.

**Comment by theconcierge2020** [comment]
Thank you for the info! Highly appreciated
