### ISSUE TITLE
Upgrading to version v2.9.2 without color display

### ISSUE THREAD

**Issue by fengzirock** [projectdiscovery/nuclei#3581]
![image](https://user-images.githubusercontent.com/59859409/233567697-1b7ce02c-a9dd-4a40-ac7b-a9dd6d94fb62.png)
Normal default output should have colors

**Comment by fengzirock** [comment]
![image](https://user-images.githubusercontent.com/59859409/233571189-559c6737-6989-4c3a-adf9-9abaf54227ea.png)

**Comment by ehsandeep** [comment]
@fengzirock This is expected as per - https://github.com/projectdiscovery/nuclei/issues/3529

**Comment by fengzirock** [comment]
I hope there is a color. What command should I use

**Comment by mastercho** [comment]
> @fengzirock This is expected as per - #3529

yes this is expected for CMD and Powershell but if use WLS or Git Bash in windows should display color as previous versions

**Comment by fengzirock** [comment]
![image](https://user-images.githubusercontent.com/59859409/233825250-6f996a52-2094-4261-bc9e-a5682ae7d37d.png)
In the previous version, I used Windows Terminal (CMD or PowerShell) to display the color. There is no way now, right?

**Comment by Mzack9999** [comment]
https://github.com/projectdiscovery/nuclei/issues/3529 should be reverted and colors enabled by default. The only way to enable them now on windows is the following one:
```console
nuclei -no-color=false
```

**Comment by fengzirock** [comment]
Thank you for your answers
