### ISSUE TITLE
Crash on interactshclient.URL

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3584]
### Nuclei version:
`main`

### Current Behavior:
![image](https://user-images.githubusercontent.com/13421144/233688724-4dde2baa-887c-43e6-9d54-e9faccbe0d44.png)

### Expected Behavior:
No crash

### Steps To Reproduce:
`hosts.txt` contains ca 600 targets and the error is reproducible on `WSL2`, `Ubuntu 22.04.2 LTS`, `Ubuntu 22.04.6 LTS` and `Kali WSL2`

```console
$ nuclei -l hosts.txt -stats -t nuclei-templates/cves/ -s critical -o crits-cves.txt
```

**Comment by mastercho** [comment]
i think this is related to https://github.com/projectdiscovery/nuclei/issues/3462#issuecomment-1509848889

**Comment by issaclutch007** [comment]
Hello, is there any update in for this issue?

**Comment by ehsandeep** [comment]
@issaclutch007 this issue is fixed in dev version, and a new release is set to publish tomorrow.
