### ISSUE TITLE
get xxxxxxxxxxxxxxxxx% sometimes when seeing stats

### ISSUE THREAD

**Issue by molitona** [projectdiscovery/nuclei#3586]
sometimes. i get something like 9223372036854775808% when using -stats. 

![g](https://user-images.githubusercontent.com/35532337/233787258-a3051056-680b-4df4-a9d6-5facfb9f3ce2.png)

**Comment by mastercho** [comment]
thats because you have 0 hosts

**Comment by molitona** [comment]
yep but they should fix that number view...
