### ISSUE TITLE
Nuclei BaseURL param.

### ISSUE THREAD

**Issue by BenJoice** [projectdiscovery/nuclei#3587]
I use the tool version 2.9.2 
When running a scan on hosts of this type https://something/?v=0.2 the tool makes its request and substitutes its payload between the hostname and the parameter so that it turns out something like https://something/PAYLOAD/v=0 .2. Naturally, such a page does not exist(404) and there will be an error, although if done correctly and go to https://something/?v=0.2/PAYLOAD then everything works(200). It seems to me that something is going wrong or I don't understand something. 

Here is an example of such a scan that the guy did on version 2.8.1. I installed his stand in the docker and did all the steps. After that, I found such an error. Naturally, I tried to scan other resources - the problem is the same.

I found some kind of logic in the code to respond to the request:
At file "....v2/pkg/protocols/http/request.go" there is param "formedURL".
![image](https://user-images.githubusercontent.com/71026189/233794631-b8a39ec5-9a43-41fe-80db-a649d2cf8bba.png)

 Please explain to me what I am doing wrong.

**Comment by dogancanbakir** [comment]
@BenJoice In your example, `https://something/?v=0.2/PAYLOAD`, the query param `v` will have this value `0.2/PAYLOAD`. 
Another example would be:
PAYLOAD: `/webshell4/login.php?err=U&errcode=0&login=\%22%20onfocus=alert(document.domain);%20autofocus%20\%22`
BaseURL: `https://example.com/?v=0.2`

If you construct a URL from the base URL and the payload, base URL + payload: the `v` query param will have value `0.2/webshell4/login.php?err=U&errcode=0&login=\%22%20onfocus=alert(document.domain);%20autofocus%20\%22`

This is because a URL's path string comes before a query string.

**Comment by dogancanbakir** [comment]
@ehsandeep, I don't see any issue with our current approach, but I want your thoughts.

**Comment by BenJoice** [comment]
@dogancanbakir .
THX for reply.
What should i do then to get right result of scan?

**Comment by ehsandeep** [comment]
@BenJoice not sure if you tried the latest version, but I don't see the same behavior as you described; input query gets appended as query parameter and not a path as you shared in the initial example, it's possible that the older version had bug, but I can not reproduce it with latest version, let me know what you see after trying with latest version.

```
echo https://example.com/?v=2 | nuclei -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

		projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (latest)
[INF] Current nuclei-templates version: v9.5.2 (latest)
[INF] New templates added in latest release: 50
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[INF] [basic-example] Dumped HTTP request for https://example.com/test?v=2

GET /login?v=2 HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[INF] No results found. Better luck next time!
```

**Comment by dogancanbakir** [comment]
@BenJoice, everything should be correct based on the current URL-building method. The `v` query parameter will be included in the URL, which means that if the target app requires it to provide different content, there should be no issues as the `v` will already be present in the URL. Feel free to let us know if you need more help.
