### ISSUE TITLE
Markdown results in separate directories. 

### ISSUE THREAD

**Issue by cpandya2909** [projectdiscovery/nuclei#3596]
### Please describe your feature request:
If we output reports to Markdown with "-me" options, it creates all files in a single folder and have to search a big list for specific template output .

It would be better if we allow user to give option to save outputs in different folders.
User can choose to save outputs either hostname wise or template wise

### Describe the use case of this feature:

clear identification of outputs and issues.

**Comment by kchason** [comment]
What would be the intended method for determining which categorization occurs? An environment variable such as `MARKDOWN_EXPORT_SORT_MODE` that defaults to as it currently stands, but optionally allows "host" and "template"?

**Comment by cpandya2909** [comment]
yes, that can work, or else we can create 1 additional flag to mark that markdowns are stored in directory.

**Comment by kchason** [comment]
Okay, I can work on this one

**Comment by cpandya2909** [comment]
Thank you

**Comment by ehsandeep** [comment]
@cpandya2909 this is now possible with latest release - https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.10
