### ISSUE TITLE
After running the corresponding testing items have no color display

### ISSUE THREAD

**Issue by hacker-feng** [projectdiscovery/nuclei#3598]
After running the corresponding testing items have no color display
![fc2e8696844993f5b236268e3d1bede](https://user-images.githubusercontent.com/62542864/233952720-6ecac114-e1ce-4c3b-8a79-370fb781bfb9.png)

**Comment by mastercho** [comment]
that is related to https://github.com/projectdiscovery/nuclei/issues/3581

**Comment by ehsandeep** [comment]
this is being tracked at https://github.com/projectdiscovery/nuclei/issues/3581
