### ISSUE TITLE
no-sandbox flag for Linux

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei#3616]
Hi everyone. one week ago you have changed this line from Linux to Windows. But even a comment tells that it should be about linux, not windows. And after update I got an error about no-sandbox flag on linux machine. Was it a mistake ?

https://github.com/projectdiscovery/nuclei/blob/e3ce33afda548c67eaafe761bfeb9800b015e5d4/v2/pkg/protocols/headless/engine/engine.go#L126

Thanks.

**Comment by ehsandeep** [comment]
@savushkin-yauheni, thanks for flagging this, it was mistake and fixed in dev.
