### ISSUE TITLE
additional path for resolving template / workflow loading

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3622]
### Please describe your feature request:
As per https://github.com/projectdiscovery/nuclei-templates/issues/6279, http-based templates moved to `http/` directory, similar to other [protocol structures](https://github.com/projectdiscovery/nuclei-templates).

To ensure not to break the existing pipeline after the next template project release, additional paths can be supported to resolve templates with `-t` option and in workflows.

```yaml
# previous example
nuclei -t cves 
nuclei -t exposed-panels

# example after next template release
nuclei -t http/cves
nuclei -t http/exposed-panels
```

### Describe the use case of this feature:
- to ensure existing pipeline working same as before as long as nuclei is updated to latest version.

**Comment by olearycrew** [comment]
I don't understand the proposed change here...today `/` in the path works right?

For instance, I can run

`nuclei -t exposed-panel/adobe`

And it only runs the 6 Adobe templates.

So what would this proposed change change about that?

**Comment by ehsandeep** [comment]
> I don't understand the proposed change here...today `/` in the path works right?
> 
> 
> 
> For instance, I can run
> 
> 
> 
> `nuclei -t exposed-panel/adobe`
> 
> 
> 
> And it only runs the 6 Adobe templates.
> 
> 
> 
> So what would this proposed change change about that?

This is preparation for next template release when the actual changes will take effect, changes in main branch of nuclei template doesn't reflect on user side.
