### ISSUE TITLE
Does nuclei calculate stats incorrectly

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei#3630]
### Current Behavior:
I do always use -stats on nuclei and what i mostly see in big lists that they stops in middle...
So to be sure i run same list 3 times on recent version  with --stats and it's always stops at 32%

Is there any explanation for this?

![Screenshot](https://ruri.please-fuck.me/60Q_bJ0nZ.png)

I did also test with other big lists they also stops at middle on current version

![Screenshot](https://ruri.please-fuck.me/61DPjRiBY.png)

### Expected Behavior:
To continue and finish at 100%
### Steps To Reproduce:
`cat message29.txt | nuclei  -stats -t cves -t cnvd -t exposures -t network -t default-logins -t vulnerabilities -t exposed-panels -t file -o 29.nuclei -rl 100 -c 50`

**Comment by tarunKoyalwar** [comment]
Hii @mastercho , this is a known issue , while calculating stats nuclei currently does not take into account failed /errored requests and skipped requests due to `stop-at-first-match`

Ref: https://github.com/projectdiscovery/nuclei/issues/3384

**Comment by tarunKoyalwar** [comment]
@mastercho , the issue to resolve this is being tracked at https://github.com/projectdiscovery/nuclei/issues/3386
