### ISSUE TITLE
Deprecated protocol syntax / path (warning)

### ISSUE THREAD

**Issue by monixxxx** [projectdiscovery/nuclei#3645]
Hello,

I think you can fix it, otherwise all the templates do not work.

![fail_nuclei](https://user-images.githubusercontent.com/92028136/236055387-8201fb21-82e3-4e2c-8af2-568e59c2d908.png)

**Comment by ehsandeep** [comment]
@monixxxx this will be auto-updated upon next template release - https://github.com/projectdiscovery/nuclei-templates/milestone/2

**Comment by ehsandeep** [comment]
@monixxxx see https://github.com/projectdiscovery/nuclei/discussions/3648 for more details, I've also pinned this in issue / discussion section.
