### ISSUE TITLE
[Question] Maximum number of concurrent requests without compromising output

### ISSUE THREAD

**Issue by aaravmer** [projectdiscovery/nuclei#365]
I am running subdomain-takeover template on thousands of domains on a VPS that has 4GB RAM and 2 core processor.  When I use 100 threads it detects subdomain-takeover issues, but when I change threads to 1000 it misses some takeovers. 

So I want to know the maximum limit of threads I can use without compromising the output on this machine (4GB RAM and 2 core processor).

**Comment by bauthard** [comment]
Hi @aaravmer, 

Yes, `100` is the suggested number of threads to use.
