### ISSUE TITLE
High memory usage and slow execution in v2.9.3 due to new DNS fields feature when using takeover templates

### ISSUE THREAD

**Issue by d3mondev** [projectdiscovery/nuclei#3666]
### Nuclei version:
v2.9.3

### Current Behavior:
Since v2.9.3, I'm seeing very high memory usage and slow execution speed when running takeover templates on specific targets.

This seems to be due to commit f6401877091f2389047e780184f1a42782fc503f as I can't reproduce the issue with the previous commit d55ad995d0f5efb06c4089555bda181437de2704.

### Expected Behavior:
Execution time and memory usage of takeover templates should be within the same range as with v2.9.2.

### Steps To Reproduce:
You should be able to reproduce the issue easily with the following command:

```
$ time nuclei -u identity.aliyun.com -tags takeover

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

                projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (outdated)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 73
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 73 (Reduced 71 Requests)
[INF] No results found. Better luck next time!

real    1m39.119s
user    1m31.222s
sys     0m4.355s
```

During execution, notice that nuclei takes up to 1GB of memory to test a single target.

![image](https://github.com/projectdiscovery/nuclei/assets/55468528/a9b7a733-9dd8-4d96-a807-4e15bed70c4c)

Here are the results from v2.9.2 which shows the previous behavior. Notice that execution takes just a few seconds and memory usage stays normal:

```
$ time nuclei -u identity.aliyun.com -tags takeover

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2

                projectdiscovery.io

[INF] Current nuclei version: v2.9.2 (outdated)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 73
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 73 (Reduced 71 Requests)
[INF] No results found. Better luck next time!

real    0m8.630s
user    0m2.418s
sys     0m0.897s
```

### Anything else:

Thanks, keep up the good work and let me know if I can help!

**Comment by ehsandeep** [comment]
@d3mondev thanks for pointing this out, we have a fix for this here - https://github.com/projectdiscovery/nuclei/pull/3676 can you give it a try and share if any feedback?

**Comment by d3mondev** [comment]
I can't reproduce it with the fix. Seems to work nicely 👍🏻

Thanks for the quick turnaround!

**Comment by mastercho** [comment]
Thats indeed is a thing in Windows 2.9.4 version, its uses higher memory than previous versions

**Comment by ehsandeep** [comment]
Reopening the issue to tag with release, will be closed with next release of nuclei.

**Comment by ehsandeep** [comment]
@mastercho @d3mondev fix is now available in the latest release of nuclei.
