### ISSUE TITLE
[feature] make nuclei-scan possible in passive - mode

### ISSUE THREAD

**Issue by zer010bs** [projectdiscovery/nuclei#367]
**Is your feature request related to a problem? Please describe.**

we use lots of recon-data from shodan/binaryedge and also rumble-scans, where all the data is already locally available (http-headers and html-body). for certain task, especially huge datasets, if would be perfect, if we can let the nuclei-scan parse the data available, instead of scanning each service again; this would work great for discovery, but not for cve/vulncheck and speed up discovery for larger datasets.

we have a similar approach running with a custom-build tool and great success, wbut would like to switch to nuclei, if such a feature would be available

**Describe the solution you'd like**

instead of actively scanning, use already existing data (header, body) to detect/discover used technologies/applications for a faster and stealthier approach

**Comment by bauthard** [comment]
This is implemented in the latest dev branch, details will be updated with the next release.
