### ISSUE TITLE
template update issue 

### ISSUE THREAD

**Issue by phoenix-sec** [projectdiscovery/nuclei#3673]
Hello team, could you please investigate why the nuclei tool is not updating nuclei templates?"
![Screenshot from 2023-05-12 10-55-16-1](https://github.com/projectdiscovery/nuclei/assets/41837489/28b24efb-07d4-4e4c-9f98-b2c90b085167)

**Comment by ehsandeep** [comment]
@phoenix-sec Currently nuclei templates v9.5.0 is marked as pre-release - https://github.com/projectdiscovery/nuclei-templates/releases/tag/v9.5.0, so you are running the latest version.

**Comment by ehsandeep** [comment]
new template version will be published soon.

**Comment by phoenix-sec** [comment]
ok sir <3

**Comment by ehsandeep** [comment]
Closing as this is expected.
