### ISSUE TITLE
Replace deprecated github.com/alecthomas/jsonschema

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3690]
### Nuclei version:
`main|dev`

### Current Behavior:
Using deprecated https://github.com/alecthomas/jsonschema

### Expected Behavior:
Replace with https://github.com/invopop/jsonschema

Ref: https://github.com/projectdiscovery/nuclei/issues/3651#issuecomment-1539028785

**Comment by kchason** [comment]
This would require some refactoring to do. The use of YAML property tags isn't supported in the invopop fork: https://github.com/invopop/jsonschema/discussions/28

Also, `jsonschema.Type` doesn't exist as a fixture in the new fork as well.

**Comment by tarunKoyalwar** [comment]
currently used jsonschema library is deprecated for over 2 years now and is unmaintained , at same time it does not support interfaces & other crucial keywords like `deprecated` , `example` and much more . using new maintained fork fixes all this and support for examples etc thus it can vastly simplify or potentially replace `yamldoc-go` library we have
