### ISSUE TITLE
nuclei aboyt string ../// can‘t request.  unsafe-http-requests, bug

### ISSUE THREAD

**Issue by ltfafei** [projectdiscovery/nuclei#3699]
then https://github.com/projectdiscovery/nuclei/discussions/3697

https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#unsafe-http-requests

![image](https://github.com/projectdiscovery/nuclei/assets/43526141/c9be3cfa-352d-4eeb-858f-32517af83c3a)

How can I fulfill this particular request?

**Comment by Mzack9999** [comment]
I think you might need to use `unsafe` requests. For example, have a look at [CNVD-2021-09650.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cnvd/2021/CNVD-2021-09650.yaml)
