### ISSUE TITLE
Add progress bar to show stats related to rate of request and total count

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#37]
As pointed out here https://twitter.com/sw33tLie/status/1253823665529131014

For example:- 

```
500 req/second 
100/10000 done
```

**Comment by sw33tLie** [comment]
Thank you for this.
I truly believe this would be a great improvement as when you run nuclei on large lists you really don't have a clue about what it's doing.

**Comment by sw33tLie** [comment]
Maybe instead of a progress bar you could add something nmap-style...when you press enter while it's scanning, it tells you some info...

**Comment by bauthard** [comment]
Sure, we will add, not sure you know but we have updated the `-v` flag which now shows all the request nuclei making at runtime, @sw33tLie

**Comment by manuelbua** [comment]
I'm not sure any of you guys is already working on this, but i decided to take a look at this and try implement it: i'm new to the Go language and this will help me learn it better, hopefully!

A WIP version is available in my own fork at https://github.com/manuelbua/nuclei/commits/enumeration-progressbar (branch is `enumeration-progressbar`).

![nuclei-prg](https://user-images.githubusercontent.com/819314/86521035-c8dd6a80-be4b-11ea-858e-0f7b5d9d5499.gif)

It still has many rough edges and i'm totally unsure about code/encapsulation style etc.. also workflows are totally untested, but it may be a starting point for something better.

**Comment by sw33tLie** [comment]
That's awesome!!!
