### ISSUE TITLE
[ERR] The correlation id was not found (probably evicted due to inactivity): could not get correlation-id from cache

### ISSUE THREAD

**Issue by Darkcast** [projectdiscovery/nuclei#3708]
Running  nuclei v2.9.4 on an ubuntu box

### Current Behavior:
Error Message:
[ERR] The correlation id was not found (probably evicted due to inactivity): could not get correlation-id from cache

### Expected Behavior:
no receive this message 

### Steps To Reproduce:

Example: steps to reproduce the behavior:
im running a  scan baded on the result of asnmap and httpx 
I saved the results into a file and then I ran nuclei -l asnmp_result.txt 
it runs for hours and after a while all is this message over and over
[ERR] The correlation id was not found (probably evicted due to inactivity): could not get correlation-id from cache

### Anything else:
![2023-05-18_16-32](https://github.com/projectdiscovery/nuclei/assets/1676655/6ac05bb6-b85a-4c50-9edf-e52167e3fa6a)

**Comment by ehsandeep** [comment]
@Darkcast see https://github.com/projectdiscovery/nuclei/issues/3462, closing as this is duplicate ticket.
