### ISSUE TITLE
Cookie reuse from workflows is not implemented for headless templates

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#3714]
The cookie JAR should be shared between `headless` templates as well. This should work when the template is a top level template within a workflow and also when it's declared as a `subtemplate`.

This prevents writing authenticated templates that require JavaScript to validate a vulnerability.

Related: 
* https://github.com/projectdiscovery/nuclei/issues/2371
* https://github.com/projectdiscovery/nuclei/issues/1162

**Comment by ehsandeep** [comment]
@forgedhallpass this is now supported into latest release.

**Comment by forgedhallpass** [comment]
Thank you!
