### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zinminphyo0** [projectdiscovery/nuclei#3731]
I've already installed the latest version.

![2023-05-23_04-06](https://github.com/projectdiscovery/nuclei/assets/74085414/c040327e-6382-4dbc-8fe0-7055af2548da)

**Comment by Mzack9999** [comment]
@zinminphyo0 Please fill all the sections at https://github.com/projectdiscovery/nuclei/issues/new?assignees=&labels=Type%3A+Bug&projects=&template=issue-report.md

We need clear reproduction steps to investigate the issue and implement a fix if necessary. Thanks!

**Comment by zinminphyo0** [comment]
cat site.txt | nuclei -t nuclei-templates/takeovers/
