### ISSUE TITLE
The correlation id was not found  

### ISSUE THREAD

**Issue by Rahimianes** [projectdiscovery/nuclei#3735]
### Nuclei version:
Latest version: v2.9.4
### Nuclei_templates version: 
Latest  version : v9.5.0
OS : ubuntu 22.04

### Current Behavior:
After updating to the latest version I gave an below error often of time .
[ERR] The correlation id was not found (probably evicted due to inactivity): could not get correlation-id from cache

### Steps To Reproduce:
Since I updated to the latest version, I have been experiencing the following error frequently, as clearly shown in the attached image. Unfortunately, I cannot specify exactly when this issue occurs. It occurs randomly when I run the program. Sometimes I receive this error one hour after execution, sometimes two days later, and occasionally even sooner or later. I am uncertain about the exact cause and timing of this occurrence.
1. Run 
nuclei -nh -l subs.txt  -nt ~/nuclei-templates/ --severity low,medium,high,critical | notify -rl 1

2. See error...
[ERR] The correlation id was not found (probably evicted due to inactivity): could not get correlation-id from cache
![Uploading Screenshot from 2023-05-24 13-43-09.png…]()

**Comment by MetzinAround** [comment]
Hi @Rahimianes. We have another issue where this is being discussed and worked on. 

https://github.com/projectdiscovery/nuclei/issues/3462
