### ISSUE TITLE
-proxy-internal -pi flag not work

### ISSUE THREAD

**Issue by djallalzoldik** [projectdiscovery/nuclei#3742]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/3741

<div type='discussions-op-text' onload="alert(00)">

<sup>Originally posted by **djallalzoldik** May 25, 2023</sup>
 when i using nuclei like this 
nuclei -l list.txt -t screen.yaml -headless -pi "http://127.0.0.1:8080"

the traffic should go to my burp suite, but is not i don't know why 
nothing go to my brup suite , 

can you show me how this flag work?

when i start the command this what will happen 
![local](https://github.com/projectdiscovery/nuclei/assets/45321671/bd385d2c-7fd2-41b0-8b2f-eeec9110cb29)
</div>

**Comment by MetzinAround** [comment]
Gonna close this issue @djallalzoldik and keep it solely as a discussion. Thanks!
