### ISSUE TITLE
[ERR] failed to load provider keys got yaml: unmarshal errors:

### ISSUE THREAD

**Issue by timeisflowing** [projectdiscovery/nuclei#3749]
```
./nuclei
[ERR] failed to load provider keys got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/home/z...` into sources.Provider

                    __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.5

		projectdiscovery.io

[INF] Current nuclei version: v2.9.5 (latest)
[INF] Current nuclei-templates version: v9.5.0 (latest)
[INF] New templates added in latest release: 62
[INF] Templates loaded for current scan: 5958
[INF] No results found. Better luck next time!`
```

If anyone has such a problem, this is because [uncover](https://github.com/projectdiscovery/uncover/blob/main/README.md#installation-instructions) could not find the configuration file

the file that should be: `/home/user/.config/uncover/provider-config.yaml`

Solution: `go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest` then run it 1 time uncover application the configuration file is generated automatically:

That's it, regards, have a nice day.

**Comment by mastercho** [comment]
Any solution for Windows?

**Comment by reewardius** [comment]
and again the error that was in the previous version...

> nuclei -t *.yaml -validate

**Could not find template '*.yaml': no templates found for path
All templates validated successfully**

**Comment by timeisflowing** [comment]
> Any solution for Windows?

Just install uncover and the problem will be solved enough.

**Comment by timeisflowing** [comment]
> and again the error that was in the previous version...
> 
> > nuclei -t *.yaml -validate
> 
> **Could not find template '*.yaml': no templates found for path All templates validated successfully**

This is not a template problem, it's looking for a configuration file because uncover is not installed.

**Comment by mastercho** [comment]
> > Any solution for Windows?
> 
> Just install uncover and the problem will be solved enough.

just want to say that i did install in windows uncover with following command

`go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest`

but still getting the same error...

**Comment by leorac** [comment]
So do we have to install uncover to fix this error? Doesn't seem to be the best solution to me...

**Comment by ehsandeep** [comment]
@leorac, that's a temporary solution before we fix the issue in the nuclei.

@timeisflowing, thanks for opening this issue and sharing a temporary solution for others.

**Comment by u1tr0nex** [comment]
> ```
> ./nuclei
> [ERR] failed to load provider keys got yaml: unmarshal errors:
>   line 1: cannot unmarshal !!str `/home/z...` into sources.Provider
> 
>                     __     _
>    ____  __  _______/ /__  (_)
>   / __ \/ / / / ___/ / _ \/ /
>  / / / / /_/ / /__/ /  __/ /
> /_/ /_/\__,_/\___/_/\___/_/   v2.9.5
> 
> 		projectdiscovery.io
> 
> [INF] Current nuclei version: v2.9.5 (latest)
> [INF] Current nuclei-templates version: v9.5.0 (latest)
> [INF] New templates added in latest release: 62
> [INF] Templates loaded for current scan: 5958
> [INF] No results found. Better luck next time!`
> ```
> 
> If anyone has such a problem, this is because [uncover](https://github.com/projectdiscovery/uncover/blob/main/README.md#installation-instructions) could not find the configuration file
> 
> the file that should be: `/home/user/.config/uncover/provider-config.yaml`
> 
> Solution: `go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest` then run it 1 time uncover application the configuration file is generated automatically:
> 
> That's it, regards, have a nice day.

worked for me thanks, ran uncover once.

**Comment by reewardius** [comment]
> > and again the error that was in the previous version...
> > > nuclei -t *.yaml -validate
> > 
> > 
> > **Could not find template '*.yaml': no templates found for path All templates validated successfully**
> 
> This is not a template problem, it's looking for a configuration file because uncover is not installed.

uncover is installed

**Comment by timeisflowing** [comment]
> > > and again the error that was in the previous version...
> > > > nuclei -t *.yaml -validate
> > > 
> > > 
> > > **Could not find template '*.yaml': no templates found for path All templates validated successfully**
> > 
> > 
> > This is not a template problem, it's looking for a configuration file because uncover is not installed.
> 
> uncover is installed

run it 1 time uncover, after check if there is a file: `cat ~/.config/uncover/provider-config.yaml ` 

If everything is correct so far, then there is no problem.

**Comment by mastercho** [comment]
> > > Any solution for Windows?
> > 
> > 
> > Just install uncover and the problem will be solved enough.
> 
> just want to say that i did install in windows uncover with following command
> 
> `go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest`
> 
> but still getting the same error...

For Windows is not working with `go install` but if you download binary and run it once then should be fine

**Comment by ehsandeep** [comment]
Reopening as this needs to be fixed in nuclei.

**Comment by tarunKoyalwar** [comment]
@ehsandeep should be resolved with https://github.com/projectdiscovery/uncover/pull/230

**Comment by Mr-7r0j4n** [comment]
> ```
> ./nuclei
> [ERR] failed to load provider keys got yaml: unmarshal errors:
>   line 1: cannot unmarshal !!str `/home/z...` into sources.Provider
> 
>                     __     _
>    ____  __  _______/ /__  (_)
>   / __ \/ / / / ___/ / _ \/ /
>  / / / / /_/ / /__/ /  __/ /
> /_/ /_/\__,_/\___/_/\___/_/   v2.9.5
> 
> 		projectdiscovery.io
> 
> [INF] Current nuclei version: v2.9.5 (latest)
> [INF] Current nuclei-templates version: v9.5.0 (latest)
> [INF] New templates added in latest release: 62
> [INF] Templates loaded for current scan: 5958
> [INF] No results found. Better luck next time!`
> ```
> 
> If anyone has such a problem, this is because [uncover](https://github.com/projectdiscovery/uncover/blob/main/README.md#installation-instructions) could not find the configuration file
> 
> the file that should be: `/home/user/.config/uncover/provider-config.yaml`
> 
> Solution: `go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest` then run it 1 time uncover application the configuration file is generated automatically:
> 
> That's it, regards, have a nice day.

That's worked for me, Thanks for the solution...

**Comment by ehsandeep** [comment]
@timeisflowing @mastercho @leorac @u1tr0nex @Mr-7r0j4n @reewardius this is now fixed in latest release - https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.6

**Comment by TonyD0g** [comment]
> ```
> ./nuclei
> [ERR] failed to load provider keys got yaml: unmarshal errors:
>   line 1: cannot unmarshal !!str `/home/z...` into sources.Provider
> 
>                     __     _
>    ____  __  _______/ /__  (_)
>   / __ \/ / / / ___/ / _ \/ /
>  / / / / /_/ / /__/ /  __/ /
> /_/ /_/\__,_/\___/_/\___/_/   v2.9.5
> 
> 		projectdiscovery.io
> 
> [INF] Current nuclei version: v2.9.5 (latest)
> [INF] Current nuclei-templates version: v9.5.0 (latest)
> [INF] New templates added in latest release: 62
> [INF] Templates loaded for current scan: 5958
> [INF] No results found. Better luck next time!`
> ```
> 
> If anyone has such a problem, this is because [uncover](https://github.com/projectdiscovery/uncover/blob/main/README.md#installation-instructions) could not find the configuration file如果有人有这样的问题，这是因为[uncover](https://github.com/projectdiscovery/uncover/blob/main/README.md#installation-instructions)找不到配置文件
> 
> the file that should be: `/home/user/.config/uncover/provider-config.yaml`文件应该是：`/home/user/.config/uncover/provider-config.yaml`
> 
> Solution: `go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest` then run it 1 time uncover application the configuration file is generated automatically:解决方案：`go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest`然后运行1次发现应用程序，配置文件将自动生成：
> 
> That's it, regards, have a nice day.就这样，问候，祝你愉快。

Remember to use Windows to download Uncover, because I tried it on Mac and it didn't generate provider-config.yaml
