### ISSUE TITLE
Question: target's path is not respected?

### ISSUE THREAD

**Issue by c0rvax** [projectdiscovery/nuclei#375]
Hey, 

I have two `info.php` files on my host:  

http://c0rvax.com/info.php
http://c0rvax.com/subdir/info.php

I am exepcting nuclei to find the `subdir/info.php` when launching it like so: 
```
nuclei -target https://c0rvax.com/subdir -t nuclei-templates/files/phpinfo.yaml
```

However, I don't see that nuclei found it. Launching it with `-debug` shows that all requests are sent to `http://c0rvax.com/` rather than to `http://c0rvax.com/subdir`. What could be the origin of the problem and solution to it?

My version is 2.1.1

Thanks!

**Comment by bauthard** [comment]
Hey @c0rvax, 

This is fixed in the master code https://github.com/projectdiscovery/nuclei/pull/346, it was a bug introduced in the last version.

**Comment by c0rvax** [comment]
@bauthard Thanks!
That answers the question
