### ISSUE TITLE
[ERR] failed to load provider keys got yaml: unmarshal errors:   line 1: cannot unmarshal !!str `/Users/...` into sources.Provider

### ISSUE THREAD

**Issue by wuha0926** [projectdiscovery/nuclei#3755]

**Comment by lijoabraham** [comment]
<img width="570" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/119271231/5fe69a1e-07e3-43a0-97c8-e945b1633d29">

Same with the case of docker-compose as well.
`version: '3'
services:
  nuclei:
    image: projectdiscovery/nuclei
    volumes:
      - ./nuclei-templates:/nuclei-templates
      - ./nuclei-workdir:/nuclei-workdir
    command: -update-templates`

**Comment by ehsandeep** [comment]
@wuha0926 @lijoabraham see https://github.com/projectdiscovery/nuclei/issues/3749

**Comment by k3rwin** [comment]
+1
