### ISSUE TITLE
missing deadline on network write causes delay

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3762]
### Nuclei version:

dev | main

### Current Behavior:

Originally discovered by @praetorian-thendrickson in #3758 
- missing Conn.Write deadline causes delay which was detected by hang monitor (it eventually fails but after a while by due to server timeout)

### Expected Behavior:

- no hang/delay

### Steps To Reproduce:

```console
$  time nuclei -pt tcp  -hang-monitor  -u tesla.com                              1 ↵

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.4

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v2.9.5 for continued support.
[INF] Current nuclei version: v2.9.4 (outdated)
[INF] Current nuclei-templates version: v9.5.0 (latest)
[INF] New templates added in latest release: 62
[INF] Templates loaded for current scan: 92
[INF] Targets loaded for current scan: 1
[ERR] Detected hanging goroutine (count=97/97) = nuclei-stacktrace-chr5rg5roa2k9unfrupg.dump
nuclei -pt tcp -hang-monitor -u tesla.com  70.37s user 0.39s system 100% cpu 1:10.07 total
```
[stacktrace.txt](https://github.com/projectdiscovery/nuclei/files/11605599/stacktrace.txt)

### Anything else:

- [x] add setWriteDeadline in network request
- [x] ~include template-id in network error message~ added in https://github.com/projectdiscovery/nuclei/pull/3546

**Comment by tarunKoyalwar** [comment]
@praetorian-thendrickson  thanks for looking into it . i will try to check if there are other issue but for now it seems like the hang is only related to tcp / network templates right ?

**Comment by praetorian-thendrickson** [comment]
@tarunKoyalwar So far that's the only one I've observed. Updating the hang-monitor timeout to 30 and running again with `nuclei -pt tcp -hang-monitor -u tesla.com` finishes as expected without the hang monitor crashing. So it looks to be related to a missing network timeout on a read/write. I'm looking to see where that needs to be set. 

<img width="594" alt="Screenshot 2023-06-01 at 10 21 30 AM" src="https://github.com/projectdiscovery/nuclei/assets/69640071/0de0b657-4cca-4a66-a655-40eae9726fe3">

**Comment by ocervell** [comment]
Hi @ehsandeep I've encountered this issue today. It seems although we change the read deadline to a deadline, the last fix to increase -hang-timeout timeout was not applied, so the error is still here in some situations (huge number of hosts, slow tcp timeout).
