### ISSUE TITLE
add template option to skip path concatenation in raw request

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3764]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/3732

<div type='discussions-op-text'>

<sup>Originally posted by **webtester0** May 23, 2023</sup>
The problem is this: when using raw syntax in the template, there is no possibility to specify strictly path, so when you run nuclei on URLs scope, the current path from template is concatenated with path which is passed in scope.
It's possible to specify Host strictly, just using annotation, but it's not possible with path

Is there any possible solution, to fix this problem?
<img width="1163" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/44179403/f0ca4012-7cf1-451e-84b7-99b995d92e80">
</div>

**Comment by tarunKoyalwar** [comment]
### Proposed Changes

- [ ] add new option to ignore concatenation to raw requests paths
- [ ] add integration test for this usecase

**Comment by webtester0** [comment]
@RamanaReddy0M any updates about this issue?

**Comment by RamanaReddy0M** [comment]
@webtester0 working on it.
