### ISSUE TITLE
fix gitlab custom templates update issue

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#3768]
### Nuclei version:

dev | main

### Current Behavior:

original issue reported by @six2dez https://discord.com/channels/695645237418131507/700092442661355602/1112630109388677120

- unlike github custom templates . update / download of gitlab custom templates requires `GITLAB_REPOSITORY_IDS` to be set
- instead of  checking if  `GITLAB_REPOSITORY_IDS` is set before updating templates it is checking `GITLAB_TOKEN` which is causing fatal error while updating custom templates 

Note: this only happens when `GITLAB_TOKEN` env exists but `GITLAB_REPOSITORY_IDS` does not

### Expected Behavior:

no error

### Steps To Reproduce:

- Set a valid `GITLAB_TOKEN` but do not set `GITLAB_REPOSITORY_IDS` and run `nuclei -ut`

### Anything else:

![image](https://github.com/projectdiscovery/nuclei/assets/45962551/dc7527c2-72c6-437d-b00c-29bef8ce1d6b)

**Comment by ehsandeep** [comment]
@six2dez this is now fixed in latest release - https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.6
