### ISSUE TITLE
Support tcp template request merging

### ISSUE THREAD

**Issue by j4vaovo** [projectdiscovery/nuclei#3821]
<img width="294" alt="请求合并2" src="https://github.com/projectdiscovery/nuclei/assets/128683738/1fd89bcc-c562-4a32-99dd-6e9e28bdbec0">
<img width="811" alt="请求合并1" src="https://github.com/projectdiscovery/nuclei/assets/128683738/920baee2-6667-452c-aceb-c32c78ad0e60">

Same ip, port sent twice, no way to merge?

```[tasklist]
### Tasks
```

**Comment by ehsandeep** [comment]
@Mzack9999 possibly the same issue with additional context - https://github.com/projectdiscovery/nuclei/issues/3902

**Comment by Mzack9999** [comment]
@ehsandeep I think this PR already covers the runtime expected optimization, but I'm afraid I have to disagree with the proposed implicit input handling for the reasons I detailed in https://github.com/projectdiscovery/nuclei/issues/3902#issuecomment-1621085058
