### ISSUE TITLE
Issue with using socks proxy and reporting function at the same time

### ISSUE THREAD

**Issue by 6mile** [projectdiscovery/nuclei#3836]
### Nuclei version:

nuclei 2.9.6
templates 9.5.2

### Current Behavior:

If you combine a reporting function (Elasticsearch) and a socks proxy in the same command, it won't send the output to Elasticsearch.  However, if I run the exact same command without the socks proxy it works and the finding shows up in Elasticsearch.

If I run nuclei in verbose mode I get this error:
``` [WRN] Could not create issue on tracker: Post "http://elasticserver.example.org:9200/nuclei/_doc": context deadline exceeded (Client.Timeout exceeded while awaiting headers) ```

### Expected Behavior:

I want to be able to run a nuclei scan with both a socks proxy AND the Elasticsearch reporting function and have it work.

### Steps To Reproduce:

Example: steps to reproduce the behaviour:
1. Install Nuclei
2. add elasticsearch info in config file and verify you can successfully send findings to Elasticsearch.  Once you've got a working Elasticsearch reporting function, move on to step  number 3.
3. run command ``` nuclei -t http/exposures/files/npmrc-authtoken.yaml -rc /etc/elasticsearch/nuclei-config.yaml -p 'socks5://localhost:9050' -u https://app.example.org ```
4. Command will run successfully, and the detection will trigger but won't send the finding to Elasticsearch
5. Run the second command: ``` nuclei -t http/exposures/files/npmrc-authtoken.yaml -rc /etc/elasticsearch/nuclei-config.yaml -u https://app.example.org ```
6. Command will run successfully, and the detection will trigger and you will successfully see the finding in Elasticsearch.

### Anything else:

This appears to be solely related to the use of the proxy function and when I took at the code where the errors are coming from [/v2/pkg/output/output_test.go](https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/output/output_test.go) lines 47 and 50.

**Comment by 6mile** [comment]
fixed accidental link

**Comment by Mzack9999** [comment]
@6mile I tried reproducing the issue by starting an elasticsearch instance exposed at `192.168.5.30:9200` using `192.168.5.31:22` as socks5 via `ssh -D 9050` and got the data exported successfully:
```console
...
debug2: channel 3: rcvd close
debug3: channel 3: will not send data after close
debug2: channel 3: is dead
debug2: channel 3: garbage collecting
debug1: channel 3: free: direct-tcpip: listening port 9050 for 192.168.5.30 port 9200, connect from ::1 port 53983 to ::1 port 9050, nchannels 4
debug3: channel 3: status: The following connections are open:
  #2 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 7/8/9 sock -1 cc -1)
  #3 direct-tcpip: listening port 9050 for 192.168.5.30 port 9200, connect from ::1 port 53983 to ::1 port 9050 (t4 r1 i3/0 o3/0 e[closed]/0 fd 10/10/-1 sock 10 cc -1)

debug2: client_check_window_change: changed
debug2: channel 2: request window-change confirm 0
debug3: send packet: type 98
...
```

And running nuclei as follows:
```console
nuclei -u https://192.168.5.1 -id http-missing-security-headers -rc export-elastic.yaml -p 'socks5://localhost:9050' -v -debug
```
I'm not sure if that's the case, but if you are using Tor maybe the socks5 proxy ip could be unable to access the elasticsearch endpoint. From the proxy ip are you able to curl elasticsearch successfully?
