### ISSUE TITLE
[feature] Specify multiple template files in the parameter

### ISSUE THREAD

**Issue by w9w** [projectdiscovery/nuclei#384]
As of now, we can specify a single template file or a folder with template files. Both commands
nuclei -t tokens/slack-access-token.yaml,tokens/credentials-disclosure.yaml -nC -silent -target https://host.com
nuclei -t tokens/slack-access-token.yaml tokens/credentials-disclosure.yaml -nC -silent -target https://host.com
give an error. We can use nuclei -t tokens/slack-access-token.yaml -nC -silent -target https://host.com & nuclei -t tokens/credentials-disclosure.yaml -nC -silent -target https://host.com & wait. But if it was built-in already, it'd be super cool :)

**Comment by bauthard** [comment]
@w9w You can already feed multiple templates and directory using multiple `t` flag, for example:- 

```
nuclei -t tokens/slack-access-token.yaml -t tokens/credentials-disclosure.yaml
```

**Comment by bauthard** [comment]
Closing as this is already possible as shared above.
