### ISSUE TITLE
[issue] Docker Image doesn't support downloading templates to a custom directory 

### ISSUE THREAD

**Issue by jatindhankhar** [projectdiscovery/nuclei#386]
**Describe the bug**
Docker Image doesn't support downloading templates to a custom directory. 
The main idea is to update and populates templates at a common directory which can be used later for running several specific scans. 

```bash
docker run -v /tmp/templates/:/app/nuclei-templates -i projectdiscovery/nuclei -update-templates

[WRN] Could not update templates: failed to create template folder /app/nuclei-templates/.github/ISSUE_TEMPLATE : mkdir /app/nuclei-templates/.github: permission denied
```
The directory is created but templates are not downloaded.

If we use the `-update-directory` the command is successful but the templates are not written on the host machine. 

```bash
docker run -v /tmp/test_dir/:/app/nuclei-templates -i projectdiscovery/nuclei -update-templates -update-directory /tmp/test_dir/
```
<img width="1440" alt="Screenshot 2020-10-28 at 3 27 55 PM" src="https://user-images.githubusercontent.com/2412081/97421374-706a3580-1932-11eb-9990-dba31f042e16.png">

The templates are downloaded to the container only and not to the host machine. 

Ideally if building a system one would like to have flexibility to use the same for different stages. 

* One stage would be download/update templates at a shared but prefined directory. 
* In next stage, different template scans are performed using the same directory with different targets. 

The raw binary if run locally has no such issues. Looks the docker image has little flexibility with respect to custom path mapping via volume flag.

**Nuclei version**

`2.1.1`

```bash
docker run -v /tmp/templates/:/app/nuclei-templates -i projectdiscovery/nuclei -version
```

**Screenshot of the error or bug**

<img width="1440" alt="Screenshot 2020-10-28 at 3 15 15 PM" src="https://user-images.githubusercontent.com/2412081/97420287-20d73a00-1931-11eb-9db5-43a91e75934d.png">

**Comment by amiralkizaru** [comment]
Same issue here
![9U91Gb0](https://user-images.githubusercontent.com/32225186/97422808-b698a800-18e4-11eb-93d3-5d61b1836b2a.png)

**Comment by bauthard** [comment]
Thank you @jatindhankhar @amiralkizaru for reporting this, this looks like a permissions issue with the docker build user, not an expert on the subject, but we will see what we can do about this.

**Comment by jatindhankhar** [comment]
This is indeed permission issue. I tried modifying `Dockerfile` locally to investigate, although program is not exiting with permission error it is silently failing. 


## Debug Steps

**From the host**
```bash
cd /tmp/
mkdir ngh/
cd ngh/
touch created_outside_container.txt
docker run -v /tmp/ngh:/app/nuclei-templates  -it --entrypoint sh projectdiscovery/nuclei
```

**From the container**

```bash
ls nuclei-templates 
# Notice the mapping is complete, created_outside_container.txt is visible 
./nuclei -update-templates
# Fails
ls -ld nuclei-templates/
# drwxrwxr-x    2 1001     1001          4096 Nov  3 11:28 nuclei-templates/
ls -ld nuclei
# -rwxr-xr-x    1 root     root      17691399 Oct  7 14:44 nuclei
ls -ld .
drwxr-sr-x    1 appuser  appuser       4096 Nov  3 11:31 .
```

<img width="1440" alt="Screenshot 2020-11-03 at 5 07 59 PM" src="https://user-images.githubusercontent.com/2412081/97980654-2502cc00-1df7-11eb-937b-2fe6421a719b.png">



From what I can make out, it is mainly due to conflict with the `appuser` and `root` user. 
In my opinion issue is with the `appuser` commands in Dockerfile. 


Take a look at [gitleak's Dockerfile](https://github.com/zricethezav/gitleaks/blob/ede68fd95d1c501ad165483b442571448eaf975a/Dockerfile#L7) it is doing almost the same thing but has no permission issue.

**Comment by ehsandeep** [comment]
@jatindhankhar this issue was open for a while but should be fixed with the following commit https://github.com/projectdiscovery/nuclei/pull/563, here is the [updated dockerfile](https://github.com/projectdiscovery/nuclei/blob/dev/Dockerfile) from dev branch.

Thank you for reporting this.
