### ISSUE TITLE
Not able to load template for validation

### ISSUE THREAD

**Issue by harsh2403** [projectdiscovery/nuclei#3869]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/3868

<div type='discussions-op-text'>

<sup>Originally posted by **harsh2403** June 24, 2023</sup>
![image](https://github.com/projectdiscovery/nuclei/assets/40105975/03e75e1d-fba7-4d7f-aee5-9f3a0191965a)

I have updated to the latest release as well</div>

**Comment by ehsandeep** [comment]
@harsh2403 avoid creating duplicate issues/discussions.
