### ISSUE TITLE
nuclei workflow get stuck when concurrency set to 1 at certain workflows

### ISSUE THREAD

**Issue by black5ugar** [projectdiscovery/nuclei#3871]
### Nuclei version:

v2.9.6
### Current Behavior:

the nuclei get stuck running certain workflows when the concurrency set to 1 
![image](https://github.com/projectdiscovery/nuclei/assets/37103491/0d00bf68-2d45-4290-9362-49d61e5a0a67)

### Expected Behavior:

the worklflow works fine just like when the concurrency set to 2
![image](https://github.com/projectdiscovery/nuclei/assets/37103491/a267d2fd-8a8c-4efc-bf00-ec9308a9a560)

### Steps To Reproduce:

1. download the workflow and template file(can't upload yaml, I renamed it as txt)
2. Run 'nuclei -w test-workflow.yaml -u http://baidu.com -c 1‘, then you will find nulcei get stuck and would nerver exit as above
3. Run 'nuclei -w test-workflow.yaml -u http://baidu.com -c 2‘, the workflow works fine

[ali.txt](https://github.com/projectdiscovery/nuclei/files/11859275/ali.txt)
[baidu.txt](https://github.com/projectdiscovery/nuclei/files/11859276/baidu.txt)
[test-workflow.txt](https://github.com/projectdiscovery/nuclei/files/11859277/test-workflow.txt)

#### source code analysis
I am not aware of whether this is considered a feature or a bug.
Based on my understanding, the problem might be related to the following section of the source code.
https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/core/workflow_execute.go#L28-L38
```
	swg := sizedwaitgroup.New(w.Options.Options.TemplateThreads)
	for _, template := range w.Workflows {
		swg.Add()
		func(template *workflows.WorkflowTemplate) {
			if err := e.runWorkflowStep(template, ctxArgs, results, &swg, w); err != nil {
				gologger.Warning().Msgf(workflowStepExecutionError, template.Template, err)
			}
			swg.Done()
		}(template)
	}
	swg.Wait()
```
Concurrency is passed as a parameter and set to 1 in this section of the code.
We noticed that swg's size is equal to 1 because we set the concurrency to 1. 
Then, swg.Add() is called, which causes it to reach the capacity limit set for swg, and in the runWorkflowStep function, swg is passed as a pointer.
If nuclei continues to execute the workflow as provided in the example, it will reach this section of the code.
https://github.com/projectdiscovery/nuclei/blob/main/v2/pkg/core/workflow_execute.go#L125-L134
```
	for _, subtemplate := range matcher.Subtemplates {
		swg.Add()

		go func(subtemplate *workflows.WorkflowTemplate) {
			if err := e.runWorkflowStep(subtemplate, input, results, swg, w); err != nil {
				gologger.Warning().Msgf(workflowStepExecutionError, subtemplate.Template, err)
			}
			swg.Done()
		}(subtemplate)
	}
```
Although swg.Add() is called again, it does not take effect. Because the parent function does not exit, which prevents the invocation of swg.Done() from the parent function. As a result, the thread gets blocked at this point.

If the concurrency set to 2，by examining the source code, we can determine that the thread would not reach the capacity limit set for swg.
However, this is not a suitable solution for me.

**Comment by mastercho** [comment]
i thought was only on me lol

**Comment by Mzack9999** [comment]
@black5ugar Thanks for reporting this - Very nice catch and code analysis. I've implemented a simple patch that increases by one concurrency to the first nesting level in https://github.com/projectdiscovery/nuclei/pull/3903. Still, in future refactoring, we can better keep track of idle parent templates and allow subtemplates to go through the recursion flow.

**Comment by ehsandeep** [comment]
@black5ugar @mastercho this is now fixed in dev branch with https://github.com/projectdiscovery/nuclei/pull/3903, thanks again for reporting this.
