### ISSUE TITLE
option to exclude hosts to scan from input list

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3877]
### Please describe your feature request:
For the cases where the targets-to-scan list is fetched from sources (cloud providers, etc) where you don't have control to exclude specific hosts that you don't want to get scanned, it will be helpful to exclude those hosts with nuclei during the scan, similar to naabu's `-exclude-hosts` option.

```console
   -eh, -exclude-hosts string[]    hosts to exclude to scan from the input list (ip, cidr, hostname)
```

### Describe the use case of this feature:

Examples:

```bash
$ cat host_to_exclude.txt

1.1.1.1
status.example.com
1.1.1.1/24
*.gov
admin*.gov
```

```
nuclei -list scan_list.txt -eh 1.1.1.1,example.com,1.1.1.1/24
nuclei -list scan_list.txt -eh host_to_exclude.txt
```

**Comment by kchason** [comment]
I can address this one if it's not already being worked

**Comment by ehsandeep** [comment]
@kchason thank you, I've assigned the ticket to you; feel free to ping me if you get any questions about this feature.
