### ISSUE TITLE
CLI Flag to Disable Headless Mode's Chromium Sandbox

### ISSUE THREAD

**Issue by ErikOwen** [projectdiscovery/nuclei#3878]
### Please describe your feature request:

It would be nice to have a CLI flag to disable the Chromium sandbox that is configured when running headless templates. Right now [this logic](https://github.com/projectdiscovery/nuclei/blob/238ed0e9aabee2c51c695d26c9ce6cfa5db758a8/v2/pkg/protocols/headless/engine/engine.go#L115C1-L119) is what determines if chromium's sandbox is disabled or not.

```console
   -ho, -headless-options string[]   start headless chrome with additional options
```

### Describe the use case of this feature:

When running on AWS Fargate I want to be able to use Nuclei as a non-root user and still be able to launch chromium. I wish to do this by running Nuclei as a non-root user and passing in a flag to Nuclei to instruct Nuclei to disable chromium's sandbox functionality. Right now AWS Fargate does not allow containers to run in privileged mode, so the `--no-sandbox` flag must be passed to chromium for it to be able to run on AWS Fargate (see more information [here](https://github.com/aws/containers-roadmap/issues/1000#issuecomment-858133114)). So currently the only way to run nuclei's headless templates in AWS Fargate is by running Nuclei as root, which is not ideal.

**Comment by ehsandeep** [comment]
@ErikOwen I've updated the issue to add flag option, similar to what we have in Katana, that [lets the user define ](https://github.com/projectdiscovery/katana#-headless-options)any chrome related options as needed.

**Comment by ehsandeep** [comment]
@ErikOwen this is now possible with latest release - https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.10
