### ISSUE TITLE
No valid templates were found

### ISSUE THREAD

**Issue by lc** [projectdiscovery/nuclei#3885]
## Version:
v2.9.7

## go version
go version go1.20.5 linux/amd64

## Reproduction Steps:
`nuclei -t /root/nuclei-templates/http/fuzzing/cache-poisoning-fuzz.yaml -l targets.httpx --debug`

Where `targets.httpx` contains a list of URLs:

```
http://example.com/
http://another.example.com/
```

```
[WRN] Could not load template /root/nuclei-templates/http/fuzzing/cache-poisoning-fuzz.yaml: the template was excluded
[INF] Current nuclei version: v2.9.7 (latest)
[INF] Current nuclei-templates version: v9.5.3 (latest)
[INF] Targets loaded for current scan: 76
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no valid templates were found
```

**Comment by ehsandeep** [comment]
@lc `nuclei -t /root/nuclei-templates/http/fuzzing/cache-poisoning-fuzz.yaml -l targets.httpx -itags fuzz` will work; fuzzing templates are excluded as default.
