### ISSUE TITLE
`-matcher-status` option to include request/response information in output

### ISSUE THREAD

**Issue by seeyarh** [projectdiscovery/nuclei#3889]
### Please describe your feature request:
I would like a flag that works in conjunction with the -matcher-status flag to output the request and response in the json output, regardless of whether the template matched or not. 

### Describe the use case of this feature:
 I'm using the -include-rr  flag and the -matcher-status flag. This outputs the http request and response pair on a template match. However, I would like to output the http request and reponse in the json output regardless of whether the template matched or not.

I realize it is possible to dump the http request and responses to a separate directory regardless of whether the template matched, but I would like everything in one file for easier processing. Having everything in one file is easier to process, as opposed to having to parse through a directory with a different file for each host's response.

**Comment by ehsandeep** [comment]
depends on https://github.com/projectdiscovery/nuclei/issues/3891
