### ISSUE TITLE
[issue] Unable to exit after scanning, FUTEX_WAIT_PRIVATE appears

### ISSUE THREAD

**Issue by al0ne** [projectdiscovery/nuclei#389]
**Describe the bug**
Cannot exit after scanning

**Nuclei version**
 v2.1.1

**Screenshot of the error or bug**
After scanning with nuclei, I found a card stuck on the interface and could not exit. Later, I found the FUTEX_WAIT_PRIVATE error through the strace command
strace -p 7001
strace: Process 7001 attached
futex(0x10dcdc8, FUTEX_WAIT_PRIVATE, 0, NULL

**Comment by bauthard** [comment]
@al0ne Can you share more details on this -

a) what commands you executed and b) error trace log as attachments?

**Comment by al0ne** [comment]
1.command : nuclei -c 25 -l urls.txt -t nuclei-templates -severity critical,high,medium,low -o results.txt -pbar -timeout 3
2.I installed it from this connection https://github.com/projectdiscovery/nuclei/releases/download/v2.1.1/nuclei_2.1.1_linux_amd64.tar.gz
3.Ubuntu 18.04.5 LTS     Linux vultr.guest 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bauthard** [comment]
@al0ne, we have some known issues with progress bar `-pbar` and we are looking for possible ways to resolve this, Can you try running without using `-pbar` and see how it goes?
