### ISSUE TITLE
[issue] Proxy via localhost

### ISSUE THREAD

**Issue by DeC1pher** [projectdiscovery/nuclei#394]
Hello,

I found a really strange issue with the proxy url in the current nuclei `v2.2.0` Version.
If I provide for example `--proxy-url http://localhost:8080` and parallel `tcpdump -i lo port 8080` I see only about every 10th request passing to the proxy.
Using `--proxy-url http://127.0.0.1:8080` I have no issues.
I tested it on multiple devices with same results.
This will skip a lot of tests and I think if ppl. use localhost instead of the ip (which is also defined correct in the `hosts`) some of them wont even recognize.
Just wanted to let you know.

Cheers

**Comment by DeC1pher** [comment]
Hello,

looks like a problem on my side.
I updated with `GO111MODULE=on` and now it looks good!

Sorry

Cheers,
DeC1pher

**Comment by DeC1pher** [comment]
Hello @bauthard,

now I have the exact same issue with `v2.2.0` may you can have a look again at the issue?

Thanks!

**Comment by bauthard** [comment]
Hi @DeC1pher, 

You need to use `http://127.0.0.1` instead of `localhost`, additionally we have added support to the local host file which will resolve the `localhost` as well in the `dev` branch, so for now will suggest using  `http://127.0.0.1`

**Comment by DeC1pher** [comment]
Hello @bauthard 

thanks for you quick response 👍  and the future "fix".

Have a nice day
