### ISSUE TITLE
[feature] - Allow custom resolvers for DNS templates

### ISSUE THREAD

**Issue by m0chan** [projectdiscovery/nuclei#395]
**Is your feature request related to a problem? Please describe.**

Nuclei is awesome, I basically use it for all my DNS-Based bugs but I commonly encounter a case where I need to use a different single resolver or a list of resolvers. It would be cool if there was 2 flags applied

-r (Specify Resolver). for ex;

- echo github.io |  nuclei -t ~/template.yaml -r 8.8.8.8
- echo github.io |  nuclei -t ~/template.yaml -r 8.8.4.4

-rL (Specify List of Resolver). for ex;

- echo github.io |  nuclei -t ~/template.yaml -r resolvers.txt

Where resolvers.txt, contains 

- 8.8.8.8
- 8.8.4.4
- 1.0.0.1

Any nuclei can try resolve the domain against each resolver within the list, as sometimes you may find differences between resolvers.

**Comment by bauthard** [comment]
Thank you for creating this issue and making this feature request @m0chan

**Comment by Ice3man543** [comment]
This is implemented in dev branch. To keep things simple, only file support for custom resolvers has been added, so you can use `-r` flag to override resolvers used by nuclei with custom ones from a file!
