### ISSUE TITLE
Add new variable in network template that contains actual `ip|host:port`

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#3954]
### Nuclei version:
`main|dev`

### Current Behavior:
The actual behavior of the `Hostname` and `Host` variables is ambiguous and confusing (ref: https://github.com/projectdiscovery/nuclei/issues/3902) and inconsistent across protocols. The most common use case is the template writer expecting to provide only a variable without worrying too much about the format (`ip`, `ip:port`, `domain`, `domain:port`, etc).

### Expected Behavior:
Define a simple `IpPort` variable (or similar name) that points to the actual `ip|domain:port` without ambiguity and "deprecate" or disincentive `Hostname` and `Host` usage, unless necessary.

### Steps To Reproduce:
```console
$ cat test.txt 
192.168.5.1:443
192.168.1.1
$ cat template.yaml
id: test

info:
  name: test
  author: test
  severity: info
  tags: test

tcp:
    host:
      - "{{Hostname}}"
      - "{{Host}}:443"
    matchers:
      - type: dsl
        dsl:
          - "jarm(Hostname) == 'xxxxxx'"
$ cat test.txt | go run . -t test.yaml 
...
[WRN] [test] address 192.168.1.1: missing port in address
[WRN] [test] address 192.168.1.1: missing port in address

**Comment by b7acksec** [comment]
Does this issue been resolved?

**Comment by Mzack9999** [comment]
@b7acksec it should be available in the `dev` branch within a couple of weeks

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/nuclei/pull/4283#issuecomment-1936945260
