### ISSUE TITLE
Using Nuclei From Go Code,CAN NOT got Response

### ISSUE THREAD

**Issue by okadwin** [projectdiscovery/nuclei#3988]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/3982

<div type='discussions-op-text'>

<sup>Originally posted by **okadwin** July 26, 2023</sup>
i use Nuclei from go code like `v2/examples/simple.go`,outputWriter.WriteCallback only print the `event` variable(like this `fmt.Printf("\n\n\nGot Result: %+v\n", event)`),but Response is empty always.in addition,Template,TemplateURL, is empty also.

`Got Result: &{Template: TemplateURL: TemplateID:http-missing-security-headers TemplatePath:C:\Users\xxxx\nuclei-templates\http\misconfiguration\http-missing-security
-headers.yaml Info:{Name:HTTP Missing Security Headers Authors:socketz, geeknik, g4l1t0, convisoappsec, kurohost, dawid-czarnecki, forgedhallpass, jub0bs Tags:misconf
ig, headers, generic Description:This template searches for missing HTTP security headers. The impact of these missing headers can vary.
 Reference: SeverityHolder:{Severity:info} Metadata:map[max-request:1] Classification:<nil> Remediation:} MatcherName:strict-transport-security ExtractorName: Type:ht
tp Host:http://vulfocus.xxxxx.cn:58409 Path: Matched:http://vulfocus.xxxxx.cn:58409 ExtractedResults:[] Request:GET / HTTP/1.1
Host: vulfocus.xxxxx.cn:58409
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

 Response: Metadata:map[] IP:192.168.140.110 Timestamp:2023-07-26 12:54:51.750592 +0800 CST m=+16.228616501 Interaction:<nil> CURLCommand:curl -X 'GET' -d '' -H 'Acce
pt: */*' -H 'Accept-Language: en' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36' 'http://vulf
ocus.xxxxx.cn:58409' MatcherStatus:true Lines:[] FileToIndexPosition:map[]}`</div>

**Comment by Mzack9999** [comment]
@okadwin We need to be able to reproduce the problem to investigate. Could you please provide more information?
- Go code snippet/full command
- Target
- Template

Feel free to reach out to me or to pdteam on discord if you prefer to share such info directly.

Thanks!

**Comment by okadwin** [comment]
> @okadwin We need to be able to reproduce the problem to investigate. Could you please provide more information?
> 
> * Go code snippet/full command
> * Target
> * Template
> 
> Feel free to reach out to me or to pdteam on discord if you prefer to share such info directly.
> 
> Thanks!

*All GO code
```
package main

import (
	"context"
	"fmt"
	"github.com/projectdiscovery/nuclei/v2/pkg/model/types/severity"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/logrusorgru/aurora"

	"github.com/projectdiscovery/nuclei/v2/pkg/catalog/disk"
	"github.com/projectdiscovery/nuclei/v2/pkg/catalog/loader"
	"github.com/projectdiscovery/nuclei/v2/pkg/core"
	"github.com/projectdiscovery/nuclei/v2/pkg/core/inputs"
	"github.com/projectdiscovery/nuclei/v2/pkg/output"
	"github.com/projectdiscovery/nuclei/v2/pkg/parsers"
	"github.com/projectdiscovery/nuclei/v2/pkg/protocols"
	"github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/contextargs"
	"github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/hosterrorscache"
	"github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh"
	"github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/protocolinit"
	"github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/protocolstate"
	"github.com/projectdiscovery/nuclei/v2/pkg/reporting"
	"github.com/projectdiscovery/nuclei/v2/pkg/testutils"
	"github.com/projectdiscovery/nuclei/v2/pkg/types"
	"github.com/projectdiscovery/ratelimit"
)

func main() {
	cache := hosterrorscache.New(30, hosterrorscache.DefaultMaxHostsCount, nil)
	defer cache.Close()

	mockProgress := &testutils.MockProgressClient{}
	reportingClient, _ := reporting.New(&reporting.Options{}, "")
	defer reportingClient.Close()

	outputWriter := testutils.NewMockOutputWriter()
	outputWriter.WriteCallback = func(event *output.ResultEvent) {
		fmt.Printf("\n\n\nGot Result: %+v\n", event)
	}

	defaultOpts := types.DefaultOptions()
	protocolstate.Init(defaultOpts)
	protocolinit.Init(defaultOpts)

	//defaultOpts.IncludeIds = goflags.StringSlice{"cname-service", "tech-detect"}
	//defaultOpts.ExcludeTags = config.ReadIgnoreFile().Tags
	defaultOpts.Severities = severity.Severities{1, 2, 3, 4, 5, 6}

	interactOpts := interactsh.DefaultOptions(outputWriter, reportingClient, mockProgress)
	interactClient, err := interactsh.New(interactOpts)
	if err != nil {
		log.Fatalf("Could not create interact client: %s\n", err)
	}
	defer interactClient.Close()

	home, _ := os.UserHomeDir()
	catalog := disk.NewCatalog(filepath.Join(home, "nuclei-templates"))
	executerOpts := protocols.ExecutorOptions{
		Output:          outputWriter,
		Options:         defaultOpts,
		Progress:        mockProgress,
		Catalog:         catalog,
		IssuesClient:    reportingClient,
		RateLimiter:     ratelimit.New(context.Background(), 150, time.Second),
		Interactsh:      interactClient,
		HostErrorsCache: cache,
		Colorizer:       aurora.NewAurora(true),
		ResumeCfg:       types.NewResumeCfg(),
	}
	engine := core.New(defaultOpts)
	engine.SetExecuterOptions(executerOpts)

	workflowLoader, err := parsers.NewLoader(&executerOpts)
	if err != nil {
		log.Fatalf("Could not create workflow loader: %s\n", err)
	}
	executerOpts.WorkflowLoader = workflowLoader

	store, err := loader.New(loader.NewConfig(defaultOpts, catalog, executerOpts))
	if err != nil {
		log.Fatalf("Could not create loader client: %s\n", err)
	}
	store.Load()

	// flat input without probe
	inputArgs := []*contextargs.MetaInput{{Input: "http://www.okadwin.com"}}
	input := &inputs.SimpleInputProvider{Inputs: inputArgs}
	//
	//httpxOptions := httpx.DefaultOptions
	//httpxOptions.Timeout = 5 * time.Second
	//httpxClient, err := httpx.New(&httpxOptions)
	//if err != nil {
	//	log.Fatal(err)
	//}
	//
	////use httpx to probe the URL => https://scanme.sh
	//input.SetWithProbe("scanme.sh", httpxClient)

	_ = engine.Execute(store.Templates(), input)
	engine.WorkPool().Wait() // Wait for the scan to finish
}
```
*Target
I am using an intranet target, but after my testing, other targets can also be replicated, such as http://www.okadwin.com
*Template
ALL HTTP template.At first, I thought it was all templates, but later I realized that the TCP template could return normally.
*Others
After reviewing the source code, I found out why Template and TemplateURL have no content because these two parts are concatenated in the Writer, in `pkg/output/output.go`, line 213,but the Response did not perform any special processing here.

**Comment by Mzack9999** [comment]
You need to set the response read and save size, for example:
```go
defaultOpts := types.DefaultOptions()
defaultOpts.ResponseReadSize = 1024
defaultOpts.ResponseSaveSize = 1024
```

I've added these settings automatically within the linked PR
