### ISSUE TITLE
[feature] add option to manipulate of User Agent

### ISSUE THREAD

**Issue by sickwell** [projectdiscovery/nuclei#401]
**Is your feature request related to a problem? Please describe.**
A default nuclei user-agent could be easily blocked by firewall

**Describe the solution you'd like**
add function to provide string for custom user agent

**Comment by bauthard** [comment]
Hi @sickwell, 

You can use `-H` flag to provide you custom user agent, for example:- 

```
nuclei -l urls.txt -t files/ -H "User-Agent: custom-agent-goes-here"
```

**Comment by sickwell** [comment]
Thank you, i will test in in debug mode

**Comment by bauthard** [comment]
Closing, as this resovled.
