### ISSUE TITLE
Full scan Problem 

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei#4021]
Hi,
 I try to run a full scan but it is stopped at 50%
![image](https://github.com/projectdiscovery/nuclei/assets/30596083/c4579809-b273-4e4b-8842-f1778676d11d)

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.10

                projectdiscovery.io

[INF] Current nuclei version: v2.9.10 (latest)
[INF] Current nuclei-templates version: v9.6.0 (latest)
[INF] New templates added in latest release: 33
[INF] Templates loaded for current scan: 104
[INF] Targets loaded for current scan: 3777
[INF] Running httpx on input host
[INF] Found 933 URL from httpx
[INF] Templates clustered: 13 (Reduced 41547 Requests)

**Comment by mastercho** [comment]
thats is due to wrong calculation on -stats, its known issue since very beginning and will be not fixed any soon, don't worry scan is fully complete just shows wrong stats
