### ISSUE TITLE
Unable to run -headless with redhat image

### ISSUE THREAD

**Issue by lijoabraham** [projectdiscovery/nuclei#4037]
### Command to reproduce:

getting the same issue with the below nuclei version.

Nuclei version - 2.9.6
OS - Centos
Running nuclei inside EKS pod.

Error -

```
[launcher.Browser]2023/08/09 12:15:24 Downloaded: /opt/app-root/src/.cache/rod/browser/chromium-1131003

[\u001b[1;31mFTL\u001b[0m] Could not create runner: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /opt/app-root/src/.cache/rod/browser/chromium-1131003/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

```
Nuclei command : `nuclei -duc -headless  -debug  -u <url> -w /app/./app/nuclei-templates/workflow.yaml -ud /app/./app/nuclei-templates/ -rl 5 -je /app/./data/scan/scan_output.json`

What might be the issue?

**Comment by tarunKoyalwar** [comment]
@lijoabraham , nuclei internally uses [go-rod](https://github.com/go-rod/rod) project for controlling browser and if i am not wrong i think this error is related to installing chromium browser itself 

```console
$ yum install libnss3.so 
```

^ this might solve the issue but overall problem seems to be related to chromium installation
