### ISSUE TITLE
[feature] Label Requests and Specify Which Matchers Should Be Run

### ISSUE THREAD

**Issue by wdahlenburg** [projectdiscovery/nuclei#407]
**Is your feature request related to a problem? Please describe.**

There are a handful of templates that perform multi-step vulnerability checks. Currently the matchers are run on every request, which sometimes leads to false positives when the vulnerable component should display on a specific step.

An example is the security-misconfiguration/put-method-enabled.yaml template. 

1. The first request should utilize the PUT method to upload a file to the site
2. The second request should confirm that the content in the PUT request was actually uploaded to the site

A false positive will occur when the response of request 1 will include the "testing-payload" string, but the "testing-payload" string is not found in the response to request 2.

**Describe the solution you'd like**

I'd like to propose a request label or counter is optional on requests. In addition the syntax for matchers could allow for a list where the request label/counter can be matched against. All other requests will not be matched if this syntax exists, however they will still be ran.

This change would allow for template writers to only match against responses for specific requests, but still build multi-step, single templates. 

I'd recommend it be an optional feature to not require mass-updating of templates.

**Comment by bauthard** [comment]
Hi @wdahlenburg, 

Thank you for creating a detailed issue, and the good thing about this feature request is, it's already added with this PR #406 https://github.com/projectdiscovery/nuclei/pull/376, that lets you allow to write a matcher for each request, here is an [example template](https://github.com/projectdiscovery/nuclei-templates/blob/fdeff23cd40293a6f101bfa650ef477c2360ccd8/security-misconfiguration/iis-shortname.yaml) that will be merged once we create a new release for nuclei.

**Comment by wdahlenburg** [comment]
@bauthard Awesome. I hadn't noticed templates doing this. Thanks for a few references.

 I opened the above PR and will likely be opening a few similar ones.
