### ISSUE TITLE
Errors while running it on VPS 

### ISSUE THREAD

**Issue by LifeHack3r** [projectdiscovery/nuclei#41]
Works perfectly fine locally but trying it on a VPS with any template give an Error stating: **context deadline exceeded (Client.Timeout exceeded while awaiting headers)**

**Comment by Ice3man543** [comment]
Hey @LifeHack3r, can you do a `curl` request to the target site from your VPS and let me know the response. This seems like a problem on your VPS side.

**Comment by LifeHack3r** [comment]
Yes, I guess it's some issue with the host itself. Sorry for the trouble, should've checked! But also, if supposedly 5-7 of the hosts fail getting a response or ends up with some kind of error, does the whole nuclei execution stops there? or is the exception handled and the execution continues? Because trying with Verbose enabled, I just see these exceptions on the terminal and the output file is always empty. So can't make out if it didn't find anything or it just stopped abruptly. Also, pardon me if this is a complete stupid question. Just a noob trying to mess around :)

**Comment by bauthard** [comment]
Hi @LifeHack3r, 

No problem, as of now when you use `-v` flag, it will only display sites which refused to connect or are not reachable,  we are going to update this to display valid request as well. 

> if supposedly 5-7 of the hosts fail getting a response or ends up with some kind of error, does the whole nuclei execution stops there?

No, getting an error for X host doesn't stop `nuclei`, other hosts will be processed as per the entry.

**Comment by LifeHack3r** [comment]
Thanks for the update! @bauthard. Lastly, So an empty output file thus implies nothing found. Right?

**Comment by bauthard** [comment]
Yes, you are right! 

results will be displayed and write on files only if   valid match found.

**Comment by LifeHack3r** [comment]
Okay Great! Amazing work on the tool tho, thank you :D
