### ISSUE TITLE
Test "http/default-matcher-condition.yaml" failing on linux GH action

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#4103]
### Nuclei version:
`dev`

### Current Behavior:
https://github.com/projectdiscovery/nuclei/actions/runs/6009513338/job/16299100141?pr=3991

### Expected Behavior:
No error

**Comment by tarunKoyalwar** [comment]
temporarily disabled this issue due to ambiguity on why this happens
