### ISSUE TITLE
New Input option to accept request information for fuzzing

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#4131]
### Please describe your feature request:
Add new input mode (`-im, -input-mode`) option that would allow the user to specify input mode/format of given input  file (using `-l` which is expected to contain full http request information to fuzz; this option will be used to read file in correct format and construct a raw http request to be used by template to apply/perform various fuzzing operations. 

**Possible Inputs:**
```console
   -im, -input-mode       input file mode (jsonl,openai,burp,swagger,postman) (default jsonl)
```
>[!NOTE]
> existing input file option `-l -list string` will be used to specify input file

**Possible modes of input:**

```[tasklist]
- [x] JSONL Output (proxify, katana, httpx)
- [x] Burp XML Output File
- [x] OpenAPI Definition
- [x] Swagger Definition
- [x] ~Postman Definition~(temporarily removed)
- [x] Yaml Multidoc Output ( proxify)
```

### Describe the use case of this feature:
This feature would present more flexibility to the user for selecting the origin of data to be passed to the fuzzing parameters. 

For example:
```console
nuclei -l proxy.json -t fuzz_templates
nuclei -l burp_history.xml -im burp -t fuzz_templates
```

**Note:**
> This feature is a **prerequisite** for fuzzing **header/body** parameters.

**Comment by Kazzx1** [comment]
good
