### ISSUE TITLE
Nuclei does not report -stats until end of scan

### ISSUE THREAD

**Issue by mikedesu** [projectdiscovery/nuclei#4172]
### Nuclei version:

[INF] Nuclei Engine Version: v2.9.15

### Current Behavior:

Running nuclei with -stats does not report stats until the end of the scan

### Expected Behavior:

I expect nuclei to display stats every 5 seconds when the -stats flag is used, as that was the default behavior for the flag.

### Steps To Reproduce:

Run nuclei as normal with the -stats flag.
Observe that nuclei does not return stats on current scan until the end of the scan.

### Anything else:

I made an asciinema screen cast demoing the problem:

https://asciinema.org/a/qplva0KLLaPV44PJBbZzTRJvi

**Comment by MetzinAround** [comment]
Just want to check that the default length of time for a stat to appear wasn't changed in the nuclei config file. Likely not, but figured I'd ask.

**Comment by MetzinAround** [comment]
Stats is behaving correctly for my run. @ehsandeep any idea what could cause this?

**Comment by b7acksec** [comment]
@mikedesu I think you have a small service (project), which is why it's working incorrectly. Your analysis is completed in less than 2 minutes. Maybe timeout working like that.

**Comment by mikedesu** [comment]
Weird. Somehow, today's run is working correctly :X Same version, too

@MetzinAround yeah i did not change the nuclei config file

closing since the problem was likely on my end, sorry everyone! if i can reproduce again i will open a new report
