### ISSUE TITLE
Problem installing nuclei on ubuntu 

### ISSUE THREAD

**Issue by 0x4hm3d0x** [projectdiscovery/nuclei#4179]
Certainly, here's the GitHub issue for Nuclei with the provided information:

---

**Issue Description**

**Environment Information**

- Operating System: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1036-aws x86_64)
- Go Version: go1.18.1 linux/amd64
- Nuclei Version: Latest (installed via `go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest`)

**Steps to Reproduce**

1. I attempted to install the latest version of Nuclei using the following command:
   ```
   go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
   ```

**Expected Behavior**

I expected Nuclei to be installed successfully without any errors.

**Actual Behavior**

I encountered the following error during the installation process:
```
package crypto/ecdh is not in GOROOT (/usr/lib/go-1.18/src/crypto/ecdh)
```

**Additional Information**

- I'm running Ubuntu 22.04.3 LTS as my operating system.
- My Go version is 1.18.1, installed on a 64-bit architecture.
- I've ensured that my GOPATH and GOROOT environment variables are correctly configured.
sudo nano ~/.bashrc
export GOPATH=/root/go
source ~/.bashrc
echo $GOPATH
/root/go
root@ip-10-0-197-139:~/go#

- I've attempted to resolve the issue by running `go clean -modcache` and ensuring my Go environment is up to date.

Please let me know if you need any further information or if there are specific logs or details you'd like me to provide. Thank you for your assistance.

---.

**Comment by vj0shii** [comment]
I am also facing the same, when I tried it a few days back it was working fine.
But today when I tried I was getting this error.

**Comment by MetzinAround** [comment]
Hi @0x4hm3d0x and @vj0shii 

Nuclei requires go 1.20 to run. If you upgrade (which for go means delete and reinstall) nuclei should work fine. :)

**Comment by matejsmycka** [comment]
> Hi @0x4hm3d0x and @vj0shii
> 
> Nuclei requires go 1.20 to run. If you upgrade (which for go means delete and reinstall) nuclei should work fine. :)

This wont work, unless you are running “Mantic”.
Stable versions have an older golang, you will have to use different package manager, or built it from source.

**Comment by chrean** [comment]
> Stable versions have an older golang, you will have to use different package manager, or built it from source.

Not really. If you clone the repo as-is, you will still get the same error even if you build it from source.
I guess the only option is to either install or build an older version of nuclei which is compatible with golang 1.19. Or, if possible, update golang, hoping it won't break anything else on the system. Not sure which way to go on a ParrotOS myself.

**Comment by tarunKoyalwar** [comment]
@0x4hm3d0x @matejsmycka , we try to use latest/stable versions as per go recommended versions https://go.dev/dl/ . current nuclei v3 requires go 1.21 to be compiled from source .
