### ISSUE TITLE
Installation issues on android termux

### ISSUE THREAD

**Issue by schooldropout1337** [projectdiscovery/nuclei#4184]
Hi PD,

Couldnt install on termux (non-rooted), even using fakeroot [proot -0].

I used 

git clone https://github.com/projectdiscovery/nuclei.git; \
cd nuclei/v2; \
make build; \
./nuclei -version;

and

go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

![termux_installation](https://github.com/projectdiscovery/nuclei/assets/134079876/783f5e65-cb5f-4b90-bd73-a9f776a03a9d)

**Comment by schooldropout1337** [comment]
Hi PD,

i decided to revert to version 2.9.6 

and remove epps-percentile from yaml in /cve folder.

command as below

find /data/data/com.termux/files/home/nuclei-templates/http/cves/*/ -type f -name '*.yaml' -exec sed -i 's/epss-percentile: [0-9.]\+//g' {} \; 


But now, another problem with JARM

![jarm](https://github.com/projectdiscovery/nuclei/assets/134079876/e1f6a4a8-b9ad-42d5-9a26-745cb21754b2)

**Comment by ehsandeep** [comment]
@schooldropout1337, it looks like you are running older version of go? what's the go output of `go version` and you can not use public templates with older versions of nuclei as they include features supported in latest version of nuclei engine.

**Comment by romanovj** [comment]
> Hi PD,
> 
> Couldnt install on termux (non-rooted), even using fakeroot [proot -0].
> 
> I used
> 
> git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2; make build; ./nuclei -version;
> 
> and
> 
> go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
> 
> ![termux_installation](https://user-images.githubusercontent.com/134079876/270147898-783f5e65-cb5f-4b90-bd73-a9f776a03a9d.jpg)

you just need to delete everything in go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go

except 
`package permissionutil`

**Comment by schooldropout1337** [comment]
> @schooldropout1337, it looks like you are running older version of go? what's the go output of `go version` and you can not use public templates with older versions of nuclei as they include features supported in latest version of nuclei engine.

The screeshot above was installation of latest one. Since it causes failure due to redeclarations of checkCurrentUserRoot & checkCurrentUserCapNetRaw in permission_other.go & permission_linux.go, i decided to reinstall version 2.9.6 (which was the previous working version on my android running on termux).

And i remove the epss-percentile with this command

find /data/data/com.termux/files/home/nuclei-templates/http/cves/*/ -type f -name '*.yaml' -exec sed -i 's/epss-percentile: [0-9.]\+//g' {} \;

to get cve's yaml working as usual.

**Comment by schooldropout1337** [comment]
> > Hi PD,
> > Couldnt install on termux (non-rooted), even using fakeroot [proot -0].
> > I used
> > git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2; make build; ./nuclei -version;
> > and
> > go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
> > ![termux_installation](https://user-images.githubusercontent.com/134079876/270147898-783f5e65-cb5f-4b90-bd73-a9f776a03a9d.jpg)
> 
> you just need to delete everything in go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go
> 
> except `package permissionutil`

Ill give it a try. We'll get back to you.

**Comment by schooldropout1337** [comment]
> > Hi PD,
> > Couldnt install on termux (non-rooted), even using fakeroot [proot -0].
> > I used
> > git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2; make build; ./nuclei -version;
> > and
> > go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
> > ![termux_installation](https://user-images.githubusercontent.com/134079876/270147898-783f5e65-cb5f-4b90-bd73-a9f776a03a9d.jpg)
> 
> you just need to delete everything in go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go
> 
> except `package permissionutil`

Did as u advise

1. Install " go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest "
2. delete everything in go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go , except `package permissionutil`
3. Make Build
4. Got new error ; lib6c not available for termux

![make_build](https://github.com/projectdiscovery/nuclei/assets/134079876/b23a9962-9107-4d5b-8c46-25af3a121756)

**Comment by romanovj** [comment]
this was enough for me 
`go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest`

**Comment by schooldropout1337** [comment]
> @schooldropout1337, it looks like you are running older version of go? what's the go output of `go version` and you can not use public templates with older versions of nuclei as they include features supported in latest version of nuclei engine.

Bro,

`go version go1.21.0 android/arm64`

`[INF] Nuclei Engine Version: v2.9.15`

Video
https://youtube.com/shorts/6qBBDyh5MPU?si=QDMp8KCYxYk498ep

Thanks PD

**Comment by martwale** [comment]
How do i delete, save and exit in step 3 of the video description.

**Comment by schooldropout1337** [comment]
> How do i delete, save and exit in step 3 of the video description.
 

vi go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go

u can use, vi,vim,nano editor in unix.
