### ISSUE TITLE
support for iteration control

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#4193]
@ehsandeep 
### In a yaml template, the requirements for overall iteration and partial iteration of multiple payloads

In a yaml template, I need to send 4 requests at the same time
1. The first two are to do some cleaning actions
2. Then send the real payload
3. The last one is to confirm and verify the payload.

I now have n payloads
But I hope that when iterating "n payloads", the 4 requests will be iterated as a whole unit.
Rather than just p.2 iterating over each request

```
id: xx
info:
  name: xxx
  author: 51pwn
  severity: critical
  description: |
    连续发送2次clear_log
    再1次aa

  tags: web,php

requests:
 
      - |+
        POST /clear_log HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
        Content-Type: application/json
        Content-Length: 303
        Accept-Language: en-US,en;q=0.9
        Connection: close

        xxxxx

      - |+
        POST /clear_log HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
        Content-Type: application/json
        Content-Length: 303
        Accept-Language: en-US,en;q=0.9
        Connection: close

        xxxxx

      - |+
        POST /xxxx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
        Content-Type: application/json
        Content-Length: 136
        Accept-Language: en-US,en;q=0.9
        Connection: close

        payload....

      - |+
        POST /check HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
        Content-Type: application/json
        Content-Length: 136
        Accept-Language: en-US,en;q=0.9
        Connection: close

        check

    attack: pitchfork
    payloads:
      viewFile:
        - "payload1"
        - "payload2"

    unsafe: true
    req-condition: true
    stop-at-first-match: true
    matchers-condition: and
    # trust-and-safety-eng 

      
```

There are several scenarios like this
1. Each time it iterates a payload, repeat all requests in sequence.
2. When iterating the payload, specify to repeat the nth request, for example, repeat the first n times before continuing with subsequent requests.
3. While iterating and specifying the nth request, other requests are concurrently sent, which is very useful in resource competition vulnerability requests.

**Comment by ehsandeep** [comment]
@hktalent, this should be supported already in v3 branch using flow control but let's wait for v3 release to revisit the issue again.

**Comment by hktalent** [comment]
Thank you very much
Also looking forward to it
Maybe I can try to compile and try it out from v3 first
