### ISSUE TITLE
Deduplication for input lists if there is one host with multiple ports as input

### ISSUE THREAD

**Issue by cmprmsd** [projectdiscovery/nuclei#4195]
If I provide a list of hostname:port-combinations as input list, nuclei should be able to deduplicate some of the checks.

Let's say there is the following list:
```
127.0.0.1:5555
127.0.0.1:5556
127.0.0.1:5557
```

Nuclei will run at least some templates one time for the specified combination (Hostname) and then another time for the host without port (Host). If the port is known e.g. 6379 for Redis, the result will appear multiple times:

```
[exposed-redis] [tcp] [high] 127.0.0.1:6379
[exposed-redis] [tcp] [high] 127.0.0.1:6379
[exposed-redis] [tcp] [high] 127.0.0.1:6379
```

Nuclei should, when it works on the `Host` (without port) first deduplicate the list. This might be an edge case but e.g. here I mass forwarded Kubernetes pod-ports to localhost and the list is quite long, which results in displaying the warning so many times as my list is long.

**Comment by meme-lord** [comment]
We posted the same issue at the same time (#4196), maybe this is a regression?

**Comment by cmprmsd** [comment]
That's somehow an amazing coincidence :rofl:

**Comment by ehsandeep** [comment]
@cmprmsd @meme-lord This resolved - https://github.com/projectdiscovery/nuclei/issues/4157; changes will be reflected as soon as https://github.com/projectdiscovery/nuclei-templates/pull/8219 get merged and next template release gets published.

**Comment by tarunKoyalwar** [comment]
@ehsandeep , the pr was merged . is this resolved ??
