### ISSUE TITLE
Upgrade nuclei error

### ISSUE THREAD

**Issue by xiaotianstudy** [projectdiscovery/nuclei#4226]
executable nuclei not found in release asset got: [:RUNTIME] failed to read response body <- context deadline exceeded (Client.Timeout or context cancellation while reading body)
![2294981bd98c24971ad75e5cb7f3566](https://github.com/projectdiscovery/nuclei/assets/125735128/56fd3135-b967-4294-9e82-65eabc1e552b)

**Comment by xiaotianstudy** [comment]
@tarunKoyalwar It came up a couple times, just retried it and it worked, thanks!

**Comment by Arrnitage** [comment]
> @xiaotianstudy this might be a temporary network connectivity issue . can you confirm if this happens everytime or it was a one time problem . we have 30 sec timeout set for http client https://github.com/projectdiscovery/utils/blob/9d964b5d6215c52b0deeaf05be855e555c9ccc37/update/update.go#L33

 This problem occurs when the download speed is too slow, whether the timeout can be extended appropriately
