### ISSUE TITLE
Automatically generate test files

### ISSUE THREAD

**Issue by enomothem** [projectdiscovery/nuclei#4234]
### Nuclei version: 
 v2.9.15 latest and Windows10 & 11  OS

### Current Behavior: 
The automatically generated test files are in the user directory

### Expected Behavior: 
No such files are generated

### Steps To Reproduce: 

Example:
1. Run `nuclei.exe`
2. Check for the presence of a test file in the user directory
3. C:/User/xxx/
![image](https://github.com/projectdiscovery/nuclei/assets/45089051/0bfdfe88-3778-4378-94b4-81394d08ab82)

**Comment by tarunKoyalwar** [comment]
@enomothem are you still able reproduce this in latest nuclei version ?

**Comment by enomothem** [comment]
I can't reproduce it in version 3.0.3, it seems to be fixed
