### ISSUE TITLE
Targets where host exists but http connection fails

### ISSUE THREAD

**Issue by XTeam-Wing** [projectdiscovery/nuclei#4264]
### Nuclei version:
3.0
### Current Behavior:

Continuing to do invalid scanning when http connection fails
### Expected Behavior:
When http does not respond multiple times. Exit scanning

### Steps To Reproduce:
1. chose a taget,Targets where host exists but http connection fails
2.  read tcp xxxx->taget ip:5555: read: connection reset by peer
nuclei -u http://target:5555 -stats -timeout 5

**Comment by Mzack9999** [comment]
@XTeam-Wing nuclei automatically stops testing `host:port` combinations after the number of failures reaches the host-errors threshold (I think it should be 30). You can lower it, if you want to decrease the error verbosity rate.

**Comment by dogancanbakir** [comment]
Yes, it is 30. `   -mhe, -max-host-error int           max errors for a host before skipping from scan (default 30)`
