### ISSUE TITLE
Cant update to latest version

### ISSUE THREAD

**Issue by mysk4r** [projectdiscovery/nuclei#4267]
Hi,

I cant update using nuclei -update 

2.09 MiB / 23.74 MiB [----->___________________________________________________] 8.80% 74.35 KiB p/s
[updater] executable nuclei not found in release asset `131386944` got: [:RUNTIME] failed to read response body <- context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by mysk4r** [comment]
> 

> __

**Comment by wzl-yes** [comment]
1
