### ISSUE TITLE
Template Directory Not Work 

### ISSUE THREAD

**Issue by watskenet** [projectdiscovery/nuclei#4272]
hi
after update my nuclei show error ` **Could not find template './NewNucleiTemplate/': could not find template file: no such path found: ./NewNucleiTemplate/**` with -t
i used in preview version

### Anything else:

```[tasklist]
### Tasks
```

**Comment by ehsandeep** [comment]
@watskenet thanks! this is being tracked here - https://github.com/projectdiscovery/nuclei/issues/4258
