### ISSUE TITLE
Could not able to install the nuclei with the latest go version also with the old version of go.

### ISSUE THREAD

**Issue by muthumohanprasath** [projectdiscovery/nuclei#4276]
I tried to install the nuclei on the my ubuntu 20.04 lts.

I am facing some error. 

The nuclei says,. It needs the latest version of go to install the nuclei.

I installed the latest version of go tool as well.

But still i am getting the below issues.

To know more about the issue. Please check the attached screenshot.

### Steps To Reproduce:
![image](https://github.com/projectdiscovery/nuclei/assets/38808999/ebad83be-3d3e-4515-8b37-99fbe075d800)

### Anything else:
requesting you to let me know the solution for this asap.

Thanks & Regards,

Muthu.

**Comment by Mzack9999** [comment]
@muthumohanprasath can you post the output of `go env` - we need some more info as the go version and the CPU architecture to be able to reproduce the issue. Thanks
