### ISSUE TITLE
/home/user/go/pkg/mod/github.com/refraction-networking/utls@v1.5.4/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.18/src/crypto/ecdh)

### ISSUE THREAD

**Issue by sonaxpro** [projectdiscovery/nuclei#4286]
hi, 
I try install your App, but I receive the error: 

> /home/user/go/pkg/mod/github.com/refraction-networking/utls@v1.5.4/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.18/src/crypto/ecdh)

how can I this App to install?

**Comment by moolakarapasanga** [comment]
I am also got the same error after update the go language latest version.

**Comment by MetzinAround** [comment]
@sonaxpro I think you have too low a version of Go installed. That says it's go 1.18 and nuclei needs at least 1.21 to run. Please remove current go (unless you need it for something else) and then reinstall to get the latest version. 

@moolakarapasanga You may have multiple installations of go on your machine, which are conflicting with each other. Unless you need multiple versions, the best thing to do is delete go (https://gist.github.com/nikhita/432436d570b89cab172dcf2894465753) and reinstall the latest version. If that doesn't help, or you've already done that, let me know and I can see how else I can help.

**Comment by Mzack9999** [comment]
The issue is related to deprecated go. Please update to go 1.21 following the instructions at https://go.dev/doc/install

Also please while reporting an issue, provide all the information requested in the template, we are unable to investigate an issue that cannot be reproduced. Thanks!
