### ISSUE TITLE
Add Follow Redirect Flag

### ISSUE THREAD

**Issue by m0chan** [projectdiscovery/nuclei#429]
**Is your feature request related to a problem? Please describe.**
Nuclei does not follow redirects or have any way to tell it too :( 

**Describe the solution you'd like**

`-follow-redirect` Flag to follow redirect and match in that response also.

**Comment by geeknik** [comment]
I believe you can set redirects via template: https://nuclei.projectdiscovery.io/templating-guide/#redirects

**Comment by m0chan** [comment]
Awesome! You're right I didn't notice this.

Thanks
