### ISSUE TITLE
No RATE-LIMIT option to set the delay for per host

### ISSUE THREAD

**Issue by gateswizard** [projectdiscovery/nuclei#4291]
For example, I want to brute force 401 authentication,
I use "-w" to load just one workflow and "-l" parameter to load a url.txt containing 100 hosts. Due to waf or some security policies, frequent login attempts will be denied and the brute force cracking of this host will be aborted by the nuclei. I want to login attempts each host every 10s or every x seconds.  (Of course, I'm going to set "-bs, -bulk-size int" to 100 in order to check the host in parallel.)

Is there a like RATE-LIMIT option or how to do it for this purpose?

**Comment by MetzinAround** [comment]
`-rlm, -rate-limit-minute int       maximum number of requests to send per minute` set to 6 should cover 1 per 10 seconds.

**Comment by gateswizard** [comment]
> `-rlm, -rate-limit-minute int maximum number of requests to send per minute` set to 6 should cover 1 per 10 seconds.

But I also want to keep 100 hosts parallel, which means there should be 6*100 requests per minute, which is obviously not what I expected if I set "-rlm, -rate-limit-minute int" to 6 or 600.

**Comment by ehsandeep** [comment]
@gateswizard rate limit per host is not supported; you can follow https://github.com/projectdiscovery/nuclei/issues/3547 for future updates on the same.
