### ISSUE TITLE
Only display UnsignedWarning in verbose mode

### ISSUE THREAD

**Issue by clonsdale-canva** [projectdiscovery/nuclei#4294]
https://github.com/projectdiscovery/nuclei/blob/cc46f57d4d13f5e70e3539218021fde38a20ca5e/internal/runner/runner.go#L676C1-L676C1

This warning pollutes stdout causing an error when parsing results as JSON. This warning should either be only shown in verbose mode, or an additional flag is introduced to opt-out of signing functionality

**Comment by ehsandeep** [comment]
@clonsdale-canva you can disable unsigned template warning using the env variable `HIDE_TEMPLATE_SIG_WARNING=true`, ref - https://docs.nuclei.sh/template-guide/code#template-digest-and-signing-keys

**Comment by clonsdale-canva** [comment]
Perfect, works great! Thanks so much.
