### ISSUE TITLE
nuclei ignores -proxy flag for updates

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#4303]
### Nuclei version:
2.9.15, 3.0.2

### Current Behavior:
nuclei ignores the `-proxy` flag when used with `-up` or `-ut`.

### Expected Behavior:
nuclei should use the proxy.

### Steps To Reproduce:
`nuclei -proxy http://localhost:3128 -up`
or
`nuclei -proxy http://localhost:3128 -ut`

**Comment by tarunKoyalwar** [comment]
@geeknik , nuclei uses default http client to update itself and nuclei-templates . and in default http client self-signed certificates are not allowed while establishing https connection  for a good reason. hence even if we proxy it , it will error out but yeah you can still do it using env variable `HTTPS_PROXY`

```console
$ HTTPS_PROXY=127.0.0.1:8888 ./nuclei -up  -v                                        1 ↵

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.2

		projectdiscovery.io

[updater] failed to download latest release got [:RUNTIME] Get "https://api.github.com/repos/projectdiscovery/nuclei/releases/latest": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
