### ISSUE TITLE
unrecognized import path "aead.dev/minisign": reading https://aead.dev/minisign?go-get=1: 404 Not Found

### ISSUE THREAD

**Issue by Draztick** [projectdiscovery/nuclei#4348]
### Nuclei Version
v3, but currently uninstalled as this is breaking during the install process when downloading the minisign package. Trying to build using multiple methods (see the Reproduction Steps).

### Current Behavior:
Currently, I get an error on the build regardless of method stating that the minisign download fails because of a 404 Not Found status code.

### Expected Behavior:
Expect it to download the package for install.

### Reproduction Steps

Occurs in both of the following methods:

```bash
go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
```

AND 

```bash
git clone https://github.com/projectdiscovery/nuclei.git
cd ./nuclei/cmd/nuclei
go build .
```
I can access the base domain aead.dev domain, but the link for minisign on the page has apparently changed to  https://pkg.go.dev/aead.dev/minisign.

### Anything else:
https://pkg.go.dev/aead.dev/minisign

![image](https://github.com/projectdiscovery/nuclei/assets/1468321/9199cacc-6c88-4b16-a90c-f2e1526eecc3)

### Additional Details
OS: Fedora 38
golang version: 1.20.10

**Comment by softDev-os** [comment]
yo tambien tengo el mismo tipo de problema cual es el tipo de solucion que le diste

**Comment by softDev-os** [comment]
https://github.com/gogf/gf/issues/3197#issuecomment-1855216599
