### ISSUE TITLE
No Documentation on .nuclei-config.json

### ISSUE THREAD

**Issue by abrahack** [projectdiscovery/nuclei#436]
**Describe the bug**
In your docs you showed the file `.nuclei-config.json` but you failed to explain what this file looks like or what it should be used for .
So please give out a docs for this and maybe a flag so that we can pic the dir it should read it from .

**Nuclei version**
2.1.0

**Comment by bauthard** [comment]
Hi @abrahack, 

`.nuclei-config.json` is not meant to used by the users, currently, it is only used to store the installed template version and used by nuclei to update templates by comparing the installed version number.

btw, you are running older version of nuclei, the latest one is `2.2.0`
