### ISSUE TITLE
[feature] Don't warn that `nuclei-templates` are not installed if using -t on the command line

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#438]
**Is your feature request related to a problem? Please describe.**
I use Git to clone the nuclei templates directory and I cherry pick what I'm using with the `-t` command line flag.  As a result, I get a message that says `[WRN] nuclei-templates are not installed, use update-templates flag.`

**Describe the solution you'd like**
I don't believe it's necessary to warn the user about this if they are using user-defined templates via the `-t` command line flag.

**Comment by team-projectdiscovery** [comment]
Hi @geeknik,

You can already achieve this simply by doing either of one:- 

- Run `update-templates` once, and you can still use the custom or local templates as per your choice.
- Update `~/.nuclei-config.json` to include the latest version (if you don't prefer to download templates)
- Using `silent` flag.

Closing as this is already possible and not required code changes.

**Comment by geeknik** [comment]
Thank you. We already decided it would be more beneficial for us to just remove the update code altogether. 👍🏻
