### ISSUE TITLE
set IP to be used to scan with SDK. 

### ISSUE THREAD

**Issue by MetzinAround** [projectdiscovery/nuclei#4409]
From Discord, user Isec Vincent
Good morning guys.   One question: So far it looks like that with the sdk its currently not possible to set the IP that will be used to scan, when creating a new instance of the nuclei engine with NewNucleiEngine . Is there a workaround for this ? should i open a RFE for this to be added as an option ? thanks

**Comment by vince-isec** [comment]
Would be great if one could setup the scanning interface when creating an instance of the nuclei engine 

the option "Interface" is listed here:

https://github.com/projectdiscovery/nuclei/blob/c67473a85c01f125b3fe62093a60fde944935891/pkg/types/types.go#L272

but there is no way currently to set it up through the nuclei package:

https://github.com/projectdiscovery/nuclei/blob/dev/lib/config.go

as "options" field is not exported, the field cant be set directlyt

https://github.com/projectdiscovery/nuclei/blob/c67473a85c01f125b3fe62093a60fde944935891/lib/sdk.go#L76C22-L76C22


it could probably be added in the "NetworkConfig" type here: 

https://github.com/projectdiscovery/nuclei/blob/c67473a85c01f125b3fe62093a60fde944935891/lib/config.go#L222

and set through the method "WithNetworkConfig", here:

https://github.com/projectdiscovery/nuclei/blob/c67473a85c01f125b3fe62093a60fde944935891/lib/config.go#L232
