### ISSUE TITLE
nuclei fuzz payload set error

### ISSUE THREAD

**Issue by yinqinghe** [projectdiscovery/nuclei#4475]
nuclei fuzz  payload set file name 
result:

Could not parse template \FUZZ\test.yaml: could not compile request: could not parse payloads: could not load payload file: [:RUNTIME] access to helper file \FUZZ\ad.txt denied

![image](https://github.com/projectdiscovery/nuclei/assets/70678389/62b893de-937b-403c-a7a4-e16cb222b94d)

**Comment by ehsandeep** [comment]
@yinqinghe use `-lfa` option.

```
   -lfa, -allow-local-file-access  allows file (payload) access anywhere on the system
```

**Comment by yinqinghe** [comment]
Thank you so much，Good
