### ISSUE TITLE
Conditional Severity Levels in Nuclei Templates

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#4488]
I propose the introduction of conditional severity levels in Nuclei templates, especially relevant for OOB testing scenarios. Currently, the severity level in Nuclei templates is static, but different types of OOB interactions can indicate varied levels of security implications. For instance, a simple DNS ping in OOB testing might not always suggest a security issue and could be classified as `Info`. However, interactions over HTTP or SMTP might signify a more serious issue and thus warrant a `Medium` or `High`. Implementing conditional severity would allow for a more nuanced and accurate assessment of potential security issues based on the type of OOB interaction detected.

**Comment by ehsandeep** [comment]
@geeknik indeed would be great addition, looks like we have existing ticket for it - https://github.com/projectdiscovery/nuclei/issues/3407

**Comment by geeknik** [comment]
Nice, I didn't see that. Thanks! 👍🏻
