### ISSUE TITLE
[Issue] panic: runtime error: invalid memory address or nil pointer derefrence

### ISSUE THREAD

**Issue by evanRubinsteinIT** [projectdiscovery/nuclei#450]
**Describe the bug**
Whenever I try to run Nuclei against a list of targets, I always get this memory error. (nuclei -t cves -l targetfile.txt). I have tried shortening the list of domains, and using fewer templates but the issue persists.

**Nuclei version**
v2.2.1-dev

**Screenshot of the error or bug**
![NucleiError](https://user-images.githubusercontent.com/70485623/102631671-dee19d80-4102-11eb-8cff-7ada826cc9fc.PNG)

**Comment by team-projectdiscovery** [comment]
Hi @evanRubinsteinIT 

This is already fixed here https://github.com/projectdiscovery/nuclei/commit/6c86ae060bcf40d38a30d24c7e96c108a0147dee, just git pull the code again.
