### ISSUE TITLE
Problem with PDCP API keys

### ISSUE THREAD

**Issue by webtester0** [projectdiscovery/nuclei#4525]
Do u have any problems on ur side, cuz i cant auth to PDCP with my free API keys.
I tried to rotate it, tried to wait 24 hours and nothing helps me, I always get 500 and this error:
`[ERR] Invalid API key 'a3c*********************************' got error: invalid status code: 500`

<img width="1080" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/44179403/1381ed85-5b5c-4ea4-a87e-780eaa4a80ef">

**Comment by ehsandeep** [comment]
@webtester0 thanks for flagging, this is fixed in latest version of nuclei https://github.com/projectdiscovery/nuclei/releases/tag/v3.1.3

**Comment by webtester0** [comment]
thx for fix, now it works
