### ISSUE TITLE
Nuclei scanning session got killed after few hours

### ISSUE THREAD

**Issue by Remourz** [projectdiscovery/nuclei#4546]
Hello

I'm scanning like 1k hosts with custom templates, the scanning goes fine, but after like 2 hours the scanning got killed

I just getting a message "Killed"

I'm running a decent VPS with 4GB ram and 32TB traffic

Is there a way to see logs? like see why it's killed?

**Comment by dogancanbakir** [comment]
@Remourz, Can you retry it with `-hm, -hang-monitor        enable nuclei hang monitoring` to see if you can get a stack trace?

**Comment by Remourz** [comment]
> @Remourz, Can you retry it with `-hm, -hang-monitor        enable nuclei hang monitoring` to see if you can get a stack trace?

Hello , thank you for the reply, yes i'll try that!

**Comment by Remourz** [comment]
> @Remourz, Can you retry it with `-hm, -hang-monitor enable nuclei hang monitoring` to see if you can get a stack trace?

Here is the dump of the hang:

goroutine 28 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.glob..func1(0x0?)
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:94 +0x4a
github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.(*Agent).monitorWorker(0xc000ae5a10)
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:72 +0xb0
github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.NewStackMonitor.func1()
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:44 +0x96
created by github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.NewStackMonitor in goroutine 1
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:38 +0xe5

goroutine 1 [runnable]:
github.com/projectdiscovery/utils/maps.(*SyncLockMap[...]).Has(0x3244640?, {0xc0026e5c40?, 0x38?})
	github.com/projectdiscovery/utils@v0.0.68/maps/synclock_map.go:119 +0xc2
github.com/projectdiscovery/nuclei/v3/pkg/templates.Cluster({0xc05a880000, 0x5383, 0xc05261ea08?})
	github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:80 +0x4fc
github.com/projectdiscovery/nuclei/v3/pkg/templates.ClusterTemplates({_, _, _}, {{0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {{0x0, ...}}, ...}, ...})
	github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:137 +0x8a
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).ExecuteScanWithOpts(0xc00122c480, {0xc05a880000?, 0x5383, 0x5400}, {0x3213660, 0xc000a962a0}, 0x0)
	github.com/projectdiscovery/nuclei/v3/pkg/core/execute_options.go:44 +0x176
github.com/projectdiscovery/nuclei/v3/internal/runner.(*Runner).executeTemplatesInput(0xc0011eee70, 0xc000f3f4d0, 0xc05261eeef?)
	github.com/projectdiscovery/nuclei/v3/internal/runner/runner.go:569 +0x21a
github.com/projectdiscovery/nuclei/v3/internal/runner.(*Runner).runStandardEnumeration(_, {{0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {{0x0, 0x0}}, {{0x0, ...}}, ...}, ...}, ...)
	github.com/projectdiscovery/nuclei/v3/internal/runner/runner.go:325 +0x66
github.com/projectdiscovery/nuclei/v3/internal/runner.(*Runner).RunEnumeration(0xc0011eee70)
	github.com/projectdiscovery/nuclei/v3/internal/runner/runner.go:483 +0x11f0
main.main()
	./main.go:149 +0x605

goroutine 20 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000007520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x9c
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x496

goroutine 14 [chan receive, 4 minutes]:
main.main.func3()
	./main.go:135 +0x5f
created by main.main in goroutine 1
	./main.go:134 +0x5f3

goroutine 19 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000007520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x12a
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x456

goroutine 13 [syscall, 4 minutes]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x29
os/signal.loop()
	os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	os/signal/signal.go:151 +0x1f

goroutine 37 [select]:
github.com/projectdiscovery/ratelimit.(*Limiter).run(0xc001232b70, {0x3218998, 0xc000147c70})
	github.com/projectdiscovery/ratelimit@v0.0.20/ratelimit.go:31 +0x15d
created by github.com/projectdiscovery/ratelimit.New in goroutine 1
	github.com/projectdiscovery/ratelimit@v0.0.20/ratelimit.go:102 +0x165

goroutine 38 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000ae8540)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xb6
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x196

goroutine 21 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000007520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x698
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x505

goroutine 22 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000007520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x105
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x545

goroutine 23 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0003fe2a0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xb6
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x196

goroutine 24 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000007ba0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x12a
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x456

goroutine 25 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000007ba0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x9c
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x496

goroutine 26 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000007ba0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x698
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x505

goroutine 27 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000007ba0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x105
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x545

goroutine 11 [select]:
github.com/projectdiscovery/ratelimit.(*Limiter).run(0xc000f431d0, {0x3218998, 0xc000bd05a0})
	github.com/projectdiscovery/ratelimit@v0.0.20/ratelimit.go:31 +0x15d
created by github.com/projectdiscovery/ratelimit.New in goroutine 1
	github.com/projectdiscovery/ratelimit@v0.0.20/ratelimit.go:102 +0x165

goroutine 41 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000c21260)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xb6
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x196

goroutine 42 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000103520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x12a
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x456

goroutine 43 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000103520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x9c
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x496

goroutine 44 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000103520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x698
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x505

goroutine 45 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000103520)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x105
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x545

goroutine 46 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000c21420)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xb6
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x196

goroutine 47 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000a8a1a0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x12a
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x456

goroutine 48 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000a8a1a0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x9c
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x496

goroutine 65 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000a8a1a0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x698
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x505

goroutine 66 [select, 4 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000a8a1a0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x105
created by github.com/syndtr/goleveldb/leveldb.openDB in goroutine 1
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x545




I'm not seeing what is causing the issue

**Comment by AgoraSecurity** [comment]
What version of Nuclei you are using?

**Comment by dogancanbakir** [comment]
Closing this. Tracked at https://github.com/projectdiscovery/nuclei/issues/4552.
