### ISSUE TITLE
[issue] Nuclei doesn't follow redirects when response location header value is blank

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#456]
**Describe the bug**
When we have a following kind of response when the value of `Location` is blank, nuclei failed with the error:- **302 response missing Location header**

```http
HTTP/1.1 302 Found
Date: Wed, 23 Dec 2020 09:58:33 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: 
Content-Length: 4
Connection: close
Content-Type: text/html; charset=UTF-8
```

**Nuclei version**
2.2.0

**Reference**
https://github.com/projectdiscovery/nuclei-templates/pull/695#issue-544404856

**Comment by Ice3man543** [comment]
This is go http client's default behavior, so closing this issue for now as it is not possible (AFAIK) to implement this without forking net/http. If there's a way, we will reopen and add this functionality.
