### ISSUE TITLE
Pressing Ctrl-C during a nuclei run, while allowing you to resume, doesn't store the results found so far

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei#4607]
### Nuclei version:
3.1.4

### Current Behavior:
Pressing Ctrl-C mid-scan results in a resume file, but the partial results of the scan are not stored, i.e. `--json-export` outcome is empty

### Expected Behavior:
Pressing Ctrl-C mid-scan should result both in a resume file being created, and the `--json-export` directive being followed and a partial scan result being saved

### Steps To Reproduce:
`nuclei -target example.com --json-export some-report.json`

Wait for at least one 'match' / finding to get reported, press Ctrl-C

### Possible fix
The code found here:
https://github.com/projectdiscovery/nuclei/blob/3978d5dd59e667bbda3d7db5e20ce543e7110e77/cmd/nuclei/main.go#L136

Seems to lack the understanding that the `--json-export` directive has been provided

This bug is probably relevant to all `exporters` supported

**Comment by nrathaus** [comment]
it seems that `Close` that is being called here, doesn't trickle down to the `issuesClient` which holds the exporter (I hope I am reading the code correctly) - because the `issuesClient` is only closed in the `RunEnumeration` and not inside `Close` of the runner:
```
func (r *Runner) Close() {
        if r.output != nil {
                r.output.Close()
        }
        if r.projectFile != nil {
                r.projectFile.Close()
        }
        r.hmapInputProvider.Close()
        protocolinit.Close()
        if r.pprofServer != nil {
                _ = r.pprofServer.Shutdown(context.Background())
        }
        if r.rateLimiter != nil {
                r.rateLimiter.Stop()
        }
```

Maybe a fix would be to move the issuesClient close to here?

I am knowledgeable enough on the design to say that

**Comment by tarunKoyalwar** [comment]
@nrathaus , thanks for reporting issue and pointing out the issue , looks like we missed that one

**Comment by nrathaus** [comment]
Great update @ehsandeep thanks
