### ISSUE TITLE
Getting Issue while running Nuclei - Not sure how to decsribe the issue

### ISSUE THREAD

**Issue by Shri1610** [projectdiscovery/nuclei#461]
**Describe the bug**
A clear and conc
![Screenshot from 2020-12-26 18-24-21](https://user-images.githubusercontent.com/28747114/103151900-5325dc00-47a8-11eb-97fa-d4bbf69477ae.png)
ise description of what the bug is.

**Nuclei version**
Please share the version of the nuclei you are running with `nuclei -version` 

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.

**Comment by bauthard** [comment]
@Shri1610 as requested in the issue template, you need to share the `nuclei` version and used command before we review this, can you please share that?

**Comment by Shri1610** [comment]
![Screenshot from 2020-12-26 18-57-47](https://user-images.githubusercontent.com/28747114/103152254-502cea80-47ac-11eb-9021-dd25f3d0e7ec.png)

**Comment by Shri1610** [comment]
Should I try and use the 2.2.0 version

**Comment by Shri1610** [comment]
Issue Fixed. I think I was in 2.2.1-dev that was the issue, my bad
