### ISSUE TITLE
[feature] Adding matches count in stats data

### ISSUE THREAD

**Issue by nirvana-msu** [projectdiscovery/nuclei#462]
It would be great to have an option to avoid printing matches to console. There is often just too much data to print - especially when one includes request/response with `-include-rr` flag. I'm saving results to file (running Nuclei as part of a larger pipeline) so I want stdout to be fairly concise. Showing which templates are used and showing progress is great, but showing individual matches just unnecessarily bloats stdout in my case.

A somewhat related request - it would be nice to include number of found matches in the progress stats.

Thanks!

**Comment by bauthard** [comment]
Hi @nirvana-msu, 

You can simply redirect `stdout` data to `/dev/null` to avoid printing it on console, for example:-  `nuclei -t templates/ -include-rr -json -silent -o output_file -stats > /dev/null` and still track the progress of the scan, and +1 for adding match count in the stats table.
