### ISSUE TITLE
remove unneeded dependency for kerberos js module

### ISSUE THREAD

**Issue by 5amu** [projectdiscovery/nuclei#4646]
It's not really a feature, but it's a dependency issue for the kerberos js module: at the moment, the module `github.com/ropnop/gokrb5` is used to handle functionalities concerning Kerberos.

The [README.md](https://github.com/ropnop/gokrb5/blob/729746023c02496cb7f43ab64108a37aeca8d6e3/README.md) of that repo states:

> I had to export some functions in order to get my tool [kerbrute](https://github.com/ropnop/kerbrute) to work, so I forked the package. You don't want to use this probably.

But new and updated features are missing from the upstream ([jcmturner's gokrb5](https://github.com/jcmturner/gokrb5)). In the PR that will reference this issue I found a way to export the function needed by [kerbrute](https://github.com/ropnop/kerbrute) without using a fork of the module.

**Comment by olearycrew** [comment]
@Mzack9999 can you take a look at this issue and associated PR?
