### ISSUE TITLE
[issue] bug with matched part (all)

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#465]
Template:- 

```yaml
part: all
```

Expected, matcher looks for body + header. 

Currently, matcher looks for the only body.

**Comment by bauthard** [comment]
cc @dwisiswant0 ^^

**Comment by bauthard** [comment]
Fixed in https://github.com/projectdiscovery/nuclei/commit/65e14e1c9176b6b3c06ba22ea289b631bfdde300

**Comment by dwisiswant0** [comment]
That was so fast! :fire:
