### ISSUE TITLE
The -system-resolvers option does not work with HTTP requests

### ISSUE THREAD

**Issue by tovask** [projectdiscovery/nuclei#4677]
### Nuclei version:
Nuclei version: v3.1.7

### Problem:
Even when running Nuclei with the `-system-resolvers` option, the hardcoded external servers are used to resolve the domain names for a HTTP request, instead of relying on the system configured DNS servers.
(Providing the resolver(s) in a file with the `-resolvers` parameter does work as expected.)
I run it on Windows (also tried under WSL (Windows Subsystem for Linux) and that produced similar result).

`.\nuclei.exe -disable-update-check -target https://imdb.com -templates simple_debug_template.yaml -system-resolvers`

![image](https://github.com/projectdiscovery/nuclei/assets/22732484/f6b1890a-66e8-4183-8c84-4eff6d6d18c6)

https://github.com/projectdiscovery/nuclei/issues/2967 is maybe related, but I experience the same behavior with a single template as with a workflow.

**Comment by niwamo** [comment]
I was about to open an issue when I saw this. I did some digging and found the following:

- the breaking change occurred between 3.1.5 and 3.1.6 (i.e., I built 3.1.5 --> no issue; I built 3.1.6 --> issue)
- the breaking change _may_ be the update to fastdialer between those two versions. I pulled the latest source, forced a downgrade to the fastdialer version used in v3.1.5 (fastdialer version 0.0.52), built nuclei, and had no issues with DNS resolution for HTTP requests

However, the potentially complicating factor is that downgrading fastdialer forced several other packages to be downgraded as well, including rawhttp, retryablehhtp-go, and 'utils' -- so I can't be 100% positive what fixed the issue based on the simple tests so far. It does seem certain that issue is coming from a dependency and not nuclei itself.

I'll look into it more when I have time (as I use nuclei frequently, and need it to properly use system resolution), but if someone else finds the root cause before I do, even better.

**Comment by tovask** [comment]
Hi @niwamo, thanks for your comment!

However, I experience exactly the same behavior with [v3.1.5](https://github.com/projectdiscovery/nuclei/releases/tag/v3.1.5) (i.e. it's not using the system DNS servers for HTTP requests, despite the `-system-resolvers` flag).
I used the binaries available here in the [releases](https://github.com/projectdiscovery/nuclei/releases), maybe you got different result because you built it yourself? How did you do the testing?

**Comment by niwamo** [comment]
My test process was:

```Bash
go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@v3.1.5
go/bin/nuclei -u # <host defined in /etc/hosts, but not my DNS server>
```

Interestingly, I just downloaded the 3.1.5 binary from releases after seeing your comment, and it also works with system resolution on my host.

Just to make sure we're looking into the same issue:

In the versions I consider to be "working," Nuclei does still make queries for the target hostname to external DNS servers... but `-sr` is only to "use system DNS resolving as error fallback" (from manpage) after all.

The issue that I have been having is that Nuclei did not use system resolution at all, so it was completely unable to connect to hosts defined solely in my /etc/hosts file. 

Are we looking into the same thing? Or are you trying to ensure that Nuclei does not use external resolvers whatsoever?

**Comment by tovask** [comment]
My problem is that my target hostnames are known by a _local_ DNS server (only available in the local network), so they are not specifically defined in the _hosts_ file, and can't be resolved with external DNS servers (like 1.0.0.1 or 8.8.8.8).
Basically, I would like Nuclei to rely on the system DNS resolution, and as a result, the DNS servers configured in the system (e.g.: the one comes from DHCP) should be used.
(Currently, I provide the DNS servers with the `-resolvers` parameter as a workaround, but this is just a temporary solution as the servers might change address and it needs additional configuration when moving to another system/network.)

**Comment by niwamo** [comment]
I tested your use case and actually had no problem with it. I built the latest version and tested against a host known only to my local DNS server (which is configured for my Nuclei host via DHCP), and Nuclei performed the lookup without a hitch. Viewing the queries through Wireshark, it did try Cloudflare and Google DNS first, but used my system resolver as a backup, which is good enough for me. 

I'll open a separate issue for my problem regarding hosts defined only in the /etc/hosts file. Sorry to have cluttered up your thread!

**Comment by tovask** [comment]
Okay, I found out what's the problem: the Nuclei scan timed out before fastdialer fell back to the system resolvers... increasing the `-timeout` solves the issue.

Thank you @niwamo for your investigation anyway!

I would suggest to have an option to use the system resolvers first, but that's a bit different discussion, so closing this now.
