### ISSUE TITLE
[feature] Expose IP information of the hostname and matched timestamp in the JSON output 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#468]
Example:- 

```json
{
  "author": "Dawid Czarnecki",
  "severity": "info",
  "description": "Checks if the HSTS is enabled by looking for Strict Transport Security response header.",
  "matched": "https://docs.hackerone.com",
  "template": "missing-hsts",
  "type": "http",
  "host": "https://docs.hackerone.com",
  "ip": "185.199.111.153",
  "timestamp":"Wed Jan 13 00:56:52 IST 2021",
  "name": "Strict Tranposrt Security Not Enforced"
}
```

When `IP` is not applicable, in case of DNS template or when IP used to scan the HTTP/NETWORK template, the IP field will become `null`.

Progress:- 

- [x] timestamp
- [x] ip

**Comment by p-l-** [comment]
Hi!

What would also be nice is to have a way to force a specific IP address for a target. [ZGrab2 has implemented this](https://github.com/zmap/zgrab2#input-format) by letting the user specifying both a name and an IP address for a target.

This could be useful, for example, when different servers serve a same name (but behave differently, maybe one is the main server and has more files, or one server has been updated and another has a vulnerable version of a tool, etc.), or when we can reach an IP "behind" Cloudflare-like services.

What do you think? (i.e., would it be 1. useful, and 2. easy to implement?)

**Comment by bauthard** [comment]
Hi @p-l-, 

We updated the issue to include matched timestamp as well, about your 2nd suggestion, we already implemented something similar in the dev branch https://github.com/projectdiscovery/nuclei/commit/4f5fb2baed898a17131147cba23582343d88e928 here, to feed a list with `hostname,ip` format, where that specific IP will be used to connect the hostname, the most common use case for detecting the `vhost` and same as what you suggested here, we are testing it for now, most probably will be pushed to master in the next release of nuclei.

**Comment by p-l-** [comment]
HI @bauthard,

That's awesome! Thanks a lot.

**Comment by p-l-** [comment]
Thanks!
