### ISSUE TITLE
Nuclei (v3.1.6 and up) does not resolve hosts defined in /etc/hosts

### ISSUE THREAD

**Issue by niwamo** [projectdiscovery/nuclei#4681]
### Nuclei version: 

v3.1.6 and higher (including the latest)

### Current Behavior:

Hosts defined in /etc/hosts are not resolved by Nuclei, leading to failed scans. `-debug` messages indicate no route to host.

### Expected Behavior:

Nuclei resolves hosts defined in /etc/hosts

### Steps To Reproduce:

Attempt a Nuclei scan for a host defined only in /etc/hosts.

### Anything else:

Testing so far:
- Determined which version the issue first occurred in by iteratively building and testing
  - e.g., `go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@v3.1.5`
- Determined breaking change occurred between 3.1.5 and 3.1.6
  - e.g., 3.1.5 correctly resolves locally-defined hosts, but 3.1.6 does not
- Reviewed changelog for 3.1.6
- Built the latest version (3.1.7) from source _after_ downgrading fastdialer to version 0.0.52 (the version used in v3.1.5 of Nuclei)
  - This led to the automatic downgrade of rawhttp to 0.1.34, retryablehttp-go to 1.0.43, and utils to 0.0.73
  - The latest build with downgraded dependencies successfully resolved hosts defined in /etc/hosts

**Comment by tarunKoyalwar** [comment]
@niwamo , there was a minor issue with recent change made in fastdialer (while fixing memory leak) which caused this but it is now fixed in linked PR and will be included in next nuclei release
