### ISSUE TITLE
support passive mode(OfflineHTTP) and other param when using nulcei as library

### ISSUE THREAD

**Issue by CyL0NG** [projectdiscovery/nuclei#4683]
when using nuclei as library, it does not support to set offline http and other param.

code support offline http mode may like this.
```golang
func WithPassiveMode() NucleiSDKOptions {
	return func(e *NucleiEngine) error {
                e.opts.OfflineHTTP = true
		return nil
	}
}
```

or may add such code to support all param
```golang
type SetOptionsFunc func (opts *types.Options) error

func SetOptions(setFunc SetOptionsFunc) NucleiSDKOptions {
	return func(e *NucleiEngine) error {
		return setFunc(e.opts)
	}
}
```

**Comment by dogancanbakir** [comment]
Thanks for opening the issue. I do agree that introducing a generic function for setting options can make things easier but, at the same time, unclean in terms of API. Therefore, by naming things, we create this pattern, which is often used to create more readable and maintainable code, especially when dealing with functions or methods that might require many optional parameters.
