### ISSUE TITLE
Nuclei as a webservice with a queue system

### ISSUE THREAD

**Issue by lucmichalski** [projectdiscovery/nuclei#469]
Hi guys,

Hope you are all well and happy new year 2021 !

It would be awesome to create a webservice mode for nuclei with a system of queue and throttling the number of audits per second.

How to implement that ?
- Adding gin-gonic for the server
- Redis for the queue

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by ehsandeep** [comment]
@lucmichalski we started to work on this and tracking at https://github.com/projectdiscovery/nuclei/issues/1275 https://github.com/projectdiscovery/nuclei/issues/1276
