### ISSUE TITLE
Docker image [no templates provided for scan]

### ISSUE THREAD

**Issue by IGNFIfortrue** [projectdiscovery/nuclei#4698]
Hello Nuclei teams,

I installed docker image, version 3.1.7, but it shows no templates, I am currently testing it so I simply use 'nuclei -u',
![image](https://github.com/projectdiscovery/nuclei/assets/122549520/f284f05d-d723-4de4-98db-db247584005f)

could you please help me check this issue?
![image](https://github.com/projectdiscovery/nuclei/assets/122549520/229b4bd1-1cd7-49fd-85f6-2ebf85e92322)
I also try the command suggested on your documents, doesn't work either :(

**Comment by dogancanbakir** [comment]
Can you please run the following command and share the output with us:
`docker run --rm projectdiscovery/nuclei -u scanme.sh`

**Comment by IGNFIfortrue** [comment]
$ docker run --rm projectdiscovery/nuclei -u scanme.sh

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.7

		projectdiscovery.io

[INF] nuclei-templates are not installed, installing...
[INF] Successfully installed nuclei-templates at /root/nuclei-templates
[WRN] Found 1 templates with runtime error (use -validate flag for further examination)
[INF] Current nuclei version: v3.1.7 (latest)
[INF] Current nuclei-templates version: v9.7.4 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 6
[INF] Templates loaded for current scan: 7426
[INF] Executing 7447 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 1265 (Reduced 1231 Requests)
[nameserver-fingerprint] [dns] [info] scanme.sh ["ns69.domaincontrol.com.","ns70.domaincontrol.com."]
[caa-fingerprint] [dns] [info] scanme.sh
[INF] Using Interactsh Server: oast.site
[http-missing-security-headers:x-permitted-cross-domain-policies] [http] [info] https://scanme.sh
[http-missing-security-headers:cross-origin-opener-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:x-frame-options] [http] [info] https://scanme.sh
[http-missing-security-headers:x-content-type-options] [http] [info] https://scanme.sh
[http-missing-security-headers:permissions-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:referrer-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:clear-site-data] [http] [info] https://scanme.sh
[http-missing-security-headers:cross-origin-embedder-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:cross-origin-resource-policy] [http] [info] https://scanme.sh
[http-missing-security-headers:strict-transport-security] [http] [info] https://scanme.sh
[http-missing-security-headers:content-security-policy] [http] [info] https://scanme.sh
[rdap-whois] [http] [info] https://gateway.zscaler.net:443/auT?origurl=https%3A%2F%2Fwww%2erdap%2enet%2fdomain%2fscanme%2esh&wexps=1&_ordtok=HQk3WVZSQbL56r5SS8HkHkt2MF&wexps=1
[waf-detect:zscaler] [http] [info] https://scanme.sh/
[ssl-issuer] [ssl] [info] scanme.sh:443 ["KUKA AG"]
[mismatched-ssl-certificate] [ssl] [low] scanme.sh:443 ["CN: scanme"]
[self-signed-ssl] [ssl] [low] scanme.sh:443
[untrusted-root-certificate] [ssl] [low] scanme.sh:443
[deprecated-tls] [ssl] [info] scanme.sh:443 ["tls10"]
[deprecated-tls] [ssl] [info] scanme.sh:443 ["tls11"]
[tls-version] [ssl] [info] scanme.sh:443 ["tls10"]
[weak-cipher-suites:tls-1.0] [ssl] [low] scanme.sh:443 ["[tls10 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA]"]
[tls-version] [ssl] [info] scanme.sh:443 ["tls11"]
[weak-cipher-suites:tls-1.1] [ssl] [low] scanme.sh:443 ["[tls11 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA]"]
[tls-version] [ssl] [info] scanme.sh:443 ["tls12"]
[tls-version] [ssl] [info] scanme.sh:443 ["tls13"]
Hello please kindly check.

**Comment by IGNFIfortrue** [comment]
Hello,
I ran the scan and found it was our firewall that leads to failure of running nuclei, now I switch to binary file, now it is working, thank you so much for your help :)
