### ISSUE TITLE
 Issue with Cloud Dashboard Displaying Empty Results

### ISSUE THREAD

**Issue by nobbieboy1337** [projectdiscovery/nuclei#4699]
**Description:**

Hi Projectdiscovery Team,

 I wanted to bring to your attention an issue I encountered while using the recent Cloud Dashboard feature. Despite completing a scan successfully, I am facing a problem where the dashboard appears empty with no data.

**Steps to Reproduce:**

1. Start a scan using the Cloud Dashboard feature.
2. Complete the scan successfully.
3. Visit the provided dashboard link.

**Issue:**
The dashboard is displaying empty results, even though the scan has been completed.

**Screenshot:**

![Screenshot 2024-01-29 212501](https://github.com/projectdiscovery/nuclei/assets/40710395/d49b3ac3-555e-4505-a0c4-d9d390460c36)

![Screenshot 2024-01-29 212518](https://github.com/projectdiscovery/nuclei/assets/40710395/366eee76-4905-4a67-9e26-6e12b8ae25a9)

I believe this issue may be hindering the proper functioning of the Cloud Dashboard feature, and I hope the provided information and screenshot will assist you in quickly identifying and resolving the problem.

Thank you for your attention to this matter.

Best regards,
Akram

**Comment by ehsandeep** [comment]
@nobbieboy1337 thank you, this should be fixed by now!
