### ISSUE TITLE
Add Proxy support

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#47]

**Comment by Ice3man543** [comment]
Fixed by #52

**Comment by Zeokat** [comment]
Tested the proxy implementation and doesn't work as expected.

When i run next commands:
```nuclei -v -nC -proxy-url "https://185.254.xxx.xxx:8080" -l sitelist.txt -t "template/*.yaml" -o results.txt```

```nuclei -v -nC -proxy-url "http://185.254.xxx.xxx:8080" -l sitelist.txt -t "template/*.yaml" -o results.txt```

Both commands runs good, but none of them is using a proxy. For the tests i'm using `https://webhook.site` service, and i always can see that my IP is doing the request.

To discar a proxy problem, i setup the same proxy on FireFox and everything works as expected and my IP is hidden behind the proxy.

Hope you can fix this.

Thanks.

**Comment by Mzack9999** [comment]
@Zeokat I just tested with mitmproxy and burp suite, it works just fine. I suggest to use http as proxy protocol, even if https should also be supported natively by golang. The final connection will happen anyway through HTTPS via the CONNECT proxy directive, if requested by the input url.

**Comment by Zeokat** [comment]
Don't know, maybe is my master branch compilation on Windows, but i tested in depth and i'm pretty sure that proxy is totally ignored, mitmproxy ignores the request also.

I can also add more proofs about this don't work, if you use the command with a proxy that doesn't exist, it still works, for example:

```nuclei -v -nC -proxy-url "http://what:8080" -l sitelist.txt -t "template/*.yaml" -o results.txt```

This still send requests but ignoring proxy totally.

**Comment by Mzack9999** [comment]
@Zeokat I think I got the issue. There was a bug in the CLI parameter not passed to the HTTP engine. This has been fixed also in #56 that will be merged shortly, I was erroneously testing on that branch, therefore you are correct here, Thanks for reporting the issue!

**Comment by Zeokat** [comment]
@Mzack9999 Tested proxy with latests commits and now seems that works as expected. In the following days i will perform some deeper tests with various proxy software available (also including tests for socks5).

Good job guys!
