### ISSUE TITLE
`-cloud-upload` not working as expected

### ISSUE THREAD

**Issue by aravindb26** [projectdiscovery/nuclei#4701]
### Nuclei version:
Current nuclei version: v3.1.7 (latest)

### Current Behavior:
when i run `nuclei -l subdomains1.txt -t $HOME/nuclei-templates/http/cves/ -cloud-upload` and few other templates like `cves` all at a time, it's getting killed automatically after running for sometime.

### Expected Behavior:
It shouldn't be killed because when i run without `-cloud-upload` i got results as expected. So it should work good even if we use `-cloud-upload`

### Steps To Reproduce:
1. Run `nuclei -l subdomains1.txt -t $HOME/nuclei-templates/http/cves/ -cloud-upload` and few other templates like `cves` all at a time.
2. It's getting killed automatically after running for sometime.

### Anything else:
No
<img width="836" alt="nuclei" src="https://github.com/projectdiscovery/nuclei/assets/89305482/3f3e9a5a-529b-4dcc-8f23-6407d1bdabc2">

**Comment by olearycrew** [comment]
Okay I think this is probably related to other resource issues we are working on:

See https://github.com/projectdiscovery/nuclei/issues/4552 and https://github.com/projectdiscovery/nuclei/pull/4680

**Comment by tarunKoyalwar** [comment]
@aravindb26 this should be fixed with new release , can you retry it and confirm ?

**Comment by tarunKoyalwar** [comment]
closing this as crash has been fixed based on discussion at https://github.com/projectdiscovery/nuclei/issues/4552

**Comment by aravindb26** [comment]
> @aravindb26 this should be fixed with new release , can you retry it and confirm ?

Sorry for the late response, thanks for the update. I will check it and let you know
