### ISSUE TITLE
[Feature] Accepting nuclei ignore as file arguments using flag

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#471]
**Is your feature request related to a problem? Please describe.**

Currently, users have no control or ways to make use of nuclei ignore files in running from a custom location (git clone), and don't have templates installed using nuclei. 

**Describe the solution you'd like**

A flag to accept a file that works same as `.nuclei-ignore`, if the custom file is provided, the default `.nuclei-ignore` file will be ingored.

This is also time to consider having config file for nuclei? as such this feature can be implemented in config file along with other options and avoid having new flag for this and different for config file in future.

**Comment by Narenjarvis** [comment]
When I run this tool I got this ERROR.
[ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory

**Comment by ehsandeep** [comment]
@Narenjarvis you need to download the templates with `nuclei -ut`

**Comment by lambardarr** [comment]
nuclei -ut

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.3

                projectdiscovery.io

[ERR] Could not update templates: could not read configuration file: EOF

**Comment by bndr567** [comment]
i try to fix this but i can't :) i use that nuclei -ut  ? how i can fix it .
