### ISSUE TITLE
[issue] random-agent flag not working (and not included in the help text)

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#474]
**Describe the bug**
The flag -random-agent does not work as described on github page. ( nuclei -random-agent) it says
'flag provided but not defined: -random-agent'
Also, the flag is not included in the help text. 

**Nuclei version**
2.2.0

**Screenshot of the error or bug**

![Screenshot from 2021-01-11 20-14-34](https://user-images.githubusercontent.com/20244863/104249184-a7d48280-5449-11eb-8068-d894f508d9e2.png)

**Comment by pdelteil** [comment]
I noticed it works on the development version.

**Comment by jsgv** [comment]
Shouldn't this still be open? 

[Guide](https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-usage) also specifies the `-ra -random-agent` flags.

Cli does not know of those flags nor does it exist in the code.

**Comment by ehsandeep** [comment]
@jsgv with https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.3, `random-agent` is enabled as default, will update docs to remove this.

**Comment by jsgv** [comment]
Ok, I see where it is done now. It is set to random if a value is not set.

I currently have an `User-Agent` value set in `$HOME/.config/nuclei/config.yaml`. 
It would be useful to set that value to a random one which currently can't be done I believe. 
Please correct me if I am wrong.

**Comment by ehsandeep** [comment]
> It would be useful to set that value to a random one which currently can't be done I believe.

If you set a custom one, it will be used as default, if you don't set any, random agents will be picked per template.

**Comment by jsgv** [comment]
> > It would be useful to set that value to a random one which currently can't be done I believe.
> 
> If you set a custom one, it will be used as default, if you don't set any, random agents will be picked per template.

Yes, I understand that. 
I meant that I have to remove the custom one from the config file for every run that I desire a random one. 
And then return the config file to the original value after the run. A little tedious as of now.

**Comment by ehsandeep** [comment]
If you wanted to maintain scans with 2 types of UA, it's better to maintain 2 config files and feed the one you want using `-config` flag.
