### ISSUE TITLE
Rate Limit Issue

### ISSUE THREAD

**Issue by jaikishantulswani** [projectdiscovery/nuclei#4777]
Not setting the rate limit as supplied when using the templates having max-request parameter, even when change the max-request: 10 it still RPS to 200+
```
cat domains | /root/Downloads/nuclei -t tmpx -bs 1 -c 1 -nc -rate-limit 64 -timeout 7 -stats -retries 2 -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20200101 Firefox/72.0"
```
`
[0:00:05] | Templates: 3 | Hosts: 1 | RPS: 302 | Matched: 0 | Errors: 0 | Requests: 1514/1919 (78%)
`
I am running template like php-backup-files.yaml
```[tasklist]
### Tasks
```

**Comment by ehsandeep** [comment]
@jaikishantulswani this was known issue in last release and already fixed in dev with https://github.com/projectdiscovery/nuclei/pull/4752

**Comment by jaikishantulswani** [comment]
@ehsandeep is there any way to control max-request value for all templates like some templates are having `max-request: 400` and some are having `max-request: 10` so what if I would like to run both on the same value.
