### ISSUE TITLE
Code in template is executed without a signature if the template is in a Workflow

### ISSUE THREAD

**Issue by gpc1996** [projectdiscovery/nuclei#4796]
### Current Behavior:
When executing a Workflow with an unsigned Template that uses the code protocol, the execution still happens (the -code tag still needs to be present).

### Expected Behavior:
Before executing a Workflow, nuclei checks if the code protocol is being used by any of the Templates and checks whether it is signed and if the signature is from a trustworthy entity, in the same way that it does when the Template is executed with the "-t" tag.

### Steps To Reproduce:
1.  Have a workflow with a template that uses the code protocol and is unsigned
2. Run 'nuclei -u "url_path" -w "workflow_path" -code'

**Comment by mastercho** [comment]
ites related to https://github.com/projectdiscovery/nuclei/issues/4792

**Comment by toufik-airane** [comment]
Dear @gpc1996,

Could you kindly contact me at security@projectdiscovery.io?

I'd like to connect with you to address this matter following our security workflow procedures.

Thank you.
