### ISSUE TITLE
Extracted variables not recognized if the next Template in the Workflow uses the code protocol

### ISSUE THREAD

**Issue by gpc1996** [projectdiscovery/nuclei#4797]
### Current Behavior:
I have a Workflow that executes 2 Templates, where the the second Template is a Subtemplate of the first. The second Template relies on an extracted variable that it gets from the response of the first Template. 
The variable is successfully extracted, and if the second Template doesn't use the code protocol, the variable is recognized and used for its call. However, if the second Template uses the code protocol, the extracted variable is not recognized, leading to a failure in the execution of the second Template.

### Expected Behavior:
I have a Workflow that executes 2 Templates, where the the second Template is a Subtemplate of the first. The second Template relies on an extracted variable that it gets from the response of the first Template. 
The variable is successfully extracted, and used by the second Template, even if the second Template uses the code protocol.

### Steps To Reproduce:

1. Create a Workflow with 2 Templates: a first Template and a second Subtemplate of the first
2. The first Template must extract a value that will be used by the second Template
3. The second template must use the code protocol
4. Run 'nuclei -u "url_path" -w "workflow_path -code -debug'
5. See that an error is in the output when executing the second Template because it doesn't recognize the variable that was extracted during the execution of the first Template

**Comment by ehsandeep** [comment]
@gpc1996 code template can read template variables using env variable, so make sure you are using it in correct way or share the template content to understand it better.

Reference - https://github.com/projectdiscovery/nuclei/discussions/4355

**Comment by gpc1996** [comment]
Absolutely, env variables can be read by a code template, but it only reads them if they aren't extracted by another template. 
I apoligize, I'm using a custom template that uses confidential information, so I can't share details of the workflow and the templates, but I'll try and show it in here:

Workflow content:

```
id: workflow_test

info:
   ...

workflows:
     - template: template_1.yaml
       subtemplates:
           - template: template_2.yaml
```

Template_1 content:

```
id: template_1

info:
  ...

requests:
    - raw:
          -  |
          ...

      matchers:
           - type: dsl
             negative: false
             dsl:
                - "status_code == 201"

      extractors:
         - type: regex
           name: ext_variable
           part: body
           group: 1
           regex:
              - '"ext_variable":"([a-zA-Z0-9-_]+)"'
```

Template_2 content:

```
id: template_2

info:
  ...

code:
    - engine:
          - py
          - python3
       source: |
           import os

           ext_variable = os.getenv('ext_variable')

           print(ext_variable)
```

This is similar to what I'm using. Template_2 doesn't read  'ext_variable'.
However, this same call but with a Template_2 that uses a similar http request to the one in Template_1 manages to use the 'ext_variable' in its requests.

**Comment by tovask** [comment]
I'm experiencing the same problem.
Even the http protocol doesn't receive the extracted variables from the previous template if there's a code protocol in that template (in a multi-protocol template).  
I also noticed that if I execute the second template's protocol(s) from [`flow`](https://docs.projectdiscovery.io/templates/protocols/flow) then the extracted variables from the first template appear as expected, so this can be a workaround until the issue is fixed.

```javascript
flow: code()
```
  
FYI, this _Shared Execution Context_ feature is implemented by https://github.com/projectdiscovery/nuclei/pull/2576 , and documented [here](https://docs.projectdiscovery.io/templates/workflows/overview#shared-execution-context).
