### ISSUE TITLE
Allow dynamic variables on headers {{BaseURL}} and {{Hostname}}

### ISSUE THREAD

**Issue by Zeokat** [projectdiscovery/nuclei#48]
Allow using dynamic variables into headers is very usefull.

For example, if i need to set a different "Referer" header to ech request, will be very nice have the option to setup into the template something like:

```
id: issue-headers

info:
  name: Example for issue
  author: Zeokat
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/test.php"
    headers:
       Referer: "{{BaseURL}}"
    matchers:
      - type: word
        words:
            - "application/json"
        part: header
```

Hope you can improve this.

Thanks.

**Comment by Ice3man543** [comment]
So PR #51 should fix it and the above template should work. Can you check and let me know!

**Comment by Zeokat** [comment]
@Ice3man543 Tested and works good. Thanks!
