### ISSUE TITLE
Hope regular expressions can incorporate forward and backward lookup functionality

### ISSUE THREAD

**Issue by Hades-p** [projectdiscovery/nuclei#4811]
When using the forward and backward search function with "?=" and "?<=" in regular expressions, an error is reported. We look forward to improving it.

**Comment by dogancanbakir** [comment]
Thank you for the report. Go's regex engine does not include lookahead support, so they cannot be used directly. However, you can simulate lookahead functionality using capture groups or adjusting your regex patterns. In Nuclei, you can use a positive regex pattern combined with `negative: true` for similar outcomes. More context at https://github.com/projectdiscovery/nuclei/issues/244
