### ISSUE TITLE
Donot Escape Extractor Output

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4841]
### Nuclei version:

main | latest 

### Current Behavior:

![image (1)](https://github.com/projectdiscovery/nuclei/assets/45962551/985b3b6d-04d3-455e-a8e7-1241d263b394)

- Earlier due to newlines in extractor output we quoted the extracted value but that affects json extracted value , since it cannot be directly used and need to manually unescaped since " are escaped
- instead we can just escape newlines instead of escaping all special chars

**Comment by ehsandeep** [comment]
quoted text in extractor impacing other cases like this:

<img width="713" alt="image" src="https://github.com/projectdiscovery/nuclei/assets/8293321/05577198-c9bb-47c8-8ca1-52e868b0ab88">
