### ISSUE TITLE
Test cases support for nuclei templates

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#485]
Unit Tests are an excellent tool for validating the quality of any piece of code.  Tests should be written in a file with suffix `<filename>_test.yaml` for a specific template ID similar to golang. This allows them to be distributed coupled with templates and can be used by the users to gain an idea of either what is the purpose of a template or validate if a template is working correctly as intended.

These tests should simulate responses like HTTP, DNS etc with support for multiple responses, etc.

**Comment by forgedhallpass** [comment]
@Ice3man543 is there anything else we'd need within this ticket, or can it be closed?

**Comment by Ice3man543** [comment]
It can be closed.
