### ISSUE TITLE
Code Protocol should implement a prerequisite DSL condition

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#4888]
### Nuclei version:
`main|dev`

### Current Behavior:
Templates containing `code` protocols logic are arbitrarily executed on the host operative system, while this may be intentional in most cases, for templates such as `privesc` ones, if the user doesn't specify correctly also tags like `linux`, all of them will be executed

### Expected Behavior:
Implement a pre-condition check for execution, for example the same that was implemented for javascript protocol:
```
pre-condition: |
      isLinux() && isAmd64()
```

**Comment by tarunKoyalwar** [comment]
+1 , we can reuse the precondition executor from `javascript` protocol and just need to export osutils as functions
