### ISSUE TITLE
Nuclei v3.2.1 // panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by ptf-laurentvetter** [projectdiscovery/nuclei#4898]
Nuclei v3.2.1 panics and crashes during a scan:

````
nuclei -nc -stats -s low -target https://www.pentestfactory.de:8443 -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.1

                projectdiscovery.io

[VER] Started metrics server at localhost:9092
[WRN] [phpsys-info] Could not execute request for https://www.pentestfactory.de:8443: [:RUNTIME] got err while executing https://www.pentestfactory.de:8443/phpsysinfo/index.php?disp=bootstrap <- context deadline exceeded
panic: assignment to entry in nil map

goroutine 103 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute.func1(0xc00a3f6af0)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:257 +0x1a6
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0xc00a3f6af0)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:436 +0x435
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).executeRequest(0xc0033590e0, 0xc008270288, 0xc008b9eaa0, 0xc0085e64e0, 0x0, 0xc0096a1b18, 0x0?)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:706 +0x3562
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc0043b6d50, 0xb}, 0xe367eb55199dc178?, 0x80?)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:409 +0x56b
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults(0xc0033590e0, 0xc008270288, 0xc0085e6510, 0xc0085e64e0, 0xc0082702a0)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:473 +0x36a
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute(0xc006afd5c0, 0xc0025b2280)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:254 +0x14a
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x22f5907?, 0x0?, 0xc006b16e40)
        github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:132 +0x1d8
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 102
        github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:108 +0x459
````

Using Nuclei v3.2.0 works flawlessly for the same target url and command line arguments.

**Comment by tarunKoyalwar** [comment]
@ptf-laurentvetter https://github.com/projectdiscovery/nuclei/issues/4895

**Comment by s1d6point7bugcrowd** [comment]
Same issue also: 

panic: assignment to entry in nil map

goroutine 39522 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute.func1(0xc16b55b1d0)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:257 +0x1a6
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0xc16b55b1d0)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:436 +0x435
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).executeRequest(0xc0b8250b40, 0xc14b67af30, 0xc16b846460, 0xc16da1fd40, 0x0, 0xc058f19b18, 0x0?)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:706 +0x3562
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc0b8202e70, 0x2a}, 0x7f9c2ea55010?, 0x29255a0?)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:409 +0x56b
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults(0xc0b8250b40, 0xc14b67af30, 0xc16da1fd70, 0xc16da1fd40, 0xc14b67af48)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:473 +0x36a
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute(0xc0b220e6c0, 0xc0f15b7040)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:254 +0x14a
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x7b8fe5?, 0x0?, 0xc11e0fc300)
        github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:132 +0x1d8
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 1198
        github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:108 +0x459

**Comment by tarunKoyalwar** [comment]
@s1d6point7bugcrowd it should be fixed with linked Pr in that issue https://github.com/projectdiscovery/nuclei/issues/4895#issuecomment-2000403434

**Comment by s1d6point7bugcrowd** [comment]
Got it. Thanks

**Comment by osamahamad** [comment]
I'm facing the same on latest version. The issue occured to me while using a list of private templates but it does not happen when using public nuclei templates.
