### ISSUE TITLE
nuclei v3.2.1 - Could not run nuclei: no templates provided for scan

### ISSUE THREAD

**Issue by skalvin** [projectdiscovery/nuclei#4899]
Hello,,

I've just update my nuclei to the version 3.2.1

there's a problem with the scanner cannot load the template

before the update i was running the scanner

cat file.txt | nuclei -t fuzz/ 

(the file fuzz contain 2 templates) it was loading fine

after the update I'm trying to run it with

cat file.txt | nuclei -t fuzz/

cat file.txt | nuclei -t fuzz/template.yml

cat file.txt | nuclei -t /home/user/waymore/fuzz/template.yml

i getting the same error

[FTL] Could not run nuclei: no templates provided for scan

![image](https://github.com/projectdiscovery/nuclei/assets/103864971/8db57074-b202-4c62-97be-855932e4b98f)

**Comment by mastercho** [comment]
they changed tags from fuzz to lot other tags

**Comment by Mzack9999** [comment]
If the template contains fuzzing functionalities, you need to use the `-fuzz` flag

**Comment by skalvin** [comment]
> If the template contains fuzzing functionalities, you need to use the `-fuzz` flag

hmm it's worked with nuclei -t fuzz/ -fuzz
