### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Dark-Aura** [projectdiscovery/nuclei#4904]
Latest version:
![image](https://github.com/projectdiscovery/nuclei/assets/65353593/8b7131f4-10c3-4990-a046-0533dd141d49)

while running the nuclei scan I'm getting this error.
![image](https://github.com/projectdiscovery/nuclei/assets/65353593/a2b091fb-d9ed-485c-9c8d-7f42fc836f83)

How to resolve this issue? and please let me know if this issue is from my side or your side.

**Comment by kolor33** [comment]
The same issue 

Using Interactsh Server: oast.me
panic: assignment to entry in nil map

goroutine 11769 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute.func1(0xc00fbf67d0)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:257 +0x1a6
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0xc00fbf67d0)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:436 +0x435

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/nuclei/issues/4895#issuecomment-2000403434

**Comment by emadshanab** [comment]
I can not run nuclei because this bug, please fix it and thanks for your kind.
Best regards.
