### ISSUE TITLE
goroutine 5294308 [running]:

### ISSUE THREAD

**Issue by zulfakar404** [projectdiscovery/nuclei#4905]
goroutine 5294308 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute.func1(0xc00f317590)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:257 +0x1a6
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0xc00f317590)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:436 +0x435
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).executeRequest(0xc000bb5680, 0xc00dd10e40, 0xc00965cf50, 0xc011b28210, 0x0, 0xc00985fb18, 0x0?)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:706 +0x3562
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc00237f920, 0x1c}, 0xc008afa680?, 0xca9560?)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:409 +0x56b
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults(0xc000bb5680, 0xc00dd10e40, 0xc011b28240, 0xc011b28210, 0xc00dd10e58)
        github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/request.go:473 +0x36a
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute(0xc008520680, 0xc00f654dc0)
        github.com/projectdiscovery/nuclei/v3/pkg/templates/cluster.go:254 +0x14a
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x106db05?, 0x0?, 0xc0018de180)
        github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:132 +0x1d8
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 5293946
        github.com/projectdiscovery/nuclei/v3/pkg/core/executors.go:108 +0x459

### Nuclei version:
v3.2.1

**Comment by dogancanbakir** [comment]
We're working on this https://github.com/projectdiscovery/nuclei/issues/4895. Closing this.
