### ISSUE TITLE
Feature request [Add more clarity to the result and remove duplicates]

### ISSUE THREAD

**Issue by reewardius** [projectdiscovery/nuclei#4908]
### Please describe your feature request:

I propose to implement (if it already exists, provide a link to documentation and examples) the following functionality in recently extended fuzzing:

1. display the vulnerable parameter, path, header, where the vulnerability was found, and HTTP method that was used to find the vulnerability, because when testing API the path can be the same, but HTTP methods are different, I would like to see the method and parameter where the problem is.
![image](https://github.com/projectdiscovery/nuclei/assets/68978608/7a8d5a2c-1428-46b5-94f1-5d1eaa18fcf5)
![image](https://github.com/projectdiscovery/nuclei/assets/68978608/c9d24d5e-669b-4909-afe0-530a3ae72f22)

2. Add flag -dedupe that will allow duplicate queries with the same parameters but different values to be removed, and then this can be used in fuzzing. How it is implemented in this toolkit:

https://github.com/ameenmaali/urldedupe
https://github.com/s0md3v/uro

![image](https://github.com/projectdiscovery/nuclei/assets/68978608/577bf17a-edca-4465-b111-541982cc7052)

Thank you!

**Comment by GeorginaReeder** [comment]
Thanks so much for this feature request @reewardius , we appreciate it!
