### ISSUE TITLE
[Feature] Add More Global Variables 

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#491]
It Is Possible To Add More Global Variables In Row Request , You Only Declared {{Hostname}} And {{BaseURL}} So It Will Be A Great If You Add More e.g. Jaeles Project Declares 

![Screenshot!UNITO-UNDERSCORE!2021-01-25!UNITO-UNDERSCORE!04-46-46](https://user-images.githubusercontent.com/54332136/105662729-2402a780-5ed9-11eb-8d92-e66ec9d364ff.png)

So You Can Add e.g.

{{Path}} It Will Help Us If We Need Do Action On Specific Endpoint e.g. Use It To Spoof Origin Endpoint By Using Header e.g. X-Original-URL: {{Path}}

{{Parameters}} It Will Help Us If We Need To Control On GET Queries OR POST Body e.g. Change Request From GET To POST Or Vice Versa

{{CustomHeader}} It Will Help Us If We Need To Add Custom Headers From stdin

Also It Will Be A Great If You Add UpdateLength Option To Help Us To Control On Content-Length Header , That Will Be Awesome While Doing HTTP Request Smuggler e.g. If I Set -UpdateLength 6 Then Content-Length Header Will Be Like This Content-Length: 6 And If I Set  -UpdateLength All Then Content-Length Header Will Be Length Of The Whole Body Of Request

**Comment by 99red** [comment]
I second this. Also {{.Proto}} for http/https.

**Comment by sudo-jtcsec** [comment]
Ive run into this as well, for wanting to use full paths in templates. The list of Jaeles Project Declares would be awesome to have available!

**Comment by Mzack9999** [comment]
This should be covered in https://github.com/projectdiscovery/nuclei/pull/641 (still in development) as all the above are accessible through the scripting engine.

**Comment by ehsandeep** [comment]
@0xAwali @99red @sudo-jtcsec 

This is now supported in [dev](https://github.com/projectdiscovery/nuclei/tree/dev) version:-

Newly added Global variables:-

- `{{RootURL}}`
- `{{Host}}`
- `{{Port}}`
- `{{Path}}`
- `{{Scheme}}`

Template example:-

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    headers:
      A: '{{BaseURL}}'
      B: '{{RootURL}}'
      C: '{{Hostname}}'
      D: '{{Host}}'
      E: '{{Port}}'
      F: '{{Scheme}}'
      G: '{{Path}}'
```

Example output:-

```
echo http://www.example.com:80/test/aa?a=b | ./nuclei -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.4-dev

    projectdiscovery.io

[INF] Using Nuclei Engine 2.4.4-dev (development)
[INF] Using Nuclei Templates 8.4.5 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1 (New: 25)
[INF] [basic-example] Dumped HTTP request for http://www.example.com:80/test/aa?a=b

GET /test/aa?a=b/ HTTP/1.1
Host: www.example.com:80
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
A: http://www.example.com:80/test/aa?a=b
B: http://www.example.com:80
C: www.example.com:80
D: www.example.com
E: 80
F: http
G: /test/aa

[INF] No results found. Better luck next time!
```

**Comment by 0xAwali** [comment]
Thank You 💖

**Comment by hdbreaker** [comment]
Hi team, I'm also need to take control in GET/POST Parameters, there is a Global Variable for that? How can por example if my request is to site.com/sqli.php?vulnerableID=1 just use all the URL complete
