### ISSUE TITLE
The Latest Nuclei Version is not working with the fuzzing-templates. 

### ISSUE THREAD

**Issue by 0xKayala** [projectdiscovery/nuclei#4918]
### Nuclei version:
Nuclei v3.2.2

### Current Behavior:
The Latest Nuclei Version is not working with the fuzzing-templates.

### Expected Behavior:
Previous Versions of Nuclei are working fine with the fuzzing-templates.

### Steps To Reproduce:

Example: steps to reproduce the behavior:
1. Run 'nuclei -u vulnweb.com -t fuzzing-templates -rl 05'

### Anything else:

![image](https://github.com/projectdiscovery/nuclei/assets/16838353/2041de62-de84-4eb6-8d7c-aae5746fdeeb)

**Comment by ehsandeep** [comment]
@0xKayala see https://github.com/projectdiscovery/nuclei/releases/tag/v3.2.0, to run fuzzing templates, you additionally need to use `-fuzz` option.

**Comment by 0xKayala** [comment]
Thank you

**Comment by 0xKayala** [comment]
Can you help me with how we can turn off these errors or alerts in the nuclei output?

![image](https://github.com/projectdiscovery/nuclei/assets/16838353/b82df060-6d65-45c5-a2b5-3021086851dc)

**Comment by ehsandeep** [comment]
You can follow the updates here - https://github.com/projectdiscovery/nuclei/issues/4907
