### ISSUE TITLE
[issue] gologger error

### ISSUE THREAD

**Issue by Rishang** [projectdiscovery/nuclei#493]
**Describe the bug**
Go logger error while running:
`+ GO111MODULE=on go get -u github.com/projectdiscovery/nuclei/v2/cmd/nuclei`

fixes
instead of: `gologger.Warningf`
using: `gologger.Warning().Msgf("some warning")`

**Nuclei version**
latest

**Screenshot of the error or bug**

    # github.com/projectdiscovery/nuclei/v2/internal/progress
    pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.2.0/internal/progress/progress.go:33:4: undefined: gologger.Warningf
    pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.2.0/internal/progress/progress.go:53:4: undefined: gologger.Warningf
    pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.2.0/internal/progress/progress.go:143:4: undefined: gologger.Warningf

**Comment by bauthard** [comment]
@Rishang `GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei`, you don't need to use `-u` flag.

**Comment by hahwul** [comment]
Hi @ehsandeep 
Experiencing the same error in github action workflow. Is there a solution? 🤔

setup.sh
```bash
GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
```

output
![1414](https://user-images.githubusercontent.com/13212227/109184776-a8935f00-77d2-11eb-885f-18aa22c58580.jpg)
