### ISSUE TITLE
use nuclei sdk result dns error "no address found for host"

### ISSUE THREAD

**Issue by iuliu8899** [projectdiscovery/nuclei#4947]
### Current Behavior: 

I use nuclei sdk and integrate within my service. My service is deployed on kubernetes and has a connection with mysql server. In my code, I connect to mysql by using a Kubernetes domain name, e.g. mysql-server.srv.xxx, which can only be resolved inside pod. 

When I start a nuclei scan, my service lost the mysql connection and print error "no address found for host".

### Steps To Reproduce:
1. start my service, everything goes fine
2. trigger nuclei scan, and then my service cannot connect to mysql server. log error "no address found for host".
3. when I change mysql address (from kubernetes domain name) to ip address, restart service, trigger nuclei scan, it works good

### Anything else:

I init the nuclei server by this code

```
func getEngine(options ...nuclei.NucleiSDKOptions) (*nuclei.NucleiEngine, error) {
	networkConfig := nuclei.WithNetworkConfig(nuclei.NetworkConfig{Timeout: 60, SystemResolvers: true, Retries: 3})
	options = append(options, networkConfig)
	return nuclei.NewNucleiEngine(options...)
}
```

I've set the network config to use system resolvers and tried add kubernetes dns by using InternalResolversList config, still not work.

so is that something I did wrong?  how to use nuclei sdk with my mysql connection ?

I read the nuclei code and it seems modify the mysql driver dialer. (might be the reason?)

```
        // override dialer in mysql
	mysql.RegisterDialContext("tcp", func(ctx context.Context, addr string) (net.Conn, error) {
		return Dialer.Dial(ctx, "tcp", addr)
	})
```

Looking forward to any reply. Thanks

**Comment by Mzack9999** [comment]
@iuliu8899 This should be fixed with #5035 (it was due to a missing check, since previously resolvers were just loaded from file into the slice)
