### ISSUE TITLE
-no-color option is not respected when using -update option

### ISSUE THREAD

**Issue by andrejtomci** [projectdiscovery/nuclei#4997]
### Nuclei version: 
v3.2.3

### Current Behavior: 
When running `nuclei -update -no-color`, there is color displayed.

### Expected Behavior: 
When running ` nuclei -update -no-color`, no color is displayed.

### Steps To Reproduce:

1. Run `nuclei -update -no-color`.
2. See that the output still contains color

**Comment by dogancanbakir** [comment]
depends on https://github.com/projectdiscovery/utils/issues/389
