### ISSUE TITLE
[Question] Timeout error

### ISSUE THREAD

**Issue by A91K3C1l** [projectdiscovery/nuclei#500]
please me why when I start the scan an error like this appears what should I do? is it because of the waf website? [WRN] Unable to execute step: unable to request http request: Unable to make request: POST https://example.com/lib/crud/userprocess.php gave up after 2 attempts: Posting "https://example.com / lib / crud / userprocess.php ": context timeout exceeded (Client.Timeout exceeded while waiting for header)

**Comment by geeknik** [comment]
What is the command line you're receiving this error with?

**Comment by bauthard** [comment]
@A91K3C1l As the error indicates `Client.Timeout exceeded while waiting for header` it's a timeout error, the target is not responding to your request and reason could be anything depending on the target.

**Comment by bauthard** [comment]
Also please consider using the discussion section for any doubts.

**Comment by A91K3C1l** [comment]
> @A91K3C1l As the error indicates `Client.Timeout exceeded while waiting for header` it's a timeout error, the target is not responding to your request and reason could be anything depending on the target.

**Comment by A91K3C1l** [comment]
@bauthard 
whatever website I try it always does

**Comment by bauthard** [comment]
@A91K3C1l either you can share the target link + template you are running to verify this from our side, you can DM us at discord server https://discord.gg/KECAGdH
