### ISSUE TITLE
There Is Issue In Nuclei While Sending Raw HTTP 

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#501]
nuclei Send Only The Second Header e.g. If I Want To send Raw Request Like This

![1570772549000-image-20191009111046828 png-w331s](https://user-images.githubusercontent.com/54332136/106237918-81b03000-6208-11eb-9054-9fe13062ef4e.png)

This Lap Depend On TE.TE Technique  So I should To Submit Two Transfer-Encoding Headers
And This Was My Template 

```
id: 0x00
info:
 name: HTTP request smuggling TE Frond-end , TE Back-end
 author: 0xAwali

requests:
  - raw:
    - |
      POST / HTTP/1.1
      Host: {{Hostname}}
      Content-Type: application/x-www-form-urlencoded
      Content-length: 4
      Transfer-Encoding: chunked
      Transfer-Encoding: cow

      5c
      GPOST / HTTP/1.1
      Content-Type: application/x-www-form-urlencoded
      Content-Length: 15

      x=1
      0
       
    unsafe: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body, "Unrecognized method GPOST")'
```

Then I Ran Nuclei With Debug Option And Result Of Raw HTTP Was nuclei Only Submit The Second Header As You Can See Below 

![Screenshot_2021-01-29_06-30-17](https://user-images.githubusercontent.com/54332136/106239515-6bf03a00-620b-11eb-9711-97e4b4722ecf.png)

And If I Want To Submit Any Two Headers , Nuclei Only Submit The Second Header
So Can You Solve This Issue ?

**Comment by bauthard** [comment]
@0xAwali I can confirm this is not possible with the current stable release, but we fixed this in the development version, so you will be able to execute duplicate headers in the next release of nuclei.

![image](https://user-images.githubusercontent.com/8293321/106251390-eab09b80-623a-11eb-9d1d-bb82829dc0d8.png)

**Comment by 0xAwali** [comment]
Thank You For All Your Works , You are A Great Team

**Comment by Ice3man543** [comment]
Closing this as fixed in dev branch!
