### ISSUE TITLE
Incorrect newline in multipart raw requests

### ISSUE THREAD

**Issue by winnie22** [projectdiscovery/nuclei#502]
**Describe the bug**
Hi,
during writing nuclei plugin i found that raw multipart requests are handled incorrectly. Nuclei ending line in multipart requests only using \n but should be \r\n

**Nuclei version**
v2.2.0

**Screenshot of the error or bug**
nuclei request:
![nuclei multipart request](https://user-images.githubusercontent.com/6103248/106294708-c9a67580-624f-11eb-9ad6-076637282608.png)

correct request:
![correct multipart request](https://user-images.githubusercontent.com/6103248/106294714-cc08cf80-624f-11eb-846e-773bd1f3ef6c.png)

**Comment by bauthard** [comment]
Thank you @winnie22 for creating an issue, we will review and fix this.

**Comment by winnie22** [comment]
Hi @bauthard,
Thanks for quick response. I think I found where the bug is. Fix in attached PR.

**Comment by winnie22** [comment]
Quite changes in dev branch :). I think that this bug don't exists in dev branch, but I can't verify for sure because dev branch fail to compile due to missing goflags dependency from your repo :/. But according to my understanding in file https://github.com/projectdiscovery/nuclei/blob/dev/v2/pkg/protocols/http/request.go at line 250 there is already crlf handled correctly:
```
if parsed, err := url.Parse(formedURL); err == nil {
	hostname = parsed.Hostname()
}
**request.rawRequest.Data = strings.ReplaceAll(request.rawRequest.Data, "\n", "\r\n")**
options := request.original.rawhttpClient.Options
options.AutomaticContentLength = !r.DisableAutoContentLength
```

**Comment by bauthard** [comment]
@winnie22 do you have an example template that you can share and I can confirm this, also we will make goflags public soon so others can compile the dev version as well.

**Comment by winnie22** [comment]
Sure, thanks!
[cmsx_admin_password.yaml.txt](https://github.com/projectdiscovery/nuclei/files/5898198/cmsx_admin_password.yaml.txt)

**Comment by bauthard** [comment]
@winnie22 I can confirm this is also reproducible with dev version, we will fix this in ongoing development sprint, thank you for creating an issue for this.

**Comment by winnie22** [comment]
Thanks for fix and thanks for your great work!

**Comment by Ice3man543** [comment]
@winnie22 this should be fixed with the dev branch. Closing the issue now!
