### ISSUE TITLE
Google cloud shell nuclei not working

### ISSUE THREAD

**Issue by Sachin85y** [projectdiscovery/nuclei#5039]
package github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest: cannot use path@version syntax in GOPATH mode

**Comment by Mzack9999** [comment]
Please fill all the fields within the template issue, without reproduction steps, we are unable to investigate the problem. Here I suppose you are running `go get` command? The `@latest` syntax is meant to be used with `go install`
