### ISSUE TITLE
[issue] raw User-Agent header display with double space

### ISSUE THREAD

**Issue by toufik-airane** [projectdiscovery/nuclei#505]
**Describe the bug**
Nuclei template with raw User-Agent header badly displays during execution.
Indeed, it displayed with a double space instead of a single space.

**Nuclei version**
```
$ nuclei --version
[INF] Current Version: 2.2.1-dev
```

**Code to trigger bug**
```
 raw:
    - |
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
```

**Affected Nuclei templates**
```
grafana/grafana-default-credential.yaml
33:        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
apache/tomcat-manager-default.yaml
29:        User-Agent: Mazella/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0
```

**Screenshot of the error or bug**
![Screenshot 2021-01-29 at 22 51 46](https://user-images.githubusercontent.com/5610269/106331169-b9f55400-6284-11eb-835b-9aa23056dcbc.png)

**Comment by Ice3man543** [comment]
This is fixed in dev branch! Closing now.
