### ISSUE TITLE
Add stop-at-first-match: true for tcp network based templates

### ISSUE THREAD

**Issue by epicsilence99** [projectdiscovery/nuclei#5055]
As part of http based templates you can use a field called stop-at-first-match: true to prevent additional requests when there is a match hit on a matcher.

Currently network (tcp) based templates do not support that feature.

### Please describe your feature request:
My feature request would be for network based templates (tcp) to also support the `stop-at-first-match: true` so for network based requests that include multiple ports stops at the first match and does not make additional requests.

### Describe the use case of this feature:
This use case would be more efficient and save additional queries where for example a service could be running on 3-4 differnet ports and you list and hit it's on the first one, it would not then move onto the other ports to query.

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @epicsilence99 , we appreciate it! :)

**Comment by epicsilence99** [comment]
@GeorginaReeder is there any update on this?
It's been sitting since April
