### ISSUE TITLE
Bug(?) with fuzzing templates in v3.2.4

### ISSUE THREAD

**Issue by reewardius** [projectdiscovery/nuclei#5057]
### Nuclei version:

3.2.4
### Version 3.2.2 Behavior:

In version 3.2.2 we can import results from other scanners (katana,burp etc.) and then use custom rules to fuzz them.
```
docker run -v $(pwd):/src projectdiscovery/nuclei:v3.2.2 -l /src/burp -im burp -t /src/fuzzing-requests -id time-body
```
![image](https://github.com/projectdiscovery/nuclei/assets/68978608/6adaf421-c8d8-46cc-8fe4-2042ae12264b)

```
id: time-body

info:
  name: Blind SQL Injection
  author: reewardius
  severity: high
  tags: fuzzing-req
  
http:
  - filters:
      - type: dsl
        dsl:
          - 'method == "POST"'
      
    payloads:
      blind:
        - "'+(select*from(select(sleep(9)))a)+'"
        
    fuzzing:
      - part: body
        type: replace
        mode: single
        fuzz:
          - "{{blind}}"
          
    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - 'duration>=9'
```

### Current Behavior:

In version 3.2.4 the same rule gives an error, what has changed in the new version, how to run them now?
```
docker run -v $(pwd):/src projectdiscovery/nuclei:v3.2.4 -l /src/burp -im burp -t /src/fuzzing-requests -id time-body
```
![image](https://github.com/projectdiscovery/nuclei/assets/68978608/1f9052f1-11ab-4cc1-a724-c7f6ef3c49a6)

**Comment by reewardius** [comment]
filters has been replaced by pre-condition

**Comment by reewardius** [comment]
Fix it in the documentation then, that filters no longer exist, but instead pre-condition is used, because versions 3.2.2 and 3.2.4 work differently, and many rules that were written in the first days of release do not work...

![image](https://github.com/projectdiscovery/nuclei/assets/68978608/ddddec0a-8fc1-4a77-a5f7-61270256e692)

but the [rules](https://github.com/projectdiscovery/nuclei-templates/tree/main/dast) use pre-condition 
![image](https://github.com/projectdiscovery/nuclei/assets/68978608/a09c26cf-d112-4828-85e8-ff536675a331)

**Comment by ehsandeep** [comment]
@reewardius https://github.com/projectdiscovery/docs/pull/41
