### ISSUE TITLE
issue with installing on alpine linux

### ISSUE THREAD

**Issue by jffin** [projectdiscovery/nuclei#511]
**Describe the bug**
When I try to install the library on Alpine Linux, it fails on installation step library ```github.com/segmentio/ksuid```.

```The command '/bin/sh -c GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei' returned a non-zero code: 2```

**Nuclei version**
alpine: ```FROM golang:alpine as builder```
I can't install to check the version, but I believe it's the latest version.

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/22579497/106379727-a944fb00-63b6-11eb-8857-d363120c2a56.png)

**Comment by jffin** [comment]
Looks like it stops on the same step on Debian in Docker container.

**Comment by bauthard** [comment]
@jffin I can see, `GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei` command is being used, you need to remove `-u` from this command to make it work.

**Comment by jffin** [comment]
Yes, it works now. Thanks a lot.

But now I can't find the nuclei templates folder.
I believe that is why I previously installed the library as a user because the app downloaded the templates to a home user directory, but now I can't figure out where they are.

When I run ```nuclei -update-templates```
The result is ```[INF] Your nuclei-templates are up to date: v8.0.2```

But in ```-t``` option I had to add a full path to the templates.

**Comment by bauthard** [comment]
@jffin can you share more specific details over chat https://discord.gg/KECAGdH?

**Comment by jffin** [comment]
Thank you very much

if somebody will face similar problem the path in Alpine is ```/root/nuclei-templates/```
