### ISSUE TITLE
Adding external context to NucleiEngine

### ISSUE THREAD

**Issue by pedrofialho94** [projectdiscovery/nuclei#5151]
### Please describe your feature request:
Supporting adding an external context to the NucleiEngine to be used when running a scan.

### Describe the use case of this feature:
After #5096, it is now possible to cancel a running scan through a context. Adding support for external context would allow a user of the sdk to cancel running scans at any time. This could be used to implement a stop feature in a service that runs nuclei scans.

**Comment by tarunKoyalwar** [comment]
@pedrofialho94  see https://github.com/projectdiscovery/nuclei/pull/5154
