### ISSUE TITLE
update timeout

### ISSUE THREAD

**Issue by watskenet** [projectdiscovery/nuclei#5161]
please increasing update time out
i always have problem with update  
10.02 MiB / 25.32 MiB [--------------------->________________________________] 39.58% 356.01 KiB p/s
[updater] executable nuclei not found in release asset `165996088` got: [:RUNTIME] failed to read response body <- context deadline exceeded (Client.Timeout or context cancellation while reading body)

┌──(omid㉿DESKTOP-G96DDHA)-[~]
└─$ nuclei -up -r resolvers2.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.4

                projectdiscovery.io

5.62 MiB / 25.32 MiB [------------>__________________________________________] 22.18% 199.08 KiB p/s
[updater] executable nuclei not found in release asset `165996088` got: [:RUNTIME] failed to read response body <- context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by dogancanbakir** [comment]
If you need to extend the timeout, simply utilize the `-timeout` flag.

```
 nuclei -up -timeout 60
```
