### ISSUE TITLE
Ability to name scans for PDCP

### ISSUE THREAD

**Issue by rxerium** [projectdiscovery/nuclei#5170]
Hey team,

Currently when running scans with the `-cup` flag it uploads the scan results to PDCP with a generic name, it would be useful to set a name for scans within the command such as:
```
nuclei -u rxerium.com -tags dns -cup dns-scan
```

This will especially be useful for automations where scans are run on a schedule which is unattended (through CI/CD etc..) and can allow one to easily view / access scans through the PDCP dashboard. 

Many thanks,

Rishi

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/nuclei/pull/5155, already added in latest release.
