### ISSUE TITLE
 Nuclei skips the active ip from scanning problem

### ISSUE THREAD

**Issue by Rameshkanna2k** [projectdiscovery/nuclei#5178]
Hi team,

While scanning the target with nuclei using

nuclei -u 129.33.40.139:443 -s low,medium,high,critical

its not working and target skipped
and also

nuclei -u https://129.33.40.139 -s low,medium,high,critical

not working and target skipped

While reaching the ip with broswer using

https://129.33.40.139 ---> working
129.33.40.139:443 ------->not working

i have attached the screenshots.
Kindly help me to fix my issue , why nuclei skippping the target . is their anything i need to fix from my network settings or in broswer or nuclei.using kali linux and wifi.
![Screenshot from 2024-05-13 11-11-40](https://github.com/projectdiscovery/nuclei/assets/67623153/e2025f0f-97d6-4b2c-ba4e-00f38b5d7ebf)
![Screenshot from 2024-05-13 11-12-22](https://github.com/projectdiscovery/nuclei/assets/67623153/5546fb87-833f-4a7b-8014-b2d1cb3d0b9c)
![Screenshot from 2024-05-13 11-10-31](https://github.com/projectdiscovery/nuclei/assets/67623153/4f08a191-2d22-46d0-81b6-92d329121c8b)

**Comment by Mzack9999** [comment]
@Rameshkanna2k if you look at the browser output in the second image, the host was found unresponsive (connection reset error), which matches nuclei behavior. I think it might be something related to your network. In order to ensure the page is correctly fully loaded try to execute the following command (if it doesn't work, it's unrelated to nuclei):
```console
# curl -k https://129.33.40.139/
<script LANGUAGE="JavaScript">
window.location="/global-protect/login.esp";
</script>
<html><head></head><body><p>JavaScript must be enabled to continue!</p></body></html>
```

I confirm that nuclei works for me:
```console
go run . -id tech-detect -duc -u https://129.33.40.139                      

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.7

                projectdiscovery.io

[WRN] Found 26 template[s] loaded with deprecated paths, update before v3 for continued support.
[INF] Current nuclei version: v3.2.7 (outdated)
[INF] Current nuclei-templates version: v9.8.6 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 65
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[tech-detect:bootstrap] [http] [info] https://129.33.40.139/global-protect/login.esp
```

**Comment by ehsandeep** [comment]
see https://github.com/projectdiscovery/nuclei/issues/5179#issuecomment-2107291469, closing this as duplicate.
