### ISSUE TITLE
Jira not getting custom fields on issue creation

### ISSUE THREAD

**Issue by davide136** [projectdiscovery/nuclei#5201]
https://github.com/projectdiscovery/nuclei/blob/7a4969d2a2a7f0d56530c5072a0650e3ad2377fc/pkg/reporting/trackers/jira/jira.go#L176

Hi, it seems like the integration with Jira is not working, I tried a lot of times to make it work, changed field type on jira multiple times but it seems like the api implementation has the customfields mapped on the wrong level of the dto.

See here: 
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post

**Comment by davide136** [comment]
maybe it's me not getting how a marshal map works, never used it...if it's something like [ ...items ] in js then probably it's fine, anyway with this config I'm not getting any values mapped in the tickets:

`  custom_fields:
    security:
      name: $Severity  
    customfield_11031:
      freeform: $CVEID    
    customfield_11032:
      freeform: $CVSSScore
    customfield_11033:
      freeform: $CVSSMetrics`

**Comment by davide136** [comment]
is it possible for you to check if in https://<domain>.atlassian.net/rest/api/latest/field you custom fields are like mine? Or post them here as an example?


Thank you.

```json
  {
    "id": "customfield_11031",
    "key": "customfield_11031",
    "name": "CVSS",
    "untranslatedName": "CVSS",
    "custom": true,
    "orderable": true,
    "navigable": true,
    "searchable": true,
    "clauseNames": [
      "cf[11031]",
      "CVSS",
      "CVSS[Paragraph]"
    ],
    "schema": {
      "type": "string",
      "custom": "com.atlassian.jira.plugin.system.customfieldtypes:textarea",
      "customId": 11031
    }
  },
  {
    "id": "customfield_11032",
    "key": "customfield_11032",
    "name": "CVSS Score",
    "untranslatedName": "CVSS Score",
    "custom": true,
    "orderable": true,
    "navigable": true,
    "searchable": true,
    "clauseNames": [
      "cf[11032]",
      "CVSS Score",
      "CVSS Score[Paragraph]"
    ],
    "schema": {
      "type": "string",
      "custom": "com.atlassian.jira.plugin.system.customfieldtypes:textarea",
      "customId": 11032
    }
  },
  {
    "id": "customfield_11033",
    "key": "customfield_11033",
    "name": "CVSS Metrics",
    "untranslatedName": "CVSS Metrics",
    "custom": true,
    "orderable": true,
    "navigable": true,
    "searchable": true,
    "clauseNames": [
      "cf[11033]",
      "CVSS Metrics",
      "CVSS Metrics[Paragraph]"
    ],
    "schema": {
      "type": "string",
      "custom": "com.atlassian.jira.plugin.system.customfieldtypes:textarea",
      "customId": 11033
    }
  },
  {
    "id": "security",
    "key": "security",
    "name": "Security Level",
    "custom": false,
    "orderable": true,
    "navigable": true,
    "searchable": true,
    "clauseNames": [
      "level"
    ],
    "schema": {
      "type": "securitylevel",
      "system": "security"
    }
  },

**Comment by dogancanbakir** [comment]
@davide136 Did you find it helpful?

**Comment by davide136** [comment]
cvss metrics have the same configuration between yours and mine, I should be having values here:
![image](https://github.com/projectdiscovery/nuclei/assets/43040672/ce58e961-132b-42e7-82ed-9cd7432f2e58)
I'm trying to see if there's anything that's breaking when creating tickets but nothing shows up in logs or in console, even when running it in verbose mode.
The only other red flag I have is that when I run nuclei with update-existing: true I'm getting the following errors:
[INF] 30 jira tickets created successfully, 2 failed 
but console log is too short too see where it failed, and output log is not verbose like the console one, and it's not containing any errors related to jira

**Comment by dogancanbakir** [comment]
Can you post your config file?

**Comment by dogancanbakir** [comment]
I don't see anything wrong with the configuration, but to be honest, I'm not sure why this isn't working for you.

**Comment by davide136** [comment]
May i ask you which kind of project template you selected on project creation in Jira? Maybe there's something hidden that's blocking me

**Comment by dogancanbakir** [comment]
Was the information useful to you?

**Comment by davide136** [comment]
nope, I have the same type on the project info. I tried more stuff but my solution was to use Jira automation to check the ticket labels on creation to set the ticket priority and I'm surrending on the CVSS + CVSS metrics column, I'll just read them from the tickets.

**Comment by dogancanbakir** [comment]
Closing it now. You can reopen it at any time.
