### ISSUE TITLE
使用sdk包创建的并发安全的引擎，因共享资源的释放无法正常执行完全部任务

### ISSUE THREAD

**Issue by ti4nly** [projectdiscovery/nuclei#5202]
本次使用的 v3.2.7版本
我在测试使用sdk包并发对多个目标进行扫描任务时发现一个问题，在第一个任务结束的时候在en.ExecuteNucleiWithOptsCtx函数中有一个defer tmpEngine.Close()，在其中的protocolstate.Close()会将一些共享资源释放，这样就会对其他正在执行且没有执行完成的任务收到影响，导致其他任务被中断。

![image](https://github.com/projectdiscovery/nuclei/assets/161565005/f3f2cf72-cc54-4c3f-ab21-bb05cec291d2)

原始逻辑，只扫描出一次漏洞，第二次并没有进行正常的发包扫描
![image](https://github.com/projectdiscovery/nuclei/assets/161565005/cb068a79-138a-4548-bcd0-d1c2ee26816c)

将protocolstate.Close()注释掉，正常扫描出两次漏洞

![image](https://github.com/projectdiscovery/nuclei/assets/161565005/8b3b9747-aef9-4389-aafa-f3aee9e39a8f)

**Comment by ti4nly** [comment]
要想要sdk足够好用就得避免全局共享变量的存在，应当检查整个项目中使用到的全局变量，将其绑定到特定的对象上

**Comment by ti4nly** [comment]
这里主要是涉及到protocolstate.Dialer 调用了Close()方法将其中的数据清除掉了，这个数据如果不清除的话对程序会造成什么危害呢，这个bug影响了正常的功能使用，希望能早日修复

**Comment by Mzack9999** [comment]
Potentially already fixed in https://github.com/projectdiscovery/nuclei/pull/5187
