### ISSUE TITLE
proxy rotation 

### ISSUE THREAD

**Issue by devcoinfet** [projectdiscovery/nuclei#521]
can someone add support for http or socks proxies nuclei runs slow often behind a vpn on large hosts

**Comment by geeknik** [comment]
Proxy rotation isn't available at the moment (which is a great idea by the way) but proxy support is available via:

```
-proxy-socks-url string
    	URL of the proxy socks server
-proxy-url string
    	URL of the proxy server
```

**Comment by devcoinfet** [comment]
but my proxies if they work like u showed are rotating so that is implemented upstream if i can supply my proxy like that u just saved the day lol
