### ISSUE TITLE
Output looks corrupted during first time scan on Windows 10 x64

### ISSUE THREAD

**Issue by JuraLys** [projectdiscovery/nuclei#5218]
Install Nuclei and start first scan for some target: nuclei -target target.net
Observe corrupted output without line breaks, see attached screenshot
![nuclei-first-scan(](https://github.com/projectdiscovery/nuclei/assets/146434286/99bf8678-5458-4ad9-bfda-1f964654a233)

**Comment by Mzack9999** [comment]
This will be fixed with next gologger release (ref: https://github.com/projectdiscovery/gologger/issues/52) - Thanks for reporting!
