### ISSUE TITLE
[feature] Allow to define HTTP response block size to read for matchers

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#523]
**Is your feature request related to a problem? Please describe.**
Context:- https://github.com/projectdiscovery/nuclei-templates/pull/757#issuecomment-760309966

**Describe the solution you'd like**
Adding support for `max-size` for the HTTP response, similar to file protocol.

**Comment by Ice3man543** [comment]
This is done in dev branch. Closing now!
