### ISSUE TITLE
Unable to install in termux..can we instal3.2.8 in termuxl

### ISSUE THREAD

**Issue by krivadna** [projectdiscovery/nuclei#5245]
Binary isn't executed

**Comment by GeorginaReeder** [comment]
Hi there @krivadna - are you seeing any specific errors when trying to install in Termux? And which installation instructions did you follow from here exactly? https://docs.projectdiscovery.io/tools/nuclei/install

Let us know, and we'll be happy to take a closer look.

**Comment by krivadna** [comment]
Its working
