### ISSUE TITLE
[issue] Repo download tracking

### ISSUE THREAD

**Issue by griff4594** [projectdiscovery/nuclei#525]
**Describe the bug**
You really need to add some type of ping back to another remote server so instances of abusing this application can be tracked. My company is currently being attacked by this application and it isn't the first time. Take some accountability and prevent users from abusing this codeset.

**Nuclei version**
ALL

**Screenshot of the error or bug**
![Screen Shot 2021-02-03 at 1 41 29 PM](https://user-images.githubusercontent.com/4130905/106806829-ad2a8480-6625-11eb-9a18-30f10b88b028.png)

**Comment by geeknik** [comment]
Nginx:
```
if ($http_user_agent ~* (Nuclei) ) {
   return 403;
}
```

Apache:
```
RewriteEngine On
RewriteCond %{HTTP_USER_AGENT} Nuclei [NC]
RewriteRule . - [R=403,L]
```

HAProxy:
```
https://briansnelson.com/HAProxy_Block_by_User-Agent
```

Lighttpd:
```
$HTTP["useragent"] =~ "Nuclei" {url.access-deny = ( "" )}
```
