### ISSUE TITLE
Nuclei transparently capitalizes and cannonicalizes headers 

### ISSUE THREAD

**Issue by denandz** [projectdiscovery/nuclei#5288]
### Nuclei version:
v3.8.2

### Current Behavior:

Nuclei cannonicalizes headers sent to back end servers. Lower case headers become capitalized and cannonicalized. This prevents nuclei from being able to test bugs which require a specific capitalization of a header name.

### Expected Behavior:

User specified headers should remain lowercase

### Steps To Reproduce:

```
nuclei --proxy http://127.0.0.1:8081 -H "some-lowercase-header: foo" -u http://127.0.0.1:8000
```

And what actually gets sent:

```
GET /login.jsp HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
Accept-Encoding: gzip
Connection: close
Content-Type: application/x-www-form-urlencoded
Some-Lowercase-Header: foo
```

### Anything else:

This is due to a know issue in Golang's `net/http`, where headers are transparently modified as they are read/written from the Headers object (https://github.com/golang/go/issues/37834)

**Comment by jimen0** [comment]
Although it would be nice to have nuclei preserve the header capitalization it must be noted HTTP/1 headers are case insensitive. See https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.

```text
Each header field consists of a case-insensitive field name followed
by a colon (":"), optional leading whitespace, the field value, and
optional trailing whitespace.
```

For HTTP/2 the standard specifies all headers must be converted to lower case. See https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.

```text
Just as in HTTP/1.x, header field names are strings of ASCII
characters that are compared in a case-insensitive fashion.  However,
header field names MUST be converted to lowercase prior to their
encoding in HTTP/2.  A request or response containing uppercase
header field names MUST be treated as malformed ([Section 8.1.2.6](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.6)).
```

Then on https://datatracker.ietf.org/doc/html/rfc9113#section-8.2.

```text
Field names MUST be converted to lowercase when constructing an HTTP/2 message.
```

I wouldn't expect the Go issue be resolved with a change as it is currently compliant with the RFCs. This might need forking Go's http2. See https://github.com/golang/net/blob/9617c6335bca5e4e80949a5b1dbe43273260e8a3/http2/write.go#L331-L349.

**Comment by denandz** [comment]
Sure, the RFC's are clear on what compliant behaviour looks like.

The issue is that non-RFC compliant implementations exist, and Nuclei is currently unable to scan them due to Golang's net/http forcing header canonicalization.

**Comment by dogancanbakir** [comment]
@denandz,
Could you please confirm if what @ehsandeep shared works for you?

**Comment by denandz** [comment]
Closing an issue as abandoned after a week is pretty brutal there @dogancanbakir 

@ehsandeep's suggestion of `unsafe: true` method works for specific templates, sure. Headers added via `-H` at runtime; however, get cannonicalized.

**Comment by dogancanbakir** [comment]
I don't want to be mean! I close issues quickly to keep things moving, but I'm always happy to reopen them with new information or an update. Thanks for the update!
