### ISSUE TITLE
Miscellaneous Templates Fail to Load[issue]

### ISSUE THREAD

**Issue by machevalia** [projectdiscovery/nuclei#530]
**Describe the bug**
Expected - when providing the directory ~/nuclei-templates/miscellaneous/ all templates under the miscellaneous directory will be loaded and run.

Actual - when providing the directory ~/nuclei-templates/miscellaneous/ no templates are loaded for scanning. I have tested this against other template directories and they work fine. When specifying a specific template (case 1 in screen shot) the template is run just fine. When specifying an asterisk the dir-listing template is found and run (case 2 in screen shot). When specifying the entire directory no templates are loaded (case 3 in the screen shot).

I have rm -rf the ~/nuclei-templates dir and the ~/.nuclei-config.json file then updated with the same results.

**Nuclei version**

v2.2.0 (See in screen shot)

**Screenshot of the error or bug**

![image](https://user-images.githubusercontent.com/36945847/107532776-3d1f7f80-6b8c-11eb-820f-7576306d0e91.png)

**Comment by geeknik** [comment]
Try removing `miscellaneous/` from the `~/nuclei-templates/.nuclei-ignore` file and re-run your 3rd command line.

**Comment by machevalia** [comment]
Whoops, thanks!!! That was the ticket.
