### ISSUE TITLE
The -proxy-url option doesn't resolve host.docker.internal 

### ISSUE THREAD

**Issue by the-remmer** [projectdiscovery/nuclei#532]
**Describe the bug**

When running Nuclei in Docker, setting the option `-proxy-url http://host.docker.internal:31337`, results in the following error:

> ` proxyconnect tcp: no address found for host`

If I run a shell on the container, I can do `nslookup host.docker.internal`, which returns the IP `192.168.65.2`. So, the hostname is in fact resolvable from the container just fine, but it seems that Nuclei isn't able to do it.

If I try to run Nuclei with the option `-proxy-url http://192.168.65.2:31337`, it works as expected, but this is not a valid solution because the internal IP is not static and it can change.

**Nuclei version**
2.2.0

**Comment by ehsandeep** [comment]
@the-remmer thank you for reporting this, this is fixed here https://github.com/projectdiscovery/nuclei/pull/570
