### ISSUE TITLE
[feature] add back the nuclei usage with examples in description

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#536]
Heyy

I noticed in all project discovery tools, the wiki of usage with examples was deleted. I found that really usefull when looking for flags and everything. I know I can always use the --help flag but I prefer the gui to look for those kind of options <3

**Comment by ehsandeep** [comment]
Hi @marcelo321, 

You can find the detailed version of the readme here https://nuclei.projectdiscovery.io/nuclei/get-started/, we will be adding more details to it.

**Comment by ehsandeep** [comment]
Closing this one, please see the above link.
