### ISSUE TITLE
[question] -bulk-size & -rate-limit flags

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#537]
The flags: 
```
-rate-limit int
        Rate-Limit (maximum requests/second (default 150)
-bulk-size int
        Maximum Number of hosts analyzed in parallel per template (default 25)
```

got my attention. `-rate-limit` states a max of 150 requests per second, while `-bulk-size` states a max of 25 analyzed hosts per template (and a max of 150 r/s of rate limit flag).

If I am running a list of hosts against a single template, which flag is going to have more weight in the scan? is there going to be a max of 25 hosts analyzed in parallel and only like 50-100 requests per second?

I'm asking this question because maybe if I use a single templates against a list of hosts, I should move the value of `-bulk-size` to like 50 or more? But maybe that is way to fast and will get me problems.

Sorry for the long issue, just want to understand which option has more weight in this situation.

Edit:

```
rate-limit flag takes precedence over other two flag, number of request/seconds can't go beyond the value defined for rate-limit flag regardless the value of c and bulk-size flag.
```

So according to this, the right way to run this would be `-bulk-size 75 -rate-limit` since nuclei will still have the limit of 150 requests per second, regardless of the bulk-size (so against one template alone I should increase it?)

**Comment by ehsandeep** [comment]
Hi @marcelo321, 

We have added detailed information on the documentation website, check this out https://nuclei.projectdiscovery.io/nuclei/get-started/#rate-limits

> rate-limit flag takes precedence over other two flag, number of request/seconds can't go beyond the value defined for rate-limit flag regardless the value of c and bulk-size flag.
