### ISSUE TITLE
Cannot Execute Workflows with SDK

### ISSUE THREAD

**Issue by alban-stourbe-wmx** [projectdiscovery/nuclei#5408]
### Nuclei version:
Last Realease
### Current Behavior:
The SDK launches templates but no workflows even if we load it with nuclei.WithTemplatesOrWorkflows

### Expected Behavior:
Can execute workflows

### Steps To Reproduce:
Create an Nuclei engine and load workflows with  nuclei.WithTemplatesOrWorkflows. When we execute it nothing happened. 

### Anything else:
I have already fix the issue with a PR :). In the SDK, only templates are executed but we just need to consider also workflows like it is done with the nuclei runner

**Comment by alban-stourbe-wmx** [comment]
PR #5409

**Comment by dogancanbakir** [comment]
Could you please provide the exact repro steps? Thanks!

**Comment by alban-stourbe-wmx** [comment]
Here a detailed explanation: 

First, i create a demo function to show the current behavior in a package _engine:_

```
func DemoWorkflowEngine(workflow string) {
	ne, err := nuclei.NewNucleiEngine(
		nuclei.WithTemplatesOrWorkflows(
			nuclei.TemplateSources{
				Workflows: []string{workflow},
			},
		),
		nuclei.WithVerbosity(
			nuclei.VerbosityOptions{
				Verbose:       true,
				Silent:        false,
				Debug:         false,
				DebugRequest:  false,
				DebugResponse: false,
			},
		),
	)
	if err != nil {
		panic(err)
	}
	// load targets and optionally probe non http/https targets
	ne.LoadTargets([]string{"scanme.sh"}, false)
	err = ne.ExecuteWithCallback(nil)
	if err != nil {
		panic(err)
	}
	defer ne.Close()
}

```

And i call it from main.go

```
func main() {
	engine.DemoWorkflowEngine("74cms-workflow.yaml")
}
```
When i run the code, nothing happens but i made a print to show you the workflow has been loaded

<img width="214" alt="Capture d’écran 2024-07-16 à 14 44 48" src="https://github.com/user-attachments/assets/b7706aa1-33e6-4f9a-8c8b-31669a6122c2">

Nothing is executed beacuse in the function **ExecuteCallbackWithCtx** in _sdk.go_, the **ExecuteScanWithOpts** function takes only Templates and not Worklfows :

```
_ = e.engine.ExecuteScanWithOpts(context.Background(), e.store.Templates(), e.inputProvider, false)
```


With my changes made in the PR: https://github.com/projectdiscovery/nuclei/pull/5409
The SDK executes the workflow

<img width="551" alt="Capture d’écran 2024-07-16 à 14 48 37" src="https://github.com/user-attachments/assets/321532fc-c32b-4b26-85e7-5a291bcc3a8d">

**Comment by alban-stourbe-wmx** [comment]
@dogancanbakir i hope it is better to understand
