### ISSUE TITLE
[issue] Ubuntu's OOM killer kills Nuclei when using very large lists

### ISSUE THREAD

**Issue by 0x0luke** [projectdiscovery/nuclei#541]
**Describe the bug**
Ubuntu's OOM killer kills Nuclei when using large lists due to the OOM system protection, additionally this causes Nuclei to not log out found vulnerabilities.

**Nuclei version**
2.2.0 

**Screenshot of the error or bug**

![image](https://user-images.githubusercontent.com/24577556/108176149-8bd39900-70f9-11eb-8ad4-df68e7c72d0e.png)

**Comment by ehsandeep** [comment]
Hey @0x0luke, 

As you said, this behavior is a result of OOM system protection, we can not do much about it, for results, as of now you can make use of `tee` to save results, for example:- `nuclei -t templates -l urls.txt | tee nuclei-results.txt`

Additionally, in the development version, we have updated the output logic and now nuclei stores found results in the file at run time.

**Comment by 0x0luke** [comment]
Hi ehsandeep,

Thanks for the update, I reckon the patch to make Nuclei export results as it finds them is the best mitigation for this issue, Users CAN disable OOM, but it'll more than likely cause kernel panics which is something that's obviously not ideal.. 

Thanks
