### ISSUE TITLE
nuclei  3.29  扫着扫着就突然崩溃了出现了很多错误

### ISSUE THREAD

**Issue by web1919** [projectdiscovery/nuclei#5423]

**Comment by ehsandeep** [comment]
@web1919 please fill out all the information so we can review / replicate the bheavior, feel free to create new issue or add additional information in https://github.com/projectdiscovery/nuclei/issues/5348

**Comment by web1919** [comment]
![image](https://github.com/user-attachments/assets/4a68eb69-8af0-4c70-9c7b-ead45a599c3d)

**Comment by web1919** [comment]
就是这种情况
