### ISSUE TITLE
Unable to load some templates

### ISSUE THREAD

**Issue by wa0er** [projectdiscovery/nuclei#5441]
## Current Behavior:

When I run the command to load the template, one of the templates cannot be loaded。
Perhaps other templates may also have similar situations, it is recommended to investigate。

## Anything else:

![image](https://github.com/user-attachments/assets/06307e81-1b57-41e0-877a-9cc0ccd061da)

![image](https://github.com/user-attachments/assets/8987e251-5c3b-47d5-80f1-447ec50e83d3)

![image](https://github.com/user-attachments/assets/77cff8ee-a149-4652-99fe-822b1be74ef8)

**Comment by zrquan** [comment]
The `fuzz` tag is excluded by default, you can include tongda-auth-bypass.yaml by adding `-itags fuzz`.

**Comment by wa0er** [comment]
> The `fuzz` tag is excluded by default, you can include tongda-auth-bypass.yaml by adding `-itags fuzz`.

Thanks for your generosity. Besides `fuzz`, are there any other tags that are excluded by default? Where can I find a list of the tags or templates that are excluded by default? I have gone through all the parameters and configuration files but haven't found such a list.

**Comment by zrquan** [comment]
> Where can I find a list of the tags or templates that are excluded by default?

In nuclei's configuration directory, you should see a `.nuclei-ignore` file (on linux, the path is `~/.config/nuclei/.nuclei-ignore`).

More details - https://docs.projectdiscovery.io/tools/nuclei/running#template-exclusion

**Comment by wa0er** [comment]
> > Where can I find a list of the tags or templates that are excluded by default?
> 
> In nuclei's configuration directory, you should see a `.nuclei-ignore` file (on linux, the path is `~/.config/nuclei/.nuclei-ignore`).
> 
> More details - https://docs.projectdiscovery.io/tools/nuclei/running#template-exclusion

Thank you very much, I was careless.

**Comment by RamanaReddy0M** [comment]
Seems resolved closing it.
