### ISSUE TITLE
redirects didn't work with `<meta http-equiv="refresh" content="1;URL='/admin'"/>`

### ISSUE THREAD

**Issue by ke0ge** [projectdiscovery/nuclei#5478]
### Nuclei version:

v3.3.0
### Current Behavior:

redirects didn't work with `<meta http-equiv="refresh" content="1;URL='/admin'"/>`

### Expected Behavior:

first GET `/redirect.html`，then follow redirects to `/admin`

### Steps To Reproduce:

1. Create redirect.html:
```
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
       <meta http-equiv="refresh" content="1;URL='/admin'"/>
    </head>
</html>
```
2. Create simple-get-request.yaml:
```
id: simple-get-request

info:
  name: simple get request
  author: me
  severity: info

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    host-redirects: true
    max-redirects: 5
```
3. `python3 -m http.server 80`
4. `nuclei -u http://127.0.0.1/redirect.html -t . -id simple-get-request -debug -duc`
![image](https://github.com/user-attachments/assets/08404b65-1b57-41ba-8511-b5e579f48779)
![image](https://github.com/user-attachments/assets/501015d2-a480-4a9d-8ef2-340f3d99c397)

**Comment by dwisiswant0** [comment]
The `host-redirects` are relevant when dealing with 3XX status codes and it will follow the new location provided in the `Location` header of the response.
