### ISSUE TITLE
Add Socks5 proxy support

### ISSUE THREAD

**Issue by Zeokat** [projectdiscovery/nuclei#55]
I could see that you added proxy support, but if i'm not wrong, only HTTP/s proxies are supported.

Will be very usefull have Socks5 proxy support, i think that it can be possible, but i'm not an expert with Golang. Anyway a reference: https://godoc.org/golang.org/x/net/proxy#SOCKS5

Thanks for your attention.

**Comment by Mzack9999** [comment]
@Zeokat I was going to create this issue right now, but you have been faster. Thanks a lot for the suggestion!

**Comment by Zeokat** [comment]
I have a question here, how is supposed to be a proxy Socks5 URL?

Something like next line will work?

``socks5://user:pass@hostname:port``

**Comment by Mzack9999** [comment]
Works for me with a syntax like:

```
nuclei -t template.yml -proxy-socks-url "127.0.0.1:9050"
```

**Comment by Zeokat** [comment]
Ok, as soon as this commit is merged i will run some tests :+1:

**Comment by Zeokat** [comment]
Well, i could run some tests and found a little improvement that maybe can be done easily (not sure).

When you use HTTP/s proxy, the proxy URL schema can contain an `user:pass` combination to authenticate into proxy. For example:
```nuclei -v -nC -proxy-url "http://user:pass@187.150.xxx.xxx:8080" -l sitelist.txt -t "template/*.yaml" -o results.txt```

In HTTP/s proxy that schema works good, i tested into Nuclei and i can use it without problems. Good job! :+1: 

The problem is with SOCKS5 proxies, because these kind of proxies can be also authenticated by `user:pass` combination, but not follows the same schema as HTTP/s proxy. Sadly, with the actual Nuclei code seems that we can't pass username:password combination to authenticate in socks proxy.

Can be this fixed?

Thanks.

**Comment by Mzack9999** [comment]
@Zeokat This should be fixed in #60 . Now the syntax should be:

`nuclei -t template.yaml -proxy-socks-url socks5://user:pass@proxy.address:port`

**Comment by Zeokat** [comment]
Waiting for the merge into master branch to run tests.

**Comment by Zeokat** [comment]
Tests done successfully! Authentication works good now with Socks5. Well done :+1:
