### ISSUE TITLE
[issue] nuclei `-l` flag not working

### ISSUE THREAD

**Issue by TMFRook** [projectdiscovery/nuclei#550]
**Describe the bug**
When I run nuclei with `-l urls.txt`, it returns `nothing found`. When I run it with `-t "https://single_host" it does.

With `-l`:

You'll notice trace.log says `no address found for host`.

![image](https://user-images.githubusercontent.com/68116003/108434050-02b18480-7215-11eb-81c3-13c8e1b30a75.png)

With `-t`:

![image](https://user-images.githubusercontent.com/68116003/108434147-2a085180-7215-11eb-9491-127e90fd653e.png)

 
**Nuclei version**
2.2.0

**Comment by geeknik** [comment]
In your first image, you used `pestore.swagger.io` which returns NXDOMAIN. In your second image, you used `petstore.swagger.io` which resolves to an IP.

**Comment by TMFRook** [comment]
Bah I
