### ISSUE TITLE
isPortOpen func doesnt work if the port is not specified in the input

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei#5524]
`isPortOpen(Host,Port)` func doesnt work if the port isnt specified in the input, for example:
```
nuclei -u https://123.123.123.123 -t /javascript/example.yaml
```
Expected result:
```
[DBG]  [example] Javascript Code:

        isPortOpen(Host, Port);

[DBG] [example] Precondition for request was satisfied
[DBG] [example] Dumped Javascript request for https://123.123.123.123:443:
Variables:
...
```

Actual result:
```
[DBG]  [example] Javascript Code:

        isPortOpen(Host, Port);

[WRN] [example] Could not execute request for https://123.123.123.123: [example:RUNTIME] could not execute pre-condition: dial tcp 123.123.123.123:0: connect: can't assign requested address
```

**Comment by dwisiswant0** [comment]
Please note that to pass parameters to JavaScript, you should use `args`, and dynamic DSL variables at runtime won’t reflect on JavaScript variables.

Example: https://github.com/projectdiscovery/nuclei-templates/blob/main/javascript/detection/samba-detect.yaml#L37

Also, `Port` is a special variable and it should NOT contain any DSL expr.

Workaround:

```
nuclei -t template.yaml -u http://HOST:PORT
```

```yaml
javascript:
  - code: isPortOpen(h, p)
    args:
      h: "{{Host}}"
      p: "{{Port}}"
```
```

**Comment by daffainfo** [comment]
I though nuclei can auto detect the port based on the protocol even though the `Port` isnt specified in the template
