### ISSUE TITLE
dast features enhanced

### ISSUE THREAD

**Issue by ansanyuan** [projectdiscovery/nuclei#5530]
### Please describe your feature request:

I hope nuclei can add controllable fields in XML, json, and headers in POST to fuzz points, otherwise the current fuzz (dast) function will seem a bit incomplete.
### Describe the use case of this feature:
Significantly increase the usability of nuclei fuzz so that it has practical value, rather than just being used in shooting ranges.
THX nuclei team. ^ ^

**Comment by ehsandeep** [comment]
@ansanyuan nuclei does support fuzzing all part of request, you just need to write custom template for it, see https://blog.projectdiscovery.io/nuclei-fuzzing-for-unknown-vulnerabilities/ for details.
