### ISSUE TITLE
[BUG]  yaml source code id unknown xxx.jsp format

### ISSUE THREAD

**Issue by Superhero-zero** [projectdiscovery/nuclei#5568]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

I found that id: anmei-weather.php-File-reading cannot call the yaml file in yaml text

only
id: anmei-weather_php-File-reading to invoke the yaml file

### Expected Behavior

I think this tool can support yaml source code id: anmei-weather.php-File-reading, this yaml text can still be called

### Steps To Reproduce

nuclei..exe -u http://xxx.com -t ./test.yaml

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```

**Comment by dwisiswant0** [comment]
Template ID must match expression `^([a-zA-Z0-9]+[-_])*[a-zA-Z0-9]+$`.
