### ISSUE TITLE
Skipped from target list as found unresponsive 30 times

### ISSUE THREAD

**Issue by Teicu** [projectdiscovery/nuclei#5652]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

I'm encountering the same issue regardless of the site or URL list I'm testing; the error persists across all attempts.

[INF] Skipped github.com:443 from target list as found unresponsive 30 times 

[INF] Skipped www.google.com:443 from target list as found unresponsive 30 times
 
Skipped x.com:443 from target list as found unresponsive 30 times

### Expected Behavior

not sure

### Steps To Reproduce

nuclei -u https://x.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.2

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.3.2 (latest)
[INF] Current nuclei-templates version: v10.0.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 255
[INF] Templates loaded for current scan: 7544
[INF] Executing 7542 signed templates from projectdiscovery/nuclei-templates
[WRN] Loading 2 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Templates clustered: 1457 (Reduced 1371 Requests)
[INF] Using Interactsh Server: oast.pro
[azure-domain-tenant] [http] [info] https://login.microsoftonline.com:443/x.com/v2.0/.well-known/openid-configuration ["65f4e401-7113-49dc-ad96-a12e72c308de"]
[waf-detect:cloudfront] [http] [info] https://x.com
[waf-detect:apachegeneric] [http] [info] https://x.com
[waf-detect:nginxgeneric] [http] [info] https://x.com
**[INF] Skipped x.com:443 from target list as found unresponsive 30 times**

### Relevant log output

```shell
➜  ~ nuclei -u https://x.com

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.2

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.3.2 (latest)
[INF] Current nuclei-templates version: v10.0.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 255
[INF] Templates loaded for current scan: 7544
[INF] Executing 7542 signed templates from projectdiscovery/nuclei-templates
[WRN] Loading 2 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Templates clustered: 1457 (Reduced 1371 Requests)
[INF] Using Interactsh Server: oast.pro
[azure-domain-tenant] [http] [info] https://login.microsoftonline.com:443/x.com/v2.0/.well-known/openid-configuration ["65f4e401-7113-49dc-ad96-a12e72c308de"]
[waf-detect:cloudfront] [http] [info] https://x.com
[waf-detect:apachegeneric] [http] [info] https://x.com
[waf-detect:nginxgeneric] [http] [info] https://x.com
[INF] Skipped x.com:443 from target list as found unresponsive 30 times
```

### Environment

```markdown
- OS: Mac
- Nuclei: v3.3.2
- Go: go version go1.21.3 darwin/arm64
```

### Anything else?

no, thank you

**Comment by ehsandeep** [comment]
@Teicu this being tracked / worked on at https://github.com/projectdiscovery/nuclei/issues/5564
