### ISSUE TITLE
[FEATURE] Detailed http responses in javascript code templates debug mode

### ISSUE THREAD

**Issue by KGorbakon** [projectdiscovery/nuclei#5662]
### Describe your feature request

Current http responses are not visible entirely, so it's impossible to debug javascripte code templates. 
![image](https://github.com/user-attachments/assets/27298ca7-9ef9-42d3-830e-df57d32f7f95)

There should be an option to view them entirely as it works in raw http tempates debug mode. 

### Describe the use case of the feature

The template creator is testing the template. If there was no match when testing the template on a vulnerable stand, the creator launches nuclei with the debug option, and the system displays http requests and responses in their entirety.

### Describe alternatives you've considered

1. If i start nuclei with options -sresp/-srd all request/response should be stored entirely. How it looks now: 
![image](https://github.com/user-attachments/assets/8467f980-246b-43f3-9c3b-fbd135804bf9)

2. Javascript code templates might be intercepted with option -p (-proxy).

### Additional context

Tested on template:
```
javascript:
  - code: |   
      let m = require('nuclei/net');
      let address=Host+':'+Port;
      let conn;
      conn = m.OpenTLS('tcp', address)
      conn.Send('GET / HTTP/1.1\r\nHost:'+Host+'\r\nConnection: close\r\n\r\n');
      conn.RecvString();

    args:
      Host: "{{Host}}"
      Port: "443"
```

Nuclei Engine Version: v3.3.1

**Comment by GeorginaReeder** [comment]
Thanks so much for this feature request @KGorbakon , we'll take a look into it!
