### ISSUE TITLE
[BUG] Do not use backticks in shell files

### ISSUE THREAD

**Issue by vil02** [projectdiscovery/nuclei#5684]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

[gh_retry.sh](https://github.com/projectdiscovery/nuclei/blob/d1614857bd345affb24f209aeebde94db7303b6d/gh_retry.sh) uses depreciated _backticks_ (cf. [SC2006](https://www.shellcheck.net/wiki/SC2006)).

### Expected Behavior

Not relevant.

### Steps To Reproduce

One can run [shellcheck](https://www.shellcheck.net/) on mentioned script.

### Relevant log output

Not relevant.

### Environment

Not relevant.

### Anything else?

Feel free to assign me to this issue.

Usually I would submit a PR directly, but the [contribution guidelines](https://github.com/projectdiscovery/nuclei/blob/d1614857bd345affb24f209aeebde94db7303b6d/CONTRIBUTING.md) asked to create an issue first.

**Comment by monu-y** [comment]
can someone assign this to me. I would like to take this forward.

**Comment by vil02** [comment]
@monu-y: please have a look at the `Anything else?` section of my post.
