### ISSUE TITLE
Making response from difference input formats (Burp XML file, Proxify logs...) available in the context of Nuclei template

### ISSUE THREAD

**Issue by nth347** [projectdiscovery/nuclei#5723]
### Describe your feature request

Making response from difference input formats (Burp XML file, Proxify logs...) available in the context of Nuclei template for further inspection and comparison when needed.

### Describe the use case of the feature

There is a use case when I want to compare the test response (returned by the test request sent by a Nuclei template) to the original response from the input (Burp XML file) for confirming vulnerabilities.

### Describe alternatives you've considered

If Nuclei templates do not support this, I need to code the tool myself for performing the comparison (between test response and original response).

**Comment by dogancanbakir** [comment]
duplicate of https://github.com/projectdiscovery/nuclei/issues/5722
