### ISSUE TITLE
[BUG] Headless Options fails to split properly when comma is present in option value

### ISSUE THREAD

**Issue by r3naissance** [projectdiscovery/nuclei#5743]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

```
nuclei -target http://testphp.vulnweb.com -headless -nh -ho '--window-size=1280,800'

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.4

                projectdiscovery.io

[FTL] Could not create runner: [launcher] Failed to get the debug url: [1017/214522.609371:ERROR:command_line_handler.cc(103)] Malformed window size: 1280
```

### Expected Behavior

Seems like the https://github.com/projectdiscovery/nuclei/blob/dev/cmd/nuclei/main.go#L408 is the cause of the issue where `goflags.FileCommaSeparatedStringSliceOptions`

Perhaps we could use a substitute character (':' || 'x')..?

`-ho '--window-size=1280:800'` OR `-ho '--window-size=1280x800'`

Then when the String[] is split on commas, logic could be added to replace the substitute character back to a comma?

I attempted to escape the comma but would throw the same error `Malformed window size: 1280\,800`

### Steps To Reproduce

```
nuclei -target http://testphp.vulnweb.com -headless -nh -ho '--window-size=1280,800'

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.4

                projectdiscovery.io

[FTL] Could not create runner: [launcher] Failed to get the debug url: [1017/214522.609371:ERROR:command_line_handler.cc(103)] Malformed window size: 1280
```

### Environment

- OS: Kali
- Nuclei: v3.3.4
- Go: go version go1.23.2 linux/amd64

### Anything else?

:heart: ProjectDiscovery!

**Comment by dogancanbakir** [comment]
As a workaround, you can try  ``'`--window-size=1280,800`'``
