### ISSUE TITLE
[FEATURE] sdk functions to access workflows & store

### ISSUE THREAD

**Issue by iuliu8899** [projectdiscovery/nuclei#5765]
### Describe your feature request

access workflow templates and engine store by using sdk

There are GetTemplates func but no GetWorkflows function. 

And for engine.Store, I hope to get the store so that get templates more flexiable

### Describe the use case of the feature

To analyze the relationship between templates and subtemplates, I need to get all workflows.

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @iuliu8899 , we'll take a look into this!
