### ISSUE TITLE
Nuclei templates issues

### ISSUE THREAD

**Issue by Mathumitha97** [projectdiscovery/nuclei#5785]
While using nuclei, templates are not recognised even if I specify with the whole path it simply scanning with all the templates,I tried to validate templates it shows error.

**Comment by dogancanbakir** [comment]
It would be helpful to have additional details. Could you include the command and the output?

**Comment by Mathumitha97** [comment]
Yes, I will.

**Comment by Mathumitha97** [comment]
![Image](https://github.com/user-attachments/assets/a30839a9-3cb7-4d71-b2b7-3e212edd0765)

**Comment by Mathumitha97** [comment]
![Image](https://github.com/user-attachments/assets/57d837c8-d69e-479c-9eaf-210bc9649061)

**Comment by Mathumitha97** [comment]
Before when tried to run it simply scans with all templates instead of particular template

**Comment by Mathumitha97** [comment]
Even after updating nuclei and nuclei templates it shows the same error , please help me to resolve this issue..

**Comment by noob6t5** [comment]
Hello there ,
For using _dast_   based templates , You need to use **-dast** option.


Like this
`nuclei -l subdomain.txt -dast /path/for/templates` .

**Comment by dogancanbakir** [comment]
@Mathumitha97 Have you tried the cmd @noob6t5 shared?

**Comment by Mathumitha97** [comment]
Yes still it is not working, instead of one templates it loaded all the templates,it shows no permission and some templates are unsigned.

**Comment by dogancanbakir** [comment]
@Mathumitha97 My bad. The previous command @noob6t5 shared should include `-t` flag as well. The `-dast` flag is only to enable DAST feature. Here, a working cmd:

`nuclei -u honey.scanme.sh -t /home/mathumitha/.local/nuclei-templates/dast -dast`

Closing the issue. Feel free to reopen if the issue persists.
