### ISSUE TITLE
[BUG] No error when directory doesn't exist or is not writable

### ISSUE THREAD

**Issue by JaneX8** [projectdiscovery/nuclei#5824]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

I noticed that when using `-jsonl /somepath/file.jsonl` does not throw any error when the path does not exist or there are no sufficient permissions to write to that path. In this case nuclei exists normally but no findings are written to disk.

### Expected Behavior

Thrown an error that the path is not writable or does not exist, even before the scan starts.

### Steps To Reproduce

Output to a any non-existing path using like `-jsonl /tmp/some1/random2/dir3/file4.jsonl`

### Environment

```markdown
- OS: alpine 3.20
- Nuclei: v3.3.5
- Go: 1.22.9
```

**Comment by dogancanbakir** [comment]
In addition to `-jsonl`, you must also provide `-o` to specify the output file location. Ref: https://docs.projectdiscovery.io/tools/nuclei/running#nuclei-flags. I am closing this. Feel free to reopen if you have any other questions.
