### ISSUE TITLE
[BUG] nuclei fails to create the markdown files

### ISSUE THREAD

**Issue by s7e11ar** [projectdiscovery/nuclei#5842]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

When running nuclei with the `-me markdown` argument, sometimes nuclei fails to create the markdown files. Fails silently.

### Expected Behavior

Markdown files are expected to be created in the directory provided to nuclei. A visible error/warning indicating a failure mode.

### Steps To Reproduce

Run:
`mkdir ./markdown`
 `nuclei -l targets.txt \
-H $USERAGENT \
-iserver $INT_SERVER \
-itoken $INT_TOKEN \
-ts \
-stats \
-si 200 \
-je nuclei-scan.json \
-me markdown \
-o nuclei-scan.txt
`

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Kali 6.1.0-25-amd64
- Nuclei: v3.3.6
- Go: go1.22.6 linux/amd64
```

**Comment by jimen0** [comment]
If you could please share an example template and endpoint raw response that emits errors I could look into this next week.

**Comment by s7e11ar** [comment]
Hi @jimen0 it's failing silently. No output errors in terminal output. Is there a error log I can retreive?

**Comment by jimen0** [comment]
As said before, a reproducer (template and target/responses served by the target so I can build one locally) would be useful. Without one I can't help you here.

**Comment by s7e11ar** [comment]
The issue was using `tee` with my command. I think that broke the output somehow. Removing that worked.
