### ISSUE TITLE
[BUG] Docker Image for release 3.3.6 is missing

### ISSUE THREAD

**Issue by J12934** [projectdiscovery/nuclei#5844]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Latest build image is [v3.3.5](https://hub.docker.com/layers/projectdiscovery/nuclei/v3.3.5/images/sha256-71a996d15409d7b64d1c12d38f1807c5b121284c47c33cee29508c3427e6041d?context=explore)

### Expected Behavior

3.3.6 should be available in docker hub: https://hub.docker.com/r/projectdiscovery/nuclei/tags

### Steps To Reproduce

docker pull projectdiscovery/nuclei:v3.3.6

### Relevant log output

```shell
Error response from daemon: manifest for projectdiscovery/nuclei:v3.3.6 not found: manifest unknown: manifest unknown
```

### Environment

```markdown
- OS: MacOS
- Nuclei: v3.3.6
- Go:
```

**Comment by dogancanbakir** [comment]
We pushed here two days ago, see https://hub.docker.com/layers/projectdiscovery/nuclei/v3.3.6/images/sha256-3ba4267c2c7af9b292e14a5a0666392a1404275d48f3dce336e0fc27c29a36ee?context=explore
