### ISSUE TITLE
[issue] update-templates misc bug fixes and updates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#585]
- [x] Bug:- All templates are marked as modified apart from the newly added ones.
- [x] Update:- Printing only newly added templates on terminal
- [x] Addition: Adding newly added templates to cache to reuse for https://github.com/projectdiscovery/nuclei/issues/567

**Comment by Ice3man543** [comment]
This is done in dev branch. Closing!
