### ISSUE TITLE
Add minimal setup instructions to readme

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#5865]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Nuclei readme is missing basic install instructions

### Expected Behavior

Add minimal go setup:
```
go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
```

**Comment by ehsandeep** [comment]
Added in https://github.com/projectdiscovery/nuclei/commit/25495925332ae2d50ab960f7eb0dd04d72b612fb
