### ISSUE TITLE
[issue] Unexpected matches with passive mode

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#587]
**Describe the bug**
Upon using `passive` flag to run templates on HTTP response data, we found unexpected matches, this is because `path` is not considered in offline mode, so its possible responses from the root page will be matched with a template having a specific matcher defined for specific endpoint resulting into the valid match but invalid result.

**Nuclei version**
dev

**Proposed fix**
As response data doesn't have requested path Information, and it is assumed that input data is response data of root URLs, `passive` template support should be limited to templates having `{{BaseURL}}` or `{{BaseURL}}/` as path to make the matchers works in the expected way.

**Comment by Ice3man543** [comment]
This is done in dev branch!
