### ISSUE TITLE
[BUG] ... context deadline exceeded while executing while running tcp and javascript template together

### ISSUE THREAD

**Issue by jeyaseelans86** [projectdiscovery/nuclei#5881]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Getting error while while running tcp and javascript template together

[WRN] [ssh-auth-methods] Could not execute request for ip:22: errKind=unknown-error [address=ip:22] context deadline exceeded

But individually running templates produces output
![Image](https://github.com/user-attachments/assets/f15c1128-ea5f-4a08-b058-f1721326679a)

[ssh-auth-methods] [javascript] [info] ip:22 ["["publickey","gssapi-keyex","gssapi-with-mic","password"]"]

nuclei -t ~/nuclei-templates/network/detection/openssh-detect.yaml -debug 
[openssh-detect:regex-1] [tcp] [info]ip:22 ["SSH-2.0-OpenSSH_8.0"]

### Expected Behavior

Both Templates should work while running together

### Steps To Reproduce

1. Run nuclei with javascript and tcp based templates together. 
nuclei -t ~/nuclei-templates/javascript/detection/ssh-auth-methods.yaml -t ~/nuclei-templates/network/detection/openssh-detect.yaml 

2. you will get [WRN] [ssh-auth-methods] Could not execute request for: ip:22 errKind=unknown-error [address=:22] context deadline exceeded

### Relevant log output

```shell
[INF] Current nuclei version: v3.3.6 (outdated)
[INF] Current nuclei-templates version: v10.0.4 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 74
[INF] Templates loaded for current scan: 2
[INF] Executing 2 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[DBG] [ssh-auth-methods] Executing Precondition for request
[DBG]  [ssh-auth-methods] Javascript Code:

        isPortOpen(Host, Port);

[INF] [openssh-detect] Dumped Network request for ip:22 address=ip:22
[openssh-detect:regex-1] [tcp] [info] ip:22 ["SSH-2.0-OpenSSH_8.0"]
[DBG] [openssh-detect] Dumped Network response for ip:22

00000000  53 53 48 2d 32 2e 30 2d  4f 70 65 6e 53 53 48 5f  |SSH-2.0-OpenSSH_|
00000010  38 2e 30 0d 0a                                    |8.0..|


[WRN] [ssh-auth-methods] Could not execute request for ip:22: errKind=unknown-error [address=ip:22] context deadline exceeded
```

### Environment

```markdown
- OS: MAC
- Nuclei: v3.3.6
- template v10.0.4
- Go: go1.23.1 darwin/arm64
```

### Anything else?

Thanks PD Team !

**Comment by dogancanbakir** [comment]
Thanks for opening the issue. I couldn't repro it. Could you retry it with a higher timeout and see if it works? Let us know!

**Comment by jeyaseelans86** [comment]
> Thanks for opening the issue. I couldn't repro it. Could you retry it with a higher timeout and see if it works? Let us know!

Yes its still reproducible. Tried on multiple networks , devices etc.. .

If needed can share more info over discord or github

**Comment by dogancanbakir** [comment]
Yes, please! My handle is same on Discord @dogancanbakir

**Comment by Mzack9999** [comment]
This seems fixed with [`https://github.com/projectdiscovery/fastdialer/pull/381](https://github.com/projectdiscovery/fastdialer/pull/381)

```console
% go run . -t ~/nuclei-templates/javascript/detection/ssh-auth-methods.yaml -t ~/nuclei-templates/network/detection/openssh-detect.yaml -u scanme.sh

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.7

                projectdiscovery.io

[INF] Current nuclei version: v3.3.7 (latest)
[INF] Current nuclei-templates version: v10.1.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 114
[INF] Templates loaded for current scan: 2
[INF] Executing 2 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 1
[openssh-detect] [tcp] [info] scanme.sh:22 ["SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.11"]
[ssh-auth-methods] [javascript] [info] scanme.sh:22 ["["publickey","password"]"]
mzack@MacBookPro nuclei % 
```
