### ISSUE TITLE
[issue] Output is missing when there's no results.

### ISSUE THREAD

**Issue by gaby** [projectdiscovery/nuclei#594]
**Describe the bug**
When running nuclei and no results are found, there's no output available to corroborate this. Using -json generates no output instead of `{}`, and running with `-o` generates no files.

* Suggestion:
- If there's no result and using -json, the program should output `{}`
- If there's no result and using -o , the program should generate an empty file

**Nuclei version**
v2.2.0 - Docker

**Screenshot of the error or bug**

```
~ $ ./nuclei -l urls.txt -t nuclei-templates/workflows/rabbitmq-workflow.yaml -json -o results.txt

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.2.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [rabbitmq-workflow] RabbitMQ Security Checks (@fyoorer)
[INF] Using 1 rules (0 templates, 1 workflows)
[INF] No results found. Happy hacking!

~ $ ls
nuclei            nuclei-templates  urls.txt
~ $ 

```

**Comment by ehsandeep** [comment]
Blank output file created upon no results in the latest release [v2.3.8](https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.8), thanks again for reporting this.

**Comment by gaby** [comment]
Thank you! 😁
