### ISSUE TITLE
[issue] in miscellaneous

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [projectdiscovery/nuclei#595]
all working fine but getting this issue in running miscellaneous "**[FTL] Error, no templates were found.**" while running 

cat alive-domain.txt | nuclei -silent -t ~/nuclei-templates/miscellaneous/  -H 'User-Agent: Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/85.0' -o nuclei_miscellaneous.txt

where as the templates were updates and others working fine

**Comment by geeknik** [comment]
Look for and edit the .nuclei-ignore file in your templates directory. 👍🏻

**Comment by GDATTACKER-RESEARCHER** [comment]
i guess it worked
