### ISSUE TITLE
Does this program have thread parameters?

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/nuclei#597]
hello. thanks for great project.. When I looked at the available parameters, I couldn't find the thread parameter. Do you think I'm looking wrong? Which parameter should we use to use thread? thanks

**Comment by ehsandeep** [comment]
@Phoenix1112 Hey, check this out https://nuclei.projectdiscovery.io/nuclei/get-started/#rate-limits

**Comment by Phoenix1112** [comment]
@ehsandeep thanks <3
