### ISSUE TITLE
[issue] nuclei crash

### ISSUE THREAD

**Issue by linksucre** [projectdiscovery/nuclei#599]
nuclei -target http://127.0.0.1  -t fuzzing/wp-plugin-scan.yaml  
![image](https://user-images.githubusercontent.com/22881777/110435265-c96e8500-80ed-11eb-986c-3fa199f05e03.png)
![image](https://user-images.githubusercontent.com/22881777/110435314-d7bca100-80ed-11eb-9090-10d907181074.png)

**Comment by ehsandeep** [comment]
closing as this is already fixed.
