### ISSUE TITLE
[feature] Skip/Ignore Templates With A Tag

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/nuclei#602]
**Is your feature request related to a problem? Please describe.**
Nuclei now has tag support for when you want to run templates that match a tag but I would also like to be able to ignore by tag as well.

**Describe the solution you'd like**
For example `-exclude-tags xss,token` would run all templates except those with the XSS tag

**Comment by ehsandeep** [comment]
@meme-lord `exclude-tags` / `etags` to exclude the tags, also `dos` will be excluded as default.
