### ISSUE TITLE
[issue] DNS templates no longer work with 2.3.0

### ISSUE THREAD

**Issue by Marmelatze** [projectdiscovery/nuclei#606]
**Describe the bug**
The DNS templates (e.g. azure-takeover-detection) no longer work, as the retryabledns resolver does not return the DNS response if it encounters a NXDomain "retryabledns/client.go:57" instead it returns the "could not resolve, max retries exceeded" error.

**Nuclei version**
2.3.0

**Screenshot of the error or bug**
2.2.0:
![Screenshot 2021-03-11 um 11 29 12](https://user-images.githubusercontent.com/199681/110773513-1b81e880-825d-11eb-8a80-9db9747e9d61.png)

2.3.0:
![Screenshot 2021-03-11 um 11 31 05](https://user-images.githubusercontent.com/199681/110773671-49ffc380-825d-11eb-9040-006784fbd5a4.png)

**Comment by Ice3man543** [comment]
@Marmelatze This is fixed by PR #615. We will create a new release with patches soon!
