### ISSUE TITLE
[issue] [FTL] Error, no templates were found.

### ISSUE THREAD

**Issue by coffeehb** [projectdiscovery/nuclei#608]
**Describe the bug**
I'm sorry, I can't understand this error. Please help me answer.

```nuclei -t headless/ -u http://demo.testfire.net/```

Why does it always report an error： [FTL] Error, no templates were found.

**Nuclei version**
v2.3.0

**Screenshot of the error or bug**

![image](https://user-images.githubusercontent.com/5829776/110884968-f22a9080-8320-11eb-88d4-8a390438a6fd.png)

**Comment by Ice3man543** [comment]
To run headless templates, you also need to pass -headless flag. This is done to prevent users from running all headless templates by mistake as they are quite intensive by nature.

Also the headless/ directly is excluded by default, so you need to manually pass the templates in headless directory you need to run. Let me know if that helps!

**Comment by coffeehb** [comment]
![image](https://user-images.githubusercontent.com/5829776/110885731-58fc7980-8322-11eb-9409-ca5dc6962efe.png)

the same error with : nuclei -tags headless -u http://demo.testfire.net/ -t headless/window-name-domxss.yaml

Can you show me the correct command to use headless mode?

**Comment by geeknik** [comment]
You'll need to add the `-headless` flag to your command line.

`nuclei -headless -tags headless -u http://demo.testfire.net/ -t headless/window-name-domxss.yaml`

**Comment by coffeehb** [comment]
@geeknik  thank you very much, I succeeded
