### ISSUE TITLE
[issue] Output file is missing when no results are found

### ISSUE THREAD

**Issue by gaby** [projectdiscovery/nuclei#618]
**Describe the bug**
When running nuclei with -o and/or -json if there's no results nuclei doesn't create an output file. I would expect that if there's no results it would still write some kind of metadata file saying that no results were found.

Even an empty file with `{}` would help.

**Nuclei version**
Version 2.3.0

**Screenshot of the error or bug**

```
usr/local/bin # echo hackerone.com | ./nuclei -t dns/cname-service-detector.yaml -o output.txt -json

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.0

		projectdiscovery.io

[INF] Loading templates...
[INF] [cname-service-detector] 3rd party service checker (@pd-team) [info]
[INF] Loading workflows...
[INF] Using 1 rules (1 templates, 0 workflows)
[INF] No results found. Better luck next time!
/usr/local/bin # ls -la
total 25140
drwxr-xr-x    1 root     root          4096 Mar 14 05:41 .
drwxr-xr-x    1 root     root          4096 Feb 17 15:07 ..
-rwxr-xr-x    1 root     root      25730485 Mar 13 20:18 nuclei
```

**Comment by ehsandeep** [comment]
@gaby looks like a duplicate of another issue you raised here https://github.com/projectdiscovery/nuclei/issues/594?

**Comment by gaby** [comment]
@ehsandeep I completly forgot I created that issue, i'm closing this one
