### ISSUE TITLE
[issue] nuclei stuck on 99%

### ISSUE THREAD

**Issue by mr-n30** [projectdiscovery/nuclei#624]
**Describe the bug**
nuclei stuck on 99%

**Nuclei version**
v2.3.1

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/69602501/111095636-e2bb6b00-850b-11eb-8d87-1f777ff04dfd.png)

**command used**
```bash
nuclei \
    -c 100 \
    -stats \
    -headless \
    -severity high \
    -severity critical \
    -l httpx.txt \
    -t nuclei-templates/ \
    -o nuclei.txt
```

**env**
DigitalOcean
```bash
root@vps:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Comment by Ice3man543** [comment]
@mr-n30 using high values of -c such as `100` along with `headless` will cause unexpected things to happen, since for each -c value, a browser tab is launched so it is quite resource intensive.

Can you try running with lower values of -c and see if you can reproduce the hang?

**Comment by mr-n30** [comment]
Hello @Ice3man543,

Removing -headless fixed the issue. I guess it's not recommended to run `-c 100` with systems that have little RAM. Using the same command without -headless finished in about 30 minutes:
![image](https://user-images.githubusercontent.com/69602501/111115543-c0891380-8532-11eb-979a-cd103c1e3645.png)

Trying again with the same command and using the -headless flag has been stuck around 27%-28% for the past hour:
![image](https://user-images.githubusercontent.com/69602501/111115629-e4e4f000-8532-11eb-8286-5a32a6654d74.png)

I think maybe a check in the yaml/templates files for `headless` should spawn headless browsers when needed the same way nuclei checks for severity.

**Comment by geeknik** [comment]
> I think maybe a check in the yaml/templates files for `headless` should spawn headless browsers when needed the same way nuclei checks for severity.

That is why you have to specify the -headless flag. They won't run otherwise. 👍🏻

**Comment by ehsandeep** [comment]
@mr-n30 avoid using `-headless` flag if you are not using headless-based templates, even if you are using a headless template make sure to run specific templates instead of running with all.
