### ISSUE TITLE
[issue] Running nuclei with non-root user in supervisor config file crashes

### ISSUE THREAD

**Issue by m-Schlitzer** [projectdiscovery/nuclei#631]
**Describe the bug**
In our setup we call nuclei from another go binary, which gets started by supervisord. While working through the cves/2020 (all others work fine) directory nuclei crashes with 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6fb110]
```

This only happens when we set the user to something other than root in the config file. If we let the service run as root, or we exclude the cves/2020 directory, nuclei does not crash.

**Nuclei version**
`Current Version: 2.3.0`

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/20104782/111300604-91b58f00-8651-11eb-88e4-ca73d6ae6e06.png)

I have created a repository with the necessary files to reproduce the error. https://github.com/m-Schlitzer/nuclei-supervisor-crash
All you need to do is clone it and then:
```
go build
docker build . -t nuclei-supervisor-crash
docker run nuclei-supervisor-crash
```

**Comment by ehsandeep** [comment]
@m-Schlitzer we fixed a crash issue and created a new release [here](https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.1), can you make sure to update it to the latest version 2.3.1 and retry?

**Comment by m-Schlitzer** [comment]
Ok, tried with 2.3.1 now and the crash still happens.

**Comment by ehsandeep** [comment]
@m-Schlitzer should be now fixed in the master code, we will create a new release shortly, thanks again for reporting this.
