### ISSUE TITLE
[issue] hostMap         *hybrid.HybridMap doesn't clear resources after launching nuclei

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei#632]
Hi team.

**Describe the bug**
if i understand it properly, according to that code, hostMap should clean resources. 

```

// Close releases all the resources and cleans up
func (r *Runner) Close() {
	if r.output != nil {
		r.output.Close()
	}
	r.hostMap.Close()
	if r.projectFile != nil {
		r.projectFile.Close()
	}
}

```

But you can check my screenshot. It doesn't work. It become a problem when we use nuclei at server without rebooting. It creates thouthands of folders in one day.

<img width="876" alt="Screenshot 2021-03-17 at 15 17 17" src="https://user-images.githubusercontent.com/5173352/111466190-05c86380-8734-11eb-9047-a0eae93a227b.png">

**Nuclei version**
2.3.0

Thanks!

**Comment by geeknik** [comment]
Can confirm with 2.3.1 built from `5cd493`. 

![2021-03-17_09-19](https://user-images.githubusercontent.com/466878/111482435-cf86e600-872b-11eb-93cb-e2a661e0c7bc.png)

**Comment by ehsandeep** [comment]
Closing this, as the new release is created with fix.
