### ISSUE TITLE
[issue] 2.3.1 workflows load ALL existing templates.

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei#635]
Hi team.

**Describe the bug**
in 2.3.1 version launching workflows loads ALL templates
<img width="1435" alt="Screenshot 2021-03-19 at 12 23 42" src="https://user-images.githubusercontent.com/5173352/111758931-1ef51f80-88ae-11eb-9a09-0acb9d97b063.png">

as you see 2.3.0 couldn't parse workflow. but 2.3.1 started load every existing template. so it generates tones of requests on any workflow

**Nuclei version**
2.3.1

Thanks.

**Comment by notwhy** [comment]
also on my mac and centos .

**Comment by ehsandeep** [comment]
looks like sharing the same root cause as https://github.com/projectdiscovery/nuclei/issues/628, we will be pushing fix and release shortly.

**Comment by ehsandeep** [comment]
@savushkin-yauheni this should be fixed in the master code.
