### ISSUE TITLE
"[FTL] Error, no templates were found." regarding Headless and Workflows 

### ISSUE THREAD

**Issue by d4715** [projectdiscovery/nuclei#649]
Hello there, 

I have some problem in my two scripts.

I made 2 scripts regarding headless and workflows

but when i ran those scripts i got this error :> "[FTL] Error, no templates were found."

1)OS DETAILS :
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.1"
VERSION_ID="2021.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

2)Nuclei Current Version: 2.3.2

3)Nuclei-Templates : v8.1.7

1) headless  
this is my script:

#!/bin/bash

nuclei -l $1 -t /root/nuclei-templates/headless/dvwa-headless-automatic-login.yaml -silent -c 50 | tee /root/Desktop/vianuc/headless/dvwa-headless-automatic-login.txt
nuclei -l $1 -t /root/nuclei-templates/headless/postmessage-tracker.yaml -silent -c 50 | tee /root/Desktop/vianuc/headless/postmessage-tracker.txt
nuclei -l $1 -t /root/nuclei-templates/headless/prototype-pollution-check.yaml -silent -c 50 | tee /root/Desktop/vianuc/headless/prototype-pollution-check.txt
nuclei -l $1 -t /root/nuclei-templates/headless/window-name-domxss.yaml -silent -c 50 | tee /root/Desktop/vianuc/headless/window-name-domxss.txt

i open mousepad and paste code in it and save as headlesstoday.sh

then i used this command chmod +x headlesstoday.sh for excute this script

my command is :> ./headlesstoday.sh 1.txt :> 1.txt is my target file in this txt i paste some wesbite's url like this 
                                                                                         https://www.example.com
											 https://example.com
											 https://1.example.com
whenever i ran my script i got error "[FTL] Error, no templates were found."											 

here you can see error :> IMAGE 1.JPG (PLEASE SEE THIS)
![IMAGE 1](https://user-images.githubusercontent.com/11803332/112742262-990e5e00-8faa-11eb-84a4-b05717b8573f.JPG)

											 
2)workflows											 
this is my script:

#!/bin/bash

nuclei -l $1 -t /root/nuclei-templates/workflows/artica-web-proxy-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/artica-web-proxy-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/bigip-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/bigip-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/cacti-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/cacti-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/cisco-asa-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/cisco-asa-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/dell-idrac-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/dell-idrac-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/grafana-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/grafana-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/harbor-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/harbor-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/jira-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/jira-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/liferay-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/liferay-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/lotus-domino-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/lotus-domino-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/magmi-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/magmi-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/micro-focus-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/micro-focus-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/mida-eframework-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/mida-eframework-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/netsweeper-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/netsweeper-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/rabbitmq-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/rabbitmq-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/samsung-wlan-ap-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/samsung-wlan-ap-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/sap-netweaver-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/sap-netweaver-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/solarwinds-orion-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/solarwinds-orion-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/springboot-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/springboot-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/thinkcmf-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/thinkcmf-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/thinkphp-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/thinkphp-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/vbulletin-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/vbulletin-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/weblogic-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/weblogic-workflow.txt
nuclei -l $1 -t /root/nuclei-templates/workflows/wordpress-workflow.yaml -silent -c 50 | tee /root/Desktop/vianuc/workflows/wordpress-workflow.txt

i open mousepad and paste code in it and save as workflowstoday.sh

then i used this command chmod +x workflowstoday.sh for excute this script

my command is :> ./workflowstoday.sh 1.txt :> 1.txt is my target file in this txt i paste some wesbite's url like this 
                                                                                         https://www.example.com
											 https://example.com
											 https://1.example.com
whenever i ran my script i got error "[FTL] Error, no templates were found."											 

here you can see error :> IMAGE 2.JPG (PLEASE SEE THIS)
![IMAGE 2](https://user-images.githubusercontent.com/11803332/112742252-8e53c900-8faa-11eb-8824-93726d4d801d.JPG)

**NOTE:> ALL OTHER SCRIPTS ARE PERFECLTY RUNNING THESE 2 SCRIPTS ARE NOT WORKING PROPERLY SO PLEASE GUIDE ME HOW CAN I SOLVE THIS ISSUE** 

I am waiting for your reply.

Thanks and Regards,
d4715

**Comment by ehsandeep** [comment]
Hey, just replace the 't' with 'w' for workflows and it will work as expected.

**Comment by ehsandeep** [comment]
Closing as this is not an issue, check https://nuclei.projectdiscovery.io/nuclei/get-started/#running-nuclei for more details.

**Comment by d4715** [comment]
Hello @ehsandeep 
As per suggestion i replaced w with t for workflows and yes it's work for me now i am successfully run my workflowstoday.sh script. Thank You . 
Please help me for my headless script issue. How can i solve headless script issue?
I am waiting for your reply
Thanks and Regards,
d4715

**Comment by d4715** [comment]
Hello @ehsandeep 
can i get any update regarding headless ?
Thanks and Regards,
d4715

**Comment by geeknik** [comment]
@d4715 In order to use the headless templates, please run nuclei with the -headless flag:

`nuclei -headless -t $template -target $target`

**Comment by ehsandeep** [comment]
@d4715 right, you need to use `-headless` flag in order to run a headless based template, but beware, headless templates are not meant to run along with regular templates and can not be used to run at scale as it really runs a real browser and has it's limitations so I will not suggest them running as you doing now and should be used for specific runs.

**Comment by d4715** [comment]
Thank You @geeknik @ehsandeep  for this valuable information
