### ISSUE TITLE
[issue] Unsolicited response 

### ISSUE THREAD

**Issue by knowthetech** [projectdiscovery/nuclei#650]
2021/03/29 23:31:38 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 200 BANNED\r\n"; err=<nil>

**Comment by ehsandeep** [comment]
Hey @knowthetech, this doesn't look like an issue but a server response, do you have more relevant details to share?

**Comment by knowthetech** [comment]
https://github.com/golang/go/issues/19895  this seems to be same

**Comment by ehsandeep** [comment]
thanks for sharing this, this is not an issue and this response depends on the target server you are scanning and not related to nuclei, with that said, I'm closing this issue.
