### ISSUE TITLE
[issue] Latest Docker image points to wrong release

### ISSUE THREAD

**Issue by gaby** [projectdiscovery/nuclei#651]
**Describe the bug**
The current latest image of nuclei is pointing to release 2.3.1 instead of 2.3.2

**Logs**
ubuntu@ubuntu-vb:~$ docker run -it --rm projectdiscovery/nuclei -version
Unable to find image 'projectdiscovery/nuclei:latest' locally
latest: Pulling from projectdiscovery/nuclei
ba3557a56b15: Pull complete 
712067766eba: Pull complete 
4402ba7fde2c: Pull complete 
Digest: sha256:9e5fba920e92b4570f81779b7d2f3c0ca7a2fff1df54535033f01796df76e373
Status: Downloaded newer image for projectdiscovery/nuclei:latest

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.1

		projectdiscovery.io

[INF] Current Version: 2.3.1

**Comment by ehsandeep** [comment]
thank you @gaby, should be fixed now.

**Comment by gaby** [comment]
Thanks!
