### ISSUE TITLE
Fuzzing templates excluded without nuclei-ignore flag set

### ISSUE THREAD

**Issue by shotop** [projectdiscovery/nuclei#653]
**Describe the bug**
When attempting to run the fuzzing/ directory, I see messages that the templates in the directory are excluded due to the nuclei-ignore filter.  I do not have the filter set though.  This error started occurring within the past 24 hours on the latest version of nuclei.  

**Nuclei version**
![Screen Shot 2021-04-01 at 9 55 04 AM](https://user-images.githubusercontent.com/510693/113312901-5a411680-92d0-11eb-9dc0-a686fae86ee6.png)

**Screenshot of the error or bug**
![Screen Shot 2021-04-01 at 9 53 56 AM](https://user-images.githubusercontent.com/510693/113312748-38479400-92d0-11eb-9f97-8b0480294a57.png)

**Comment by geeknik** [comment]
Hello. Look for the .nuclei-ignore file in your nuclei-templates directory. Remove the entry for the fuzzing directory. Good luck out there. 👍🏻

**Comment by shotop** [comment]
I feel shame.  Thank you!
