### ISSUE TITLE
Cannot run single specific nuclei-ignored (fuzzing) templates

### ISSUE THREAD

**Issue by shotop** [projectdiscovery/nuclei#654]
I will preface this by saying this could totally be user error (I submitted an issue this morning that was!), but I've read the docs and also the release notes, which within the past 24 hours seem to be related to an issue I'm having, so I've decided to post this issue. 

**Describe the bug**
I understand that full template directories by default are disabled, fuzzing/ for example.  As a result, I've tried to edit the .nuclei-ignore file to remove the lines for fuzzing, as well as remove it all together.  I've also tried to run single fuzzing templates, but still no luck.  Can anyone spot what I am doing wrong?  I thought maybe I had to pass an additional flag to turn off the ignore filter, but I haven't found anything that made sense. 

**Nuclei version**
![Screen Shot 2021-04-01 at 3 21 13 PM](https://user-images.githubusercontent.com/510693/113349591-eb7ab200-92fd-11eb-9317-75af69d5e95a.png)

**Screenshot of the error or bug**
*trying to run a single fuzzing template*
![Screen Shot 2021-04-01 at 3 26 14 PM](https://user-images.githubusercontent.com/510693/113350102-9ee3a680-92fe-11eb-90bc-95c8dcb28d2f.png)

*nuclei-ignore file has been completely removed*
![Screen Shot 2021-04-01 at 3 26 56 PM](https://user-images.githubusercontent.com/510693/113350213-c76ba080-92fe-11eb-8f37-e135ec929873.png)

**Comment by ehsandeep** [comment]
Hi @shotop, 

Once you edited or removed the ignore file, you can run those templates like this `nuclei -t urls.txt -t fuzzing/generic-lfi-fuzzing.yaml`, we are also going to change something to make this more simple.

**Comment by shotop** [comment]
Hello @ehsandeep, thanks for responding.  I went ahead and shortened it like you suggested but still get the same issue.  Is it possible there is a second location for the nuclei-ignore file?

![Screen Shot 2021-04-01 at 4 07 35 PM](https://user-images.githubusercontent.com/510693/113354248-81b1d680-9304-11eb-87bc-6da38330e11c.png)

**Comment by ehsandeep** [comment]
@shotop yes, I guess that's it, you need to remove from two locations `rm $HOME/nuclei-templates/.nuclei-ignore $HOME/.config/nuclei/.nuclei-ignore` it should be at once place only, this is a bug.

**Comment by shotop** [comment]
Thanks @ehsandeep - I went ahead and removed that second file, but it appears something is rewriting it when the executable is run.  Details below in case it helps you debug:

*removing the .config file and confirming it's removal*
![Screen Shot 2021-04-01 at 4 23 20 PM](https://user-images.githubusercontent.com/510693/113355567-98f1c380-9306-11eb-8a95-715b4dedc7ea.png)

*running the executable appears to add it back*
![Screen Shot 2021-04-01 at 4 24 21 PM](https://user-images.githubusercontent.com/510693/113355679-c0e12700-9306-11eb-951c-659651d054a6.png)


Let me know if I can provide any additional info and thanks for your help!

**Comment by ehsandeep** [comment]
@shotop we fixed this with the latest release of nuclei [v2.3.4](https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.4), now default ignored templates are ignored using [tags](https://github.com/projectdiscovery/nuclei-templates/blob/master/.nuclei-ignore), and you simply then using tags.

For example, fuzzing templates excluded as default, but you can run them using `-tags fuzz`, just make sure to download the latest nuclei and templates and everything will be smooth.

**Comment by shotop** [comment]
@ehsandeep Awesome - thanks for the quick turnaround!

**Comment by ehsandeep** [comment]
Thank you for reporting this @shotop, you can also jump into https://discord.gg/projectdiscovery for more discussions around this project.

**Comment by shotop** [comment]
Changes look good to me!
