### ISSUE TITLE
Add template attributes for cross-template connections

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#656]
An attribute should be added to allow defining before, after, etc steps that can be starlight code / yaml templates that define a pre-requisite action for a template to be run. Only when the actions match will the execution move forward.

This will be used by the planner to chart an execution flow for the scanning engine.

**Comment by forgedhallpass** [comment]
@Ice3man543 would the #1047 ticket solve this? If yes, please close this ticket.

**Comment by Ice3man543** [comment]
Yes, closing as duplicate.
