### ISSUE TITLE
[feature] Add template-id to config file (exclusions)

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#665]
**Is your feature request related to a problem? Please describe.**
I'm usually adding and removing templates from the config file, often need to find the path and name (from the output for example) 

**Describe the solution you'd like**
Wouldn't be easier just to reference the template-id ? 
For example use _**springboot-actuators-jolokia-xxe**_  instead of _**vulnerabilities/springboot/springboot-actuators-jolokia-xxe.yaml.**_

**Comment by forgedhallpass** [comment]
The problem with `template-id`s is that they are not necessarily unique, hence you might exclude unwanted templates. We have multiple ways of excluding templates, so the value it would bring vs the development/maintenance effort is not worth it for now. 

We might consider revisiting this in the future if more use cases would require it.

Thank you for the ticket though.
