### ISSUE TITLE
[issue] exclude tag invalid handler 

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei#666]
Hi team.

**Describe the bug**
```
nuclei  -t miscellaneous/unencrypted-bigip-ltm-cookie.yaml -target https://google.com  --debug

[WRN] Could not parse file '/root/nuclei-templates/miscellaneous/unencrypted-bigip-ltm-cookie.yaml': exclude-tags filter matched misc
[INF] Loading workflows...

```
that error should raise only if i pass exclude tag option, according to code:

```
if len(options.Options.ExcludeTags) > 0 && !matchWithTags {
		if err := matchTemplateWithTags(types.ToString(templateTags), types.ToString(template.Info["severity"]), options.Options.ExcludeTags); err == nil {
			return nil, fmt.Errorf("exclude-tags filter matched %s", templateTags)
		}
	}
```

But the original command doesn't contain an exclude tag option. Or i use it incorrect ?

**Nuclei version**
2.3.4

Thanks.

**Comment by ehsandeep** [comment]
Hey @savushkin-yauheni, we maintain the list of tags to exclude as default, here is the [list](https://github.com/projectdiscovery/nuclei-templates/blob/master/.nuclei-ignore), more details here https://nuclei.projectdiscovery.io/faq/templates/, you need to explicitly method those tags to run template with excluded tag s.
