### ISSUE TITLE
[issue] Severity based execution using tags doesn't respect excluded tags

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#671]
**Describe the bug**
Recently, we added support to run templates based on severity using `tags`, for `-tags low,medium` which also introduced a bug to run templates with excluded tags.

**Nuclei version**
2.3.4

```
nuclei-templates $echo http://0.0.0.0:8000 | nuclei -t miscellaneous/ -silent
[FTL] Error, no templates were found.

nuclei-templates $echo http://0.0.0.0:8000 | nuclei -t miscellaneous/ -tags low -silent
[2021-04-13 13:47:13] [missing-x-frame-options] [http] [low] http://0.0.0.0:8000
```

**Comment by Regala** [comment]
Can confirm this, also reproducible using `tags` and `exclude` config:

```
exclude-tags: info

exclude:
  - default-logins/
  - exposures/
  - fuzzing/
  - iot/
  - miscellaneous/missing*
  - miscellaneous/missing-x-frame-options
  - miscellaneous/missing-x-frame-options.yaml
```
Ends up still reporting `missing-x-frame-options`.

**Comment by Regala** [comment]
+- unrelated, but if in the config.yaml `update-directory` is set, why is it still necessary to provide the `-t` flag?

**Comment by ehsandeep** [comment]
> why is it still necessary to provide the -t flag?

@Regala is this question for **a)** nuclei template update or **b)** running templates using tags?

**Comment by Regala** [comment]
Hi @ehrishirajsharma, sorry this was more a generic question about the config file; what I meant was that if the update-directory is set on the config file, then there might not be necessary to supply the -t flag.

**Comment by ehsandeep** [comment]
@Regala so I'm assuming this is about running templates without the need of `-t` as we already know where the templates are stored, in that case, we can execute templates without using `-t` flag, i.e either using `tags` or `severity` flag which will execute based on the location of installed template, additionally w ecan also use `-t` flag to limit/filter templates to a specific directory.

**Comment by Regala** [comment]
Got it. Also on this exclude templates matter, I'm having issues excluding a single template using the config file. So e.g.:

`$ nuclei -u https://localhost -t ~/nuclei-templates`
![default](https://user-images.githubusercontent.com/1380527/119633699-ea4f9800-be09-11eb-932a-a9cbb3475f36.png)

(using the default configurations so `~/.config/nuclei/config.yaml` is not configured and `~/.config/nuclei/.nuclei-ignore` is:

```
tags:
  - "dos"
  - "iot"
  - "misc"
  - "fuzz"
  - "revision"
```

Now if I change the config to add the exclusion:
`exclude: ['exposures/tokens/google/']`

![nuclei2](https://user-images.githubusercontent.com/1380527/119634148-57632d80-be0a-11eb-9920-9879e3ee0ea6.png)

Which is great, it's concatenating the default exclusions with the user supplied. BUT if I try to exclude a single template it doesn't seem to work:
`exclude: ['exposures/tokens/google/google-api-key.yaml']`

![image](https://user-images.githubusercontent.com/1380527/119634314-8d081680-be0a-11eb-8022-62c928736811.png)

(note that unless we exclude the specific folder, that particular template is always picked up, [log attached](https://github.com/projectdiscovery/nuclei/files/6545382/nuclei.log))

Any ideas?
