### ISSUE TITLE
[feature] Adding random UA per request

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#672]
**Is your feature request related to a problem? Please describe.**
Currently, random UA is generated per template instead of per request.

**Describe the solution you'd like**
Generate random UA per request.

**Comment by yabeow** [comment]
Hi @ehsandeep,

With my merged PR (https://github.com/projectdiscovery/nuclei/pull/670), I believe that this issue also had been fixed.

**Comment by ehsandeep** [comment]
Can confirm this @yabeow thanks again :D, closing this issue as it's implemented in https://github.com/projectdiscovery/nuclei/pull/670
