### ISSUE TITLE
CodeQL warning zip: file paths

### ISSUE THREAD

**Issue by jfcg** [projectdiscovery/nuclei#675]
https://github.com/projectdiscovery/nuclei/blob/851d1c26053994a43166115d1d11e578c8ec5257/v2/internal/runner/update.go#L312-L322

CodeQL warns about zip files containing files named like `../some/thing`. Also is it always `len(paths) >= 2` ?

**Comment by Ice3man543** [comment]
@jfcg yes, the download is done using the Zip generated by Github for a release and is trusted to contain the correct paths. Closing this issue. Feel free to reopen if something is amiss.
