### ISSUE TITLE
showing the following error

### ISSUE THREAD

**Issue by Dixith1999** [projectdiscovery/nuclei#676]
**Describe the bug**
showing error

**Nuclei version**
latest version just updated

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
![Screenshot (372)](https://user-images.githubusercontent.com/29366858/114820753-23452780-9ddd-11eb-9477-b77327038bce.png)

**Comment by HJ23** [comment]
Here is text version of error : 


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9b4895]

goroutine 1159 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteHTTP(0xc002f3a960, 0xc000218870, 0xc001ba6f60, 0x13, 0x2d)
	/home/xxx/nuclei/v2/pkg/executer/executer_http.go:386 +0x5e5
github.com/projectdiscovery/nuclei/v2/pkg/workflows.(*NucleiVar).Call(0xc002f071d0, 0x0, 0x0, 0x0, 0xc003280028, 0x0, 0x7ff, 0x0)
	/home/xxx/nuclei/v2/pkg/workflows/var.go:89 +0x6b3
github.com/d5/tengo/v2.(*VM).run(0xc003280000)
	/home/xxx/go/pkg/mod/github.com/d5/tengo/v2@v2.6.2/vm.go:633 +0x3326
github.com/d5/tengo/v2.(*VM).Run(0xc003280000, 0x23, 0x30)
	/home/xxx/go/pkg/mod/github.com/d5/tengo/v2@v2.6.2/vm.go:77 +0xcf
github.com/d5/tengo/v2.(*Compiled).RunContext.func1(0xc002f35860, 0xc003280000)
	/home/xxx/go/pkg/mod/github.com/d5/tengo/v2@v2.6.2/script.go:222 +0x2b
created by github.com/d5/tengo/v2.(*Compiled).RunContext
	/home/xxx/go/pkg/mod/github.com/d5/tengo/v2@v2.6.2/script.go:221 +0x22d

**Comment by ehsandeep** [comment]
@HJ23 you are running an outdated version of nuclei, the latest one is 2.3.4, you can confirm with `nuclei -version`

**Comment by Dixith1999** [comment]
how to update to latest version?

**Comment by HJ23** [comment]
Afak you should do it manually (remove old one install new one) there is only option for update that is for template update . check out readme for more info (installation)

**Comment by Dixith1999** [comment]
not able to install again after removing nuclei
![Screenshot (374)](https://user-images.githubusercontent.com/29366858/114839196-1f240480-9df3-11eb-8dfc-af3260c85168.png)

**Comment by ehsandeep** [comment]
Hey, you are running an outdated version of GO as well, make sure you have the right environment before installing tools or just download the compiled binary, more details https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-installation

**Comment by ehsandeep** [comment]
Closing as this is not an issue with nuclei
