### ISSUE TITLE
Getting 'Error,  no templates were found.' - V2.3.4

### ISSUE THREAD

**Issue by ja1sh** [projectdiscovery/nuclei#680]
**Describe the bug**
Getting 'Error,  no templates were found.' error while running some nuclei templates.

**Nuclei version**
2.34

**Screenshot of the error or bug**

```

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.4

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[VER] Downloading config file from https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/master/.nuclei-ignore
[WRN] nuclei-templates are not installed (or indexed), use update-templates flag.
[VER] Identified 1 templates
[INF] Loading templates...
[WRN] Could not parse file '/home/kali/Downloads/tools/nuclei-templates/miscellaneous/phpmyadmin-setup.yaml': exclude-tags filter matched misc
[INF] Loading workflows...
[FTL] Error, no templates were found.
```

**Comment by ehsandeep** [comment]
@ja1sh few tags are [excluded](https://nuclei.projectdiscovery.io/nuclei/get-started/#template-exclusion) as default, you need to mention tags to run them, for this case, `-tags misc` to run this and other templates in this directory.

**Comment by ja1sh** [comment]
@ehsandeep Is there any way to clear the default exclusion list?

**Comment by ehsandeep** [comment]
it's not recommended but if you want, you can update your [own default config](https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-config) file to mention those tags to explicitly run them.

**Comment by ja1sh** [comment]
Thanks, @ehsandeep , closing this!
