### ISSUE TITLE
[issue] templates not correctly updated

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#682]
**Describe the bug**
So, I had a hit `` unauthenticated-cache-purge`` I looked for that template, but I couldn't find it. It had a filename `` misconfiguration/unautneicated-cache-purge.yaml `` I went to the template repo to check it out, but the name was [``unauthenticated-varnish-cache-purge.yaml``](https://github.com/projectdiscovery/nuclei-templates/blob/master/misconfiguration/unauthenticated-varnish-cache-purge.yaml) (typo was corrected recently).  I ran the template-update option several times and the template with the old name persisted. 

The flag -template-update does not deal with a template being renamed (it seams). 

**Nuclei version**
v2.3.4

**Comment by ehsandeep** [comment]
This is expected, check this out https://nuclei.projectdiscovery.io/faq/templates/

![image](https://user-images.githubusercontent.com/8293321/115141909-7547b080-a05c-11eb-838e-cdecb2fa7f35.png)

**Comment by pdelteil** [comment]
> This is expected, check this out https://nuclei.projectdiscovery.io/faq/templates/
> 
> ![image](https://user-images.githubusercontent.com/8293321/115141909-7547b080-a05c-11eb-838e-cdecb2fa7f35.png)

My bad. I just realized the new version was not on the latest template release.
