### ISSUE TITLE
[issue] Can't run headless template

### ISSUE THREAD

**Issue by omarhashem123** [projectdiscovery/nuclei#684]
**Describe the bug**
when running nuclei -tl -tags headless nuclei output this errors 

headless
[ERR] Could not parse file '/home/omar/nuclei-templates/headless/postmessage-tracker.yaml': cannot create template executer
[ERR] Could not parse file '/home/omar/nuclei-templates/headless/prototype-pollution-check.yaml': cannot create template executer
[ERR] Could not parse file '/home/omar/nuclei-templates/headless/dvwa-headless-automatic-login.yaml': cannot create template executer
[ERR] Could not parse file '/home/omar/nuclei-templates/headless/window-name-domxss.yaml': cannot create template executer

and try to run headless templates nuclei -t ~/nuclei-templates/headless/ -tags headless nuclei output [FTL] Error, no templates were found.

**Nuclei version**
v2.3.4

**Comment by geeknik** [comment]
Hi, please add the `-headless` flag to your command line and try again.

**Comment by omarhashem123** [comment]
## this error appear to me and checked proxy there is no requests were sent

![Screenshot from 2021-04-19 08-37-44](https://user-images.githubusercontent.com/70245773/115192584-4cbac780-a0eb-11eb-8681-35322399168f.png)

**Comment by ehsandeep** [comment]
@omarhashem123 headless templates are executed as default, you need to add `-tags headless` to run them, for more details :- https://nuclei.projectdiscovery.io/faq/templates/

**Comment by omarhashem123** [comment]
![Screenshot from 2021-04-19 10-04-49](https://user-images.githubusercontent.com/70245773/115202444-b4c2db00-a0f6-11eb-8c73-c633c7149db5.png)

**Comment by omarhashem123** [comment]
@ehsandeep
![Screenshot from 2021-04-19 10-04-49](https://user-images.githubusercontent.com/70245773/115202576-d1f7a980-a0f6-11eb-83e7-5b5abc6822e6.png)

**Comment by ehsandeep** [comment]
You missed `-headless` flag from your previous run, `-headless` flag and `-tags headless` both are different and required for this. @omarhashem123

**Comment by omarhashem123** [comment]
@ehsandeep
It works with me now
Thank you for your effort and for this great tool
