### ISSUE TITLE
Override stdin target in a raw request

### ISSUE THREAD

**Issue by zzeitlin** [projectdiscovery/nuclei#686]
**Is your feature request related to a problem? Please describe.**
Within #223, they state:
> I also noticed that nuclei connects to the host that is included in the RAW HTTP request, instead of connection to the one supplied by stdin.

I desire this behavior as I am having stdin (or file) be a list of strings to test against a set of custom templates. The templates have a hard-coded destination URLs, but they manipulate the strings provided by stdin.

If my template uses a RAW request, the `host` header is set by the template but the connection goes to the one provided by stdin.

If my template uses a non-RAW request, (i.e., a `- method: POST` with `path: - "..."`) then the header is set by the template and the connection goes to the one provided by the template (the desired behavior, only I lose my ability to perform needed helper functions).

**Describe the solution you'd like**
Is there a way to have the template specify the connection destination and override the input in stdin (or `-l`)?

**Comment by zzeitlin** [comment]
Realizing a solution to #554 (i.e., having global helper functions) would solve this for me. Going to close this and subscribe to that issue.

I almost solved my issue by using `network` requests, but those do not enable parameters/variables within the `data` portion of the request.

**Comment by ehsandeep** [comment]
@zzeitlin ^^ following PR now supports this: https://github.com/projectdiscovery/nuclei/pull/938
