### ISSUE TITLE
[issue] Problems running headless templates

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#687]
**Describe the bug**
So, it took me sometime to understand why my scan with only headless templates was not working, the only way that worked was: 

`` nuclei -stats -si 180 -t ~/nuclei-templates/headless/prototype-pollution-check.yaml  -l urls.txt -tags headless  -headless``

  ```  / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.4

		projectdiscovery.io

[INF] Loading templates...
[INF] [prototype-pollution-check] Prototype Pollution Check (@pdteam) [medium]
[INF] Loading workflows...
[INF] Using 1 rules (1 templates, 0 workflows)
```

All other options failed:

``nuclei -stats -si 180 -t ~/nuclei-templates/headless/prototype-pollution-check.yaml -headless -l urls.txt ``

```
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.4

		projectdiscovery.io

[INF] Loading templates...
[INF] Loading workflows...
[FTL] Error, no templates were found.

```

``nuclei -stats -si 180 -t ~/nuclei-templates/headless/prototype-pollution-check.yaml -l urls.txt ``

```
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.4

		projectdiscovery.io

[INF] Loading templates...
[INF] Loading workflows...
[FTL] Error, no templates were found.

```

**Nuclei version**
2.3.4

It's pretty confusing in my opinion. Isn't the tag flag unnecessary in this case?

**Comment by ehsandeep** [comment]
Please see the https://github.com/projectdiscovery/nuclei/issues/684 for more context.

> Isn't the tag flag unnecessary in this case

It is not, because you don't want someone running tons of URLs with a real browser and eventually nuclei will be crashed.

**Comment by ehsandeep** [comment]
Closing as this is expected, `-headless` flag to run headless based templates, and `-tags headless` as headless based templates are excluded as default, again you can alter your own config file to remove the need to using tags each time.
