### ISSUE TITLE
[issue/question] any reason I always get errors?

### ISSUE THREAD

**Issue by gprime31** [projectdiscovery/nuclei#689]
![2021-04-23_22-33](https://user-images.githubusercontent.com/44535257/115944508-3498ce80-a484-11eb-9ad8-0b73fca935e5.png)

**Comment by gprime31** [comment]
I does not seem to matter if I run 1 yaml or a folder, I always get errors, anything I can do to fix it?

**Comment by geeknik** [comment]
Happens to everyone, could be any kind of an error from 404 Not Found to getting blocked by Cloudflare to a host timing out or just not responding.  I'd really only worry if the errors count is going up exponentially whilst the request count remains near or close to zero. Good luck out there!

**Comment by geeknik** [comment]
You can verify a specific template is running correctly by adding the `-debug` flag to your command line like `nuclei -t template_name.yaml -target https://www.google.com -debug` in order to view the raw request and response.

**Comment by gprime31** [comment]
Ok thanks, closing

**Comment by gprime31** [comment]
Great to by the way!!!
