### ISSUE TITLE
[issue] Problem updating nuclei 2.3.4 to 2.3.5

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#695]
**Describe the bug**
While trying to update nuclei I get the following error

```
> GO111MODULE=on go get -u github.com/projectdiscovery/nuclei/v2/cmd/nuclei

# github.com/projectdiscovery/nuclei/v2/pkg/protocols/headless/engine
go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.5/pkg/protocols/headless/engine/page_actions.go:469:27: too many arguments in call to page.Search
	have (number, number, string)
	want (string)
go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.5/pkg/protocols/headless/engine/page_actions.go:473:9: invalid argument elms (type *rod.SearchResult) for len
go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.5/pkg/protocols/headless/engine/page_actions.go:474:15: invalid operation: elms[0] (type *rod.SearchResult does not support indexing)

```

**Nuclei version**
2.3.4

**Comment by Ice3man543** [comment]
Try without the -u in the command. That should solve the issue @pdelteil!

**Comment by pdelteil** [comment]
> Try without the -u in the command. That should solve the issue @pdelteil!

Thanks @Ice3man543, that worked.  

I always updated nuclei with the -u flag, I don't understand why it failed this time.

**Comment by Ice3man543** [comment]
@pdelteil without the `-u` flag, go fetches the locked versions of all dependencies which ensures compatibility between nuclei code and those libraries. With `-u` it tries to update them and hence the error. It's a good idea to always fetch locked deps when not doing active development.

Closing the issue as the fix works!

**Comment by pdelteil** [comment]
> @pdelteil without the `-u` flag, go fetches the locked versions of all dependencies which ensures compatibility between nuclei code and those libraries. With `-u` it tries to update them and hence the error. It's a good idea to always fetch locked deps when not doing active development.
> 
> Closing the issue as the fix works!

Thanks again!
