### ISSUE TITLE
[personal issue] nuclei doesn't detect headless templates

### ISSUE THREAD

**Issue by fortoken01** [projectdiscovery/nuclei#696]
This is a bug that happens to me in the last version of nuclei (2.3.5) and only in one of my VPS, the other ones works even in previous versions of nuclei.

**Nuclei version**
2.3.5

**Screenshot of the error or bug**

```
echo "http://host.example/?page=1" | nuclei -headless -t /root/nuclei-templates/headless/

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.5

                projectdiscovery.io

[INF] Loading templates...
[INF] Loading workflows...
[FTL] Error, no templates were found.
```

None of the headless templates are detected and I don't know why. It doesn't happen in my other vps but can't figure what's different and/or don't know how to debug it

**Comment by geeknik** [comment]
Add `-tags headless` to your command line and try again.

**Comment by fortoken01** [comment]
ooh it worked, no idea why it is needed in this version or what but it is working

**Comment by fortoken01** [comment]
Feel free to close this @geeknik and thanks for quickly knowing what was missing.

**Comment by geeknik** [comment]
You're welcome. Good luck out there! 👍🏻

**Comment by Ice3man543** [comment]
Thanks @geeknik! Closing this issue as resolved.
