### ISSUE TITLE
[issue] headless chrome keeps running/bugged

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#699]
**Describe the bug**

After running nuclei headless templates I saw that after nuclei finished that I had chrome processes running all over the ps list consuming most of my ram.

**Nuclei version**

2.3.6

**Screenshot of the error or bug**

When running `htop` I see chrome headless all over the place

![imagen](https://user-images.githubusercontent.com/29487296/117220725-2d57b600-adde-11eb-8e2d-a656a60e8c63.png)

I am wondering if this happened because I runned the command like `timeout 1h nuclei -t...` or because it is just a chrome bug that nuclei didn't stop or the issue relays on nuclei.

**Comment by marcelo321** [comment]
Temporary solution was adding `pkill -f chrome -9;` in my script after execution nuclei but if im running chrome for something else im also killing it which is not really good

**Comment by ehsandeep** [comment]
@marcelo321 thank you for raising an issue for this, this is a known issue with headless mode.
