### ISSUE TITLE
Add support for conditional requests flow to allow chained workflows

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/nuclei#7]
It would be great being able to define multiple requests within the same template with conditional execution in order to define flow chain

**Comment by Zeokat** [comment]
And i'm sure that this enhacement will also works with the issue https://github.com/projectdiscovery/nuclei/issues/13

From my point of view, conditional requests (or a subtemplate system) is a great addition! +1

**Comment by Pxmme** [comment]
This is a must-have! Can't wait until it's implemented.

**Comment by toufik-airane** [comment]
This feature should be a game-changer. 👍
