### ISSUE TITLE
How Search Using All Categories

### ISSUE THREAD

**Issue by secfb** [projectdiscovery/nuclei#706]
I want to scan with all the template on the nuclei-template. But some categories don't exactly work. Is there a way to fix this problem? Am I using the Nuclei tool incorrectly?

```powershell
xargs -a nuclei.txt -L1 -I@ bash -c "nuclei -c 40 -l httpx.txt -t ~/nuclei-templates/@/ -o @_result.txt"
```
**Categories that don't work.**
```ruby
headless
helpers
miscellaneous
workflows
iot
fuzzing
```
![2](https://user-images.githubusercontent.com/38748801/117871345-f124c980-b2a5-11eb-8e29-7f6d44ff247c.png)

---------

 **nuclei.txt**
```golang
cves
vulnerabilities
exposed-panels
misconfiguration
exposures
headless
helpers
miscellaneous
takeovers
technologies
default-logins
workflows
network
iot
fuzzing
dns
```

**Comment by geeknik** [comment]
Please read this article about nuclei [template exclusion](https://nuclei.projectdiscovery.io/nuclei/get-started/#template-exclusion). You will need to either update the `.nuclei-ignore` file in your `nuclei-templates` directory or create a [custom configuration file](https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-config) for nuclei which doesn't exclude the tags you mentioned. Good luck out there.

**Comment by secfb** [comment]
@geeknik I know how to use it as you mentioned. It is already easy to browse as a single category.  I want to scan all categories at the same time.

**Comment by geeknik** [comment]
> I want to scan all categories at the same time.

Okay, well, I gave you links to all of the resources to enable you to do just that, so I'm not sure what else I do to help.

**Comment by ehsandeep** [comment]
@secfb As geeknik mentioned, those templates are excluded as default for a reason mentioned in the linked URL, if you still want to run them, you can overwrite default ignore list with custom config file, for example:-

```
cat test.yaml
```

```
tags: 
  - "iot"
  - "misc"
  - "revision"
```

And run a scan with `nuclei -config test.yaml -t miscellaneous`
