### ISSUE TITLE
[issue] Edge-case HTTP/2 support

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/nuclei#709]
**Describe the bug**
I stumbled upon an edge case where the server responds with HTTP/2 without an upgrade response to or from the client. Browsers, Burpsuite, curl, and some other tools take this in stride but the underly Golang libraries used by Nuclei are more strict.

**Nuclei version**
v2.3.2, compiled from github 05/23/2021.

**Screenshot of the error or bug**
I can't upload an image from here, so:

```
GET / HTTP/1.1
Host: <redacted>
User-Agent: Nuclei - Open-source project (github.com/projectdiscovery/nuclei)
```

```
HTTP/2 200 OK
Date: Thu, 13 May 2021 19:18:13 GMT
Content-Type: text/html;charset=UTF-8
Set-Cookie:...
```

I changed some of Nuclei's error handling so I could see more, and got:
`net/http: HTTP/1.x transport connection broken: malformed HTTP version "HTTP/2"`

**Details**

* I don't see that nuclei is specifically disabling HTTP/2, and it should be [enabled by default as of 1.6](https://golang.org/pkg/net/http/). I can confirm Nuclei works against https://http2.golang.org/.
* After digging into Go's net/http quite too far, I think the problem lies in the fact that http/2 is supported but not very well implemented. This [post](https://stackoverflow.com/questions/62387069/golang-parse-raw-http-2-response) details the exact some condition I found in the code--that Golang's request.go does not validate that `HTTP/2` is valid (it would validate `HTTP/2.0` though :/). The logic can be seen [here](https://golang.org/src/net/http/request.go) in the ParseHTTPVersion function (line 783), and per this [issue](https://github.com/golang/go/issues/25476) it's just simply not supported by Golang unless using net/http2.
* According it's own [page](https://pkg.go.dev/golang.org/x/net/http2), net/http2 is a work in progress and the "client work has just started" 

**Suggestions**

As this is an edge case and I'm not sure how many servers this may impact, so I'm not sure what the right answer is for Nuclei. 

* Obvious option is to start testing and using net/http2.
* Don't use Golang's built-in http modules, instead use lower-level functionality where you manually build requests (I think I saw nuclei has some of this already). This might be a better long-term strategy as Nuclei grows and tries to support more complex and non-standard requests.
* "Override" the Golang error by forcing the response to be `HTTP/2.0` as talked about [here](https://stackoverflow.com/questions/33471704/making-go-http-client-work-with-non-standard-http-servers) or [here](https://stackoverflow.com/questions/62387069/golang-parse-raw-http-2-response) (the latter seeming more straightforward).
* Ignore me and my edge case. I used Burp to change the HTTP version. But perhaps spit out a warning that suggests a user do that. 

I don't mind working on this and test it if I can get some direction from the core team as to how it could be fixed, or if this shouldn't be considered now. FWIW, back in the day I had to quickly move off perl's built in HTTP libraries because of things like this, so Nuclei should consider the future. 

Cheers!

**Comment by ehsandeep** [comment]
@sullo woah! Just wanted to say, thank you for writing this well-detailed issue with a list of suggestions to address this. We are looking into this and will be addressing this in the coming release of nuclei.

**Comment by sullo** [comment]
No problem @ehsandeep. Glad to help.

**Comment by Mzack9999** [comment]
@sullo Thanks again for the very detailed analysis. After further tests, it looks like that the http2 connection upgrade is already supported by the standard `net/http` library. I wasn't able to find a target replying directly with `http/2` and noticed the behavior happens mostly when using Burp as a proxy, as a conversion layer wraps the `http/1.x` protocol to the binary `http/2` one, but leaves the `http/2` version when converting back to `http/1.x` representation, basically:

```
nuclei => http/1.x => burp => http/2 => target
nuclei <= http/2 <= burp <= http/2 <= target
```

The returned version lacks the minor version number required by the `net/http` library. I think the library implementation might be the correct one, as the stream happens within the `http/1.x` context and according to [RFC2145](https://datatracker.ietf.org/doc/html/rfc2145#section-1), both major and minor version needs to be specified.
I've implemented a [patch](https://github.com/projectdiscovery/retryablehttp-go/pull/3/commits/9fbe1f2b072766d05863cc5362362072f2e8eda7) in retryablehttp consisting of a retry strategy with a transport layer compatible with `http/2` if the go error is related to `http/2` over `http/1.x`. Most likely, we will implement some low-level libraries to support non-standard requests (e.g., for `http/2` smuggling). Please let us know if this fixes the issue.

**Comment by sullo** [comment]
Trying those changes out but I'm experiencing the same behavior. 

Curl:
```
╰─○ curl -v https://<redacted>/
*   Trying 10.47.193.158...
* TCP_NODELAY set
* Connected to <redacted> (<redacted>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
[ ssl things]
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa1a080d600)
> GET / HTTP/2
> Host: <redacted>
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< date: Thu, 27 May 2021 19:00:09 GMT
< content-type: text/html;charset=UTF-8
[content]
```

When connecting directly , it still doesn't see the response from the server:
```
[INF] [compal-panel-detect] Dumped HTTP request for https://<redacted>/

GET /common_page/login.html HTTP/1.1
Host: <redacted>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[WRN] [compal-panel-detect] Could not execute request for https://<redacted>/: GET https://<redacted>/common_page/login.html giving up after 2 attempts: Get "https://<redacted>/common_page/login.html": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[INF] No results found. Better luck next time!
```

However, going through burpsuite (without changing HTTP/2 to HTTP/2.0), it does see the 404:

**Comment by ehsandeep** [comment]
Hi @sullo, 

Just to double-check, we pushed the fix in the following PR https://github.com/projectdiscovery/nuclei/pull/731. Can you please confirm if you tested the fix with binary built from this PR, otherwise do you have an example host with this edge case that you can share will be helpful to confirm or prepare a new fix on our side?

**Comment by dpnishant** [comment]
Doesn't seem to be fixed yet. 
<img width="1680" alt="Screen Shot 2021-06-06 at 5 47 54 PM" src="https://user-images.githubusercontent.com/1339669/120945852-6b067200-c6ef-11eb-9f5c-80e8aae93b87.png">

**Comment by ehsandeep** [comment]
@dpnishant thanks for checking, I'm not sure if you checked out the PR branch and build binary to test changes, here is how you can do it if not already.


Building Nuclei from `bugfix-709-http2` branch.

```
git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2/cmd/nuclei; git checkout bugfix-709-http2; go build
```

Running nuclei binary build from`bugfix-709-http2` branch.
```
./nuclei -u https://mobile.twitter.com -proxy-url http://127.0.0.1:8080 -t .
```

**Comment by dpnishant** [comment]
@ehsandeep Yes I haven't tried with a local PR build. Will give it a shot.

**Comment by ehsandeep** [comment]
Closing as this has been resolved and fixed in the latest release, fix is verified locally, we can reopen this again if we encounter more new edge cases to handle.

**Comment by sullo** [comment]
Sorry I fell into a black-hole for a week here... but can confirm this is resolved. Thanks for the great support!

**Comment by ehsandeep** [comment]
Thanks again for confirming @sullo
