### ISSUE TITLE
[feature] Hex output while debugging network templates

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei#710]
It would be easy to debug the network templates if the debug output is hexadecimal.

<img width="765" alt="Screenshot 2021-05-14 at 2 08 46 AM" src="https://user-images.githubusercontent.com/16654365/118184733-5371fb80-b459-11eb-8f38-b21054d263e2.png">

**Comment by Ice3man543** [comment]
Added in #781
