### ISSUE TITLE
[feature] Adding support of severity based filter in workflows

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#717]
When using workflow such as the wordpress workflow, there are some annoying  templates such as `wp-license-file` that I don't want to run at all.

It would be awesome if I could run `-w workflow.yaml -severity low,medium,high,critical` to get ride of the info templates

**Comment by ehsandeep** [comment]
Currently `severity` works as a filter but doesn't apply on workflows as workflows run subtemplates, but somehow adding support for the will be useful for the cases like mentioned above.

**Comment by marcelo321** [comment]
Thanks :) Hopefully it is added soon.
