### ISSUE TITLE
[issue] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory

### ISSUE THREAD

**Issue by wantedbhai** [projectdiscovery/nuclei#719]
[**Describe]([url]([url](url))) the bug**
![nuclei](https://user-images.githubusercontent.com/72160000/118690749-34f36380-b7bd-11eb-8acb-08d88cedd0ef.png)

**Nuclei version**
Please share the version of the nuclei you are running with `nuclei -version` 

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.

**Comment by ehsandeep** [comment]
@wantedbhai Running `nuclei -ut` will download the templates and config files, not an issue or bug.

**Comment by wantedbhai** [comment]
i ran " nuclei -update-templates"  and it is fix now
