### ISSUE TITLE
[issue] Why latest docker image is pointing to chaos?

### ISSUE THREAD

**Issue by Villae** [projectdiscovery/nuclei#723]
**Describe the bug**
Hi,
I noticed that latest docker image is pointing to chaos:
https://hub.docker.com/layers/projectdiscovery/nuclei/latest/images/sha256-44b678290cc6c516a6a36e88324f1cc6b76f779ad052d34b9e58d426017bdd12?context=explore

"ENTRYPOINT ["chaos"]"

Is it wrong / invalid image?

**Nuclei version**
No nuclei command in that image.

**Screenshot of the error or bug**

![image](https://user-images.githubusercontent.com/511887/118758193-31bcae00-b877-11eb-8146-543244919907.png)

**Comment by ehsandeep** [comment]
@Villae thanks for reporting this, should be fixed now - https://hub.docker.com/r/projectdiscovery/nuclei/tags?page=1&ordering=last_updated

It was the result of https://github.com/projectdiscovery/chaos-client/pull/52.
