### ISSUE TITLE
Descriptive error handling 

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#724]
**Is your feature request related to a problem? Please describe.**
Generic errors across multiple features.

**Describe the solution you'd like**
Descriptive error giving more context to what went wrong.

**Comment by ehsandeep** [comment]
This will resolve many and frequent GH issue like this - https://github.com/projectdiscovery/nuclei-templates/issues/1501

**Comment by forgedhallpass** [comment]
Multiple improvements were already implemented in this direction. If other cases will be identified, new tickets will be created.
