### ISSUE TITLE
Exposing failed matched information to JSON output

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#725]
**Suggested by**
swapmaurya

**Is your feature request related to a problem? Please describe.**
Currently, nuclei only report success output.

**Describe the solution you'd like**
This feature will be helpful for the Internal pentesting where the developer will get to know which test case has failed, consider the case where the test cases the developer/security team have built all is having an unsuccessful result will result nuclei producing no results.

This addition will also help the developer to get the data around, how many tests/scans are executed, and with failed or success status.

Also adding this support as default will result in too much data in case of large scans, so we can keep this optional with an additional flag.

**Comment by ehsandeep** [comment]
Test!

**Comment by Ice3man543** [comment]
A new flag, called `-summarize` that presents the matched/not-matched information like below - 

```
[✔] cmdi-test-1 matched on https://test.com
[✖] ssrf-test-1 did not match on https://test.com
```

Similar to JSON output described above

**Comment by Rvn0xsy** [comment]
I anticipated very much that

**Comment by forgedhallpass** [comment]
Duplicate of #1133
