### ISSUE TITLE
nuclei panic

### ISSUE THREAD

**Issue by Udyz** [projectdiscovery/nuclei#735]
panic: assignment to entry in nil map

goroutine 91320 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).handleHTTP(0xc0020334a0, 0xc001ba8200, 0x17, 0xc004f684c0, 0xc004d77b90, 0xc0041ed980, 0xc0023f5290, 0x0, 0x0, 0xc005c39d80, ...)
        /root/nuclei/v2/pkg/executer/executer_http.go:562 +0x53c
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteParallelHTTP.func1(0xc00454ec00, 0xc0020334a0, 0xc001ba8200, 0x17, 0xc004d77b90, 0xc0041ed980, 0xc0023f5290, 0xc006847210, 0xc000032420, 0x15ed4, ...)
        /root/nuclei/v2/pkg/executer/executer_http.go:245 +0xd3
created by github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteParallelHTTP
        /root/nuclei/v2/pkg/executer/executer_http.go:239 +0x53b

**Comment by geeknik** [comment]
Hello, could you share the version of nuclei you were running when you encountered this error?

**Comment by Udyz** [comment]
v2.2.1-dev

**Comment by Udyz** [comment]
i'm update latest version so it was fix, sorry

**Comment by geeknik** [comment]
No worries friend, good luck out there! 🤙
