### ISSUE TITLE
[Issue] Bug in template based exclusion

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#736]
Got it. Also on this exclude templates matter, I'm having issues excluding a single template using the config file. So e.g.:

`$ nuclei -u https://localhost -t ~/nuclei-templates`
![default](https://user-images.githubusercontent.com/1380527/119633699-ea4f9800-be09-11eb-932a-a9cbb3475f36.png)

(using the default configurations so `~/.config/nuclei/config.yaml` is not configured and `~/.config/nuclei/.nuclei-ignore` is:

```
tags:
  - "dos"
  - "iot"
  - "misc"
  - "fuzz"
  - "revision"
```

Now if I change the config to add the exclusion:
`exclude: ['exposures/tokens/google/']`

![nuclei2](https://user-images.githubusercontent.com/1380527/119634148-57632d80-be0a-11eb-9920-9879e3ee0ea6.png)

Which is great, it's concatenating the default exclusions with the user supplied. BUT if I try to exclude a single template it doesn't seem to work:
`exclude: ['exposures/tokens/google/google-api-key.yaml']`

![image](https://user-images.githubusercontent.com/1380527/119634314-8d081680-be0a-11eb-8022-62c928736811.png)

(note that unless we exclude the specific folder, that particular template is always picked up, [log attached](https://github.com/projectdiscovery/nuclei/files/6545382/nuclei.log))

Any ideas?

_Originally posted by Regala in https://github.com/projectdiscovery/nuclei/issues/671#issuecomment-848608080_

**Comment by Regala** [comment]
Wondering if anyone else was able to reproduce this just to confirm, and if we can fix 😇

💜

**Comment by ehsandeep** [comment]
@Regala Yes, this is a confirmed bug that we will fix in the next release.

**Comment by ehsandeep** [comment]
@Regala Can you try this 

```
nano ~/.config/nuclei/config.yaml
```

Add or update the following line:-

```
exclude:
  - exposures/tokens/google/google-api-key.yaml
```

Run Nuclei 
```
nuclei -t exposures/tokens/google/
```

Do you still see Google API template running?

Note:- try this on the default config file and not the custom one.

**Comment by Regala** [comment]
Hummm no! The template is excluded 🤔 

My config looked like this before:
![old](https://user-images.githubusercontent.com/1380527/121189483-0e779400-c862-11eb-8435-e4c9e6374107.png)

**Comment by ehsandeep** [comment]
As the exclude flag accepts multiple templates, multi-line YAML sequence is the expected format, let me know if you still this as an issue?

**Comment by Regala** [comment]
@ehsandeep need to confirm something, but are we supposed to edit `.config/nuclei/.nuclei-ignore`? Or we shouldn't touch that.

**Comment by Regala** [comment]
Btw @ehsandeep would you be able to try and reproduce the following behavior?

On the config.yaml e.g.: 
```
exclude:
  - exposures/tokens/google/google-api-key.yaml
  - exposures/tokens/generic/general-tokens.yaml
  - exposed-tokens/generic/general-tokens.yaml
  - miscellaneous/missing-x-frame-options.yaml
```

Then run `echo 'target.com' | nuclei -t templates/ -severity low,medium,high `

However, because `missing-x-frame-options.yaml` is set as low, it will still be loaded. Is this supposed to happen? I think if they are manually excluded shouldn't matter if it's included with the `-severity` flag.

**Comment by ehsandeep** [comment]
I know @Regala :( that's not expected, as there are multiple ways to execute/filter templates, and they got added as part of incremental updates, there are a few bugs and missing elements to keep everything in sync, we are working currently to uniform all ways of template execution along with config file to avoid future issues/bugs, let's hope in next update we fix them once for all.

Answering your 1st question:-

> are we supposed to edit .config/nuclei/.nuclei-ignore? Or we shouldn't touch that.

No, users are not supposed to edit/update this file, and even you do, it supposes to update/overwrite periodically upon nuclei execution, this is strictly to ensure as default no one running **fuzzing/dos**/etc based template and to avoid unexpected scans, and then we have a nuclei config `~/.config/nuclei/config.yaml` default or custom file that can be used to overwrite `/.nuclei-ignore` as per the need.

Maybe I will have a better answer about features after we fix existing bugs.
