### ISSUE TITLE
Question about encodings supported?

### ISSUE THREAD

**Issue by Zeokat** [projectdiscovery/nuclei#74]
By default Nuclei adds the header `Accept-Encoding: gzip` and I can overwrite this with other alternatives:
`Accept-Encoding: deflate`
`Accept-Encoding: br`
`Accept-Encoding: gzip, deflate, br`

My question is: ¿Is the body's HTTP response correctly decompresed when i use `deflate` or `br` (brotli)?

Thanks.

**Comment by Esonhugh** [comment]
how do u fix it?
