### ISSUE TITLE
[issue] Automatic handling of Content endcoding

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#741]
Request with `Accept-Encoding: gzip` in request header.

```http
GET /+CSCOU+/../+CSCOE+/files/file_list.json?path=/sessions HTTP/1.1
Host: {{Hostname}}
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36
Connection: close
Accept: */*
Accept-Encoding: gzip
Accept-Language: en
```

```http
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: Keep-Alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Mon, 31 May 2021 03:58:33 GMT
Pragma: no-cache
Set-Cookie: text/plain

???/N-.???+??????
```

Request with `Accept-Encoding: deflate` in request header.

```http
GET /+CSCOU+/../+CSCOE+/files/file_list.json?path=/sessions HTTP/1.1
Host: {{Hostname}}
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36
Connection: close
Accept: */*
Accept-Encoding: deflate
Accept-Language: en
```

```http
HTTP/1.1 200 OK
Set-Cookie: text/plain
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Pragma: no-cache
Connection: Keep-Alive
Date: Mon, 31 May 2021 03:57:50 GMT
Content-Length: 14

///sessions
[
```

**Describe the bug**

Currently, the response is dependent based on the request `Accept-Encoding` header, which should be handled automatically by nuclei engine to avoid missing true positive results in the unknown cases.

**Nuclei version**
2.3.7

**Comment by ehsandeep** [comment]
Linking few related issues - https://github.com/projectdiscovery/nuclei-templates/issues/1563

**Comment by Mzack9999** [comment]
Could share same fix of https://github.com/projectdiscovery/httpx/pull/307

**Comment by Mzack9999** [comment]
Can't reproduce. Misconfigured web servers still trigger the same error as in https://github.com/projectdiscovery/httpx/pull/307. The "bug" is documented at https://github.com/projectdiscovery/retryablehttp-go/issues/6
