### ISSUE TITLE
Crash in Nuclei Cluster (nil pointer)

### ISSUE THREAD

**Issue by CharanRayudu** [projectdiscovery/nuclei#745]
![Screenshot 2021-06-02 150210](https://user-images.githubusercontent.com/51598016/120456779-8d2c8700-c3b3-11eb-9465-1c5eceec1696.png)

**Comment by ehsandeep** [comment]
@CharanRayudu Can you please follow the issue template to include more information, for example, the cmd you used to reproduce this crash?

**Comment by CharanRayudu** [comment]
I have added some templates to the /nuclei-templates/ 
The command I used :  nuclei -silent -l /home/andr0idh4ppi3r/Recon/$1/urls.txt -t ~/nuclei-templates/

**Comment by ehsandeep** [comment]
```
echo http://0.0.0.0:8000 | nuclei -t nuclei-templates/
```

This doesn't produce any crash with the default template list, so might be related to some custom template you added?

**Comment by CharanRayudu** [comment]
I have added nearly 300 templates from different resources, Is it possible that which template is causing this error?

**Comment by ehsandeep** [comment]
You can try running those templates with `-v` flag.

**Comment by CharanRayudu** [comment]
I generally use silent mode to keep less pressure on RAM, but it doesn't accept silent and verbose mode at the same time. And it goes off too much scrolling, So I feel it's better to use "silent" mode. Thanks for the resolution.

**Comment by ehsandeep** [comment]
@CharanRayudu reopening this issue as any kind of template shouldn't crash the nuclei engine, so will investigate this further.

**Comment by CharanRayudu** [comment]
Yaa sure!! Thanks

**Comment by ehsandeep** [comment]
Hey @CharanRayudu, we pushed a fix for this in [fix-master-crashes](https://github.com/projectdiscovery/nuclei/tree/fix-master-crashes) branch, Can you can test / confirm it on your side? you can build binary using fix branch as follows -

Building Nuclei from `fix-master-crashes` branch.
```
git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2/cmd/nuclei; git checkout fix-master-crashes; go build
```

Running nuclei binary built from `fix-master-crashes` branch.
```
./nuclei -u https://example.com -t custom_templates
```

**Comment by CharanRayudu** [comment]
Yes, this is resolving the issue. So can it be cleared in the next update ?

> Hey @CharanRayudu, we pushed a fix for this in [fix-master-crashes](https://github.com/projectdiscovery/nuclei/tree/fix-master-crashes) branch, Can you can test / confirm it on your side? you can build the binary using fix branch as follows -
> 
> Building Nuclei from `fix-master-crashes` branch.
> 
> ```
> git clone https://github.com/projectdiscovery/nuclei.git; cd nuclei/v2/cmd/nuclei; git checkout fix-master-crashes; go build
> ```
> 
> Running nuclei binary built from `fix-master-crashes` branch.
> 
> ```
> ./nuclei -u https://example.com -t custom_templates
> ```

**Comment by ehsandeep** [comment]
Yes, the fix is now merged into dev version and soon we will create a new release.
