### ISSUE TITLE
[issue] -nt flag ignores -severity flag

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#746]
When using the -nt flag, nuclei automatically ignores the -severity flag, so if u try

```
nuclei -nt -severity critical
```

It will ignore the severity flag and load all templates that are new

**Comment by ehsandeep** [comment]
It's working fine @marcelo321, what version of nuclei you are using?

![image](https://user-images.githubusercontent.com/8293321/120586348-fe6e4780-c450-11eb-973e-4b97932ab8ca.png)

**Comment by marcelo321** [comment]
I don't know but I updated it and works perfectly now. Sorry, closing
