### ISSUE TITLE
Headless Mode Improvements

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei#749]
* [x] nuclei headless mode currently uses same thread pool as normal nuclei templates. (currently, we force lower limits with headless). ideally headless should use a different limiter separate from normal concurrent parameters.
* [x] headless mode zombie processes (hanging somewhere)

**Comment by forgedhallpass** [comment]
additional TODOs:
- [ ] write more tests
- [ ] benchmarks (run multiple templates against multiple hosts to see how it reacts)

**Comment by Ice3man543** [comment]
The first part of the issue was merged in the refactor in #539
