### ISSUE TITLE
[issue] Jira reporting does not work with the Jira On-Prem version

### ISSUE THREAD

**Issue by gano3s** [projectdiscovery/nuclei#752]
**Describe the bug**
We are using the on-premise version of Jira server (v8.13.2#813002) and the Jira reporting feature does not work correctly. The RestAPI for the on-prem version is different then the Jira Cloud instance. Set an example in our release, the jira account does not have any accountId and login via email does not work.

![image](https://user-images.githubusercontent.com/2551605/120795837-4d43dc00-c53a-11eb-8893-69bf3558d4b2.png)

The fix requires to use the username instead of it. 
Once the fix UI is correctly authorized, the next issue is with the creation of the new issue. The field `reporter` is not recognized by the RestAPI and it requires to use `Name` instead of the `AccountID`

![image](https://user-images.githubusercontent.com/2551605/120796131-bcb9cb80-c53a-11eb-9b2f-31ced27474a8.png)
![image](https://user-images.githubusercontent.com/2551605/120796242-e4a92f00-c53a-11eb-923d-93359f2ce5f9.png)

**Nuclei version**
Tested on the latested dev version of the nuclei. The same behavior even on v2.3.7. 

**Proposed fix**
The proposed solution, which seems to be working correctly is here https://github.com/projectdiscovery/nuclei/pull/751 
Unfortunately, I cannot test the cloud version, but I believe that my changes do not affect it.

The example of the issue created by my fix:
![image](https://user-images.githubusercontent.com/2551605/120797068-d871a180-c53b-11eb-978e-66693826b994.png)
![image](https://user-images.githubusercontent.com/2551605/120797158-f0492580-c53b-11eb-9c7c-55680800a119.png)

**Comment by Ice3man543** [comment]
Thank you @gano3s for the detailed issue and pr. The PR at #751 fixes this and has been merged, hence closing the issue now!
