### ISSUE TITLE
Timeout support for TCP requests

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#756]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible to define a timeout for network-based templates, causing missing valid matches for the cases where a server took some time before responding. 

**Describe the solution you'd like**
timeout support using flag.

**Comment by Mzack9999** [comment]
This should be already supported as the read timeout is set at https://github.com/projectdiscovery/nuclei/blob/4764a34224965c7b130e778175071e4b3034aa89/v2/pkg/protocols/network/request.go#L79 using the value of `timeout` flag https://github.com/projectdiscovery/nuclei/blob/4764a34224965c7b130e778175071e4b3034aa89/v2/pkg/types/types.go#L61 (with default value of 5 seconds)

**Comment by ehsandeep** [comment]
@Mzack9999 thanks, will check this out, can we also confirm if the `timeout` flag is considered when using `unsafe: true` i.e unsafe http library?

**Comment by Mzack9999** [comment]
It's supported in `rawhttp` but it seems like we are using the default options (30 seconds) at https://github.com/projectdiscovery/nuclei/blob/1ef8f824886785ec94671ebf2dcb0dac70a5278b/v2/pkg/protocols/http/httpclientpool/clientpool.go#L84
Probably this should be changed to reflect the value of `timeout` passed via CLI

**Comment by ehsandeep** [comment]
Created a separate issue to track this.
