### ISSUE TITLE
Unable to run nuclei inside golang-based container through AWS Lambda

### ISSUE THREAD

**Issue by terryf82** [projectdiscovery/nuclei#760]
**Describe the bug**
I have a basic golang container that installs several binaries, including nuclei:

```
FROM golang:alpine
...
ENV GO111MODULE=on
RUN go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@dev
RUN nuclei -update-templates
...
```

A lambda function has been written to receive an SQS notification and run nuclei using the following command:

```
cmd := exec.Command("/go/bin/nuclei", "-u", request.Url, "-silent", "-json", "-tags", tagList)
var stdout, stderr bytes.Buffer
cmd.Stdout = &stdout
cmd.Stderr = &stderr
cmdErr := cmd.Run()

outStr, errStr := stdout.String(), stderr.String()
fmt.Printf("out:\n%s\nerr:\n%s\n", outStr, errStr)
```

While this container runs correctly locally, once deployed to the AWS Lambda environment it encounters an error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xc7bfaa]

goroutine 1 [running]:
github.com/projectdiscovery/nuclei/v2/internal/runner.New(0x172d1c0, 0x442dbc, 0xc000000180, 0x300000002)
	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.8-0.20210608111746-673c98c3f4e0/internal/runner/runner.go:75 +0x12a
main.main()
	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.8-0.20210608111746-673c98c3f4e0/cmd/nuclei/main.go:23 +0x55
```

Thinking that perhaps nuclei isn't able to access the templates and/or config file in `/root` when triggered via Lambda, I have tried moving these into different paths and referencing them via `-config` and `-ud` arguments, but the error remains the same.

The code on line 75 of the error above reads:

```
runner.catalog.AppendIgnore(runner.templatesConfig.IgnorePaths)
```

It could be that nuclei cannot access the `/root/.config/nuclei/.nuclei-ignore` file too, but there doesn't seem to be anyway to override the location of this by argument.

**Nuclei version**
v2.3.7-dev

**Comment by terryf82** [comment]
These two environment variables in Lambda may be relevant:
```
LAMBDA_TASK_ROOT: /var/task
LAMBDA_RUNTIME_DIR: /var/runtime
```

I don't reference either of these directories in my code or Dockerfile, but they probably have an impact on where resources can be located, which could explain why config files in `/root` aren't accesible?

**Comment by ehsandeep** [comment]
Hi @terryf82, We pushed a fix for this crash in the following PR https://github.com/projectdiscovery/nuclei/pull/763.

Can you confirm this fix by pulling code from `fix-eof` branch?

```
RUN go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@fix-eof
```

**Comment by ehsandeep** [comment]
We pushed the fix in latest release [v2.3.8]( https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.8)

**Comment by terryf82** [comment]
Fix works, much appreciated =)

I still need to move/copy the templates from `/root/nuclei-templates` to e.g `/nuclei-templates` for them to be accessible within the lambda runtime context, but that only requires one additional line in the Dockerfile and argument to the nuclei command.

**Comment by ehsandeep** [comment]
@terryf82 yeah, you can always feed custom location to install the template using `-ud` flag.
