### ISSUE TITLE
[issue]panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by viston03** [projectdiscovery/nuclei#761]
panic: assignment to entry in nil map

goroutine 674 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).handleHTTP(0xc001f2b720, 0xc002d9f380, 0x15, 0xc002dc87c0, 0xc002dd2300, 0xc002dc8400, 0xc002dd29c0, 0x0, 0x0, 0xc00208f740, ...)
	/root/nuclei/v2/pkg/executer/executer_http.go:562 +0x53c
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteParallelHTTP.func1(0xc002dd4020, 0xc001f2b720, 0xc002d9f380, 0x15, 0xc002dd2300, 0xc002dc8400, 0xc002dd29c0, 0xc002d99ec0, 0xc000230300, 0x3e8, ...)
	/root/nuclei/v2/pkg/executer/executer_http.go:245 +0xd3
created by github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteParallelHTTP
	/root/nuclei/v2/pkg/executer/executer_http.go:239 +0x53b

**Comment by ehsandeep** [comment]
@viston03 Can you include more details, what cmd you used, and what version of nuclei are you running? also, can you try to pull the dev version, as we fixed some crash here - https://github.com/projectdiscovery/nuclei/pull/747

**Comment by Ice3man543** [comment]
@viston03 you need to update the nuclei version. This error is related to a previous version of nuclei. Doing `go get -v github.com/projectdiscovery/nuclei@v2.3.7` should fix the issue.

**Comment by ehsandeep** [comment]
Closing as this is fixed in the latest release.
