### ISSUE TITLE
[feature] Request and response review for multiple targets

### ISSUE THREAD

**Issue by sickwell** [projectdiscovery/nuclei#764]
When starting scanning with nuclei, is it possible to save each request and response to output log?
I know about debug feature, but this prints all in terminal.

**Comment by sickwell** [comment]
btw, this is imposible to save -debug to file. pipe not working too...

**Comment by ehsandeep** [comment]
@sickwell you can use [proxify](https://github.com/projectdiscovery/proxify) for this, for example - 

![image](https://user-images.githubusercontent.com/8293321/121746747-f59e0580-cb23-11eb-9946-856db1f339f8.png)
