### ISSUE TITLE
[feature] Simplified Output 

### ISSUE THREAD

**Issue by indianajson** [projectdiscovery/nuclei#768]
### **Is your feature request related to a problem? Please describe.**

As it stands, even when using the `-o` flag, the output will still contain significant data, which has to be sanitized before being pumped into other toolkits. For example, using the `dns/servfail-refused-hosts.yaml` the response looks like this:

```
[2021-06-13 15:47:57] [servfail-refused-hosts] [dns] [info] XYZ.com
[2021-06-13 15:47:57] [servfail-refused-hosts] [dns] [info] ABC.org
[2021-06-13 15:47:57] [servfail-refused-hosts] [dns] [info] 123.com
[2021-06-13 15:47:57] [servfail-refused-hosts] [dns] [info] 456.org
[2021-06-13 15:47:57] [servfail-refused-hosts] [dns] [info] 789.net
```

For me to run this into another system I have to remove the `[2021-06-13 15:47:57] [servfail-refused-hosts] [dns] [info]` from each line. This can be done via a script but adds an unnecessary step into the workflow.  

### **Describe the solution you'd like:**

I would like to be able to add a flag (perhaps `-dump` or `-raw` or `-quiet`) that only returns the answer from the template (in this case domain name) and ***nothing else!***

```
XYZ.com
ABC.org
123.com
456.org
789.net
```

I read through the documentation and issues, but could not find a way to do this.

**Comment by ehsandeep** [comment]
@indianajson you have it `-no-meta` flag for this.

```
-nm, -no-meta                          Don't display metadata for the matches
```

**Comment by indianajson** [comment]
Thank you for letting me know, I don't know how I missed it.

**Comment by geeknik** [comment]
You could try the the `-no-meta` or `-nm` command line flag.
