### ISSUE TITLE
[Question] Network Templates Multiple Inputs

### ISSUE THREAD

**Issue by wdahlenburg** [projectdiscovery/nuclei#786]
This may make more sense on the Nuclei issues. Let me know if this should be moved over there instead.

**Is your feature request related to a problem? Please describe.**

The [weblogic-t3-detect](https://github.com/projectdiscovery/nuclei-templates/blob/master/network/weblogic-t3-detect.yaml) module is able to detect T3 supported instances of Weblogic without TLS. It would be handy if network modules could support different inputs. This would allow templates to check non-tls and tls hosts at the same time. In the case of T3, the only modification to the input data is `t3s` instead of `t3`. A separate template can be created to solve this, but it's a bit redundant. 

**Describe the solution you'd like**
It would be nice to be able to do something like this:

```
id: weblogic-t3-detect

info:
  name: Detect Weblogic T3 Protocol
  author: F1tz,milo2012
  severity: info
  description: Check T3 protocol status.
  tags: network,weblogic

network:
  - inputs:
    data: 
      - "t3 12.2.1\nAS:255\nHL:19\nMS:10000000\nPU:t3://us-l-breens:7001\n\n"
      - "t3s 12.2.1\nAS:255\nHL:19\nMS:10000000\nPU:t3://us-l-breens:7001\n\n"
     
    host:
      - "{{Hostname}}"
      - "tls://{{Hostname}}"
    read-size: 1024

    matchers:
      - type: word
        words:
          - "HELO"

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "HELO:(.*).false"
```
Since T3 changes the application level data with TLS, if it makes more sense to keep this one split out as a separate template then I can submit the `t3s` template.

**Comment by wdahlenburg** [comment]
I checked and you can have multiple `-inputs`. This works, but isn't much shorter than a new templates :

```
id: weblogic-t3-detect

info:
  name: Detect Weblogic T3 Protocol
  author: F1tz,milo2012
  severity: info
  description: Check T3 protocol status.
  tags: network,weblogic

network:
  - inputs:
      - data: "t3 12.2.1\nAS:255\nHL:19\nMS:10000000\nPU:t3://us-l-breens:7001\n\n"
    host:
      - "{{Hostname}}"
    read-size: 1024
    matchers:
      - type: word
        words:
          - "HELO"

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "HELO:(.*).false"

  - inputs:
      - data: "t3s 12.2.1\nAS:255\nHL:19\nMS:10000000\nPU:t3://us-l-breens:7001\n\n"
    host:
      - "tls://{{Hostname}}"
    read-size: 1024
    matchers:
      - type: word
        words:
          - "HELO"

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "HELO:(.*).false"
```

What are your thoughts on this? Can this be improved?

**Comment by ehsandeep** [comment]
@wdahlenburg similar to having 2 templates, but as you said you wanted to make a separate TCP connection, the above example looks good to me.

**Comment by wdahlenburg** [comment]
That's fair. This is a little lengthier than I'd like, but a TLS and a non-TLS check for the same matcher work. 2 requests is going to be better than 4.

I'll submit this as a PR.
