### ISSUE TITLE
Don't save empty result

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei#79]
Can you add options if there are no results with the `matchers` condition, then the output will not be saved (even if there is a `-o` flag)?

Thanks.

**Comment by bauthard** [comment]
Thanks @dwisiswant0, this will be fixed in coming updates.

**Comment by Ice3man543** [comment]
Fixed by #108.

**Comment by dwisiswant0** [comment]
Nice! :+1:
