### ISSUE TITLE
Network enhancement Certificate SSL check

### ISSUE THREAD

**Issue by xpagedeveloper** [projectdiscovery/nuclei#797]
an extension of nuclei network that would be good is

Certificate information extraction like certificate info like common name and similar info 
to detect miss configuration with SSL

Something like this
https://www.freecodecamp.org/news/how-to-validate-ssl-certificates-in-go/

**Comment by ehsandeep** [comment]
@xpagedeveloper just to double confirm, here we wanted to expose SSL cert fields exposed to nuclei engine so we can write matchers / extractors for it right?

**Comment by xpagedeveloper** [comment]
Exactly what I meant sorry for not writing this.
