### ISSUE TITLE
307 Temporary Redirect not working

### ISSUE THREAD

**Issue by blacklist-arcc** [projectdiscovery/nuclei#810]
**Describe the bug**
The template `nuclei-templates/technologies/tech-detect.yaml` uses the `redirects: true` option. The target system for my test is a typo3 cms which answeres with `HTTP/1.1 307 Temporary Redirect` and redirects to `/start/`. Nuclei does not follow this redirection and is not able to detect the typo3 cms. If i specify the `/start/` in the target url the detection works as expected.

**Nuclei version**
v2.3.8

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/26464774/124564562-7ad5bb00-de41-11eb-8293-e5e957529354.png)

The same behavior goes to httpx
![image](https://user-images.githubusercontent.com/26464774/124565499-67771f80-de42-11eb-95b3-77c2fb5a3bf5.png)

**Comment by ehsandeep** [comment]
Similar to https://github.com/projectdiscovery/httpx/issues/280, thanks for reporting.

This should be supported in httpx [v1.1.0](https://github.com/projectdiscovery/httpx/releases/tag/v1.1.0) @blacklist-arcc,

**Comment by blacklist-arcc** [comment]
Thanks for your fast feedback! I feel very bad for not using the latest version of httpx :/

I will update all the things!

Cheers.

**Comment by ehsandeep** [comment]
@blacklist-arcc this is now supported into dev branch with https://github.com/projectdiscovery/nuclei/pull/1446

```
[tech-detect:typo3-cms] [http] [info] http://194.163.137.237
```

**Comment by blacklist-arcc** [comment]
Time to change our internal arch package ci pipeline to use nuclei's dev branch! #bleedingedge

Thanks for your reply, have a great time.
