### ISSUE TITLE
Ability to specify headers for all requests

### ISSUE THREAD

**Issue by michael1026** [projectdiscovery/nuclei#82]
My request is an option for specifying request headers for all requests sent by Nuclei.

Often times when participating in a bug bounty program, they require a customer header to be sent along with all of your traffic. 

For example `nuclei -t "templates/*.yaml" -H "X-Bug-Bounty: michael1026"

This could also be helpful if you want to supply a cookie value or authorization header for your target.

**Comment by vzamanillo** [comment]
This should be useful to not be rejected by some WAF too.

**Comment by bauthard** [comment]
Hey @michael1026 @vzamanillo this feature is added now, also you can directly connect with the team at discord.gg/pAVhJdR for any feedback and features request.

**Comment by vzamanillo** [comment]
Great news, thanks!
