### ISSUE TITLE
Adding Custom Header Doesn't Work With unsafe=true

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#825]
**Describe the bug**

I'm Trying To Add Custom Header While Using unsafe=true But Doesn't Work

![Screenshot!UNITO-UNDERSCORE!2021-07-11!UNITO-UNDERSCORE!21!UNITO-UNDERSCORE!17!UNITO-UNDERSCORE!06](https://user-images.githubusercontent.com/54332136/125207705-014d2b00-e28e-11eb-89a7-8b87cf50fd3f.jpg)

**Nuclei version**
2.4.0

**Comment by ehsandeep** [comment]
@0xAwali this is now supported in the dev version, thanks for reporting this.

**Comment by 0xAwali** [comment]
thank you guys
