### ISSUE TITLE
Not able to update to 1.1.4

### ISSUE THREAD

**Issue by sumgr0** [projectdiscovery/nuclei#84]
I'm running go version go1.14.2 linux/amd64

and after running the command go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei
I'm still stuck on 1.1.3

For some reason even the tar file *nuclei-linux-amd64.tar*, throws and error:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by lc** [comment]
Hey @sumgr0,

I'm essentially running the same go version, `go1.14.2 darwin/amd64` – do you have your `$GOPATH` set in your environment?

Also, the `nuclei-linux-amd64.tar` opens just fine for me: `tar xzf nuclei-linux-amd64.tar`.

Can you try downloading it again?

**Comment by sumgr0** [comment]
hi @lc,

My $GOPATH is setup properly. and even after downloading the tar file to a different location, does not work. Still gives the same error message about gzip: stdin: not in gzip format

I've even done, 
- remove the binary from $GOPATH/bin/
- git pull in $GOPATH/src/github.com/projectdiscovery/nuclei/ 
- run: go install

Even then the version is stuck to 1.1.3

**Comment by bauthard** [comment]
Hey @sumgr0, 

`tar -xvf nuclei-linux-amd64.tar` should work. 


We messed up with the version number update, so you might seeing 1.1.3 even you are on the latest version, a new release is drafted and will be pushed after testing [feature-fuzz](https://github.com/projectdiscovery/nuclei/tree/feature-fuzz) branch.

**Comment by sumgr0** [comment]
Oh if the version number is messed, then I might be already on the latest version already...
cool

**Comment by bauthard** [comment]
This should be fixed with a new release at https://github.com/projectdiscovery/nuclei/releases
