### ISSUE TITLE
Nuclei Doesn't Allow Using Two Helper Functions Together

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/nuclei#840]
**Describe the bug**

**Nuclei Doesn't Allow Using Two Helper Functions Together e.g. 
I'm Trying To Encode Base64 The Hostname Then Replace equal sign == From The Result Because It Will Break My Idea**

**e.g. My Demo Was This** 

```
id: 0x00
info:
  name: Demo
  author: 0xAwali
  severity: inf0

requests:
  - raw:
      - |
          GET /path HTTP/1.1
          Host: {{Hostname}}
          HeaderONE: {{base64("{{Hostname}}")}}
          HeaderTWO: {{replace("{{Hostname}}", "35", "Mahmoud")}}
```

**Nuclei Work Fine**

![Screenshot_2021-07-17_19_51_14](https://user-images.githubusercontent.com/54332136/126045862-28e48dd1-44fe-4b1b-a1c6-e89196d170cb.jpg)

**But When I'm Trying To Integrate replace("", "", "") AND base64("") Together e.g.
{{replace("{{base64("{{Hostname}}")}}", "=", "Mahmoud")}}**

**It Can't Work** 

![Screenshot_2021-07-17_20_13_09](https://user-images.githubusercontent.com/54332136/126046157-b7460465-6312-418a-ac83-4ff68b236894.jpg)

**And My Template To Try It Is :**

```
id: 0x00
info:
  name: Demo
  author: 0xAwali
  severity: inf0

requests:
  - raw:
      - |
          GET /path HTTP/1.1
          Host: {{Hostname}}
          Header: {{replace("{{base64("{{Hostname}}")}}", "=", "Mahmoud")}}
```

**I Tried A Lot To Solve This But I Think There Is Issue From Your Side**

**Nuclei version**
**2.4.0**

**Comment by Mzack9999** [comment]
@0xAwali The helpers that you are using already returns a string that is automatically recognized internally, so there is no need to wrap it between `"{{helper}}"`, your template could be simplified as follows:

```
id: 0x00
info:
  name: Demo
  author: 0xAwali
  severity: inf0

requests:
  - raw:
      - |
          GET /path HTTP/1.1
          Host: {{Hostname}}
          Header: {{replace(base64(Hostname), "=", "Mahmoud")}}
```

Please let us know if you still face any issues.

**Comment by 0xAwali** [comment]
Thank You

**Comment by ehsandeep** [comment]
Thank you @Mzack9999, Closing as this is resolved.
