### ISSUE TITLE
[issue] Misleading error message (Template not found)

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#842]
**Describe the bug**
When a template has errors and you run nuclei without using the verbose flag, you will get a ``[FTL] Could not run nuclei: no templates were found`` but using the verbose flag you will get  ``[WRN] Could not load template /home/op/nuclei-templates/exposed-gitignore.yaml: yaml: line 25: found character that cannot start any token`` 

Two things here, you get a Warning (WRN) when it's in fact an error and you get the impression that the template is not in the folder. 

**Nuclei version**
2.4.0

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.

**Comment by ehsandeep** [comment]
Thanks for reporting @pdelteil, it's a known generic issue for error handling and something we are tracking here - https://github.com/projectdiscovery/nuclei/issues/724, we will fix this in coming release, closing this as duplicate.

**Comment by pdelteil** [comment]
No way! 

 I'm getting my reports marked asduplicates and now also Github issues?

Hahaha.

**Comment by forgedhallpass** [comment]
I've also ran into this same scenario recently, hence I've changed the message in `dev` to "no valid templates were found".
