### ISSUE TITLE
Not able to run with Multiple templates

### ISSUE THREAD

**Issue by AshKumar06** [projectdiscovery/nuclei#85]
nuclei -l urls.txt -t nuclei-templates/cves/ -o results.txt 
Doesnt works loads only a single template.  

            __     _ 
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ / 
   / / / / /_/ / /__/ /  __/ /  
  /_/ /_/\__,_/\___/_/\___/_/   v1									  

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[FTL] Could not run recognize template extension: tools/nuclei-templates/cves/

**Comment by bauthard** [comment]
Hey @AshKumar06, 

Please see https://github.com/projectdiscovery/nuclei/issues/81, you are running an older version of the project.

**Comment by bauthard** [comment]
We also pushed new release, make sure to update https://github.com/projectdiscovery/nuclei/releases to fix this issue.
