### ISSUE TITLE
Issue with Tags are Excluded tags Filter

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#858]
**Describe the bug**
Tags and Excluded tags filters are not working together.

1. `nuclei -tags exposure` loaded 154 templates.
1. `nuclei -tags exposure -etags config` loaded 154 templates

For the 2nd run, it was expected that templates with `exposure` tags AND NOT `config` tags will be executed, instead, it ignores the AND condition and works as OR.

Expected behavior:- `tags = exposure AND tags != config`
Current behavior -  `tags = exposure OR tags != config`

**Nuclei version**
2.4.0

**Comment by Regala** [comment]
🙌🙌🙌🙌

**Comment by ehsandeep** [comment]
thank again for flagging this @Regala
