### ISSUE TITLE
[issue]No results found. Better luck next time!

### ISSUE THREAD

**Issue by rohit-sri** [projectdiscovery/nuclei#866]
**Describe the bug**
When I run any template I am getting No results found. Better luck next time!

**Nuclei version**
Please share the version of the nuclei you are running with `v2.3.8'` 

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.

**Comment by forgedhallpass** [comment]
Could you please show the CLI options you are using? A screenshot would also be helpful.

**Comment by rohit-sri** [comment]
Please find attachment 
![Error](https://user-images.githubusercontent.com/31887249/126983680-70b65083-9b6c-4d5e-a83f-fa806f83dfb6.png)

**Comment by ehsandeep** [comment]
@rohit-sri Yes, `No results found.` means nuclei doesn't find any issue on the given target, what output do you expect in case of no valid findings?

**Comment by rohit-sri** [comment]
Actually I want to search specific strings in public repository like github, bitbucket.

**Comment by forgedhallpass** [comment]
If you want something specific, you'll have to create your own templates. Please see: https://nuclei.projectdiscovery.io/templating-guide/

**Comment by pdelteil** [comment]
> Please find attachment
> ![Error](https://user-images.githubusercontent.com/31887249/126983680-70b65083-9b6c-4d5e-a83f-fa806f83dfb6.png)

Notice that you're looking for Gitlab repos on GitHub.

The template you are using is intented to find Gitlab repos self hosted by an organisation.

**Comment by rohit-sri** [comment]
I tried to 

> If you want something specific, you'll have to create your own templates.
> Please see: https://nuclei.projectdiscovery.io/templating-guide/
> You can ask for help on Discord: https://discord.gg/projectdiscovery

I create a template but when I execute command it gives error 
[INF] Loading templates...
[INF] Loading workflows...
[FTL] Error, no templates were found.

**Comment by geeknik** [comment]
> I create a template but when I execute command it gives error

Have you attempted to use the `-debug` flag to ascertain where the error is happening?
