### ISSUE TITLE
Option to disable templates auto-updates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#872]
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/835

Suggested flag:-

```
nuclei -no-update-templates
```

If specified via flag or config, template update check will be ignored.

<div type='discussions-op-text'>

<sup>Originally posted by **savushkin-yauheni** July 15, 2021</sup>
Hi team.

Am i wright that templates could be autoupdated ?

If yes, can we disable it by any flag ?

Because there is a strange logic. e.x. i override template, but after autoupdate it reverted to original version and it leads to some bugs.

Thanks</div>

**Comment by ehsandeep** [comment]
Hi  @savushkin-yauheni, this is [now](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.2) supported with `no-update-templates/nut`, keep in mind that disabling auto-updates also means that you will be missing updated templates with fixes included in each release.

**Comment by savushkin-yauheni** [comment]
Thanks again @ehsandeep !

**Comment by Regala** [comment]
Update deez nut

**Comment by terryf82** [comment]
Am I correct that this hasn't made its way into the 2.5.* version yet, only 2.4.*?

**Comment by savushkin-yauheni** [comment]
Hi @terryf82 

> Am I correct that this hasn't made its way into the 2.5.* version yet, only 2.4.*?

 -duc, -disable-update-check    disable automatic nuclei/templates update check

**Comment by terryf82** [comment]
`-duc` in 2.5, `-nut` in 2.4?

**Comment by ehsandeep** [comment]
@terryf82 yes, find the changelog here - https://github.com/projectdiscovery/nuclei/discussions/1159#discussioncomment-1511572
