### ISSUE TITLE
[feature] json export with request response

### ISSUE THREAD

**Issue by iburkhardt** [projectdiscovery/nuclei#873]
Hello everyone, everything good?

I've been looking at the documentation and saw that it has the -debug option that shows the requests made and responses received from the targets, but I didn't find any option that brings only the requests/responses of the items that were found, ie at the end when generating an export in json I came with the request/response only for the items that were found and not everything.

I already have it and I haven't seen it, or it's really not possible?

**Comment by ehsandeep** [comment]
@iburkhardt `-json -irr` is what you need to use with scan.

**Comment by kbonato** [comment]
Work it, thank you!!!

**Comment by ehsandeep** [comment]
Closing as this is resovled.
