### ISSUE TITLE
Cannot Update/Download

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [projectdiscovery/nuclei#877]
Hello!

I tried to download the nuclei, naabu, subfinder, dnsx, httpx but I am receiving this error:
```
github.com/pierrec/lz4 (download)
cannot find package "github.com/pierrec/lz4/v4" in any of:
        /usr/lib/go-1.15/src/github.com/pierrec/lz4/v4 (from $GOROOT)
        /home/snak3/go/src/github.com/pierrec/lz4/v4 (from $GOPATH)
```

**Comment by ehsandeep** [comment]
Hey @SAGEof6iixPATHS, this is an issue with go setup, make sure to configure it properly to make use of it.

**Comment by ehsandeep** [comment]
Follow the instructions here to set up Go properly on your system - https://www.callicoder.com/golang-installation-setup-gopath-workspace/
