### ISSUE TITLE
[feature] add support for sessions

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/nuclei#880]
**Is your feature request related to a problem? Please describe.**
Not a problem.

would it be possible to add session support for authenticated apps?
By session I mean *any* auth method.
zaproxy has something similar, but not sure if it would work here

Ty

**Comment by ehsandeep** [comment]
Hi @dogasantos,

Did you try `session: true`? https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#session

```
cookie-reuse: true
```

If specified cookies will be passed to the next request as like browsers to maintain sessions between multiple requests in the same template, is that what are you looking for?

**Comment by dogasantos** [comment]
Thats for cookies right?
What about headers?

**Comment by ehsandeep** [comment]
@dogasantos by headers did you mean using tokens with env variables? in that case it is being tracked here - https://github.com/projectdiscovery/nuclei/issues/643

**Comment by dogasantos** [comment]
@ehsandeep authorization header with jwt and refresh token, for instance. Thats something we can do today?

**Comment by ehsandeep** [comment]
No, in the current format we need to hardcode them in template which is not practical if you are working with the team and will be possible with the support of nuclei reading env variables as documented in the [linked](https://github.com/projectdiscovery/nuclei/issues/643) issue.

**Comment by ehsandeep** [comment]
Closing this issue as we already have an issue tracking this feature, @dogasantos feel free to jump in https://discord.gg/projectdiscovery for more active communication on ideas/discussion around nuclei.

**Comment by dogasantos** [comment]
Ty!!
