### ISSUE TITLE
[feature] support for passive scan and offline scan

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/nuclei#881]
Hey guys!

me again with more ideas to share.
What you guys think about adding the power of nuclei templates into proxify? I think it would be fantastic!

it would be possible to add a second layer of vuln detection on dalfox scanning process for example. Add more customization to those tools and also have nuclei whole own set of passive templates.

also, we can take advantage of proxify dump files in order to apply scanning templates on it. That also will be powerful resource to catch details and passive vulns even without the need to send new requests to the target.

What you guys think?
Thanks

**Comment by ehsandeep** [comment]
@dogasantos nice ideas and a few of things already supported, for example, passive scan on HTTP response data - https://nuclei.projectdiscovery.io/nuclei/get-started/#passive-scan

Also moving this to discussion as in that way we can keep issues separate from discussion/ideas
