### ISSUE TITLE
[issue] Wrong output of -debug when using a Connection header

### ISSUE THREAD

**Issue by Saikuron** [projectdiscovery/nuclei#890]
**Describe the bug**
When I set `Connection: keep-alive` in a header, the -debug option outputs that there is only one Connection header in the request (the `keep-alive` one), but this is wrong. When using a proxy, we can see that there are actually two Connection headers, the one that I specified and `Connection: close`.

So there are two issues here, the duplicate of the Connection header and the fact that -debug doesn't show the actual request.

**Nuclei version**
2.4.2

**Screenshot of the error or bug**
Use the following request

```yaml
requests:
  - method: GET
    path:
      - '{{BaseURL}}/'
    headers:
      Connection: keep-alive
```

Then start a false server to see the real request, you can use netcat for this

```bash
nc -l -p 3000
```

Execute the template using the port you set for the server

```
nuclei -t path/to/template.yaml -u http://127.0.0.1:3000 -debug
```

The results :
nuclei outputs

```
GET / HTTP/1.1
Host: 127.0.0.1:3000
User-Agent: Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Accept: */*
Accept-Language: en
Connection: keep-alive
Accept-Encoding: gzip
```

but nc shows

```
GET / HTTP/1.1
Host: 127.0.0.1:3000
User-Agent: Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36
Accept: */*
Accept-Language: en
Connection: keep-alive
Accept-Encoding: gzip
Connection: close
```

We can see the additional `Connection` header in the actual request

**Comment by ehsandeep** [comment]
thank you @Saikuron, can confirm this.

**Comment by ehsandeep** [comment]
@Saikuron this is now fixed in the [latest](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.3) release.
