### ISSUE TITLE
-etags not working

### ISSUE THREAD

**Issue by welltest** [projectdiscovery/nuclei#897]
"-etags info" not working in new version too, its not exclude info templates

**Comment by ehsandeep** [comment]
Hi @welltest, please follow the discussion here - https://github.com/projectdiscovery/nuclei/discussions/833 and see the expected use of `etags` here - https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-filters, exclude tags are not supposed to use to exclude the severity, closing we have open discussion for the same.
