### ISSUE TITLE
Exclude templates using template id only

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei#899]
It would be much easier to exclude/include templates using the config file and also using the command line if you could exclude templates only using the template id. The latest version would only exclude a template using the full path to a specific template. 

**Describe the solution you'd like**

``nuclei -t nuclei-templates -u http://test.com -exclude shopify-takeover ``

**Comment by TheSecEng** [comment]
How do you expect this to be handled if multiple templates shared the same ID?

**Comment by pdelteil** [comment]
Hi,

Why should two or more templates share the same id?

**Comment by TheSecEng** [comment]
That is a great question! In my opinion, template ID's should be completely unique, but nothing currently enforces that to my knowledge. When nuclei is implemented outside of this CLI tool, only writing custom templates would have to ensure their template-id they have chosen doesn't conflict with any other template ID.

In the current state, these would be two viable templates with the same template idea. Made unique by the template path.

```
tech/orders-api/login.yaml => TemplateID = login
tech/orders-api/get-orders.yaml => TemplateID = get-orders
tech/customer-api/login.yaml => TemplateID = login
tech/customer-api/get-orders.yaml => TemplateID = get-orders
```

I think what needs to be determined is if we move away from template paths in preference for template-id's. If you move away from paths, you then have to read every template to determine what templates to exclude. Which can get resource intensive as you add more templates.

**Comment by forgedhallpass** [comment]
Although it would be possible to implement, I don't see really see the added value. Currently it would require a significant effort to make it performant. There will be an optimization in the future towards this direction, that could help facilitate this request, but generally speaking, it is easier for the users to get the names of the templates with a directory listing (`ls` or `tree` or similar). On the other hand to get the IDs, one would need to do `grep` with regexes or would require a new option or tool to easly extract this information.

**Comment by ehsandeep** [comment]
@pdelteil @TheSecEng additional and optional filter has been implemented in https://github.com/projectdiscovery/nuclei/pull/1448 that supports running or excluding templates based on **template ID**.

Uses details are shared in https://github.com/projectdiscovery/nuclei/issues/1442

We will extend the `validate` flag of nuclei to detect and flag templates with duplicate ID as part of the template project workflow to avoid having templates with duplicate IDs in the template project, for custom / private templates having multiple templates with the same ID, they all can be executed or excluded with same `id`.

**Comment by pdelteil** [comment]
Thanks.
