### ISSUE TITLE
retryablehttp-go Error While Installation.

### ISSUE THREAD

**Issue by KathanP19** [projectdiscovery/nuclei#9]
go get: github.com/projectdiscovery/nuclei@v1.0.1 requires
        github.com/projectdiscovery/retryablehttp-go@v0.0.0-20200404122901-546f385ed972: invalid version: unknown revision 546f385ed972

**Comment by Ice3man543** [comment]
@KathanP19 can you try it again? Thanks!

**Comment by KathanP19** [comment]
So When I tried `GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei`
`go get: github.com/projectdiscovery/nuclei@v1.0.1 requires
        github.com/projectdiscovery/retryablehttp-go@v0.0.0-20200404122901-546f385ed972: invalid version: unknown revision 546f385ed972`

I got same error but when i tried this `go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei` it got installed.
`github.com/projectdiscovery/nuclei (download)
github.com/projectdiscovery/gologger (download)
github.com/logrusorgru/aurora (download)
github.com/projectdiscovery/retryablehttp-go (download)
github.com/valyala/fasttemplate (download)
github.com/valyala/bytebufferpool (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/projectdiscovery/gologger
github.com/projectdiscovery/nuclei/pkg/extractors
github.com/valyala/bytebufferpool
gopkg.in/yaml.v2
github.com/projectdiscovery/nuclei/pkg/matchers
github.com/valyala/fasttemplate
github.com/projectdiscovery/nuclei/pkg/requests
github.com/projectdiscovery/nuclei/pkg/templates
github.com/projectdiscovery/nuclei/internal/runner
github.com/projectdiscovery/nuclei/cmd/nuclei`
