### ISSUE TITLE
New filter to exclude severity based templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#902]
Related discussion - https://github.com/projectdiscovery/nuclei/discussions/833

**Is your feature request related to a problem? Please describe.**
Currently, nuclei engine supports `severity` to define/filter to run templates based on given severity but no ways to support to exclude specific severity. 

**Describe the solution you'd like**

For example, I wanted to run all templates that don't have `info` as severity, it is also doable in current form as follow:-

```
nuclei -severity critical,high,medium,low
```

With new filter support:-

```
nuclei -exclude-severity info
nuclei -exclude-severity info,low
```

will work similarly `exclude-tags`, `exclude-templates` flag.

**Comment by pdelteil** [comment]
It's like you guys are reading my mind. Come here to open issues and they are already solved! 

Haha.
