### ISSUE TITLE
[issue] Tag filter is not working correctly with other conditions

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#903]
**Describe the bug**
The tag filter is not working correctly with other conditions such as `author` or `severity`

**Nuclei version**
2.4.2

**Screenshots**
![image](https://user-images.githubusercontent.com/13679401/128175560-6fe220d2-ac21-4362-9e9c-352c2666cb46.png)

![image](https://user-images.githubusercontent.com/13679401/128175808-b7b9e183-1be8-40d5-8f8a-a60956d7006a.png)

**Comment by forgedhallpass** [comment]
#834 was recently merged to the dev branch. The issue should be resolved.

**Comment by ehsandeep** [comment]
Can confirm, this bug is now fixed in the dev version.
