### ISSUE TITLE
[issue] -severity will bypass -tags

### ISSUE THREAD

**Issue by Tedixx** [projectdiscovery/nuclei#912]
**Describe the bug**
When running nuclei on default templates, I am unable to combine tags with severity. While using -tags misc, all templates with tag 'misc' will run. While adding '-severity' to it, Tag misc will be bypassed and all other templates will run. 

`cat <file> | nuclei -t nuclei-templates/ -tags xss -severity low,medium,high,critical`

**Nuclei version**
2.4.2

**Screenshot of the error or bug**

With only tag misc; 
```
cat <file> | nuclei -t nuclei-templates/ -tags misc

[INF] Using Nuclei Engine 2.4.2 (latest)
[INF] Using Nuclei Templates 8.4.3 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 27 (New: 85)
[INF] Templates clustered: 9 (Reduced 210 HTTP Requests)
```

With tag misc and severity;
```
cat <file> | nuclei -t nuclei-templates/ -tags misc -severity low,medium,high,critical

[INF] Using Nuclei Engine 2.4.2 (latest)
[INF] Using Nuclei Templates 8.4.3 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1160 (New: 85)
[INF] Templates clustered: 95 (Reduced 2790 HTTP Requests)

```

With the usage of -tags and -severity, I expect the application to select all 'misc' templates with severity low,medium,high,critical.

**Comment by ehsandeep** [comment]
@Tedixx thanks for reporting, it's a known issue with tags filter documented here - https://github.com/projectdiscovery/nuclei/issues/903, we will get it fixed in the next release.

Closing as we are tracking this bug in https://github.com/projectdiscovery/nuclei/issues/903
