### ISSUE TITLE
Unable to build due to smtpd missing dependancy

### ISSUE THREAD

**Issue by oacyberlm** [projectdiscovery/nuclei#920]
Dear team,

SMTPD package from prologic seams to have disappeared, thus, impossible to build nuclei package.

 #12 17.69       github.com/prologic/smtpd@v0.0.0-20210126001904-0893ad18168e: git init --bare in /go/pkg/mod/cache/vcs/65b3100cfa8e2061b6047e41aaceb4a1e850f70977a718cfde5bd0e009bb0722: exec: "git": executable file not found in $PATH

404 ERROR on https://github.com/prologic/smtpd

Thanks

**Comment by ehsandeep** [comment]
@oacyberlm should be fixed now, we pushed a new [release](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.3).
