### ISSUE TITLE
[issue]fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by lijinta1984** [projectdiscovery/nuclei#921]
**Describe the bug**
I'm getting the follwing error while trying to install nuclei using go script

GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei                                                                                                                                                         
go get: github.com/projectdiscovery/nuclei/v2@v2.3.5 updating to
        github.com/projectdiscovery/nuclei/v2@v2.4.2 requires
        github.com/projectdiscovery/interactsh@v0.0.3 requires
        github.com/prologic/smtpd@v0.0.0-20210126001904-0893ad18168e: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go-workspace/pkg/mod/cache/vcs/65b3100cfa8e2061b6047e41aaceb4a1e850f70977a718cfde5bd0e009bb0722: exit status 128:
        fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Nuclei version**
 2.4.2

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.
![image](https://user-images.githubusercontent.com/75410857/128747367-469c795b-516e-4f3a-84f7-9f89f625ef04.png)

**Comment by ehsandeep** [comment]
@lijinta1984 should be fixed now, we pushed a new [release](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.3).

**Comment by lijinta1984** [comment]
> 
> 
> @lijinta1984 should be fixed now, we pushed a new [release](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.3).

Thanks for the quick response.Will check and revert
