### ISSUE TITLE
[feature] Hostname w/o port

### ISSUE THREAD

**Issue by wdahlenburg** [projectdiscovery/nuclei#927]
**Is your feature request related to a problem? Please describe.**
The `{{Hostname}}` syntax is mapped to the output of Go's [url.Parse(url).Host](https://github.com/projectdiscovery/nuclei/blob/master/v2/pkg/protocols/http/request.go#L134).

As a byproduct the parsed hostname will include the port number. This value should normally be used in the Host header for all HTTP requests. Example: https://play.golang.org/p/lyYDHByctBt

It would be great if there was a way to just access the hostname and not include the port in templates. This information is helpful when trying to uniquely tag OOB lookups.

An example I'd like to be able to include in my templates is: `{{Hostname}}.{{interactsh-url}}` or `{{Hostname}}.xyz.burpcollaborator.net`

If a port exists in the resolved hostname I might end up with something like this: example.com:443.xzyyyyyy.interact.sh. Not all DNS servers will tolerate a malformed domain name, which will fail to perform the OOB request on a vulnerable target.

**Describe the solution you'd like**

Perhaps another variable is added like `{{Domain}}` that strips out any port number. A helper function could also work to do this.

**Comment by wdahlenburg** [comment]
This links into #491. Feel free to track this request there.

**Comment by ehsandeep** [comment]
@wdahlenburg @parrasajad we also need to ensure separating port with `{{Hostname}}` doesn't affect the existing template, so it might be a good idea to include a new variable to expose both `{{Host}}` and `{{Port}}` separately instead of updating current `{{Hostname}}` behavior.

**Comment by ehsandeep** [comment]
This is now supported in [dev](https://github.com/projectdiscovery/nuclei/tree/dev) version:-

Newly added Global variables:-

- `{{RootURL}}`
- `{{Host}}`
- `{{Port}}`
- `{{Path}}`
- `{{Scheme}}`

Template example:-

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    headers:
      A: '{{BaseURL}}'
      B: '{{RootURL}}'
      C: '{{Hostname}}'
      D: '{{Host}}'
      E: '{{Port}}'
      F: '{{Scheme}}'
      G: '{{Path}}'
```

Example output:-

```
echo http://www.example.com:80/test/aa?a=b | ./nuclei -t test.yaml -debug-req

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.4-dev

    projectdiscovery.io

[INF] Using Nuclei Engine 2.4.4-dev (development)
[INF] Using Nuclei Templates 8.4.5 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1 (New: 25)
[INF] [basic-example] Dumped HTTP request for http://www.example.com:80/test/aa?a=b

GET /test/aa?a=b/ HTTP/1.1
Host: www.example.com:80
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
A: http://www.example.com:80/test/aa?a=b
B: http://www.example.com:80
C: www.example.com:80
D: www.example.com
E: 80
F: http
G: /test/aa

[INF] No results found. Better luck next time!
```

**Comment by mr-rizwan-syed** [comment]
It should also have root domain 
{{RootDomain}}
to detect 
example.com - not with subdomain

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>S0DUji

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>xhjK6Y

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XmWgiR

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>YEswrt

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>xJtEFu

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>L27p4U

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>DZcNFy

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>yCQsrC

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>EI7iUY

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1qVld8

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ykMV2Z

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1aZwwu

**Comment by dody200411** [comment]
'"><div rNnTRbt=roann>UAx1S9

**Comment by dody200411** [comment]
'" rNnTRbt="roannATTR" x=y2gRbTq

**Comment by dody200411** [comment]
'"></script><div rNnTRbt=roann>YuDc3w

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>8JyUZk

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>iHEG0e

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>hhpHrP

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>wvxLUU

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>n5jmXm

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>wG4wN7

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>knCxHu

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>UWhyVe

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>NgQ0lp

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>yNcw2Z

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>NIVT0e

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>7NfDxD

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ufPqfZ

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ncnGmt

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>u6UzRZ

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>MDgwlB

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>8X79QE

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bzkPTp

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ui92hF

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ORlYXh

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>pV14tU

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>u829ox

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>V8kM3c

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>FwYjwP

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Yh5c9i

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>X4a7Lr

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>9WYmy2
