### ISSUE TITLE
Nuclei scan optimization

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#934]
**Is your feature request related to a problem? Please describe.**
When many templates are run against a large number of hosts, a big number of hosts in the list fail to respond or error out for unclear reasons, degrading the overall scan.

**Describe the solution you'd like**

Here is a suggestion for improving scan performance that can be implemented if the following procedures are followed:-
a) During the scan, internally map the error count per host.
b) If the error count exceeds a certain threshold, drop hosts from the hosts-to-scan list for further templates.

```
nuclei -list urls.txt -tags exposures -max-host-error 10
```

Any host that has erroed 10 times will be removed from the scan list, allowing more templates to be scanned. This will reduce scan time by minimising the few attempts to connect those hosts that always result in a timeout, i.e. increased scan time.

**Comment by geeknik** [comment]
Would it be possible for nuclei to alert the user which hosts were skipped so we can follow-up on them later?

**Comment by ehsandeep** [comment]
@geeknik that information is printed to CLI if running with `-v` flag as of now.

**Comment by geeknik** [comment]
Good to know, thank you. Would love to see an end of scan summary showing that info without having to post-process out all of the extra noise that `-v` generates. 👍🏻

**Comment by Regala** [comment]
x2, having that info in the debut is already useful but having a more clean
output (even a environment/persistent file) where these hosts would be
logged would make life easier

**Comment by ehsandeep** [comment]
@geeknik @Regala +1 for this idea, this is initial implementation now added into the latest release, for sure we can include more support to this in the coming versions.
