### ISSUE TITLE
[feature] new infos in template

### ISSUE THREAD

**Issue by iburkhardt** [projectdiscovery/nuclei#940]
Hello everyone,

It is possible to put in the template information something like:

remediation effort: easy, hard etc.?
something like:
discoverability

info:
  name: Test HTTP Template
  author: pdteam
  Severity: info
  remediation effort: easy
  discoverability:

**Comment by ehsandeep** [comment]
@iburkhardt under `info:` block, you can define any number of `key: value` formatted data.

If you asking this in the context of a custom template: **Yes**, it's possible to add this information.
If you asking this in the context of existing public templates, this can not be done in automated way and & requires manual effort.
