### ISSUE TITLE
[issue] templates do not run

### ISSUE THREAD

**Issue by iburkhardt** [projectdiscovery/nuclei#942]
Hi guys,

 Could you tell me why even having several templates, my nuclei is running only 1?

![Screenshot_1](https://user-images.githubusercontent.com/88056017/129427273-f65b99e9-3d9d-4133-a344-7530e707c518.png)

I updated it to the most recent version, I tried to specify a template and it doesn't find it, it's like it doesn't exist.
![Screenshot_1](https://user-images.githubusercontent.com/88056017/129427797-bcdc8dba-7103-437c-b331-6268f6663cde.png)

**Comment by ehsandeep** [comment]
@iburkhardt there are a few templates/tags that are excluded from the default run as detailed [here](https://nuclei.projectdiscovery.io/nuclei/get-started/#template-exclusion).

You can overwrite the default behavior via flag (`nuclei -t miscellaneous/ -include-tags misc` or nuclei [config](https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-config) file.
