### ISSUE TITLE
[feature] Show progress of running scans

### ISSUE THREAD

**Issue by 0xcrypto** [projectdiscovery/nuclei#943]
**Is your feature request related to a problem? Please describe.**
Running nuclei on many hosts is very slow process. I know it is running but still it visually seems hanged.

**Describe the solution you'd like**
A progress bar similar to ffuf that will show how many requests sent or templates scanned so that user can have a feel of something is being done.

**Comment by ehsandeep** [comment]
Hi @0xcrypto, 

Nuclei have `stats` flag for the same purpose, related issues about stats  - https://github.com/projectdiscovery/nuclei/issues/664
