### ISSUE TITLE
No output after [INF] - Working properly?

### ISSUE THREAD

**Issue by m0nk3y-s3c** [projectdiscovery/nuclei#95]
I have no idea if I got it right.

After the following command cat domains.txt | ./nuclei-linux-amd64 -t nuclei-templates/files/git-config.yaml -o results.txt

I get the following output

[WRN] Developers assume no liability and are not responsible for any misuse or damage.               
[INF] [git-config] Loaded template Git Config Disclosure (@Ice3man) [medium]```

Then it exists and the domains.txt files contain 6890 alive subdomains.
So either this is the fasted tool ever or its not working without any output of an error.

Thanks in advanced.

**Comment by bauthard** [comment]
Hi @m0nk3y-s3c, 

You are doing it right, it's just no targets are vulnerable or matched with `git-config.yaml` template.

**Comment by m0nk3y-s3c** [comment]
What a quick response...
Thanks :)

**Comment by bauthard** [comment]
https://github.com/projectdiscovery/nuclei/issues/96 I've also created an issue to indicate the message in case of no results were found @m0nk3y-s3c
