### ISSUE TITLE
[feature] Can this tool run as a service?

### ISSUE THREAD

**Issue by ananan** [projectdiscovery/nuclei#959]
**Is your feature request related to a problem? Please describe.**
nuclei is a great tool for security research, but for now it can only run in command line, for some case we need this tool run as a daemon service so that we can push targets to scan continually.  

**Describe the solution you'd like**
nuclei can run as a daemon service, thus we can push targets to scan and get the results instantly, and easily intergrated with other component.

**Comment by ehsandeep** [comment]
Hi @ananan, 

Yes, that's planned for Nuclei v3, you will be able to run nuclei as a self-hosted service and initiate REST API-based scans.
