### ISSUE TITLE
nuclei maybe only Identify utf-8 but not indentify gbk

### ISSUE THREAD

**Issue by kitezzzGrim** [projectdiscovery/nuclei#971]
**Describe the bug**
nuclei maybe only Identify utf-8，I came across a website that only identify gbk，Chinese garbled characters will occur when nuclei meet gbk

**Nuclei version**
Please share the version of the nuclei you are running with `nuclei -version` 

2.4.0

**Screenshot of the error or bug**
<img width="315" alt="Snipaste_2021-08-25_14-38-45" src="https://user-images.githubusercontent.com/32265931/130739207-6a00cefc-2493-4f1e-9dee-86610810d6b8.png">

**Comment by ehsandeep** [comment]
@kitezzzGrim gbk charset is now supported in the latest version.
