### ISSUE TITLE
Matchers don't work with Redirects

### ISSUE THREAD

**Issue by 0-duke** [projectdiscovery/nuclei#98]
As per title, matchers don't work with redirects.

Example.

**BaseURL**: www.westernunion.com

Using the following template will detect "OptimusApp" string correctly. The first request will hit "www.westernunion.com/us/en/home.html" and the matcher works.

`requests:`
`  - method: GET`
`    path:`
`      - "{{BaseURL}}/us/en/home.html"`
`    matchers:`
`      - type: word`
`        words:`
`          - "OptimusApp"`
`        part: body`

But using a similar template and following the redirects nuclei doesn't detect the string "OptimusApp" in the last page accessed after all the redirects (which in this case will eventually be "www.westernunion.com/us/en/home.htm").

`requests:`
` - method: GET`
`    path:`
`      - "{{BaseURL}}"`
`    redirects: true`
`    max-redirects: 10`
`    matchers:`
`      - type: word`
`        words:`
`          - "OptimusApp"`
`        part: body`

Let me know if you need more details

**Comment by bauthard** [comment]
Hi @0-duke, this works for me, I doubt you are feeding subdomain instead of URL, and `nuclei` only accepts `URLs` for `http` related templates. 

```
root@b0x:~/test# cat redirect-test.yaml 
id: redirect-test

info:
  name: redirect-test
  author: test
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/us/en/home.html"
    redirects: true
    max-redirects: 10
    matchers:
      - type: word
        words:
          - "OptimusApp"
```


```
root@b0x:~/test# echo http://www.westernunion.com | nuclei -t redirect-test.yaml -silent
[redirect-test] [http] http://www.westernunion.com/us/en/home.html
```

**Comment by 0-duke** [comment]
OMG, you are right. How did I manage to be so naive?

Apologies.

**Comment by bauthard** [comment]
Np @0-duke, thank you for confirming this.
