### ISSUE TITLE
Crash - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#984]
**Describe the bug**

While running:-

```
nuclei -t miscellaneous/aws-ecs-container-agent-tasks.yaml -l urls.txt -rl 400 -bs 400 -stats
```

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x10278b56c]

goroutine 1589838 [running]:
crypto/tls.(*Conn).write(0x14005264a80, 0x14004118dc0, 0x115, 0x140, 0x14003252a80, 0x110, 0x180)
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/crypto/tls/conn.go:911 +0xfc
crypto/tls.(*Conn).writeRecordLocked(0x14005264a80, 0x16, 0x14003252a80, 0x110, 0x180, 0x0, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/crypto/tls/conn.go:979 +0x240
crypto/tls.(*Conn).writeRecord(0x14005264a80, 0x14003252a16, 0x14003252a80, 0x110, 0x180, 0x0, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/crypto/tls/conn.go:1001 +0xac
crypto/tls.(*Conn).clientHandshake(0x14005264a80, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/crypto/tls/handshake_client.go:167 +0x180
crypto/tls.(*Conn).Handshake(0x14005264a80, 0x0, 0x0)
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/crypto/tls/conn.go:1391 +0xf8
net/http.(*persistConn).addTLS.func2(0x0, 0x14005264a80, 0x0, 0x140033ebda0)
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/net/http/transport.go:1530 +0x38
created by net/http.(*persistConn).addTLS
	/opt/homebrew/Cellar/go/1.16.5/libexec/src/net/http/transport.go:1526 +0x184
```

**Nuclei version**
Dev version

**Screenshot of the error or bug**
please add the screenshot showing bug or issue you are facing.

**Comment by ehsandeep** [comment]
This turned out to be an issue with go version and possibly due to a security issue in the previous version, upgrading to `go1.17` solved this issue.

**Comment by ehsandeep** [comment]
This also means, `go1.17` needs to keep as a minimum required version to build nuclei.

**Comment by JeffreyShran** [comment]
I had this same error and I'm glad to see you've already identified and resolved the issue, thanks.

My little script might help people to get the latest version of golang if they are looking for help on how to do the upgrade: https://github.com/JeffreyShran/goJeffgo

**Comment by JeffreyShran** [comment]
After upgrading go to 1.17 the error persists. I've been unable to pin down which template/url causes it. There's also nothing in the nuclei log. I'll keep trying to figure it out.

Another user has also reported the same issue: https://github.com/projectdiscovery/nuclei/issues/998
